////
Included in:

- user-manual: Attributes: Setting attributes on a document
////

When an attribute is set in the header of a document, it is called an attribute entry.

.Anatomy of an attribute entry
----
:attribute name: value
----

An attribute entry consists of the attribute's name and its value.
The attribute's name is preceded and followed by a colon.
After the second colon, there is at least one space and then the value.
The value is optional.

Once set, an attribute entry and its value are available for use throughout your entire document.
Attribute entries are used to toggle settings on and off or to set configuration variables that control the output generated by the AsciiDoc processor.
For example, to include a table of contents in your document, you can turn on (i.e., set) the `toc` attribute entry.

[source]
----
:toc:
----

When the value field following an attribute is left empty, as it is in the example above, the default value will be assigned.
The default value for `toc` is `auto`; therefore, the table of contents will be placed on below the document's title when it is rendered.
If you wanted the table of contents to be placed on the right side of the document, you must assign the attribute a new value.

[source]
----
:toc: right
----

The `right` value will override the default value.
The value assigned to an attribute in the document header will replace the intrinsic value.

Attribute entries are also used to store URLs.
Here's an example:

[source]
----
:fedpkg: https://apps.fedoraproject.org/packages/asciidoc
----

Now you can refer to this attribute entry anywhere in the document (where attribute substitution is performed) by surrounding its name in curly braces:
Here's the attribute in use:

====
[source]
Information about the AsciiDoc package in Fedora is found at {fedpkg}.
====

You can also set the base path to images (default: _empty_), icons (default: `./images/icons`), stylesheets (default: `./stylesheets`) and JavaScript files (default: `./javascripts`):

[source]
----
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js
----

When you find yourself typing the same text repeatedly, or text that often needs to be updated, consider assigning it to a document attribute and use that instead.

Attribute entries have the following characteristics:

* can be assigned to a document via the CLI or in the document's header and body
* have default values
** their default values are set when the user leaves the value field empty
* some have alternate values
* they can be unset (turned off) with a `!`
* they override config files, intrinsic attributes
* they do *not* override attributes issued from the command line
** a number of entry attributes can also be used on the command line

==== Attribute entry substitutions

The `header` substitution group is applied to the header of your document.
<<user-manual#subs,Text substitution elements>> replace characters, markup, attribute references, and macros with converter specific styles and values.
When Asciidoctor processes a document it uses a set of six text substitution elements.
In the header, only <<user-manual#special-characters,special characters>> and <<user-manual#attributes-2,attribute references>> are replaced.

However, if you require other substitutions to be applied to an attribute's value, use the <<user-manual#pass-mac,pass inline macro>>.
This macro has special meaning in an attribute entry.
It allows the substitutions to be applied at the time the attribute is defined.

The pass inline macro accepts a list of substitutions in the `target` slot.
In the next example, we'll apply the <<user-manual#quotes,quotes substitution>> to an attribute entry's value.

[source]
----
:app-name: pass:quotes[MyApp^(C)^]
----

You can also specify the substitution using the single-character alias, `q`.

[source]
----
:app-name: pass:q[MyApp^(C)^]
----

Another approach is to change the order of substitutions that are applied where the attribute is referenced.

[source]
----
:app-name: MyApp^(C)^

[subs="specialcharacters,attributes,quotes,replacements,macros,post_replacements"]
The application is called {app-name}.
----

////
TODO: This section actually might make more sense in the header section.

The main focus of the learning for this documentation is how to use inline formatting in an attribute value. Normally, inline formatting in an attribute value is not interpreted because:

a. Inline formatting is not applied when an attribute is set (attribute holds raw value)
b. Inline formatting is not applied when an attribute is referenced since the relevant substitutions come before attributes are resolved
////
