////
Included in:

- user-manual: Attributes: Setting attributes on an element
////

// tag::intro[]
An attribute list can apply to blocks, inline quotes text, and macros.
The attributes and their values contained in the list will take precedence over attribute entries.

.Anatomy of an attribute list
 [positional attribute,positional attribute,named attribute="value"]

Attribute lists:

. apply to blocks as well as macros and inline quoted text
. can contain positional and named attributes
. take precedence over global attributes
// end::intro[]

==== Positional attribute
// tag::pos[]
in an attribute list

not named

the first positional attribute in the list on inline quoted text is referred to as the role attribute

the first positional attribute in the list on blocks and macros is known as the style attribute
// end::pos[]

==== Named attribute
// tag::name[]
A named attribute consists of a name and a value separated by an `=` character.

If the value contains spaces, commas, or a quote characters, it must be enclosed in double or single quotes.
Otherwise, the surrounding quotes are optional.
If used, the surrounding quotes are stripped from the parsed value.

If the value is enclosed in single quotes, normal substitutions get applied to the value at assignment time.
No special processing is performed if the value is enclosed in double quotes.

To use the same quote character in the value that's used to enclose the value, escape the character in the value by prefixing it with a backslash (e.g., `value="the song \"Dark Horse\""`).

To undefine a named attribute, set the value to `None` (case sensitive).
// end::name[]
