////
Included in:

- user-manual: Attributes: Setting attributes on a document
////

When an attribute is set in the header of a document, it is called an attribute entry.

.Anatomy of an attribute entry
----
:attribute name: value
----

An attribute entry consists of the attribute's name and its value.
The attribute's name is preceded and followed by a colon.
After the second colon, there is at least one space and then the value.
The value is optional.

Once set, an attribute entry and its value are available for use throughout your entire document.
Attribute entries are used to toggle settings on and off or to set configuration variables that control the output generated by the AsciiDoc processor.
For example, to include a table of contents in your document, you can turn on (i.e., set) the `toc` attribute entry.

[source]
----
:toc:
----

When the value field following an attribute is left empty, as it is in the example above, the default value will be assigned.
The default value for `toc` is `auto`; therefore, the table of contents will be placed on below the document's title when it is rendered.
If you wanted the table of contents to be placed on the right side of the document, you must assign the attribute a new value.

[source]
----
:toc: right
----

The `right` value will override the default value.
The value assigned to an attribute in the document header will replace the intrinsic value.

Attribute entries are also used to store URLs.

<<<<<<< HEAD
=======
[example]
>>>>>>> dc699963b50094f3083bef00945d6d602270b0f7
.URL attribute entry
[source]
----
:fedpkg: https://apps.fedoraproject.org/packages/asciidoc
----

Now you can refer to this attribute entry anywhere in the document (where attribute substitution is performed) by surrounding its name in curly braces:

.fedpkg attribute usage example
====
[source]
Information about the AsciiDoc package in Fedora is found at {fedpkg}.
====

You can also set the base path to images (default: _empty_), icons (default: `./images/icons`), stylesheets (default: `./stylesheets`) and JavaScript files (default: `./javascripts`).

<<<<<<< HEAD
=======
[example]
>>>>>>> dc699963b50094f3083bef00945d6d602270b0f7
.Base path config example
[source]
----
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js
----

When you find yourself typing the same text repeatedly, or text that often needs to be updated, consider assigning it to a document attribute and use that instead.

<<<<<<< HEAD
NOTE: If you're familiar with writing in XML, you'll recognize document attributes as (custom text) entities.
=======
NOTE: If you're used to XML, you'll know document attributes as User Entities.
>>>>>>> dc699963b50094f3083bef00945d6d602270b0f7

Attribute entries have the following characteristics:

Attributes entries can::
* be assigned to a document:
** through the CLI
** in the document's header
** in the document's body
* be unset (turned off) with a `!`
* have default values, which are set when the user leaves the value field empty
<<<<<<< HEAD
* span multiple lines
* override some intrinsic attributes
=======
* have alternate values
* span multiple lines
* override config files, intrinsic attributes
>>>>>>> dc699963b50094f3083bef00945d6d602270b0f7
* include inline AsciiDoc content.

Attribute entries can not::

<<<<<<< HEAD
* override attributes assigned from the command line
=======
* override attributes issued from the command line
>>>>>>> dc699963b50094f3083bef00945d6d602270b0f7
** a number of entry attributes can also be used on the command line
* include AsciiDoc block content (for example, bulleted lists or other types of whitespace-dependent markup)

==== Attribute entry substitutions

The `header` substitution group is applied to the header of your document.
<<user-manual#subs,Text substitution elements>> replace characters, markup, attribute references, and macros with converter specific styles and values.
When Asciidoctor processes a document it uses a set of six text substitution elements.
In the header, only <<user-manual#special-characters,special characters>> and <<user-manual#attributes-2,attribute references>> are replaced.

However, if you require other substitutions to be applied to an attribute's value, use the <<user-manual#pass-mac,pass inline macro>>.
This macro has special meaning in an attribute entry.
It allows the substitutions to be applied at the time the attribute is defined.

The pass inline macro accepts a list of substitutions in the `target` slot.
In the next example, we'll apply the <<user-manual#quotes,quotes substitution>> to an attribute entry's value.

[source]
----
:app-name: pass:quotes[MyApp^(C)^]
----

You can also specify the substitution using the single-character alias, `q`.

[source]
----
:app-name: pass:q[MyApp^(C)^]
----

Another approach is to change the order of substitutions that are applied where the attribute is referenced.

[source]
----
:app-name: MyApp^(C)^

[subs="specialcharacters,attributes,quotes,replacements,macros,post_replacements"]
The application is called {app-name}.
----

==== Splitting attribute entry values over multiple lines

===== Splitting long value strings

<<<<<<< HEAD
Use a forward-slash `\` at the end of each attribute value line to split long listings.

.A long, single line attribute
[source,asciidoc]
----
:long_verbose: Sometimes you have long lines of text in an attribute. You may find it more readable if you split these up neatly in the header. Doing this will help other readers understand the attribute value contents without scrolling.
----

To split the block up and make it more readable, insert a forward-slash (`\`) at the end of the line to extend the value to the next line.

.A long, logically-split attribute
[source]
----
:long_verbose: Sometimes you have long lines of text in an attribute.\
You may find it more readable if you split these up neatly in the header.\
Doing this will help other readers understand the attribute value contents without scrolling.\
=======
Use backslashes `\` at the end of each attribute value to split long listings.

[example]
.A long, single line attribute
[source,asciidoc]
----
:long_verbose: If you have a very long line of text that you need to substitute regularly in a document, you may find it easier to split it neatly in the header so it remains readable to the next person reading your docs code.
----

To split the block up and make it more readable, insert a  forward-slash (`\`) at the end of the line to extend the value to the next line.

[example]
.A long, logically-split attribute
[source]
----
:long_verbose: If you have a very long line of text \
that you need to substitute regularly in a document, \
you may find it easier to split it neatly in the header \
so it remains readable to folks reading your docs code.
>>>>>>> dc699963b50094f3083bef00945d6d602270b0f7
----

NOTE: You can leave long lines as they are. Splitting attribute entry values such as the preceding example is only suggested for docs code readability.

===== Preserving endlines

<<<<<<< HEAD
Endlines are removed when the document is processed, unless a plus symbol surrounded by spaces (`&nbsp;+ \`) appears before the trailing backslash.

=======
Endlines are removed when the document is processed, unless a plus symbol surrounded by spaces (`+ \`) appears before the trailing backslash.

[example]
>>>>>>> dc699963b50094f3083bef00945d6d602270b0f7
.When endlines matter
[source]
----
:haiku: Write your docs in text, + \
AsciiDoc makes it easy, + \
Now get back to work! + \
----

<<<<<<< HEAD
This syntax ensures that the newlines are preserved in the output document as hard line breaks.
=======
Preserving endlines allows you to split an attribute value across multiple lines.
>>>>>>> dc699963b50094f3083bef00945d6d602270b0f7

===== Limitations

Attributes let you do a surprising amount of formatting for what is fundamentally a text replacement tool.

It may be tempting to try and extend attributes to be used for complex replaceable markup.

Supported::
  Basic in-line AsciiDoc markup is permitted in attribute values, such as:
* *emphasis*
* `literal text`.

Unsupported::
  Complex AsciiDoc markup is not permitted in attribute values, such as:
* lists
* multiple paragraphs
* other whitespace-dependent markup types.

////
TODO: This section actually might make more sense in the header section.

The main focus of the learning for this documentation is how to use inline formatting in an attribute value. Normally, inline formatting in an attribute value is not interpreted because:

a. Inline formatting is not applied when an attribute is set (attribute holds raw value)
b. Inline formatting is not applied when an attribute is referenced since the relevant substitutions come before attributes are resolved
////
