////
Included in:

- user-manual: Attributes
////

// tag::intro[]
Attributes are one of the features that sets Asciidoctor apart from other lightweight markup languages.
Attributes activate features and store predefined styles, options, and replacement content.

In Asciidoctor, attributes are classified as:

* Intrinsic Attributes
* Attribute Entrys
* Attribute Lists
* BlockId Elements
* Macros
* API and Command Line Attributes
// end::intro[]

// tag::attributesyntax[]
=== Attribute restrictions

All attributes have a name and value.
The name:

- is at least one character long
- begins with a word character (A-Z, a-z, 0-9 or _)
- contains only word characters and hyphens

// redundant but a lot of people want to put dots in it
so it cannot contain dots or spaces.

Case is ignored, so `APPLE` `Apple` and `aPPle` are all the same, ie `apple`.
// Opinion
It is good practise to only use lower case, and not begin with a number.

The value can be almost anything, but it cannot contain line breaks.
Certain attributes have a restricted range of allowable values - see the individual attribute definitions for details.
// end::attributesyntax[]

=== Attribute assignment precedence
// tag::order[]
By default, the attribute assignment precedence, from highest to lowest, is as follows:

- Attribute passed to the API or CLI
- Attribute defined in the document
- Intrinsic attribute value (default values)

Let's use the `doctype` attribute to show how precedence works.

The intrinsic value for the doctype attribute is `article`.
Therefore, if doctype is not set and assigned a value in the document, API or CLI it will be assigned the article value (i.e. its default value).
However, if doctype is set in the document and assigned a new value, such as `book`, the book value will override the intrinsic value.
Finally, a value assigned to doctype via the API or CLI, will overrule the value in the document.

You can adjust the precedence of attribute values passed to the API or CLI.
By adding an `@` symbol to the end of an attribute value passed to the API or CLI, it makes that assignment have a lower precedence than an assignment in the document.

Let's add that to the precedence list defined earlier.

- Attribute passed to the API or CLI that does not end in `@`
- Attribute defined in the document
- Attribute passed to the API or CLI that ends in `@`
- Intrinsic attribute value (default values)
// end::order[]
