////
Included in:

- user-manual: Attributes
////

// tag::intro[]
Attributes are one of the features that sets Asciidoctor apart from other lightweight markup languages.
Attributes can activate features (behaviors, styles, integrations, etc) or hold replacement (i.e., variable) content.

In Asciidoctor, attributes are classified as:

* <<env-attributes,Environment attributes>>
* <<builtin-attributes,Built-in attributes>>
* <<charref-attributes,Predefined attributes>>
* <<glossary,User-defined attributes>>
* <<attribute-assignment-precedence,API and Command Line Attributes>>
* <<setting-attributes-on-an-element,Element Attributes>>
// end::intro[]

// tag::attributesyntax[]
=== Attribute Restrictions

All attributes have a name and a value (though the value may be implicit).

The attribute name:

* must be at least one character long,
* must begin with a word character (A-Z, a-z, 0-9 or _) and
* must only contain word characters and hyphens.

In other words, the name cannot contain dots or spaces.

Although uppercase characters are permitted in an attribute entry (the place where an attribute is defined), the attribute name is converted to lowercase before being stored.
The attribute name in an attribute reference is also converted to lowercase before the attribute is resolved.
For example, `URI`, `Uri` and `uRI` are all treated as `uri`.
(See https://github.com/asciidoctor/asciidoctor/issues/509[issue #509] for a proposed change to this restriction).
A best practice is to only use lowercase for letters in the name and avoid starting the name with a number.

The attribute value:

* can be any inline content and
* can only contain line breaks if an explicit line continuation is used.

Certain attributes have a restricted range of allowable values.
See the entries in the <<attribute-catalog>> for details.
// end::attributesyntax[]

=== Attribute Assignment Precedence
// tag::order[]
The attribute assignment precedence, listed from highest to lowest, is as follows:

* An attribute passed to the API or CLI
* An attribute defined in the document
* The default value of the attribute, if applicable

Let's use the `doctype` attribute to show how precedence works.

The default value for the `doctype` attribute is `article`.
Therefore, if the `doctype` attribute is not assigned a value (either in the document, API, or CLI), the processor will assign it the default value of `article`.
If the `doctype` attribute is set in the document (i.e., assigned a new value, such as `book`), that value will override the default value.
Finally, if a value is assigned to the `doctype` attribute via the API or CLI, that value will override both the default value and the value assigned in the document.

You can adjust the precedence of attribute values passed to the API or CLI by adding the `@` override modifier to the end of the attribute value (or, since 1.5.7, the end of the attribute name).
Adding this modifier lowers the precedence of an attribute (assigned using the API or CLI) so the document can override the value.

Let's update the attribute assignment precedence list defined earlier to reflect this additional rule:

* An attribute passed to the API or CLI
* An attribute defined in the document
* An attribute passed to the API or CLI whose value (or, since 1.5.7, name) ends in `@`
* The default value of the attribute, if applicable
// end::order[]
