////
Included in:

- user-manual: Attributes: Setting attributes on a document
////

An attribute entry is the primary mechanism used to define an attribute in a document.

.Anatomy of an attribute entry
----
:name: value
----

An attribute entry consists of the attribute's name and its value.
The attribute's name comes first and must be surrounded by colons.
The attribute's value is offset from the name part by at least one space.
The value is optional.

Once set, an attribute (and its value) are available for use throughout the remainder of the document.
Attribute entries are used to toggle settings on and off or to set configuration variables that control the output generated by the AsciiDoc processor.

Attributes are typically defined in the document header, though they may also be defined in the body of the document.
Many of the built-in attributes only take effect when defined in the document header.

For example, to enable the table of contents, you can define (i.e., set) the `toc` attribute using an attribute entry in the document header as follows:

----
:toc:
----

When the value following an attribute is left empty, as it is in the example above, the default value will be assigned.
The default value for `toc` is `auto`; therefore, the table of contents will be placed in the default location (below the document's title) when the document is rendered.
If you want the table of contents to be placed on the right side of the document, you must assign the attribute a new value.

----
:toc: right
----

The `right` value will override the default value.
The value assigned to an attribute in the document header will replace the intrinsic value (assuming the attribute is not locked).

Attributes are also used to store URLs.

.URL attribute entry
----
:uri-fedpkg: https://apps.fedoraproject.org/packages/asciidoc
----

Now you can refer to this attribute entry anywhere in the document (where attribute substitution is performed) by surrounding its name in curly braces:

.uri-fedpkg attribute usage example
----
Information about the AsciiDoc package in Fedora is found at {uri-fedpkg}.
----

You can also set the base path to images (default: _empty_), icons (default: `./images/icons`), stylesheets (default: `./stylesheets`) and JavaScript files (default: `./javascripts`).

.Base path config example
----
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js
----

When you find yourself typing the same text repeatedly, or text that often needs to be updated, consider assigning it to a document attribute and use that instead.

NOTE: If you're familiar with writing in XML, you'll recognize document attributes as user-defined entities.

Attribute entries have the following characteristics:

Attributes entries can::
* be assigned to a document:
** through the CLI or API
** in the document's header
** in the document's body
* be unset (turned off) with a leading (or trailing) `!` added to the name
* have default values (in the case of a built-in attribute)
* have alternate values (in the case of a built-in attribute)
* span multiple, contiguous lines
* include inline AsciiDoc content

Attribute entries can not::

* override locked attributes assigned from the command line
* include AsciiDoc block content (such as, bulleted lists or other types of whitespace-dependent markup)

==== Substitutions in an attribute entry

The `header` substitution group is applied to the header of your document.
<<user-manual#subs,Text substitution elements>> replace characters, markup, attribute references, and macros with converter specific styles and values.
When Asciidoctor processes a document it uses a set of six text substitution elements.
In the header, only <<user-manual#special-characters,special characters>> and <<user-manual#attributes-2,attribute references>> are replaced.

However, if you require other substitutions to be applied to an attribute's value, use the <<user-manual#pass-macros,inline pass macro>>.
This macro has special meaning in an attribute entry.
It allows the substitutions to be applied at the time the attribute is defined.

The inline pass macro accepts a list of substitutions in the `target` slot.
In the next example, we'll apply the <<user-manual#quotes,quotes substitution>> to an attribute entry's value.

----
:app-name: pass:quotes[MyApp^(C)^]
----

You can also specify the substitution using the single-character alias, `q`.

----
:app-name: pass:q[MyApp^(C)^]
----

Another approach is to change the order of substitutions that are applied where the attribute is referenced.

----
:app-name: MyApp^(C)^

[subs="specialchars,attributes,quotes,replacements,macros,post_replacements"]
The application is called {app-name}.
----

==== Splitting attribute values over multiple lines

When an attribute value is very long, it's possible to split it (i.e., soft-wrap) across multiple lines.

Let's assume we are working with the following attribute entry:

.A long, single-line attribute
----
:long-value: If you have a very long line of text that you need to substitute regularly in a document, you may find it easier to split it neatly in the header so it remains readable to the next person reading your docs code.
----

You can split the value over multiple lines to make it more readable by inserting a space followed by a backslash (i.e., `{sp}\`) at the end of each continuing line.

.A long, multiline attribute (soft wrapped)
----
:long-value: If you have a very long line of text \
that you need to substitute regularly in a document, \
you may find it easier to split it neatly in the header \
so it remains readable to folks reading your docs code.
----

The backslash and the newline that follows will be removed from the attribute value when the attribute entry is parsed, making this second example effectively the same as the first.
The space before the backslash is preserved, so you have to use this technique at a natural break point in the content.

You can force an attribute value to hard wrap by adding a plus surrounded by spaces before the backslash.

.An attribute value with hard line breaks
----
:haiku: Write your docs in text, + \
AsciiDoc makes it easy, + \
Now get back to work!
----

This syntax ensures that the newlines are preserved in the output document as hard line breaks.

==== Attribute limitations

Attributes let you do a surprising amount of formatting for what is fundamentally a text replacement tool.

It may be tempting to try and extend attributes to be used for complex replaceable markup.

Supported::
Basic in-line AsciiDoc markup is permitted in attribute values, such as:
* attribute references
* text formatting (usually wrapped in a pass macro)
* inline macros (usually wrapped in a pass macro)

Unsupported::
Complex AsciiDoc markup is not permitted in attribute values, such as:
* lists
* multiple paragraphs
* other whitespace-dependent markup types

////
TODO: This section actually might make more sense in the header section.

The main focus of the learning for this documentation is how to use inline formatting in an attribute value. Normally, inline formatting in an attribute value is not interpreted because:

a. Inline formatting is not applied when an attribute is set (attribute holds raw value)
b. Inline formatting is not applied when an attribute is referenced since the relevant substitutions come before attributes are resolved
////
