////
Included in:

- user-manual: Attributes
////

// tag::intro[]
Attributes are one of the features that sets Asciidoctor apart from other lightweight markup languages.
Attributes activate features and store predefined styles, options, and replacement content.

In Asciidoctor, attributes are classified as:

* <<env-attributes,Environment attributes>>
* <<builtin-attributes,Built-in attributes>>
* <<charref-attributes,Predefined attributes>>
* <<glossary,User defined attributes>>
* <<setting-attributes-on-an-element,Attribute Lists>>
// dont know what this means
//* BlockId Elements
* <<attribute-assignment-precedence,API and Command Line Attributes>>
// end::intro[]

// tag::attributesyntax[]
=== Attribute Restrictions

All attributes have a name and a value.

The attribute name:

- must be at least one character long,
- must begin with a word character (A-Z, a-z, 0-9 or _) and
- must only contain word characters and hyphens.

In other words, the name cannot contain dots or spaces.

Currently, case is ignored when resolving attributes, so `URI`, `Uri` and `uRI` are all the same as `uri`.
(See https://github.com/asciidoctor/asciidoctor/issues/509[issue #509] for a proposed change to this restriction).
A best practice is to only use lower case in the name and avoid starting the name with a number.

The attribute value:

- can be any inline content and
- can only contain line breaks if an explicit line continuation is used.

Certain attributes have a restricted range of allowable values.
See the individual attribute definitions for details.
// end::attributesyntax[]

=== Attribute Assignment Precedence
// tag::order[]
By default, the attribute assignment precedence, from highest to lowest, is as follows:

- Attribute passed to the API or CLI
- Attribute defined in the document
- Default value

Let's use the `doctype` attribute to show how precedence works.

The default value for the doctype attribute is `article`.
Therefore, if doctype is not set and assigned a value in the document, API or CLI it will be assigned the article value (i.e. its default value).
However, if doctype is set in the document and assigned a new value, such as `book`, the book value will override the default value.
Finally, a value assigned to doctype via the API or CLI, will overrule the value in the document.

You can adjust the precedence of attribute values passed to the API or CLI.
By adding an `@` symbol to the end of an attribute value passed to the API or CLI, it makes that assignment have a lower precedence than an assignment in the document.

Let's add that to the precedence list defined earlier.

- Attribute passed to the API or CLI that does not end in `@`
- Attribute defined in the document
- Attribute passed to the API or CLI that ends in `@`
- Default value
// end::order[]
