= Predefined attributes for character replacements

// tag::table[]
.Predefined attributes for character replacements^[1]^
[width="75%", cols="^4l,^3l,^3"]
|===
|Attribute reference |Replacement text |Appearance

|\{blank}
\{empty}
|_nothing_
|{empty}

|\{sp}
|_single space_
|{sp}

|\{nbsp}
|\&#160;
|{nbsp}

|\{zwsp}^[2]^
|\&#8203;
|{zwsp}

|\{wj}^[3]^
|\&#8288;
|{wj}

|\{apos}
|\&#39;
|{apos}

|\{quot}
|\&#34;
|{quot}

|\{lsquo}
|\&#8216;
|{lsquo}

|\{rsquo}
|\&#8217;
|{rsquo}

|\{ldquo}
|\&#8220;
|{ldquo}

|\{rdquo}
|\&#8221;
|{rdquo}

|\{deg}
|\&#176;
|{deg}

|\{plus}
|\&#43;
|{plus}

|\{brvbar}
|\&#166;
|&#166;

|\{vbar}
|{vbar}
|{vbar}

|\{amp}
|&
|&

|\{lt}
|<
|<

|\{gt}
|>
|>

|\{startsb}
|[
|[

|\{endsb}
|]
|]

|\{caret}
|^
|^

|\{asterisk}
|*
|*

|\{tilde}
|~
|~

|\{backslash}
|\
|\

|\{backtick}
|`
|`

|\{two-colons}
|::
|::

|\{two-semicolons}
|;;
|;;

|\{cpp}
|C++
|C++
|===

^[1]^ Some replacements are Unicode characters, whereas others are https://en.wikipedia.org/wiki/Numeric_character_reference[numeric character references].
The character references (e.g., \&#34;) are used whenever the Unicode character might otherwise interfere with the AsciiDoc syntax or confuse the renderer (i.e., the browser).
The idea is to output text that just works.
It's up to the converter to transform this text into something the viewer understands (for example, in the case of manpage or PDF output).

^[2]^ The Zero Width Space (ZWSP) is a code point in Unicode that shows where a long word can be split if necessary.

^[3]^ The word joiner (WJ) is a code point in Unicode prevents a line break at its position.
// end::table[]
