////
Included in:

- user-manual
////

You can group the sections of your document into parts.
Parts can only be used when the `doctype` is `book`.
Part titles are specified with a single equals sign (`=`), the equivalent to a document title, i.e. section level 0.
After the part title, you can include an optional introduction, which is designated by the `partintro` attribute.

----
[partintro]
.Optional part introduction title
--
Optional part introduction goes here.
--
----

A part can also include its own preface, bibliography, glossary and index.

----
include::multi-special-ex.adoc[tags=part]
----

When using the PDF converter (i.e., Asciidoctor PDF), the value of the `chapter-label` attribute (followed by a space) is automatically added to the beginning of the chapter title.
A chapter title is a level-1 section title when the doctype is book.

You can modify this prefix by redefining the `chapter-label` attribute.

----
:chapter-label: Chapter ~
----

To use no prefix, set the value to blank.
