////
Included in:

- user-manual: callouts: Callouts don't get caught in copy
////

In versions prior to Asciidoctor 0.1.4, when a reader visiting an HTML page generated by Asciidoctor selected source code from a listing that contained callouts and copied it, the callout numbers would get caught up in the copy.
If the reader pasted that code and tried to run it, likely the extra characters from the callouts caused compile or runtime errors.

Asciidoctor uses CSS to prevent callouts from being selected.

On the other side of the coin, you don't want the callout annotations or CSS messing up your raw source code either.
You can tuck your callouts neatly inside line comments.
Asciidoctor will recognize the line comments characters in front of a callout number, optionally offset by a space, and remove them when rendering the document.

Here are the line comments that are supported:

[source]
....
----
line of code  // \<1>
line of code   # \<2>
line of code  ;; \<3>
----
<1> A callout behind a line comment for C-style languages.
<2> A callout behind a line comment for Ruby, Python, Perl, etc.
<3> A callout behind a line comment for Clojure.
....

Here's how it looks when rendered:

----
line of code  // <1>
line of code  # <2>
line of code  ;; <3>
----
<1> A callout behind a line comment for C-style languages.
<2> A callout behind a line comment for Ruby, Python, Perl, etc.
<3> A callout behind a line comment for Clojure.

WARNING: Asciidoctor enforces that callouts be placed at the end of the line.
