////
== Conditional Include Directive

- User manual
////
You can include or exclude lines of text in your document from being processing by specifying three conditional include directives:

* ifdef
* ifndef
* ifeval

These conditions allow the processor to make decisions about whether to processes content, based on facts.

The facts are typically the existence and/or value of:

* document-level attributes, either:
** built-in,
** implicit.
* defined in one of the following ways:
** in the document
** passed through the API or CLI.

For example, you may only want to include (or not include) certain content when using the html5 backend.

In order to do that, you'd check for the existence of the backend-html5 attribute using a conditional include directive.

Specific examples are described in each section.

=== ifdef Directive

Content between the `ifdef` and `endif` directives is processed when the content is built:

.ifdef example
[source,asciidoc]
----
ifdef::env-github[]
This content is for GitHub only.
endif::[]
----

If you have a large amount of content (especially AsciiDoc content) between the `ifdef` directive, you may find it more human-readable if you use the (optional) long-form version of the directive.

.ifdef long-form example
[source,asciidoc]
----
\ifdef::env-github[]
This content is for GitHub only.

So much content in this section, I'd get confused reading the source without the closing `ifdef` directive.

It isn't necessary for short blocks, but if you are conditionally including a section it may be something worth considering.

Other readers reviewing your docs source code may go cross-eyed when reading your source docs if you don't.
\endif::env-github[]
----

TIP: A great example of long-form conditional formatting is the source of this Users Guide! We use it to show and hide entire sections when building individual content for separate guides.

If you only want to process a single line of text, it can be put inside the square brackets, which removes the requirement for the `endif` directive.

.ifdef single line example
[source,asciidoc]
----
\ifdef::revnumber[Version number 42]
----

The single-line block above is equivalent to this full `ifdef` directive:

[source,asciidoc]
----
\ifdef::revnumber[]
Version number 42
\endif::[]
----

=== ifndef Directive

`ifndef` is the opposite of `ifdef`.

Content between `ifndef` and `endif` is *not* processed when the content is built.

.ifndef Example
[source,asciidoc]
----
\ifndef::env-github[]
This content is not processed unless specified.
\endif::[]
----

=== Multiple ifdef and ifndef attributes

`ifdef` and `ifndef` macros also accept multiple attribute names.

Multiple comma-separated (,) directive names evaluate to true if one or more of the directives is defined, otherwise it’s value is undefined.

Multiple plus-separated (+) directive names evaluate to true if all of the directives are defined, otherwise it’s value is undefined.

=== ifeval directive

Content between `ifeval` and `endif` is processed if the expression inside the square brackets is true.

.ifeval example
[source,asciidoc]
----
\ifeval::[{sectnumlevels} == 3]
If the `sectnumlevels` attribute is set to `3`, this sentence is processed.
\endif::[]
----

==== Anatomy

The expression consists of a left-hand value and a right-hand value with an operator in between.

.ifeval expression examples
[source,asciidoc]
----
\ifeval::[2 > 1]
\ifeval::[{backend} == html5]
\ifeval::[{sectnumlevels} == 3]
----

==== Values

Each expression value can reference the name of an AsciiDoc attribute using the attribute reference syntax (for example, \{backend}).

Attribute references are resolved (substituted) first. Once attributes references have been resolved, each value is coerced to a recognized type.

The following values types are recognized:

number::
  Either an integer or floating-point value.
quoted string::
  Enclosed in either single (') or double (") quotes.
boolean::
  Literal value of `true` or `false`.

===== How conditional coercion works

If a value is enclosed in quotes, the characters between the quotes are preserved and coerced to a string.

If a value is not enclosed in quotes, it is subject to the following type coercion rules:

* an empty value becomes nil (aka null).
* a value of `true` or `false` becomes a boolean.
* a value of only repeating whitespace becomes a single whitespace string.
* a value containing a period becomes a floating-point number.
* any other value is coerced to an integer value.

==== Operators

The value on each side is compared using the operator to derive an outcome.

NOTE: The operators follow the same rules as operators in Ruby.

`==`::
  Checks if the two values are equal.
`!=`::
  Checks if the two values are not equal.
`\<=`::
  Checks whether the left-hand side is less than or equal to the right-hand side.
`>=`::
  Checks whether the left-hand side is greater than or equal to the right-hand side.
`<`::
  Checks whether the left-hand side is less than the right-hand side.
`>`::
  Checks whether the left-hand side is greater than the right-hand side.
