////
Included in:

- user-manual: DocBook
////

Asciidoctor 0.1.4 can produce DocBook 5.0 output, which is generated by the +docbook5+ backend.

The output from the +docbook5+ backend only differs from the +docbook45+ backend so far as to make it compliant to the DocBook 5.0 specification.
A summary of the differences are as follows:

* XSD declarations are used on the document root instead of a DTD
* +<info>+ elements for document info instead of +<articleinfo>+ and +<bookinfo>+
* elements that hold the author's name are wrapped in a +<personname>+ element
* the id for an element is defined using an +xml:id+ attribute
* +<link>+ is used for links instead of +<ulink>+
* the URL for a link is defined using the +xlink:href+ attribute

Refer to {docbook5-ref}[What's new in DocBook v5.0?] for more details about how DocBook 5.0 differs from DocBook 4.5.

To use the DocBook 5.0 backend, set the backend to +docbook5+, as shown in this example:

 $ asciidoctor -b docbook5 sample.adoc

Here's a sample DocBook 5.0 document generated by this backend:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns="http://docbook.org/ns/docbook"
    xmlns:xlink="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
  <info>
    <title>Hello, AsciiDoc!</title>
    <date>2013-09-03</date>
    <author>
      <personname>
        <firstname>Doc</firstname>
        <surname>Writer</surname>
      </personname>
      <email>doc@example.com</email>
    </author>
    <authorinitials>DW</authorinitials>
  </info>
  <simpara>
    An introduction to <link xlink:href="http://asciidoc.org">AsciiDoc</link>.
  </simpara>
  <section xml:id="_first_section">
    <title>First Section</title>
    <itemizedlist>
      <listitem>
        <simpara>item 1</simpara>
      </listitem>
      <listitem>
        <simpara>item 2</simpara>
      </listitem>
    </itemizedlist>
  </section>
</article>
```

[TIP]
====
The +xmlns+ attribute is now added to the root DocBook element by default.
Set the attribute +noxmlns+ to disable this feature.
====

Since the AsciiDoc syntax was designed with DocBook output in mind, the conversion is very good.
There's a corresponding DocBook element for each markup in the AsciiDoc syntax.

To convert the +mysample.adoc+ document to DocBook format, call the processor with the backend flag set to +docbook5+:

 $> asciidoctor -b docbook5 mysample.adoc

A new XML document, named +sample.xml+, will now be present in the current directory.

 $> ls
 mysample.adoc  mysample.html  mysample.xml

If you're on Linux, you can view the DocBook file with {yelp}[Yelp].

 $> yelp mysample.xml

Using the Asciidoctor Ruby API, you can generate a DocBook document directly from a Ruby application:

[source,ruby]
----
Asciidoctor.render_file('mysample.adoc', :in_place => true,
    :backend => 'docbook5')
----

DocBook is only an intermediary format in the toolchain.
You'll either feed it into a system that processes DocBook (like {publican}[publican]), or you can convert it to PDF using the +a2x+ command from AsciiDoc.
