////
Included in:

- user-manual: docinfo
////

You can add custom content to the header or footer of a document with document information ("docinfo") files.
The docinfo files are different for HTML and DocBook.

=== Create a docinfo head file

The docinfo file for html output can contain any of the elements allowed in an HTML `<HEAD>` section, including:

* `<base>`
* `<link>`
* `<meta>`
* `<noscript>`
* `<script>`
* `<style>`
* `<title>`

As seen in the example below, docinfo files are useful for storing metadata, stylesheet, and script information.
Note that you do not need to include the `<head>` tag, nor is the `<title>` tag required.

.A docinfo file for HTML output
[source,html]
----
<meta name="keywords" content="open source, documentation">
<meta name="description" content="The dangerous and thrilling adventures of an open source documentation team.>
<link rel="stylesheet" href="basejump.css">
<script src="map.js"></script>
----

Docinfo files for HTML output must be saved with the `.html` file extension.

The docinfo file for DocBook 5.0 output may include any of the {docbook-info-ref}[<info> element's 48 children], such as:

* `<address>`
* `<copyright>`
* `<edition>`
* `<keywordset>`
* `<publisher>`
* `<subtitle>`
* `<revhistory>`

The following example shows some of the content a docinfo file for DocBook might contain.

.A docinfo file for DocBook 5.0 output
[source,xml]
----
<author>
  <personname>
    <firstname>Karma</firstname>
    <surname>Chameleon</surname>
  </personname>
  <affiliation>
    <jobtitle>Word SWAT Team Leader</jobtitle>
  </affiliation>
</author>

<keywordset>
  <keyword>open source</keyword>
  <keyword>documentation</keyword>
  <keyword>adventure</keyword>
</keywordset>

<printhistory>
  <para>April, 2019. Twenty-sixth printing.
  </para>
</printhistory>
----

Docinfo files for DocBook output must be saved with the `.xml` file extension.
To see another example of a docinfo file for DocBook, checkout the {richfaces-docinfo}[RichFaces Developer Guide docinfo file].

=== Footer docinfo files

Footer docinfo files are differentiated from header docinfo files by adding `-footer` to the file name.
In the HTML output, the footer content is inserted immediately after the footer div (that is, `<div id="footer">`).
In the DocBook output, the footer content is inserted immediately before the ending `</article>` or `</book>` element.

TIP: To change the text in the "Last updated" line in the footer, set the text in the attribute `last-update-label` (for example, `:last-update-label: <your text> Last Updated`). +
To disable the "Last updated" line in the footer, unassign the attribute `last-update-label` (however, this leaves an empty footer div). +
To disable the footer completely, set the attribute `nofooter`. Then having a footer docinfo file effectively replaces the default footer with your custom footer.

=== Naming docinfo files

The file name depends on the backend it is for, and whether it is for a specific document ("private") or for all the documents in a directory ("shared").

.Docinfo file naming
[cols="<20,<30,<30,<30"]
|====
|Mode |Behaviour |docinfo file names for HTML |docinfo file names for DocBook


|Private
|Add content to document <docname>.adoc only
|`<docname>-docinfo.html`

`<docname>-docinfo-footer.html`
|`<docname>-docinfo.xml`

`<docname>-docinfo-footer.xml`

|Shared
|Add content to all documents in the same Asciidoctor run.
|`docinfo.html`

`docinfo-footer.html`

|`docinfo.xml`

`docinfo-footer.xml`

|====

To specify which file(s) you want to apply, set the `docinfo` attribute to any combination of these values:

`private-head`, `private-footer`, `shared-head`, `shared-footer`, `private`, or `shared`.

eg

 :docinfo: shared,private-footer

will apply the shared docinfo header and footer files if they exist AND the private footer file if it exists. 
(`shared` is shorthand for `shared-head,shared-footer`).

`docinfo` has no default value, so `:docinfo:` by itself is an error. *CHECK*

// leave this in until 1.6 then move them to the legacy guide.
[NOTE]
====
`docinfo` values and `docinfodir` were introduced in Asciidoctor 1.5.5.
Here are the equivalents of the old attributes using the new values:

`:docinfo:` = `:docinfo: private`

`:docinfo1:` = `:docinfo: shared`

`:docinfo2:` = `:docinfo: shared,private`

====

=== Locating docinfo files

By default, docinfo files are searched for in the same folder as the document file. 
If you want to keep them anywhere else, set the `docinfodir` attribute to their location:

 :docinfodir: common/meta

Note that if you use this attribute, ONLY the specified folder will be searched; any docinfo files in the document folder will not be found.


Let's apply the information above to an example.

You have two AsciiDoc documents, adventure.adoc and insurance.adoc, saved in the same folder.
You want to add the same content to the headers of both documents when they're rendered to HTML.

. Create a docinfo file using <head> elements.
. Save it as docinfo.html.
. Set the `docinfo` attribute in adventure.adoc and insurance.adoc to `shared`.

You also want to include some additional content, but only to the header of adventure.adoc.

. Create *another* docinfo file using <head> elements.
. Save it as adventure-docinfo.html.
. Set the `docinfo` attribute in adventure.adoc to `shared,private-head`

Actually, in this case you could have set `docinfo` to `shared,private` in both documents with the same effect, as the folder does not have a private docinfo file for insurance.adoc. *CHECK*

=== Attribute substitution

Docinfo files can include attribute references.

For example, if you created the following docinfo file:

.Docinfo file containing a revnumber attribute reference
[source,xml]
----
<edition>{revnumber}</edition>
----

And this source document:

.Source document including a revision number
----
= Document Title
Author Name
v1.0, 2013-06-01
:doctype: book
:backend: docbook
:docinfo:
----

Then the rendered DocBook output would be:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns="http://docbook.org/ns/docbook"
    xmlns:xlink="http://www.w3.org/1999/xlink" version="5.0" lang="en">
  <info>
    <title>Document Title</title>
    <date>2013-06-01</date>
    <author>
      <personname>
        <firstname>Author</firstname>
        <surname>Name</surname>
      </personname>
    </author>
    <authorinitials>AN</authorinitials>
    <revhistory>
      <revision>
        <revnumber>1.0</revnumber> <!--1-->
        <date>2013-06-01</date>
        <authorinitials>AN</authorinitials>
      </revision>
    </revhistory>
  </info>
</book>
----
<1> The revnumber attribute reference was replaced by the source document's revision number in the rendered output.

