////
Included in:

- user-manual: Document Types
////

Article::
Default doctype.
In DocBook, includes the appendix, abstract, bibliography, glossary, and index sections

Book::
The same as articles with the additional ability to use a top level title as part titles, includes the appendix, dedication, preface, bibliography, glossary, index, and colophon.

Inline::
+
--
Asciidoctor only.
There may be cases when you only want to apply inline AsciiDoc formatting to input text without wrapping it in a block element.
For example, in the {asciidoclet-ref}[Asciidoclet project] (AsciiDoc in Javadoc), only the inline formatting is needed for the text in Javadoc tags.

The rules for the inline doctype are as follows:

* Only a single paragraph is read from the AsciiDoc source.
* Inline formatting is applied.
* The output is not wrapped in the normal paragraph tags.

Given the following input:

[source,asciidoc]
http://asciidoc.org[AsciiDoc] is a _lightweight_ markup language...

Processing it with the options `doctype=inline` and `backend=html5` produces:

[source,html]
<a href="http://asciidoc.org">AsciiDoc</a> is a <em>lightweight</em> markup language&#8230;

The Asciidoctor processor is now able to cover the full range of output, from unstructured (inline) text to a full, standalone document!
--

Man page::
Used to generate roff format UNIX manual pages.  
{adr} manpage documents observe special header title and section naming conventions
-- see the <<man-pages>> section for details.



