////
Included in:

- user-manual: Macro and Block Passthroughs
- quick-ref
////

// tag::dollar[]
$$*Stars*$$ will not be bold.
// end::dollar[]

// tag::b-dollar[]
$$*Stars*$$ is not rendered as bold text.
The asterisks around the word are preserved.

$$&amp;$$ renders as an XML entity instead of &.
// end::b-dollar[]

// tag::in-macro[]
The markup pass:[<u>underline me</u>] renders as underlined text.
// end::in-macro[]

// tag::3p[]
The markup +++<u>underline me</u>+++ renders as underlined text.
// end::3p[]

// tag::b-3p-macro[]
+++<u>underline me</u>+++ renders as underlined text.

pass:[<u>underline me</u>] also renders as underlined text.
// end::b-3p-macro[]

// tag::tick[]
This java code: `System.out.println("No *bold* here");` will appear in a monospace font but without any other text formatting.
// end::tick[]

// tag::b-tick[]
`Text in {backticks}` renders exactly as entered, in monospace.
The attribute reference is not resolved.
// end::b-tick[]

// tag::sub-in[]
[subs="verbatim,macros"] <1>
----
I better not be *bold* or _italic_.
pass:quotes[But I should be *bold* text] <2>
----
// end::sub-in[]

// tag::sub-out[]
[subs="verbatim,macros"]
----
I better not contain *bold* or _italic_ text.
pass:quotes[I should contain *bold* text]
----
// end::sub-out[]

// tag::bl[]
++++
<video poster="images/movie-reel.png">
  <source src="videos/writing-zen.webm" type="video/webm">
</video>
++++
// end::bl[]

// tag::b-bl[]
++++
<p>
Content in a passthrough block is passed to the output unprocessed.
That means you can include raw HTML, like this embedded Gist:
</p>

<script src="http://gist.github.com/mojavelinux/5333524.js">
</script>
++++
// end::b-bl[]
