////
Included in:

- user-manual: Paragraphs
- user-manual: Text formatting
- quick-syntax
////

// tag::para[]
This journey begins one late Monday afternoon in Antwerp.
Our team desperately needs coffee, but none of us dare open the office door.

To leave means code dismemberment and certain death.
// end::para[]

// tag::b-para[]
Paragraphs don't require any special markup in AsciiDoc.
A paragraph is just one or more lines of consecutive text.

To begin a new paragraph, separate it by at least one blank line.
// end::b-para[]

// tag::hb[]
Rubies are red, +
Topazes are blue.
// end::hb[]

// tag::hb-p[]
[%hardbreaks]
Ruby is red.
Java is black.
// end::hb-p[]

// tag::b-hb[]
To preserve a line break, end the line in a space followed by a plus sign. +
This results in a visible line break (e.g., +<br>+) between the lines.
// end::b-hb[]

// tag::hb-attr[]
= Line Break Doc Title
:hardbreaks:

Rubies are red,
Topazes are blue.
// end::hb-attr[]

// tag::lead[]
[.lead]
This is the ultimate paragraph.
// end::lead[]

// tag::b-lead[]
[.lead]
This text will be styled as a lead paragraph (i.e., larger font).
// end::b-lead[]

// tag::b-i[]
_To tame_ the wild wolpertingers we needed to build a *charm*.
But **u**ltimate victory could only be won if we divined the *_true name_* of the _&#8239;_war_&#8239;_lock.
// end::b-i[]

// tag::b-i-n[]
_To tame_ the wild wolpertingers we needed to build a *charm*.
But **u**ltimate victory could only be won if we divined the *_true name_* of the __war__lock.
// end::b-i-n[]

// tag::b-bold-italic-mono[]
_italic phrase_

__i__talic le__tt__ers

*bold phrase*

**b**old le**tt**ers

*_bold italic phrase_*

**__b__**old italic le**__tt__**ers

+monospace phrase+ and le++tt++ers

+_monospace italic phrase_+ and le++__tt__++ers

+*monospace bold phrase*+ and le++**tt**++ers

+*_monospace bold italic phrase_*+ and le++**__tt__**++ers

`inline literal passthrough` (monospace text without substitutions)
// end::b-bold-italic-mono[]

// tag::c-quote[]
``What kind of charm?'' Lazarus asked. ``An odoriferous one or a mineral one?''

Kizmet shrugged. ``The note from Olaf's desk says `wormwood and licorice,' but these could be normal groceries for werewolves.''
// end::c-quote[]

// tag::b-c-quote[]
`single smart quotes'

``double smart quotes''
// end::b-c-quote[]

// tag::apos[]
Olaf's desk overflowed with heaps of paper, apple cores and squeaky toys.
We couldn't find his keyboard.
The state of his desk was replicated, sometimes in triplicate, across all of the werewolves' desks.
// end::apos[]

// tag::sub-sup[]
``Well the H~2~O formula written on their whiteboard could be part of a shopping list, but I don't think the local bodega sells E=mc^2^,'' Lazarus replied.
// end::sub-sup[]

// tag::b-sub-sup[]
^super^script phrase

~sub~script phrase
// end::b-sub-sup[]

// tag::mono[]
``Wait!'' Indigo plucked a small vial from her desk's top drawer and held it toward us.
The vial's label read ``++E=mc^2^++; +the scent of science+; +_smell like a genius_+.''
// end::mono[]

// tag::b-mono-code[]
Reference code like +types+ or +methods+ inline.
// end::b-mono-code[]

// tag::css[]
Do werewolves believe in [small]#small print#?

[big]##O##nce upon an infinite loop.
// end::css[]

////
phrase styled by CSS class .small#
////
