////
Included in:

- user-manual: URL
- quick-ref
////

// tag::base[]
La page d'accueil du projet AsciiDoctor est https://asciidoctor.org.

Discutez avec d'autres utilisateurs d'AsciiDoctor sur le irc://irc.freenode.org/#asciidoctor[canal IRC d'AsciiDoctor].

Posez vos questions sur la http://discuss.asciidoctor.org/[*mailing list*].
// end::base[]

// tag::base-co[]
La page d'accueil du projet AsciiDoctor est https://www.asciidoctor.org. // <1>
// end::base-co[]

// tag::irc[]
Discutez avec d'autres utilisateurs d'AsciiDoctor sur le irc://irc.freenode.org/#asciidoctor[canal IRC AsciiDoctor].

// end::irc[]

// tag::text[]
Posez vos questions sur la http://discuss.asciidoctor.org/[*mailing list*].
// end::text[]

// tag::scheme[]
Pour obtenir des information sur votre navigateur, aller sur le lien:about:[_About Page_].
// end::scheme[]

// tag::unconstrained[]
recherche/lien:https://ecosia.org[Ecosia]
// end::unconstrained[]

// tag::linkattrs-h[]
= Titre du Document AsciiDoctor
:linkattrs:

Un coup d'œil au code HTML de la page d'acceuil d'lien:view-source:asciidoctor.org[AsciiDoctor, window="_blank"].
// end::linkattrs-h[]

// tag::linkattrs[]
Un coup d'œil au code HTML de la page d'acceuil d'lien:view-source:asciidoctor.org[AsciiDoctor, window="_blank"].
// end::linkattrs[]

// tag::linkattrs-s[]
Un coup d'œil au code HTML de la page d'accueil d'lien:view-source:asciidoctor.org[AsciiDoctor^].
// end::linkattrs-s[]

// tag::css[]
Discutez avec d'autres utilisateurs d'AsciiDoctor sur le irc://irc.freenode.org/#asciidoctor[canal IRC d'AsciiDoctor] ou sur la http://discuss.asciidoctor.org/[*mailing list*^, role="green"].
// end::css[]

// tag::link[]
link:protocol.json[Ouvrir le fichier JSON]
// end::link[]

// tag::hash[]
link:external.html#livereload[Rechargement automatique]
// end::hash[]

// tag::b-base[]
https://asciidoctor.org - automatique !

https://asciidoctor.org[AsciiDoctor]

https://github.com/asciidoctor[AsciiDoctor @ *GitHub*]
// end::b-base[]

// tag::b-scheme[]
devel@discuss.arquillian.org

mailto:devel@discuss.arquillian.org[Discuter Arquillien]

mailto:devel-join@discuss.arquillian.org[Inscription (lien), (sujet), (corps)]

irc://irc.freenode.org/#asciidoctor
// end::b-scheme[]

// tag::b-linkattrs[]
http://discuss.asciidoctor.org[Discuter d'AsciiDoctor, role="external", window="_blank"]

http://discuss.asciidoctor.org[Discuter d'AsciiDoctor^]

https://example.org["Google, Yahoo, Bing^", role="teal"]
// end::b-linkattrs[]

// tag::b-spaces[]
link:++https://example.org/?q=[a b]++[Lien comprenant des caractères spéciaux]

link:https://example.org/?q=%5Ba%20b%5D[Lien comprenant des caractères spéciaux]
// end::b-spaces[]

// tag::b-windows[]
link:\\server\share\whitepaper.pdf[Livre blanc]
// end::b-windows[]
