////
== Constrained and unconstrained formatting marks

- User manual
////

There are two categories of formatting marks for applying styles (i.e., formatting) to text, _constrained_ and _unconstrained_.
These formatting marks are referred to as _quotes_ in the AsciiDoc syntax.
This section covers their purpose, their differences and how to apply them.

=== Constrained quotes

In short, "`constrained`" means *around* a word or sequence of words.

Constrained quotes are single characters (often symbols) placed around a word.
The "`around`" is defined by the fact that word characters do not appear immediately outside the enclosing marks.

You use this form to format a word that stands alone,

.When the word stands alone
[source]
----
That is *strong* stuff!
----

to format a sequence of words,

.When there are multiple words
[source]
----
That is *really strong* stuff!
----

or to format a word adjacent to punctuation, like an exclamation mark.

.When the word is adjacent to punctuation
[source]
----
This stuff sure is *strong*!
----

=== Unconstrained quotes

In short, "`unconstrained`" means anywhere, including *within* a word.

Unconstrained quotes are repeated characters (often symbols) placed anywhere in the text, including within a word.
The "`within`" is defined by the fact that a word character may appear directly outside one of the enclosing marks.

.Unconstrained formatting
[source]
----
She spells her name with an "`h`", as in Sara**h**.
----

=== When should I use unconstrained quotes?

Consider the following questions:

* Is there a letter, number, underscore directly outside the formatting marks (on either side)?
* Is there a colon or semi-colon directly before the starting formatting mark?
* Is there a space directly inside of the formatting mark?

If you answered "`yes`" to any of these questions, you need to switch to unconstrained (double formatting) quotes.

To help you determine whether a particular syntax pattern requires unconstrained quotes, consider the following syntactical situations.

.Constrained or Unconstrained?
[cols="2,2,2"]
|===
|Syntax |Result |What quote type?

|Sara\__h__
|Sara__h__
|Unconstrained, because of the "`a`" to the left.

|\\**B**old
|**B**old
|Unconstrained, because of the "`o`" to the right.

|&ndash;\\**2016**
|&ndash;**2016**
|Unconstrained, because of the "`&ndash;`" to the left of the emboldened number.

|\\** bold **
|** bold **
|Unconstrained, because there are spaces directly inside the formatting marks.

|\*2016*&ndash;
|*2016*&ndash;
|Constrained, because the "`&`" is not a letter, number, underscore, or semi-colon.

|\*9*-to-\*5*
|*9*-to-*5*
|Constrained, because a hyphen is not a letter, number, underscore, or semi-colon.
|===

=== Unconstrained formatting edge cases

There are cases when it might seem logical to use constrained quotes, however unconstrained quotes are required.
This happens because of the way the Asciidoctor parser (and the AsciiDoc Python parser) currently handles substitutions.

Substitutions may be applied by the parser before getting to the formatting marks, in which case the characters adjacent to those marks may not be what you see in the original source.

One such example is enclosing monospaced text inside quotation marks, such as "```endpoints```".

.Monospaced text inside quotes
[source]
----
"```endpoints```"
----

You might start with the following syntax:

[source]
----
"`endpoints`"
----

That only gives you "`endpoints`", since the backticks are contributing to the enclosing smart quotes.

Adding another backtick gets closer, but the parser still ignores the constrained formatting marks and interprets the backticks literally:

[source]
----
"``endpoints``"
----

So you have to double up the marks to coerce it into formatting the text to monospace.

[source]
----
"```endpoints```"
----

NOTE: This situation may improve in the future when Asciidoctor is switched to using a parsing expression grammar for inline formatting instead of the current regular expression-based strategy.
For details, follow https://github.com/asciidoctor/asciidoctor/issues/61[issue #61].

=== Escaping unconstrained quotes

Since unconstrained quotes are meant to match anywhere, context-free, they sometimes get caught up in formatting where it isn't expected.
Indeed, these symbols are a bit tricky to type literally when the content calls for it.
But being able to do it is just a matter of knowing the tricks, which this section will cover.

Let's assume you are trying to type the following:

----
#`CB###2`#
----

You might expect this to be converted to `CB###2` formatted in monospace and highlighted (aka marked text).
However, what you get is a scrambled mess.

There are two (stable) solutions for escaping an unconstrained formatting mark:

* Use an attribute reference to insert the unconstrained formatting marks
* Wrap the text in an inline passthrough

The attribute reference is preferred because it's the easiest to read:

----
:3H: ###

#`CB{3H}2`#
----

This works because text formatting is performed before attribute expansion under normal substitution order.
By default, monospaced text allows attribute references to be substituted.

Here's how you'd write it using the inline passthrough instead:

----
#`+CB###2+`#
----

Notice the addition of the plus symbols.
The enclosure `pass:[`+TEXT+`]` (text surrounded by pluses surrounded by backticks) is a special formatting combination in Asciidoctor.
It means to format TEXT as monospace, but don't interpolate formatting marks or attribute references in TEXT.
It's roughly equivalent to Markdown's backticks.
Since AsciiDoc offers more advanced formatting, the double enclosure is necessary.

The more brute-force solution to the inline passthrough approach is to use the `+pass:[]+` macro.

----
#`pass:[CB###2]`#
----

As you can see, however, it's not quite as elegant.
You also have to be careful with the `+pass:[]+` macro as it doesn't apply the special characters substitution by default, which is necessary when converting to HTML.

Thus, to be safe, you need to add that substitution explicitly using `+pass:c[]+`:

----
#`pass:c[CB###2]`#
----

Backslashes for escaping aren't very reliable in AsciiDoc.
While they can be used, they have to be placed so strategically that they are rather finicky.
