////
Included in:

- user-manual: Source Code Syntax Highlighting
////

To enable syntax highlighting in your document, you need to set the +source-highlighter+ attribute in the document header.

----
:source-highlighter: library value
----

Asciidoctor supports a number of syntax highlighting libraries.

.Available syntax highlighters
[width="50%"]
|===
|Library |Value

|CodeRay
|coderay

|Highlight.js
|highlightjs

|Prettify
|prettify

|Pygments
|pygments
|===

Once you've set the attribute and library, assign +source+ to the block and specify the source language in the second attribute position.

.Example
....
[source,ruby]
----
require 'asciidoctor'

puts Asciidoctor.render_file('sample.adoc', :header_footer => true)
----
....

.Example output
[source,ruby]
----
require 'asciidoctor'

puts Asciidoctor.render_file('sample.adoc', :header_footer => true)
----

[listing]
.Code block with title and syntax highlighting
....
[source,ruby]
.app.rb
----
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----
....

====
[source,ruby]
.app.rb
----
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----
====

[listing]
.Code block sourced from file
....
[source,ruby]
----
\include::app.rb[]
----
....

[listing]
.Code block sourced from file relative to source directory
....
:sourcedir: src/main/java

[source,java]
----
\include::{sourcedir}/org/asciidoctor/Asciidoctor.java[]
----
....

.Code block without delimiters (no blank lines)
----
[source,xml]
<meta name="viewport"
  content="width=device-width, initial-scale=1.0">
----

====
[source,xml]
<meta name="viewport"
  content="width=device-width, initial-scale=1.0">
====

TIP: Syntax highlighting is not disabled if an explicit +subs+ attribute is used on a source listing (as long as +specialcharacters+ is in the subs list).
