////
Included in:

- user-manual: images
////

To include an image on its own line (i.e., a _block image_), use the `image::` prefix in front of the file name and square brackets after it.

[source]
----
include::ex-image.adoc[tags=base]
----

====
include::ex-image.adoc[tags=base]
====

If you want to specify alt text, include it inside the square brackets:

[source]
----
include::ex-image.adoc[tags=alt]
----

You can also give the image an id, a title, set its dimensions and make it a link.

[source]
----
include::ex-image.adoc[tags=attr-co]
----
<1> ID, see <<anchordef>>.
<2> The title of a block image is displayed underneath the image when rendered.
<3> The first positional attribute, _Sunset_, is the image's alt text.
<4> Image width and height
<5> `link` makes the image a link

.A hyperlinked image with caption
====
include::ex-image.adoc[tags=attr]
====

Block images are prefixed by a caption label (Figure) and number automatically.
To turn off figure caption labels and numbers, add the `figure-caption` attribute to the document header and unset it.

 :figure-caption!:

If you want to include an image inline, use the `image:` prefix instead (notice there is only one colon):

[source]
----
include::ex-image.adoc[tags=in]
----

====
include::ex-image.adoc[tags=in]
====

For inline images, the optional title is displayed as a tooltip.
