////
=== Selecting parts of a document to include

- User manual
////

The include directive supports extracting portions of content from within a document.
The content is specified either by user defined tags or a range of line numbers.

The line range is assigned to the +lines+ attribute.

[source]
----
include::ex-include.adoc[tags=line]
----

Multiple ranges can be specified as well.

[source]
----
include::ex-include.adoc[tags=m-line]
----

You can refer to the last line of the document in the range using the value -1.

[source]
----
include::ex-include.adoc[tags=last]
----

Alternately, you can select tagged regions of content.
This feature is activated using the +tags+ attribute.

Here's an example of an include that retrieves a tagged region from the target file.

----
include::ex-include.adoc[tags=tag]
----

Here's how the target file looks with the tagged region.

----
include::ex-include.adoc[tags=target]
----

Here's the content retrieved by the include expanded within the rendered document:

----
include::ex-include.adoc[tags=out]
----

When placed anywhere on a line, the directive +tag::<name>[]+ identifies the start of a tagged region.
The directive +end::<name>[]+ anywhere on a subsequent line ends it.
The tag's name can be any word.
In the example above, the tagged region directives are hidden behind a line comment so that they do not break the Groovy script.
