////
== Include Directive

- User manual
////

The include directive allows you to insert content from a file into a parent file, effectively merging the content.

Include directives are handled by the preprocessor, so they are oblivious to the structure of the document.
They are primarily just a file merger, with one exception.
The include directives can resolve document-level attributes.

Only content in AsciiDoc files are preprocessed when included.
Asciidoctor recognizes files with the extensions `.asciidoc`, `.adoc`, `.ad`, `.asc`, or `.txt` as AsciiDoc files.
The content in all other files are included as is.

The include directive is _disabled_ when Asciidoctor is run in secure mode, which is the default safe mode when using Asciidoctor via the API.
In secure mode, include directives become _links_ in the output document.
To learn more about secure mode, refer to the section <<Running Asciidoctor Securely>>.

Files included in the master (top-level) document are resolved relative to the base directory, which defaults to the directory of the master document unless otherwise specified.
Files included inside a file which itself has been included are resolved relative to the current document.

.Document parts
[source]
----
include::ex-include.adoc[tags=base]
----

[#includes-and-whitespace]
.Includes and whitespace
CAUTION: Asciidoctor does not insert blank lines between adjacent include statements.
We recommend always inserting a blank line around each include directive to avoid unexpected results (e.g., a section title getting appended to the end of a previous paragraph).
Also note that the indentation of the included content _is not_ altered unless you set the <<normalizing-block-indentation,indent attribute>>.

The `tag` and `line` attributes on the include directive can be used to retrieve specific chunks of content.

TIP: Asciidoctor supports targets that include spaces and the `\{sp}` attribute references.

If you need to prevent the include directive from being processed, perhaps to show an include directive example in your document, escape it by prefixing the line with a backslash.

.Escaping an include directive
[source,indent=0]
----
 \include::fragment.adoc[]
----

The include directive will be shown without the preceding backslash in the output document.

.Unprocessed include directive
[source,indent=0]
----
 include::fragment.adoc[]
----

////
Also: this sections needs an anatomy example and an example with a non-recognized file extension.

Also: need leveloffset attribute
////
