////
=== Selecting portions of a document to include

- User manual
////

The include directive supports extracting portions of content from within a document.
The content is specified either by user-defined tags or a range of line numbers.

When including multiple line ranges or multiple tags, the individual values can be separated either by a comma or a semi-colon.
If commas are used, then the entire attribute value must be enclosed in quotes.
Using the semi-colon as the data separator alleviates this requirement.

==== By tagged regions

Tags are useful when you want to display specific regions of content from an include file instead of all of its content.
You can select tagged regions of content with the `tag` macro and the `tags` attribute.
The example below shows how you tag a region of content inside a file containing multiple code examples.

.Tagged code snippets in a file named core.rb
[source,ruby]
----
include::ex-include.adoc[tags=tag-co]
----
<1> To indicate the start of a tagged region, insert a comment line in the code.
<2> Assign a unique name to the tag macro. In this example the tag is called _timings_.
<3> Insert another comment line where you want the tagged region to end.
<4> Assign the name of the region you want to terminate to the `end` macro.
<5> This is the start a tagged snippet named _parse_.
<6> This is the end of the tagged snippet named _parse_.

IMPORTANT: The `tag::[]` and `end::[]` directives should be placed after a line comment as defined by the language of the source file.
The directives must also appear at the _end_ of the line.
In the previous example, we choose to prefix the lines with a hash (`#`) because that's the start of a line comment in Ruby.
For XML files you can use `+<!-- tag::name[] -->+` and `+<!-- end::name[] -->+`. (making sure to include the spaces as shown).

TIP: Asciidoctor supports targets that include spaces and the `\{sp}` attribute references.

In the next example, the tagged region named _parse_ is called by the `include` directive.

.Calling the _parse_ code snippet from a document
[source]
....
include::ex-include.adoc[tags=target-co]
....
<1> In the directive's brackets, set the `tag` attribute and assign it the unique name of the code snippet you tagged in your code file.

You can include multiple tags from the same file.

.Calling the _timings_ and the _parse_ code snippets from a document
[source]
....
include::ex-include.adoc[tags=target-co-multiple]
....

It is also possible to have fine-grained tagged regions inside larger tagged regions.

For example, if your include file has the following content:

[source]
----
// tag::snippets[]
// tag::snippet-a[]
snippet a
// end::snippet-a[]

// tag::snippet-b[]
snippet b
// end::snippet-b[]
// end::snippets[]
----

And you include this file using the following include directive:

[source]
----
\include::file-with-snippets.adoc[tag=snippets]
----

The following lines will be selected and displayed:

[source]
----
snippet a

snippet b
----

Notice that none of the lines with the tag directives are displayed.

==== Tag filtering

The previous section showed how to select tagged regions explictly, but you can also use wildcards and exclusions:

[horizontal]
`*`::
  All tagged regions

`**`::
 Non-tagged regions

`!`::
 Exclude

The inclusive operations (explicit names, `\*` and `**`) are applied first, then the exclusive operations (`!`), so it doesn't matter which order they appear in.

Some examples:

`tags=foo;!bar` selects regions tagged "foo" but excludes any _nested_ regions tagged "bar".

`tags=*;!foo` selects all tagged regions apart from those tagged "foo".

`tags=**;foo` selects all regions that are outside of any tags, plus any regions tagged "foo".

`tags=\**;!*` selects the non-tagged regions only.

`tags=\**;*` selects the non-tagged regions and all tagged regions, i.e. the whole file.

There is some short hand:

tags=`+**+` is the same as `tags=\**;*`, i.e. the whole file.

`tags=!foo` is the same as `tags=\**;*;!foo` because an exclusion without an inclusion implicitly selects the whole file first.

==== By line ranges

To include content by line range, assign a starting line number and an ending line number separated by a pair of dots (e.g., `lines=1..5`) to the `lines` attribute.

[source]
----
include::ex-include.adoc[tags=line]
----

You can specify multiple ranges by separating each range by a comma.
Since commas are normally used to separate individual attributes, you must quote the comma-separated list of ranges.

[source]
----
include::ex-include.adoc[tags=m-line-comma]
----

To avoid having to quote the list of ranges, you can instead separate them using semi-colons.

[source]
----
include::ex-include.adoc[tags=m-line]
----

If you don't know the number of lines in the document, or you don't want to couple the range to the length of the file, you can refer to the last line of the document using the value -1.

[source]
----
include::ex-include.adoc[tags=last]
----
