////
Install and upgrade documentation for Asciidoctor
This file is included in the install-toolchain and user-manual documents
////

== System Requirements

//tag::systemreq[]
Asciidoctor works on Linux, Mac and Windows.

Asciidoctor requires one of the following implementations of Ruby:

* Ruby 1.8.7
* Ruby 1.9.3
* Ruby 2.0 (or better)
* JRuby 1.7.5 (Ruby 1.8 and 1.9 modes)
* Rubinius 2.0 (Ruby 1.8 and 1.9 modes)
* Opal (Javascript)

We expect Asciidoctor to work with other versions of Ruby as well.
We welcome your help testing those versions if you are interested in seeing them supported.
//end::systemreq[]

== Installing the Asciidoctor Ruby Gem

//tag::basicgem[]
Asciidoctor can be installed via the +gem+ command, bundler, or popular Linux package managers.

To install Asciidoctor using the +gem+ command:

. Open a terminal
. Type the +gem+ command

 $ gem install asciidoctor

If the Asciidoctor gem installed successfully, the +asciidoctor+ command line interface (CLI) will be available on your PATH.
To confirm that Asciidoctor is available, execute:

 $ asciidoctor --version
 
The following information should be output in your terminal:

 Asciidoctor 1.5.2 [http://asciidoctor.org]
 Runtime Environment (ruby 2.2.1p85 [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
 
//end::basicgem[]
 
=== Install with Bundler

//tag::bundler[]
To install Asciidoctor using Bundler:

. Open your system Gemfile
. Add the +asciidoctor+ gem to your Gemfile using the following text

 source 'https://rubygems.org'
 gem 'asciidoctor'

. Save the Gemfile
. Open a terminal
. Install the gem with bundler

 $ bundle install

//end::bundler[]

=== Install with +yum+ or +dnf+

//tag::yum[]
To install Asciidoctor on Fedora or other RPM-based systems:

. Open a terminal
. Run the installation command

  Fedora 21 or earlier::
+
 $ sudo yum install asciidoctor

  Fedora 22 or later::
+
 $ sudo dnf install asciidoctor

The benefit of installing the gem using this method is that the package manager will also install Ruby and RubyGems if not already on your machine.
//end::yum[]

=== Install with +apt-get+

//tag::aptget[]
To install Asciidoctor on Debian Sid or Ubuntu Saucy or greater:

. Open a terminal
. Type the +apt-get+ command
 
 $ sudo apt-get install asciidoctor

The benefit of installing the gem via +apt-get+ is that the package manager will also install Ruby and RubyGems if not already on your machine.
//end::aptget[]

== Upgrading the Asciidoctor Ruby Gem

//tag::upgrade[]
If you have an earlier version of Asciidoctor installed, you can update it using the +gem+ command:

 $ gem update asciidoctor

[TIP]
====
If you accidentally use +gem install+ instead of +gem update+ then you will have both versions installed.
If you wish to remove the older version use the +gem+ command:

 $ gem cleanup asciidoctor
====

On Fedora, you can update it using:

 $ sudo yum update rubygem-asciidoctor

TIP: Your Fedora system may be configured to automatically update packages, in which case no further action is required by you.
Refer to the {fedora-docs}[Fedora docs] if you are unsure.

On Debian or Ubuntu, you can update it using:

 $ sudo apt-get upgrade asciidoctor

NOTE: The Fedora, Debian and Ubuntu packages will not be available right away after a release of the RubyGem.
It may take several weeks before the packages become available for a new release.
If you need the latest version immediately, use the +gem install+ option.
//end::upgrade[]
