////
Labeled lists
Introduction

Included in:

- user-manual
////

Labeled lists are useful when you need to include a description or supporting text for each item in a list.
Each item in a labeled list consists of a term or phrase followed by:

* a separator (typically a double colon, +::+)
* at least one space or endline
* the item's content

Here's an example of a labeled list that identifies parts of a computer:

[source]
----
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
Keyboard:: Used to enter text or control items on the screen.
Mouse:: Used to point to and select items on your computer screen.
Monitor:: Displays information in visual form using text and graphics.
----

By default, the content of each item is displayed below the label when rendered.
Here's a preview of how this list is rendered:

.A basic labeled list
====
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
Keyboard:: Used to enter text or control items on the screen.
Mouse:: Used to point to and select items on your computer screen.
Monitor:: Displays information in visual form using text and graphics.
====

If you want the label and content to appear on the same line, add the horizontal style to the list.

[source]
----
[horizontal]
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
----

[horizontal]
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.

The content of a labeled list can be any AsciiDoc element.
For instance, we could rewrite the grocery list from above so that each aisle is a label rather than a parent outline list item.

[source]
----
Diary::
* Milk
* Eggs
Bakery::
* Bread
Produce::
* Bananas
----

Labeled lists are quite lenient about whitespace, so you can spread the items out and even indent the content if that makes it more readable for you:

//[source]
----
Diary::

  * Milk
  * Eggs

Bakery::

  * Bread

Produce::

  * Bananas
----
