[[language-suport]]
== Using Asciidoctor with other languages

While Asciidoctor defaults to English for labels, messages and other built-in text, it's certainly not limited to working English-only content.
Asciidoctor recognizes the full UTF-8 character set.
That means you can write your document in any language and expect that Asciidoctor will convert the text accordingly.
You can customize the built-in labels (e.g., "`Appendix`") to match the language in which you are writing.

There are some caveats to know about:

* Currently, the official html5 and pdf converters only fully support left-to-right (and top-to-bottom) reading. Support for right-to-left (RTL) is being worked on. (See {uri-org}/asciidoctor/issues/1601[issue #1601]). In the interim, you can leverage the DocBook toolchain to get right-to-left support.
* Attributes that generate dates and times (like `docdatetime`) are always formated like `2015-01-04 19:26:06 GMT+0000`.
* Message strings are always in English.

=== Customizing labels

To customize the labels for the DocBook backend, set the `lang` attribute (it defaults to `en` for English). 
For example:

----
$ asciidoctor -a lang=es -b docbook article.adoc
----

The list of languages supported, and additional language considerations for DocBook are described in link:http://www.sagehill.net/docbookxsl/Localizations.html[DocBook XSL: The Complete Guide].

To customize the labels for the html and pdf backends, translate the various captions yourself by setting attributes:

[cols="10,20,10",width="80%"]
|====
|Attribute name |Used for |Default

|caution-caption
|CAUTION admonitions (when icons are not in use).
|Caution

|important-caption
|IMPORTANT admonitions (when icons are not in use).
|Important

|note-caption
|NOTE admonitions (when icons are not in use).
|Note

|tip-caption
|TIP admonitions (when icons are not in use).
|Tip

|warning-caption
|WARNING admonitions (when icons are not in use).
|Warning

|appendix-caption
|Appendix titles.
|Appendix

|example-caption
|Example titles.
|Example

|figure-caption
|Automatically prefixed to figure titles.
|Figure

|table-caption
|Automatically prefixed to table titles. 
|Table

|last-update-label
|Label for when the document was last updated.
|Last updated

|listing-caption
|The label for listing blocks. 
By default, listing blocks do not have captions.
If you specify `listing-caption`, then you also turn on captions for listing blocks.
|(not set)

|untitled-label
|The document title, for documents that have only body content.
|Untitled

|version-label
|The label preceding the revnumber in the document's byline.
|Version
|====

There's an ongoing discussion about how to make language support even simpler (link:{uri-org}/asciidoctor/issues/1129[issue #1129]).
Input is welome.

=== Translation

Asciidoctor (or DocBook) currently does not support translation out of the box.
There's a proposal to integrate gettext (link:{uri-mailinglist}/Professional-providers-translating-Asciidoc-tt2692.html#none[discussion]), but all suggestions are welcome.
