////
Included in:

- user-manual: Listing and Source Code Blocks
////

Like literal blocks, the content in listing blocks is displayed exactly as you entered it.
Listing block content is rendered as +<pre>+ text.
The content in listing blocks is only subject to <<user-manual#special-characters,special character>> and callout substitutions.

The +listing+ style can be applied to content two ways.

. Set the +listing+ attribute on the element.
. Contain the content within a delimited +listing+ block.

The +listing+ style is applied to an element, such as a paragraph, by setting the +listing+ attribute on that element.

[source]
----
include::ex-listing.adoc[tags=para]
----

.Rendered listing paragraph
====
include::ex-listing.adoc[tags=para]
====

A delimited listing block is surrounded by lines composed of four hyphens (+----+).

[source]
....
include::ex-listing.adoc[tags=bl]
....

Here's how the block above appears when rendered as HTML:

.Rendered listing block
====
include::ex-listing.adoc[tags=bl]
====

You should notice a few things about how the content is processed:

* the HTML tag +<pre>+ is escaped
* then endlines are preserved
* the phrase ``listing block'' is not italicized, despite having underscores around it.

Listing blocks are good for displaying raw source code, especially when used in tandem with the +source+ and +source-highlighter+ attributes.
The example below shows a listing block with +source+ and the language +ruby+ applied to its content.

[source]
....
include::ex-source.adoc[tags=bl]
....

.Rendered listing block with the +source+ attribute set
====
include::ex-listing.adoc[tags=bl]
====

Detailed instructions for using the +source+ and +source-highlighter+ attributes are provided in the <<user-manual#source-code-blocks, source code blocks>> section.

[listing]
.Custom substitutions
....
include::ex-listing.adoc[tags=subs]
....

====
// the attribute value is hard-coded in this result since the example depends
// on a hypothetical document attribute
include::ex-listing.adoc[tags=subs-out]
====
