////
Included in:

- user-manual: Listing and Source Code Blocks: To wrap or to scroll
////

Previously, the Asciidoctor stylesheet was configured to prevent line wrapping (e.g., +white-space: pre-wrap; word-wrap: normal+) in listing and literal blocks.
This behavior isn't always desirable because it causes the browser window to scroll if the content overflows the width of the page.
For many, this horizontal scrolling is considered a greater readability problem than line wrapping.

Since there are two camps on this preference, neither setting will please both.
For that reason, we've made this behavior configurable in Asciidoctor 0.1.4.

By default, the default Asciidoctor stylesheet now wraps long lines in listing and literal blocks by applying the CSS +white-space: pre-wrap+ and +word-wrap: break-word+.
The lines are wrapped at word boundaries, similar to how most text editors wrap lines.

There are two ways to prevent lines from wrapping so that horizontal scrolling is used instead:

* nowrap block option
* prewrap document attribute

You can use the +nowrap+ option on literal or listing blocks to prevent lines from being wrapped in the HTML:

```
[source, java, options="nowrap"]
----
public class ApplicationConfigurationProvider extends HttpConfigurationProvider
{
   @Override
   public Configuration getConfiguration(ServletContext context)
   {
      return ConfigurationBuilder.begin()
               .addRule()
               .when(Direction.isInbound().and(Path.matches("/{path}")))
               .perform(Log.message(Level.INFO, "Client requested path: {path}"))
               .where("path").matches(".*");
   }
}
----
```

When the +nowrap+ option is used, the +nowrap+ class is added to the +<pre>+ element.
This class changes the CSS to +white-space: pre+ and +word-wrap: normal+.

To apply the nowrap option globally, just set the +prewrap+ attribute on the document.

```
:prewrap:
```

When the +prewrap+ attribute is set, the +nowrap+ class is added to any +<pre>+ element even when the +nowrap+ option is absent.

Now, you can use the line wrapping strategy that works best for you and your readers.
