////
Load and render doc using API
This file is included in the user-manual document
////

To use Asciidoctor in your application, you first need to require the gem:

 require 'asciidoctor'

With that in place, you can start processing AsciiDoc documents.
To parse a file into an +Asciidoctor::Document+ object:

 doc = Asciidoctor.load_file 'sample.adoc'

You can get information about the document:

 puts doc.doctitle
 puts doc.attributes

More than likely, you will want to render the document.
To render a file containing AsciiDoc markup to HTML 5, use:

[source,ruby]
----
 Asciidoctor.render_file 'sample.adoc', :in_place => true
----

The command will output to the file +sample.html+ in the same directory. 

You can render the file to DocBook 5.0 by setting the +:backend+ option to +'docbook'+:

[source,ruby]
----
 Asciidoctor.render_file 'sample.adoc', :in_place => true, :backend => 'docbook'
----

The command will output to the file +sample.xml+ in the same directory. 
If you're on Linux, you can view the file using {yelp}[Yelp].
