////
Included in:

- user-manual: Man pages
////

One of the more unusual uses of AsciiDoc is for creating man pages (short for manual pages) for Unix and Unix-like operating systems.

A man page is written in the roff typesetting language.
By adhering to a specific structure in the man page file, the linux `man` help system can parse the file and provide text formatted command-line help on all the installed commands.
For a full description, see http://man7.org/linux/man-pages/man7/roff.7.html, or type `man 7 man` or `man man-pages`.

{adr} can produce these roff files if some special rules are followed in the Asciidoc document (described later in this section).
In addition, {adr} can produce html and pdf versions similar to the `man` output, for viewing in other contexts.

To produce a man page roff file:

 $ asciidoctor --doctype manpage --backend manpage source.adoc

Note that the manpage backend sets the output file name to `progname.1` where `progname` is the name of the command, defined in the source document.

To see it in html instead:

 $ asciidoctor --doctype manpage --backend html source.adoc
 
Here is a shortened version of the {adr} man page written in AsciiDoc:

[source]
----
include::sample-manpage.adoc[]
----

It has these required parts:

Document Header::
  A manpage document Header is mandatory.
The title line contains the man page name followed immediately by the manual section number in brackets.
The title name should not contain white space.
The manual section number is a single digit optionally followed by a single character.

The NAME Section::
  The first manpage section is mandatory, must be titled 'NAME' and must contain a single paragraph (usually a single line) consisting of a list of one or more comma separated command name(s)
separated from the command purpose by a dash character.
The dash must have at least one white space character on either side.

The SYNOPSIS Section::
The second manpage section is mandatory and must be titled 'SYNOPSIS'.

Subsequent sections are not mandated, but the example is typical.

There are some built-in attributes that affect only manpages.
If used, they must be set in the header.

[cols="<15,<30,<30"]
.Manpage built-in attributes
|====
|Attribute name |Description |Example (if parsed from the example document above)

|mantitle
|Alternative way to set the man page name.
|ASCIIDOCTOR(1)

|manvolnum
|Manual section number.
|1

|manname
|Alternative way to set the command name.
|asciidoctor

|manpurpose
|Alternative way to set the command purpose.
|converts AsciiDoc source files

|man-linkstyle
|Style the links in the manpage output.
A valid link format sequence.
// Needs a reference to this.
|blue R <>

|mansource
|The source to which the manpage pertains.
If using the docbook backendand  docbook stylesheets, it becomes a docbook http://www.docbook.org/tdg5/en/html/refmiscinfo.html[refmiscinfo] attribute, and appears in the footer.
It is not used in the {adr} backends.
|Asciidoctor

|manversion
|The version of the man page.
If using the docbook backendand  docbook stylesheets, it becomes a docbook http://www.docbook.org/tdg5/en/html/refmiscinfo.html[refmiscinfo] attribute, and appears in the footer.
It is not used in the {adr} backends.
|1.5.4

|manmanual
|Manual name.
If using the docbook backendand docbook stylesheets, it becomes a docbook http://www.docbook.org/tdg5/en/html/refmiscinfo.html[refmiscinfo] attribute, and appears in the footer.
It is not used in the {adr} backends.
|Asciidoctor Manual

|====

Refer to {man-raw}[the AsciiDoc source of the Asciidoctor man page] to see a complete example.
The man page for Asciidoctor is produced using the built-in manpage converter in Asciidoctor.
The man pages for git are also produced from AsciiDoc documents, so you can use those as another example to follow.
