// Issue #480. #434, #463 refer.
:uri-diagram: https://github.com/asciidoctor/asciidoctor-diagram/
:uri-migrate: {uri-org}/docs/migration/
:uri-recommended: {uri-org}/docs/asciidoc-recommended-practices/
:uri-diffs: {uri-org}/docs/asciidoc-asciidoctor-diffs/

== Migrating from {adp}

The purpose of this section is to help you migrate legacy AsciiDoc documents written for {adp} to the modern AsciiDoc syntax supported by {adr}.

The differences are minor, so most documents will need very few changes, if any.
Once you've made the necessary changes, this section also describes how to take advantage of the new features provided in {adr}.

NOTE: Specifically, this section is about migrating from {adp} version 8 to {adr} version 1.5.4.
It assumes you have already updated any content that is deprecated in {adp} version 8.

=== Command Line Interface

{adr} was designed from the outset to be a drop-in replacement for {adp}.
For most documents, you can simply replace the call to {adp}:

 $ asciidoc document.adoc

with an equivalent call to {adr}:

 $ asciidoctor -a compat-mode document.adoc

If this doesn't work for you, check out the differences below, particularly <<migrate-deprecated>>.

==== Internationalization

// ref ap UG, not checked
{adp} has built-in .conf files that are used to translate the built-in labels.
You load the appropriate .conf file by setting the `lang` attribute to a supported language code (e.g., `-a lang=<language code>`).
See <<language-support>> for the {adr} equivalent.

==== Configuration Files

{adr} does not use .conf files or filters, so `--conf-file`, `--dump-conf`, and `--filter` are not implemented.
{adr} provides an <<extensions,extension API>> that replaces the configuration-based extension and filter mechanisms in {adp}.

==== Themes

// ref ap UG. Actually seems to set JS as well. OK to ignore?
{adp} themes are just stylesheets, so replace `--theme` with `-a stylesheet=<stylesheet>`.

==== Doctest

// ref ap UG. 
{adp} `--doctest` runs units tests.
See {tests}[Tests] for how to run the {adr} unit tests.

==== Default HTML Backend

{adp} used xhtml 1.1 as its default backend; {adr} uses html5, which adheres closely to the backend by the same name in {adp}.
The web has moved forward since {adp} was created, so the switch to HTML5 is recommended anyway.

==== Help

{ad} has `--help syntax` to show a syntax cheatsheet, and `--help manpage` to show the command usage as a Linux manpage.
{adr} only has `--help`, which shows the command usage.

If you installed {adr} using a Linux package, you can view the manpage using:

 $ man asciidoctor

If you installed {adr} using RubyGems, you have to tell the man command where to find the manpage using:

 $ man "`gem which asciidoctor | xargs dirname`/../man/asciidoctor.1"

You can also view the manpage online at {uri-org}/man/asciidoctor/[asciidoctor(1)].

The {adr} cheatsheet is available at {uri-org}/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference].

=== Changed Syntax

// Simplified from migration guide
These changes are not backward-compatible, but if you set the `compat-mode` attribute, {adr} will accept the {adp} syntax.
For the long term, you should update to the {adr} syntax.
Consult the {uri-migrate}[Migration Guide] to get the full details and learn how to migrate smoothly.

.Changed syntax affected by compat-mode
[cols="1a,1a,1a"]
|====
|Feature |{adp}, or {adr} with `compat-mode` |{adr} without `compat-mode` 

|_italic text_
|pass:['italic text']
|pass:[_italic text_]

|`monospaced text`
|pass:[+monospaced text+]
|pass:[`monospaced text`]

|Prevent attribute replacement
|pass:[`{asciidoc-version}`]
|pass:[`+{asciidoc-version}+`]

|"`double quotes`"
|pass:[``double quotes'']
// not keen on just 'use the unicode quote characters' because it implies adr doesn't end up inserting unicode.
|pass:["`double quotes`"] or type the Unicode quote characters using your editor

|'`single quotes`'
|pass:[`single quotes']
|pass:['`single quotes`'] or type the Unicode quote characters using your editor

|Document title ^[1]^
|
----
Title
=====
----
|
----
= Title
----

|====

//"two-line title" is the term in the ap ug
CAUTION: [1] {adr} accepts the two-line heading style to set the document title, but using it implicitly sets `compat-mode`.
Therefore, if you want to use the new {adr} syntax, make sure to use the single-line style for the document title.

// dont bother to say not backward comatible, it is implicit from the context
These changes are not affected by the `compat-mode` attribute:

.Changed syntax not affected by compat-mode
[cols="1a,1a,2a"]
|====
|Feature |{adp} |{adr}

// NO deprecated in ad 8 so no need to mention it (covered by comment at top)
//|Index terms
//|pass:[`++`] and pass:[`+++`]
//|pass:[((Sword))] and pass:[(((Sword, Broadsword, Excalibur)))]

|Underlined titles
|Underline length must match title length +/- 2 characters.
|Underline length must match title length +/- 1 character (Underlined titles are deprecated anyway - see <<sections>>.)

|+ifeval::[]+ 
|Evaluates any Python expression.
|Evaluates simple logical expressions testing the value of attributes.
See <<ifeval-directive>>.

|Block delimiters
|Delimiter lines do not have to match in length.
|The length of start and end delimiter lines must match exactly.

|AsciiDoc table cell
|`a\|` or `asciidoc\|`.
|`a\|` only.

// NO deprecated in ad 8 so no need to mention it (covered by comment at top)
//|Deprecated tables
//|Yes
//|No (you don't want them anyway)

|====

[[migrate-deprecated]]
=== Deleted and Deprecated Attributes

These are attributes that either no longer exist, work differently, or have better alternatives.

.Deleted and deprecated attributes
[cols="<20a,<20a,<60a"]
|====
|{adp} |{adr} |Notes

|`big`, `small`, `underline`, `overline`, `line-through`, colors
|_deprecated_
|Character attributes to apply formatting directly.
Usually better to apply a role, then apply the formatting based on that role by using a stylesheet.

|`halign`, `valign` for table cells
|Column and cell specifiers
|See <<cell>>.

|`infile`
.2+|_not implemented_
.2+|Provides the name and directory of the current document.
(Distinct from `docfile`, because `infile` may be an included document, and `docfile` is always the master document.)
No {adr} equivalent.

|`indir`

|`asciidoc`
|`asciidoctor` 
|{adp} sets `asciidoc` to show that it is the current processor.
{adr} sets `asciidoctor` instead.

// Ref migration guide
|`toc2`
.2+|`toc`
.2+|Combined in a single attribute, see <<toc>>.

// Ref migration guide
|`toc-placement`

// No checked
|`options="pgwide"`
|_not implemented_
|DocBook attribute to make tables full page width, whatever the current indent.
No {adr} equivalent.

// Ref ap UG. I know it works in ad tables; no ref to ad paragraphs so assume not implemented.
|options="unbreakable"
|
|In {adr}, this only works for tables, not paragraphs.

// http://www.methods.co.nz/asciidoc/userguide.html#X39
// an ugly hack so not implemented
|`plaintext`
|_not implemented_
|{adp} uses this to suppress inline substitutions and retain block indents when importing large blocks of plain text.
{adr} deliberately does not implement it; the closest {adr} equivalent is a passthrough block.

// old table
|`replacements2`
|`post_replacements`
|Renamed.

// does this need an explanation?
|`presubs`
|-
|Not required.

// rarely used so dont mention it
//|`sgml`
//|_not implemented_
//|SGML is archaic and has been replaced by XML.

// It may be a perversion, but it is a useful perversion!
|`showcomments`
|_not implemented_
|In {adp}, turns single line comments into DocBook `<remark>` elements.
{adr} considers this an inappropriate use of comments.
If you want to send remarks to the output, use an extension, or:

----
 ifdef::showcomments+basebackend-docbook[]
 ++++
 <remark>Your comment here</remark>
 ++++
 endif::[]
----

|`specialwords`
|_not implemented_
|In {adp}, applies special formatting to named text.
In {adr} this could be implemented using an extension.

|`tabsize` (in-document and include directive)
|in-document only
|{adp} applies it to all text, with a default of 8.
{adr} only applies it to blocks with a verbatim content model (listing, literal, etc), and it has no default (so tabs will not be expanded by default).
For all other text, {adr} tabs are fixed at 4 spaces, see <<normalize-block-indentation>>.

|====

[[migrate-stylesheet]]
=== Default HTML Stylesheet

The {adp} and Acidoctor stylesheets look quite different but are completely compatible, because their formatting is based on the same role attributes.
If you happen to prefer the {adp} stylesheet, you can use it by copying it from the {adp} [.path]_stylesheets_ directory and telling {adr} to use it with 

 $ asciidoctor -a stylesheet=asciidoc.css

IMPORTANT: Unlike {adp}, {adr} loads some resources from a CDN.
It's possible to configure {adr} to load all resources from local files.
For instance, you can unset the `webfonts` attribute so that the generated HTML does not use fonts from Google Fonts.
There are similar attributes to control how additional resources are resolved.

// From Dan. Noted but I dont think it is needed. 
////
Asciidoctor styles the first paragraph of the preamble as a "lead paragraph". 
A lead paragraph has a larger font size than normal paragraph content. 
This effect is activated by the default stylesheet. 
If you don't like it, you can tweak the stylesheet or add additional CSS to reverse the effect.
////


=== Mathematical Expressions

Both {adp} and {adr} can convert inline Latex and AsciiMath using `pass:[asciimath:[expression]]` or `pass:[latexmath:[expression]]`, but with {adr} you need to activate `stem` support first (see <<activating-stem-support>>.)

For block content, {adp} uses a `[latex]` style delimited block.
In {adr}, use  a `stem` passthrough block instead.
See <<stem-bl>>.

[[migrate-extensions]]
=== {adp} Extensions

The extension mechanism is completely different in {adr}, but the '`standard`' extensions have been re-implemented, so they should work with minor changes.

.Standard extensions
[cols="<20,<80a"]
|====
|{adp} |{adr}

|source
|
* You can choose from a number of highlighters <<source-code-blocks>>.

* Highlighters are built-in, not separately installed.

* `src_numbered`, `src_tab`, `args` are not implemented directly, but check the highlighter you are using for what features it has and how to configure them.


|music
|Not implemented.

|latex (block macro)
|Use a `stem` passthrough block <<stem-bl>>.

|graphviz
|Incorporated into {uri-diagram}[Asciidoctor Diagram].

|====

=== Custom Extensions

{adp} custom extensions will not work with {adr} because {adp} extensions are essentially Python commands, and the {adr} extensions are Ruby (or Java) classes.
To re-write your extensions, see <<extensions>>.

=== New Features

==== New Syntax

{adr} has shorthand for id, role, style and options.
See <<setting-attributes-on-an-element>> for details.

The following longhand syntax in {adp}:

[source,asciidoc]
----
[[id]]
[style,role="role",options="option1,option2"]
----

can be written using the shorthand supported by {adr}:

[source,asciidoc]
----
[style#id.role%option1%option2]
----

The longhand forms still work, but you should use the new forms for future compatibility, convenience and readability.

==== Recommended Practises

See the {uri-recommended}[AsciiDoc Style Guide and Recommended Practices] for ways to make your documents clearer and more consistent.

==== Enhancements

There are lots of new features and improvements {adr}.
These are some of the more interesting ones when migrating:

* <<include-directive-2,Partial includes>>
* <<running-asciidoctor-securely,Additional safe modes>>
* <<inline-icons,Icon-based fonts and inline icons>>
* {uri-diagram}[Asciidoctor Diagram]

A detailed list of the improvements is shown in {uri-diffs}[Differences between Asciidoctor and AsciiDoc].
