[[non-english]]
== Using Asciidoctor with other languages

Asciidoctor defaults to English, but Asciidoctor is certainly not limited to English.
Asciidoctor recognizes the full UTF-8 character set, so you can write your document in any language and Asciidoctor will convert the text accordingly.
The only extra thing you have to do is customize the labels and other built-in text to match the language in which you are writing.

Still, there are some caveats to know about:

* Currently, the official html5 and pdf converters only fully support left-to-right (and top-to-bottom) reading. Support for right-to-left (RTL) is being worked on. (See {uri-org}/asciidoctor/issues/1601[issue #1601]). In the interim, you can leverage the DocBook toolchain to get right-to-left support.

* Attributes that generate dates and times (like `docdatetime`) are always formated like `2015-01-04 19:26:06 GMT+0000`.

=== Customizing labels

To customize the labels for the DocBook backend, set the `lang` attribute (it defaults to `en` for English). 
For example:

----
$ asciidoctor -a lang=es -b docbook article.adoc
----

The list of languages supported, and additional language considerations for DocBook are described in link:http://www.sagehill.net/docbookxsl/Localizations.html[DocBook XSL: The Complete Guide].

To customize the labels for the html and pdf backends, translate the various captions yourself by setting attributes:

[cols="10,20,10",width="80%"]
|====
|Attribute name |Used for |Default

|caution-caption
|CAUTION admonitions, if icons are not used.
|Caution

|important-caption
|IMPORTANT admonitions, if icons are not used.
|Important

|note-caption
|NOTE admonitions, if icons are not used.
|Note

|tip-caption
|TIP admonitions, if icons are not used.
|Tip

|warning-caption
|WARNING admonitions, if icons are not used.
|Warning

|appendix-caption
|Appendix titles.
|Appendix

|example-caption
|Examples.
|Example

|figure-caption
|Automatically prefixed to figure titles.
|Figure

|table-caption
|Automatically prefixed to table titles. 
|Table

|last-update-label
|"last updated" time in the footer.
|Last updated

|listing-caption
|The label for listing blocks. 
By default, listing blocks do not have captions, so if you specify `listing-caption`, then you also turn on captions for listing blocks.
|(not set)

|untitled-label
|The document title, for documents that have only body content.
|Untitled

|version-label
|The label preceding the revnumber in the document’s byline.
|Version

|====

There is a discussion on how to make this even simpler (link:{uri-org}/asciidoctor/issues/1129[issue #1129]), all ideas are welome.

=== Translation
Asciidoctor (or DocBook) currently does not support translation.
There is a proposal to integrate gettext (link:{uri-mailinglist}/Professional-providers-translating-Asciidoc-tt2692.html#none[discussion]), but all suggestions are welcome.
