# require 'rake'
require 'fileutils'

task :locale, [:lang] do |t, args|
  if !args[:lang].nil? && args[:lang].strip.length > 0
    Dir.glob("./*.adoc").each do |file|
      puts "\n#{File.basename(file)}"
      i18n_file = "#{File.basename(file, '.adoc')}.#{args[:lang]}.adoc"
      FileUtils.cp(File.basename(file), i18n_file)
      puts i18n_file
    end
  end
end

task :fly do
  zh_files = Dir.glob("./*.zh-CN.adoc")
  if zh_files.length > 0
    files = Dir.glob("./*.adoc") - zh_files

    puts "Backuping English files...\n"
    files.each do |f|
      src = File.basename f
      dest = "#{src}.english"
      FileUtils.mv(src, dest)
    end

    puts "Converting Chinese files...\n"
    zh_files.each do |f|
      src = File.basename f
      name = File.basename(src, ".zh-CN.adoc")
      dest = "#{name}.adoc"
      FileUtils.mv(src, dest)
    end
    puts "Ready OK"
  end
end

task :land do
  files = Dir.glob("./*.english")
  if files.length > 0
    zh_files = Dir.glob("./*.adoc")

    puts "Converting to Chinese files...\n"
    zh_files.each do |f|
      src = File.basename f
      name = File.basename(src, ".adoc")
      dest = "#{name}.zh-CN.adoc"
      FileUtils.mv(src, dest)
    end

    puts "Restoring to English files...\n"
    files.each do |f|
      src = File.basename f
      name = File.basename(src, ".adoc.english")
      dest = "#{name}.adoc"
      FileUtils.mv(src, dest)
    end

    puts "Restored OK"
  end
end
