:man-linkstyle: blue R <>
:mansource: Asciidoctor
:manversion: 1.5.4
:manmanual: Asciidoctor
= asciidoctor(1)

== NAME
asciidoctor - converts AsciiDoc source files

== SYNOPSIS
*asciidoctor* ['OPTION']... 'FILE'...

== OPTIONS
*-o, --out-file*=_OUT_FILE_::
  Write output to file _OUT_FILE_.

*-q, --quiet*::
  Silence warnings.

== EXIT STATUS
*0*::
  Success.

*1*::
  Failure (syntax or usage error; configuration error; document processing failure; unexpected error).

== BUGS
Refer to the *Asciidoctor* issue tracker at https://github.com/asciidoctor/asciidoctor/issues?q=is%3Aopen.

== AUTHORS
*Asciidoctor* was written by Dan Allen, Ryan Waldron, Jason Porter, Nick Hengeveld and other contributors.

*AsciiDoc* was written by Stuart Rackham and has received contributions from many other individuals.

== RESOURCES
*Project web site:* http://asciidoctor.org

== COPYING
Copyright \(C) 2012-2016 Dan Allen, Ryan Waldron and the Asciidoctor Project.
Free use of this software is granted under the terms of the MIT License.