////
Sections
Introduction
Titles as headings
Title id and prefix
Links
Anchors
Numbering

Included in:

- user-manual
////

// tag::intro[]
Sections partition the document into a content hierarchy.
In Asciidoctor, sections are defined using section titles.

A section title represents the heading for a section.
Section title levels are specified by two to six equal signs.
The number of equal signs represents the nesting level (using a 0-based index) of the title.

.Section titles available in an article doctype
[source]
----
include::ex-section.adoc[tags=base]
----

.Render section titles
====
include::ex-section.adoc[tags=b-base]
====

TIP: In addition to the equals marker used for defining single-line section titles, Asciidoctor recognizes the hash symbol (+#+) from Markdown.
That means the outline of a Markdown document will render just fine as an AsciiDoc document.

Section levels must be nested logically.
There are two rules you must follow:

. A document can only have multiple level 0 sections if the +doctype+ is set to +book+.
. Section levels cannot be skipped when nesting sections (i.e., you can't nest a level 5 section directly in a level 3 section)

For example, the following syntax is illegal:

[source]
----
include::ex-section.adoc[tags=bad]
----

Content above the first section title is designated as the document's preamble.
Once the first section title is reached, content is associated with the section it is nested in.

[source]
----
include::ex-section.adoc[tags=content]
----

// end::intro[]

=== Titles as headings
// tag::heading[]
When the document is rendered as HTML 5 (using the built-in `html5` backend), each section title becomes a heading element where the heading level matches the number of equal signs.
For example, a level 1 section (`==`) maps to an `<h2>` element.
// end::heading[]

=== Title id and prefix
// tag::id[]
Section ids are generated from the section title and prefixed with an underscore (`+_+`) by default.
You can change the prefix using the `idprefix` attribute.

[source]
----
:idprefix: -
----

If you want to remove the prefix, assign it to an empty value:

[source]
----
:idprefix:
----

To disable the auto-generation of section IDs, unset the `sectids` attribute:

[source]
----
:sectids!:
----

// end::id[]

=== Links
// tag::link[]
To turn section titles into links, enable the `sectlinks` attribute.
The default Asciidoctor stylesheet displays linked section titles with the same color and styles as unlinked section titles.
// end::link[]

=== Anchors
// tag::anchor[]
When the `sectanchors` attribute is enabled on a document, an anchor (empty link) is added before the section title.
The default Asciidoctor stylesheet renders the anchor as a section entity (`&sect;`) that floats to the left of the section title.
// end::anchor[]

=== Numbering
// tag::number[]
Asciidoctor allows section numbering to be toggled on and off throughout a document.
You can enable section numbers using the `numbered` attribute.

[source]
----
:numbered:
----
You can also use this attribute entry above any section title in the document to toggle the auto-numbering setting.
When you want to turn off the numbering, add an exclamation point to the end of the attribute name:

[source]
----
include::ex-section.adoc[tags=num-off]
----

For regions of the document where section numbering is turned off, the section numbering will not be incremented.

Given:

[source]
----
include::ex-section.adoc[tags=num]
----

The sections will be numbered as follows:

[source]
----
include::ex-section.adoc[tags=num-out]
----

Asciidoctor will always curtail incrementing the section number in regions of the document where section numbers are off.

If `numbered` is set on the command line (or API), that overrides the value set in the document header, but it does not prevent the document from toggling the value for regions of the document.

If `numbered!` is set on the command line (or API), then the numbers are disabled regardless of toggling within the document.

////
You can also restrict section numbering with the +sectnumlevels+ attribute.

[source]
----
include::ex-section.adoc[tags=sectnuml]
----
<1> When the sectnumlevels attribute is assigned a value of 2, level 3 through level 5 section titles will not be prefixed with a number.
////
// end::number[]
