////
Included in:

- user-manual: Text Substitutions: Special characters
////

When applicable, the first text substitution to occur is the replacement of any special characters.
This process is handled by the +specialcharacters+ element.
The +specialcharacters+ element searches for three characters (+<+, +>+, +&+) and replaces them with their <<char-ref-sidebar,character entity references>>.

* The less than symbol, +<+, is replaced with the +&lt;+ character entity reference.
* The greater than symbol, +>+, is replaced with the +&gt;+ character entity reference.
* An ampersand, +&+, is replaced with the +&amp;+ character entity reference.

By default, +specialcharacters+ substitution occurs on all inline and block elements except for comments and certain passthroughs.

[NOTE]
====
Special character substitution precedes attribute substitution, so you will need to manually escape any attributes containing special characters that you set in the CLI or API.
For example, on the command line, type +$$-a toctitle="Sections, Tables &amp; Figures"$$+ instead of +$$-a toctitle="Sections, Tables & Figures"$$+.
====
