////
Included in:

- user-manual: tables: column specifiers
////

The AsciiDoc syntax provides a variety of ways to control the size, style and layout of content within columns.
These *specifiers* can be applied to whole columns.

To apply a specifier to a column, you must set the +cols+ attribute and assign it a value.
A column specifier can contain any of the following components:

* multiplier
* align
* width
* style

Each component is optional.

The multiplier operator (+*+) is used when you want a specifier to apply to more than one consecutive column.
If used, the multiplier must always be placed at the beginning of the specifier.

For example:

----
include::ex-table.adoc[tags=indv-co]
----
<1> The table will consist of three columns, as indicated by the *3*. The +*+ operator ensures that the default layout and style will be applied to all of the columns.

.Result: Rendered table with multiplier applied
[width="90"]
include::ex-table.adoc[tags=indv]

[[column-align]]
The alignment component allows you to horizontally or vertically align a column's content.
Content can be horizontally aligned left (+<+), center (+^+), or right (+>+).

To horizontally center the content in all of the columns, add the +^+ operator after the multiplier.

----
[cols="3*^"]
include::ex-table.adoc[tags=base]
----

.Result: Rendered table with horizontal, center alignment applied to all columns
[width="90"]
[cols="3*^"]
include::ex-table.adoc[tags=base]

What if you only want to center the content in the last column?
Assign the default styles to the preceding columns, and +^+ to the last column in a comma separated list.

----
[cols="2*,^"]
include::ex-table.adoc[tags=base]
----

.Result: Rendered table with horizontal, center alignment applied to last column
[width="90"]
[cols="2*,^"]
include::ex-table.adoc[tags=base]

Let's specify a different horizontal alignment for each column.

----
[cols="<,^,>"]
include::ex-table.adoc[tags=base]
----

.Result: Rendered table with a different horizontal alignment for each column
[width="90"]
[cols="<,^,>"]
include::ex-table.adoc[tags=base]

You'll notice that the content in the examples above is only centered on the horizontal.
It can also be aligned vertically when the alignment operator is prefixed with a dot (+.+).
Content can be vertically aligned to the top (+<+), middle (+^+), or bottom (+>+) of a cell.

To vertically align the content to the middle of the cells in all of the columns, add a +.+ and then the +^+ operator after the multiplier.

----
[cols="3*.^"]
include::ex-table.adoc[tags=base]
----

.Result: Rendered table with vertical, middle alignment applied to all columns
[width="90"]
[cols="3*.^"]
include::ex-table.adoc[tags=base]

If you only want to align the content to the bottom of each cell in the last column, you'd assign the default styles to the preceding columns, and +>+ to the last column in a comma separated list.

----
[cols="2*,.>"]
include::ex-table.adoc[tags=base]
----

.Result: Rendered table with vertical, bottom alignment applied to last column
[width="90"]
[cols="2*,.>"]
include::ex-table.adoc[tags=base]

Let's specify a different vertical alignment for each column.

----
[cols=".<,.^,.>"]
include::ex-table.adoc[tags=base]
----

.Result: Rendered table with a different vertical alignment for each column
[width="90"]
[cols=".<,.^,.>"]
include::ex-table.adoc[tags=base]

Finally, we'll also horizontally center the content in the last column.

----
[cols=".<,.^,^.>"]
include::ex-table.adoc[tags=base]
----

.Result: Rendered table with a different vertical alignment for each column and horizontal, center alignment in the last column
[width="90"]
[cols=".<,.^,^.>"]
include::ex-table.adoc[tags=base]

When both a horizontal and vertical alignment is assigned to a column, the horizontal alignment operator must precede the vertical operator.

The width component sets the width of a column.
Its value can be a proportional integer (the default is 1) or a percentage (1 to 99).

----
[cols="1,2,6"]
include::ex-table.adoc[tags=base]
----

.Result: Table rendered with column sizes adjusted by a proportional integer
[cols="1,2,6"]
include::ex-table.adoc[tags=base]

When assigning percentage values to the +cols+ attribute, you do not need to include the percent sign (+%+).

----
[cols="50,20,30"]
include::ex-table.adoc[tags=base]
----

.Result: Table rendered with column sizes adjusted by a percentage
[cols="50,20,30"]
include::ex-table.adoc[tags=base]

Let's create a table with custom widths and alignments.

----
[cols=".<2,.^5,^.>3"]
include::ex-table.adoc[tags=base-xtr]
----

.Result: Rendered table with variable widths and alignments
[cols=".<2,.^5,^.>3"]
include::ex-table.adoc[tags=base-xtr]

[[column-style]]
The style component must always be located at the end of the specifier.
When no style name is provided column contents will be processed as regular inline text.

The column styles are described in the table below.

[cols="20,30,50"]
|===
|Style Name |Value |Description

|AsciiDoc
|+a+ or +asciidoc+
|Any document section elements may be contained within the column. The elements will be processed and rendered

|Emphasis
|+e+ or +emphasis+
|Text is italicized

|Header
|+h+ or +header+
|Header styles are applied to the column

|Literal
|+l+ or +literal+
|Column content is treated as if it were inside a literal block

|Monospaced
|+m+ or +monospaced+
|Text is rendered in monospaced font

|Strong
|+s+ or +strong+
|Text is bolded

|Verse
|+v+ or +verse+
|Column content is treated as if it were inside a verse block
|===

Let's apply the header style to the first column, the monospaced style to the second, the strong style to the third, and the emphasis style to the fourth.
 
----
[cols="h,m,s,e"]
include::ex-table.adoc[tags=4col]
----

.Result: Rendered table with a header, monospaced, and strong styled column
[width="90"]
[cols="h,m,s,e"]
include::ex-table.adoc[tags=4col]

Specifiers can also be applied to individual cells.
