////
Provide custom templates using the API
This file is included in the user-manual document
////

Asciidoctor allows you to override the converter methods used to render almost any individual AsciiDoc element. 
If you provide a directory of {uri-tilt}[Tilt]-compatible templates, named in such a way that Asciidoctor can figure out which template goes with which element, Asciidoctor will use the templates in this directory instead of its built-in templates for any elements for which it finds a matching template. 
It will fallback to its default templates for everything else.

[source,ruby]
----
 puts Asciidoctor.render '*This* is Asciidoctor.', :header_footer => true,
   :template_dir => 'templates'
----

The Document and Section templates should begin with +document.+ and +section.+, respectively. 
The file extension is used by Tilt to determine which view framework it will use to use to render the template. 
For instance, if you want to write the template in ERB, you'd name these two templates +document.html.erb+ and +section.html.erb+. 
To use Haml, you'd name them +document.html.haml+ and +section.html.haml+.

Templates for block elements, like a Paragraph or Sidebar, would begin with +block_<style>.+. 
For instance, to override the default Paragraph template with an ERB template, put a file named +block_paragraph.html.erb+ in the template directory you pass to the +Document+ constructor using the +:template_dir+ option.

For more usage examples, see the (massive) {tests}[test suite].
