////
Included in:

- user-manual: text formatting: Smart quotation marks
////

Single and double quotation marks are *not* rendered as curved quotation marks (also known as smart, curly, typographic or book quotation marks).
When entered using the kbd:[{apos}] and kbd:[{quot}] key, Asciidoctor outputs straight (dumb, vertical, typewriter)
quotation marks.
However, by creating a set of backticks (`{backtick}`) contained within a set of single quotes (`{apos}`) or double quotes (`{quot}`), you can tell Asciidoctor where to output curved quotation marks.

.Single and double curved quotation marks syntax
[source]
----
include::ex-text.adoc[tags=c-quote-co]
----
<1> To output double curved quotes, enclose a word or phrase in a set of double quotes (`{quot}`) and a set of backticks (`{backtick}`).
<2> To output single curved quotes, enclose a word or phrase in a set of single quotes (`{apos}`) and a set of backticks (`{backtick}`). In this example, the phrase _wormwood and licorice_ should be enclosed in curved single quotes when the document is rendered.

.Rendered curved quotation marks
====
include::ex-text.adoc[tags=c-quote]
====

When entered with the kbd:[{apos}] key, Asciidoctor renders an apostrophe that is directly preceded and followed by a character, such as in contractions and possessive singular forms, as a curved apostrophe.
This inconsistent handling of apostrophes and quotation marks is a hold over from the original AsciiDoc processor.
An apostrophe directly bounded by two characters is processed during the <<user-manual#replacements,replacements substitution phase>>, not the <<user-manual#quotes,quotes phase>>.
This is why an apostrophe directly followed by white space, such as the possessive plural form, is not curved by default.

To render an apostrophe as curved when it is not bound by two characters, mark it as you would a single curved quote.

.Curved apostrophe syntax
[source]
----
include::ex-text.adoc[tags=apos]
----

In the rendered output, note that the plural possessive apostrophe, seen trailing _werewolves_, is curved, as is the omission apostrophe before _60s_.

.Rendered apostrophes
====
include::ex-text.adoc[tags=apos]
====

If you don't want an apostrophe that is bound by two characters to be rendered as curved, escape it by preceding it with a backslash (`{backslash}`).
The <<user-manual#preventing-substitutions,preventing substitutions>> and <<user-manual#passthru,passthrough>> sections detail additional ways to prevent punctuation substitutions.

----
Olaf\'s desk ...
----

.Rendered escaped apostrophe
====
Olaf\'s desk ...
====

////
Add a sidebar describing the history and concerns with smart quotes regarding copy and paste and correct Unicode output.
////
