// Included in:
//
// - user-manual: URLs, URL Troubleshooting sidebar
// - troubleshoot
// - faq: troubleshoot
Why don't URLs containing underscores (+_+) or carets (+{caret}+) work after they're rendered?::
+
--
// tag::sb[]
This problem occurs because the processor misinterprets parts of the link target as valid <<user-manual#text-formatting,text formatting markup>>.
Most lightweight markup languages have this issue because they don't use a grammar-based parser.
Asciidoctor plans to move to a grammar-based parser in the future, but don't worry, there are ways to solve this problem now.

.Solution A
====
The simplest way to get a link to behave is to assign it to an attribute.

[source]
----
= Document Title
:link-with-underscores: http://www.asciidoctor.org/now_this__link_works.html

This URL has repeating underscores {link-with-underscores}.
----
Asciidoctor won't break links with underscores when they are assigned to an attribute because <<user-manual#text-substitutions,inline formatting markup is substituted before attributes>>.
The URL remains hidden while the rest of the document is being formatted (strong, emphasis, monospace, etc).
====

.Solution B
====
Another way to solve formatting glitches is to explicitly specify the formatting you want to have applied to a span of text.
This can be done by using the <<user-manual#passthrough-macros,inline pass macro>>. 
If you want to display a URL, and have it preserved, put it inside the +pass+ macro and enable the <<user-manual#sub-macros,macros substitution>>, which is what substitutes links.

[source]
----
This URL has repeating underscores pass:macros[http://www.asciidoctor.org/now_this__link_works.html].
----
The +pass+ macro removes the URL from the document, applies the +macros+ substitution to the URL, and then restores the processed URL to its original location once the substitutions are complete on the whole document.
====
// end::sb[]
--
