////
=== Include content from a URI

This content is included in the user manual
////

The +include+ directive can include content directly from a URI.

Here's an example that demonstrates how to include AsciiDoc content:

```
:asciidoctor-source: https://raw.github.com/asciidoctor/asciidoctor/master

\include::{asciidoctor-source}/README.adoc[]
```

Since this is a potentially dangerous feature, it's disabled if the safe mode is +SECURE+ or greater.
Assuming the safe mode is less than +SECURE+, you must also set the +allow-uri-read+ attribute to permit Asciidoctor to read content from a URI.

Reading content from a URI is obviously much slower than reading it from a local file.
Asciidoctor provides a way for the content read from a URI to be cached, which is highly recommended.

To enable the built-in cache, you must:

* install the open-uri-cached gem
* set the +cache-uri+ attribute

When these two conditions are satisfied, Asciidoctor will cache content read from a URI according the to {http-ref}[HTTP caching recommendations].
