////
=== Include content from a URI

This content is included in the user manual
////

The include directive can insert content directly from a URI when the `allow-uri-read` attribute is:

* Passed on the command-line,
* Passed as an attribute to the Asciidoctor API (Asciidoctor, AsciidoctorJ or Asciidoctor.js).

.Including content from a URI
====
This example demonstrates how to include an AsciiDoc file from a GitHub repo directly into your document.

[source]
----
include::ex-include.adoc[tags=uri]
----
====

WARNING: Including content from sources outside your control carries certain risks, including the potential to introduce malicious behavior into your documentation.

Because `allow-uri-read` is a potentially dangerous feature, it will only work if safe mode is set to `SERVER` or less. `SECURE` or higher prevents this feature from running altogether.

.URI vs URL
****
URI stands for https://en.wikipedia.org/wiki/Uniform_Resource_Identifier[Uniform Resource Identifier].
When we talk about a URI, we're usually talking about a URL, or Uniform Resource Locator.
A URL is simply a URI that points to a resource over a network, or web address.

As far as Asciidoctor is concerned, all URIs share the same restriction, whether or not it's actually local or remote, or whether it points to a web address (http or https prefix), FTP address (ftp prefix), or some other addressing scheme.
****

When running Asciidoctor with safe mode set to `SERVER` or less, you must also set the `allow-uri-read` attribute on the command-line to permit Asciidoctor to read content from a URI.

.Command Example
[source]
----
asciidoctor -a allow-uri-read filename.adoc
----

The same restriction applies when embedding an image that is referenced from a URI, such as when `data-uri` is set or when converting to PDF using Asciidoctor PDF.

=== Caching URI Content

Reading content from a URI is obviously much slower than reading it from a local file.

Asciidoctor provides a way for the content read from a URI to be cached, which is highly recommended.

To enable the built-in cache, you must:

. Install the `open-uri-cached` gem.
. Set the `cache-uri` attribute in the document.

When these two conditions are satisfied, Asciidoctor caches content read from a URI according the to {uri-http}[HTTP caching recommendations].
