////
Included in:

- user-manual: Defining an Anchor
////

Anchor can be defined everywhere: header, image, listing or text bloc.
The cross reference ID is defined between two square brackets.

.Inline anchor example
----
include::ex-xref.adoc[tags=anchor-brackets]
----

[.result]
====
include::ex-xref.adoc[tags=anchor-brackets]
====

It is possible to define the text that will be used in the cross reference link (called `xreflabel`).
If not defined asciidoctor does it best to find a suitable text (the solution differs from case to case).
In case of an image, the image caption will be used.
In case of a section header, the text of the header will be used.

To define the `xreflabel`, add it in the anchor definition right after the ID (separated by a coma).

.anchor with a defined xreflabel, the caption will not be used as link text
----
include::ex-xref.adoc[tags=anchor-xreflabel]
----

Instead of the bracket form, you can use the macro `anchor` to achieve the same goal.

.anchor using the macro form
----
include::ex-xref.adoc[tags=anchor-macro]
----
