////
Included in:

- user-manual: Inter-document cross references
- faq
////
In certain environments, such as GitHub and the browser extensions, you view the generated HTML from the AsciiDoc source URL.
Since the default suffix for relative links is `.html`, the inter-document cross references end up pointing to non-existent HTML files.
You need, instead, to get inter-document cross references to refer to other AsciiDoc source files.
You can achieve this behavior by setting the `outfilesuffix` attribute to the value as `.adoc`, as the example below shows.

----
= Document Title
\ifdef::env-github,env-browser[:outfilesuffix: .adoc]

See the <<README#,README>>.

We could also write the link as link:README{outfilesuffix}[README].
----

The links in the generated document will now point to [path]_README.adoc_ instead of the default, [path]_README.html_.

CAUTION: You probably don't want to set `outfilesuffix` to `.adoc` without the `ifdef` condition as it could result in Asciidoctor overwriting input files when you run it locally (though there's some protection against this).
