////
Included in:

- user-manual: Defining an Anchor
////

An anchor can be defined anywhere: header, image, listing or text block.
The anchor's ID is defined between two square brackets.

.Defining an inline anchor ID
----
include::ex-xref.adoc[tags=anchor-brackets]
----

[.result]
====
include::ex-xref.adoc[tags=anchor-brackets]
====

In addition to being able to define anchors on sections and blocks, anchors can be defined inline where ever you can type normal text (anchors are a macro substitution).
The anchors in the text get replaced with invisible anchor points in the output.

For example, you would not put an anchor in front of a list item:

.Wrong position for an anchor ID in front of a list item.
----
include::ex-xref.adoc[tags=anchor-wrong]
----

Instead, you would put it at the very start of the text of the list item:

.Defining an inline anchor ID in a list item
----
include::ex-xref.adoc[tags=anchor-list]
----

An other example with headers (the anchor needs to be in the text):

.Defining an inline anchor ID in an header
----
include::ex-xref.adoc[tags=anchor-header]
----

Just keep in mind that inline anchor points are discovered where text is permitted.
If text doesn't belong somewhere, then neither does an inline anchor point.

It is possible to customize the text that will be used in the cross reference link (called `xreflabel`).
If not defined, Asciidoctor does it best to find suitable text (the solution differs from case to case).
In case of an image, the image caption will be used.
In case of a section header, the text of the section's title will be used.

To define the `xreflabel`, add it in the anchor definition right after the ID (separated by a comma).

.An anchor ID with a defined xreflabel. The caption will not be used as link text.
----
include::ex-xref.adoc[tags=anchor-xreflabel]
----

Instead of the bracket form, you can use the macro `anchor` to achieve the same goal.

.Setting an anchor ID using the macro form
----
include::ex-xref.adoc[tags=anchor-macro]
----
