////
Included in:

- user-manual: Internal cross references
- writers-guide
////

In Asciidoctor, the xref inline macro is used to create cross references to content, sections, and elements using an ID.
A cross reference is created by enclosing the element's ID in double angled brackets.

.Cross reference using a section heading's ID
[source]
----
include::ex-xref.adoc[tags=base]
----

.Rendered cross reference using a section heading's ID
====
include::ex-xref.adoc[tags=base]
====

You can also link to section headings using their titles.

.Cross reference using a section's title
[source]
----
include::ex-xref.adoc[tags=xref-title]
----

.Rendered cross reference using a section's title
====
include::ex-xref.adoc[tags=xref-title]
====

Some converters, such as the HTML converter, will use the `xreflabel` as default text of the link.
For each link, you can also customize this text, include it after the ID, separating them by a comma.

[source]
----
include::ex-xref.adoc[tags=text]
----

====
include::ex-xref.adoc[tags=text]
====

You can also use the macro `xref` to achieve the same goal.

[source]
----
include::ex-xref.adoc[tags=xref-macro]
----