= Notices for the asciidoctor.org Project

This repository contains the source code and documentation content used to produce the site at https://asciidoctor.org.
The published site along with its source is maintained as part of the Asciidoctor project.

Project home: https://asciidoctor.org

== Trademarks

AsciiDoc(R) and AsciiDoc Language(TM) are trademarks of the Eclipse Foundation, Inc.

== Copyright

All source code and content is the property of the respective authors or their employers.
For more information regarding authorship of these files, please consult the listed source code repository logs.

== Declared Project Licenses

The source code in this repository, which is used to produce the site published at https://asciidoctor.org, is licensed under the terms of the MIT license, which is available at https://mit-license.org/.

SPDX-License-Identifier: MIT

The documentation content in the docs/ folder of this repository, which is published to https://asciidoctor.org, is made available under the terms of a Creative Commons Attribution 4.0 International License, which is available at https://creativecommons.org/licenses/by/4.0/.

SPDX-License-Identifier: CC-BY-4.0
