= asciidoctor.org image:https://secure.travis-ci.org/asciidoctor/asciidoctor.org.svg?branch=master["Build Status", link="https://travis-ci.org/asciidoctor/asciidoctor.org"]
// URIs:
:uri-letsencrypt: https://letsencrypt.org
:uri-letsencrypt-article: https://fedoramagazine.org/letsencrypt-now-available-fedora/

This is the project site for the http://asciidoctor.org[Asciidoctor] project.
The site is composed in AsciiDoc, styled by http://foundation.zurb.com/sites/docs/v/4.3.2[Foundation 4], baked with http://awestruct.org/[Awestruct], and published by https://travis-ci.org/[Travis CI].

For instructions on how to install Awestruct and its dependencies, refer to the <<Install Awestruct>> section below.

== Preview the site locally

To preview the site locally, simply run the default rake build task:

 $ rake

The default rake build task is `preview`, so you're effectively typing:

 $ rake preview

The `preview` task is just a short way of invoking Awestruct in development mode directly:

 $ awestruct -d

Now visit http://localhost:4242 to preview the site.

To rebuild the site from a clean state, pass the `--force` flag to the `preview` task:

 $ rake preview[--force]

You can pass any flag through to Awestruct using the syntax in the previous command.

If you just want to generate the site, run:

 $ rake gen

////
=== Set the JavaScript runtime

If you're building the site on Linux and Awestruct fails to locate a JavaScript runtime, you can either:

. install a node.js package or
. set the following environment variable in your shell profile scripts (e.g., `~/.bash_profile`):

 $ export EXECJS_RUNTIME=SpiderMonkey
////

== Add and commit files

Add new files (such as a new blog entry or image):

 $ git add news/news-slug.adoc

or all new files present in a directory (it only affects new files, skips files already committed)

 $ git add news/

Commit all files marked to be committed, including new files that were just added:

 $ git commit -m 'your message here'

Commit all files that have changed, even if not marked to be committed:

 $ git commit -a -m 'your message here'

Make sure there are no files that are "untracked" or "modified":

 $ git status

You should see:

[.output]
....
nothing to commit (working directory clean)
....

Now you are ready to deploy.

== Deploy the site to GitHub Pages

The following commands will push changes (`git push`), clean build the site (`--force -g`) using the production profile (`-P production`), then deploy it to github pages (`--deploy`):

 $ git push &&
   awestruct -P production --force -g --deploy

Or simply run the prepared rake build task (to deploy locally):

 $ rake deploy

Or just push and let https://travis-ci.org/asciidoctor/asciidoctor.org[Travis CI] do the work of deploying the site:

 $ rake push

If you want to push without triggering a publish, add the following to the commit message:

....
[ci skip]
....

== Install Awestruct

First, install http://rvm.io[RVM].
Trust me on this.

 $ curl -#L https://get.rvm.io | bash -s stable --ruby

Next, setup an RVM gemset for working with the Asciidoctor site:

 $ rvm use 2.4 --create

At this point, you could install Awestruct directly, but since the site build has some additional dependencies, it's best to let bundler handle the installation.
Bundler will also ensure that you are using the correct versions of each gem when you run Awestruct.

 $ bundle --path=.bundle/gems

You're now Awestruct!

== DNS records

The site runs on the domain name asciidoctor.org, which is specified in the CNAME file.
The GitHub server automatically sets up redirects that point from www.asciidoctor.org to asciidoctor.org.

See the following help page for more details: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages

== TLS Certificate (https)

The TLS certificate for asciidoctor.org was issued by https://github.com/mojavelinux[mojavelinux] using {uri-letsencrypt}[Let's Encrypt]
It was last created on 2018-02-13 using the `letsencrypt` tool installed from the Fedora package `letsencrypt`.

 $ sudo letsencrypt certonly -a manual -d asciidoctor.org

The acme challenge page was created on asciidoctor.org when prompted, then removed once the process was complete.

//The certificate (PEM) (from fullchain.pem) and key (PEM) (from privkey.pem) were then entered into the Netifly configuration screen for asciidoctor.org.

The certificate will expire on 2018-05-06.
Verify the certificate is valid using:

 $ curl -vI https://asciidoctor.org

Look for `CN=asciidoctor.org` under the "`Server certificate`" section.

To obtain a new version of this certificate in the future, simply run the `letsencrypt` command above again.
To non-interactively renew all registered certificates, run `letsencrypt renew`.

Refer to the {uri-letsencrypt-article}[Let's Encrypt article] in Fedora Magazine for more details about this process.
