= Write Javadocs in Asciidoc with Asciidoclet
John Ericksen
2013-06-03
:revdate: 2013-05-19 21:43:51 -0600
:awestruct-tags: [announcement, plugin]
:asciidoc-ref: http://asciidoc.org
:asciidoctor-ref: link:/
:aji-ref: https://github.com/asciidoctor/asciidoctor-java-integration
aa:repo-ref: https://github.com/asciidoctor/asciidoclet
:issues-ref: https://github.com/asciidoctor/asciidoclet/issues
:gh-ref: https://github.com

We're excited to announce the newest member of the {asciidoctor-ref}[Asciidoctor] family {repo-ref}[Asciidoclet].  {repo-ref}[Asciidoclet] is a Javadoc Doclet that enables Javadoc comments in {asciidoc-ref}[AsciiDoc] format.

From the very beginning, one concept the designers of Java got right was to include documentation with source code.  This allowed documentation to stay closer in sync with ever-changing source and allowed multiple viewing platforms, most notably the html generation and IDE integration.  The only drawback with this strategy has been to achieve advanced Javadoc markup, one was required to include html in the Javadoc source comments.  This is where the {asciidoc-ref}[AsciiDoc] formatting shines.  Being a lightweight markup language, {asciidoc-ref}[AsciiDoc] allows content developers to focus on the content rather than the markup while still able to achieve beautiful end-results.  Pairing this with Javadocs means readable source and beautifully rendered Javadocs, the best of both worlds!

== Usage

Once {repo-ref}[Asciidoclet] is plugged into Javadoc, it's just a matter of using {asciidoc-ref}[AsciiDoc] mark up in Javadocs.  The following demonstrates a number of features of {repo-ref}[Asciidoclet]:

[source,java]
--
/**
 * = Asciidoclet <1>
 *
 * Sample comments that include +source code+. <2>
 *
 * [source,java] <3>
 * --
 * public class Asciidoclet extends Doclet {
 *     private final Asciidoctor asciidoctor = Asciidoctor.Factory.create();
 *
 *     @SuppressWarnings("UnusedDeclaration") <4>
 *     public static boolean start(RootDoc rootDoc) {
 *         new Asciidoclet().render(rootDoc);
 *         return Standard.start(rootDoc);
 *     }
 * }
 * --
 *
 * @author https://github.com/johncarl81[John Ericksen] <5>
 */
public class Asciidoclet extends Doclet {
}
--

<1> Titles are easy to create using the +=+ markup.
<2> Paragraphs are defaulted and do not require the +<p>+ html tag.  In addition, inline source may be marked up using the +++ monospace markup.
<3> Source is easily marked up using the +[source,type]+ tag and fences (+--+)
<4> The notorious +@+ symbol is automatically handled by {repo-ref}[Asciidoclet], avoiding the standard +{@literal @}+ boilerplate.
<5> Inline {asciidoc-ref}[AsciiDoc] markup is available within Javadoc tags.  This example highlights link rendering.

== Installation

{repo-ref}[Asciidoclet] is a standard Javadoc Doclet and may be used as such.  One of the easiest ways to install {repo-ref}[Asciidoclet] is by adding it as a Doclet to the `maven-javadoc-plugin`:

.Maven Doclet declaration
[source,xml]
--
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-javadoc-plugin</artifactId>
    <version>2.9</version>
    <executions>
        <execution>
            <id>attach-javadocs</id>
            <goals>
                <goal>jar</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <doclet>org.asciidoctor.Asciidoclet</doclet>
        <docletArtifact>
           <groupId>org.asciidoctor</groupId>
           <artifactId>asciidoclet</artifactId>
           <version>${asciidoclet.version}</version>
        </docletArtifact>
    </configuration>
</plugin>
--

We hope that this extension helps you push your Javadocs to new heights.  As always, collaboration is welcome and you may find all the source on {repo-ref}[Github].

A big thanks to {gh-ref}/lordofthejars[Alex Soto] of the {aji-ref}[Asciidoctor-Java-Integration project], {gh-ref}/lightguard[Jason Porter] and {gh-ref}/mojavelinux[Dan Allen] for their feedback and support and everyone else on the {asciidoctor-ref}[Asciidoctor] team.  Writing this extension could not have been easier because of the great work and collaboration of the {asciidoctor-ref}[Asciidoctor] community.