= Asciidoctor Maven plugin 0.1.3 released!
Jason Porter
2013-06-11
:revdate: 2013-06-11 16:23:00 -0600
:awestruct-tags: [release, plugin]
:repo-ref: https://github.com/asciidoctor/asciidoctor-maven-plugin
:query-ref: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.asciidoctor%22%20AND%20a%3A%22asciidoctor-maven-plugin%22
:detail-0-1-3-ref: http://search.maven.org/#artifactdetails%7Corg.asciidoctor%7Casciidoctor-maven-plugin%7C0.1.3%7Cmaven-plugin
:get-0-1-3-ref: http://search.maven.org/remotecontent?filepath=org/asciidoctor/asciidoctor-maven-plugin/0.1.3/asciidoctor-maven-plugin-0.1.3
:java-int-ref: https://github.com/asciidoctor/asciidoctor-java-integration#readme
:asciidoctor-ref: https://github.com/asciidoctor/asciidoctor
:github-milestone-ref: https://github.com/asciidoctor/asciidoctor-maven-plugin/issues?milestone=4&state=closed

It has taken me a little while longer to get this release out the door than I would have hoped, but at least it's done!
I'm proud to release {repo-ref}[Asciidoctor Maven plugin] version 0.1.3!
Like the other versions before it, it is based on the same version of the {java-int-ref}[Asciidoctor Java integration] project and the {asciidoctor-ref}[Asciidoctor] projects -- 0.1.3.

There's very little new things for the end user in this release as the changes were mostly to use some of the new ease of use things from the Java Integration project. 

I would like to call out the help of https://github.com/bleathem[Brian Leathem] in this release in helping me go through a few things and pushing me to release it. Also, thank you to all the https://github.com/asciidoctor/asciidoctor-maven-plugin/contributors[contributors] for helping out.

Go forth and make great documentation once again!

.Plugin artifact information
[cols="4", options="header", caption=""]
|===
|Group ID
|Artifact ID
|Latest versions
|Download

|org.asciidoctor
|{query-ref}[asciidoctor-maven-plugin]
|{detail-0-1-3-ref}[0.1.3]
|{get-0-1-3-ref}.pom[pom] {get-0-1-3-ref}.jar[jar]
|===

Upgrading to 0.1.3 (recommended) is simple.
Just update the version in your Maven POM.
All necessary dependencies should be pulled in via Maven.

For more information about issues fixed in this release, please see the {github-milestone-ref}[0.1.3 milestone] in the issue tracker!
