= Asciidoctor.js 1.5.0 released to Bower and npm!
Guillaume Grossetie <https://github.com/Mogztter[@Mogztter]>
2014-08-17
:page-draft:
:page-tags: [release, asciidoctor.js]
:compat-mode!:
:asciidoctorjs-uri: https://github.com/asciidoctor/asciidoctor.js
:frontend-guide-uri: {asciidoctorjs-uri}#front-end-development
:backend-guide-uri: {asciidoctorjs-uri}#back-end-development

The release train is on the move! Version 1.5.0 of Asciidoctor.js has been released and is now available as Bower and npm package.
This release is an important step toward making Asciidoctor.js widely available in the JavaScript ecosystem.

== Release highlights

=== Asciidoctor.js is Asciidoctor

As mentionned in the Asciidoctor 1.5.0 release, we worked hard to align Asciidoctor.js with Asciidoctor core.

Now that Asciidoctor.js builds directly against master, we still need to provide specific implementations depending on the environment.
For example when you want to include files, in Asciidoctor core we are using the Ruby IO API to read the content of the included file.
As you may understand, in a JavaScript environment we want to use `XMLHttpRequest` or the File System API of Node.js `fs.readSync()` to make it work.

Be assured that we are working on it and that will we do our best to make all the great features of Asciidoctor core available in JavaScript.

=== Using Asciidoctor.js is easier than ever before

If you are a JavaScript developer, you are one command line away from getting the latest version of Asciidoctor.js

[source, bash]
.bower
----
$ bower install asciidoctor.js --save
----

[source, bash]
.npm
----
$ npm install asciidoctor.js --save
----

=== Bower package

Once the package installed, you can add the following `script` tag to your HTML page:

[source,html]
----
<script src="bower_components/asciidoctor.js/dist/asciidoctor-all.min.js"></script>
----

The `asciidoctor-all.min.js` is a `minified` version and includes Asciidoctor core, extensions API and Opal.

Here is a simple example that convert AsciiDoc as HTML using `notitle!` attribute:
[source,javascript]
----
var asciidoc = "http://asciidoctor.org[*Asciidoctor*] " +
    "running on http://opalrb.org[_Opal_] " +
    "brings AsciiDoc to the browser!";
var options = Opal.hash2(['attributes'], {'attributes': ['notitle!']});
var html = Opal.Asciidoctor.$convert(asciidoc, options);
----

See the {frontend-guide-uri}[Front-end development guide] to learn more about the Bower package.

=== npm package

The first thing to do is to load the `asciidoctor.js` module `require('asciidoctor.js')();`, then you are good to go:

[source,javascript]
----
var asciidoctor = require('asciidoctor.js')();

// You can get Opal
var opal = asciidoctor.Opal;

// You can get Asciidoctor with Extensions ...
var asciidoctorWithExtensions = asciidoctor.Asciidoctor(true);
// ... or without extensions
// var asciidoctorWithoutExtensions = asciidoctor.Asciidoctor();

// Now you can use it
var asciidoc = "http://asciidoctor.org[*Asciidoctor*] " +
    "running on http://opalrb.org[_Opal_] " +
    "brings AsciiDoc to Node.js!";
var options = Opal.hash2(['attributes'], {'attributes': ['notitle!']});
var html = asciidoctorWithExtensions.$convert(asciidoc, options);
----

See the {backend-guide-uri}[Back-end development guide] to learn more about the npm package.


