= Asciidoctor Maven plugin 0.1.3.1 released!
Jason Porter
2013-06-23
:revdate: 2013-06-23 20:05:00 -0600
:awestruct-tags: [release, plugin]
:repo-ref: https://github.com/asciidoctor/asciidoctor-maven-plugin
:query-ref: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.asciidoctor%22%20AND%20a%3A%22asciidoctor-maven-plugin%22
:detail-0-1-3-1-ref: http://search.maven.org/#artifactdetails%7Corg.asciidoctor%7Casciidoctor-maven-plugin%7C0.1.3.1%7Cmaven-plugin
:get-0-1-3-1-ref: http://search.maven.org/remotecontent?filepath=org/asciidoctor/asciidoctor-maven-plugin/0.1.3.1/asciidoctor-maven-plugin-0.1.3.1
:java-int-ref: https://github.com/asciidoctor/asciidoctor-java-integration#readme
:asciidoctor-ref: https://github.com/asciidoctor/asciidoctor
:github-milestone-ref: https://github.com/asciidoctor/asciidoctor-maven-plugin/issues?milestone=6&state=closed

I'm proud to announce the {repo-ref}[Asciidoctor Maven plugin] version 0.1.3.1 release!
This is simply a bug fix release to correct some of the things I messed up with 0.1.3 (sorry about that).
Like version 0.1.3 before it, it's based on the same version of the {java-int-ref}[Asciidoctor Java integration] project and the {asciidoctor-ref}[Asciidoctor] projects -- 0.1.3.

Thank you to all the https://github.com/asciidoctor/asciidoctor-maven-plugin/contributors[contributors] for helping out.

Go forth and make great documentation once again!

.Plugin artifact information
[cols="4", options="header", caption=""]
|===
|Group ID
|Artifact ID
|Latest versions
|Download

|org.asciidoctor
|{query-ref}[asciidoctor-maven-plugin]
|{detail-0-1-3-1-ref}[0.1.3.1]
|{get-0-1-3-1-ref}.pom[pom] {get-0-1-3-1-ref}.jar[jar]
|===

Upgrading to 0.1.3.1 (recommended) is simple.
Just update the version in your Maven POM.
All necessary dependencies should be pulled in via Maven.

For more information about issues fixed in this release, please see the {github-milestone-ref}[0.1.3.1 milestone] in the issue tracker!
