= Asciidoctor 0.1.2 released!
Dan Allen
2013-04-24
:awestruct-tags: [release]
:awestruct-draft: true

We're proud to announce the release of https://rubygems.org/gems/asciidoctor[Asciidoctor 0.1.2]!
Asciidoctor is an open source text processor and publishing toolchain for converting AsciiDoc markup into HTML 5, DocBook 4.5 and other formats.

The focus of this release cycle was on:

- compliance with the AsciiDoc syntax
- conformance with the AsciiDoc HTML and DocBook output
- shipping a default stylesheet
- a new website and documentation

// I suggest taking the mention of documentation out since there isn't any mention of it else where in this post and because I think enough changes have been done to it that it deserves it's own blog post to highlight updates, the overall vision, and the gaps. To do all that here would make this realllllllly long. How about doing the State of the Documentation Spotlight next tuesday? Plus, then we can re-highlight the release? Thoughts?

Thanks to the valuable feedback we received, this release brings Asciidoctor to within 99% compliance of the AsciiDoc syntax.
The improvements have given Asciidoctor a 20% boost in speed, now over *30x* as fast as AsciiDoc.

== Key improvements

// The improvements that are likely of the most interest are as follows: <- I'm not down this sentence, too wishy washy, like you're apologizing for the stuff that didn't make the cut...I'd just remove it and let the Section header speak for the content.

docinfo files::

  docinfo files are now added to the rendered output. They are used to include custom content to the header. Resolves issues: http://github.com/asciidoctor/asciidoctor/issues/116[116], http://github.com/asciidoctor/asciidoctor/issues/193[193]

leveloffset::

  the leveloffset attribute is now supported. This attribute helps combine several standalone documents together into a master document. Resolves issue: http://github.com/asciidoctor/asciidoctor/issues/212[212]

partial includes::

  the include macro can now include select regions of a file by line numbers, line ranges or tagged regions. This macro is unique to Asciidoctor. Resolves issue: http://github.com/asciidoctor/asciidoctor/issues/226[226]

footnotes in embedded mode::

  footnotes can now be rendered at the bottom of the output in embedded mode when the header and footer are disabled, such as on GitHub.  Resolves issue: http://github.com/asciidoctor/asciidoctor/issues/206[206]

default stylesheet::

  a default stylesheet now ships with Asciidoctor to give documents a unique, modern and elegant look and feel out of the box. Resolves issues: http://github.com/asciidoctor/asciidoctor/issues/76[76], http://github.com/asciidoctor/asciidoctor/issues/165[165]

multiple authors::

  it's now possible to specify multiple authors in the header of the document. This feature is unique to Asciidoctor. Resolves issue: http://github.com/asciidoctor/asciidoctor/issues/223[223]

email macro::

  the inline email address and the inline mailto macro are now recognized. Resolves issue: http://github.com/asciidoctor/asciidoctor/issues/213[213]

custom block substitutions::

  the substitution groups applied to block content can now be customized. Resolves issue: http://github.com/asciidoctor/asciidoctor/issues/220[220]

masquerading blocks and paragraphs::

  the open block and paragraphs can now masquerade as any style of block, and masquerading is implemented for other blocks where applicable. Previously, this was one of the weakest areas of Asciidoctor, but it is now fully compliant. Resolves issue: http://github.com/asciidoctor/asciidoctor/issues/187[187]

In order to implement full support for masquerading blocks, paragraphs and custom block substitutions, the main block parsing code had to be reworked.
The refactoring not only cleaned up the code, but laid the foundation needed to implement block filters and other extensions.

The full list of new features, enhancements and patches implemented for this release can be viewed http://github.com/asciidoctor/asciidoctor/issues?milestone=3&page=1&state=closed[here].

== Thanks

The amount of participation in the Asciidoctor project, particularly around the integrations, has increased tremendously since the last release.
Asciidoctor 0.1.1 crossed the 10,000 downloads mark prior to this release.
We look forward to 0.1.2 breaking the next 10,000.

We're very grateful to everyone who participates, especially those who contribute and spread the word :)
We'd especially like to thank the following people for their contributions and feedback:

- Brian Leathem (Clutch code reviewer)
- Jason Porter (Maven plugin lead)
- Sarah White (Documentation and user experience)
- Alex Soto (Java integration lead)
- Andres Almiray (Gradle plugin lead)
- Guillaume Laforge
- Viktor Gamov
- Anders Nawroth
- Ryan Waldron
- Paul Rayner (Guard plugin lead)
- Kurt Stam
- Benjamin Muschko

Together, we're making documentation easy, fun and rewarding!
