= Diagrams come to Asciidoctor
Pepijn Van Eeckhoudt <https://github.com/pepijnve>
2014-02-16
:revdate: 2014-02-16 03:37:00 +0200
ifndef::awestruct[]
:imagesdir: ../images
endif::[]
:icons: font
:page-tags: [github]
:asciidoctor-uri: http://asciidoctor.org
:pygments-uri: http://pygments.org

Asciidoctor is a fantastic tool to use when writing technical documentation.
It allows you to spend more time focusing on your content rather than struggling with wysiwyg tools.
One thing that has been more difficult then necessary up until now is integrating technical diagrams in your documents.
This still required opening a UML or diagramming tool, drawing the diagrams, exporting them to a usable image format and integrating them into your documents.
The many benefits that asciidoc provides in terms of visual consistency, ease of collaboration, etc are not available to this part of your document.

All that changes today with the announcement of the asciidoctor-diagram extension.
Asciidoctor-diagram integrates existing plain text syntax diagramming tools into the Asciidoctor processing allowing you to embed the source code for your diagrams directly into your documents.
The first version of the plugin supports the http://ditaa.sourceforge.net[ditaa], http://www.graphviz.org/content/dot-language[graphviz dot] and http://www.plantuml.com[PlantUML] syntaxes.

== Enabling the extension


== Adding your first diagram

The simplest way to add diagrams to your documents is by adding diagram blocks inline in the document.
Just add a listing block to your file using the appropriate syntax name (`ditaa`, `graphviz` or `plantuml`) as block style.

[source]
---------
[ditaa]
----
                   +-------------+
                   | asciidoctor |-------+
                   |  diagram    |       |
                   +-------------+       | png out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ asciidoctor +--> |               |
 |  Text  |   +-------------+    |Beatiful output|
 |Document|   |   !magic!   |    |               |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
----
---------

When asciidoctor-diagram processes this type of block it will read the body of the block, pass it to the ditaa library, write the resulting image to disk and generate an image block.
Generating one of these images is fairly quick, but if you start adding lots of diagrams to your document the processing time can start adding up.
Asciidoctor-diagram optimizes the processing by keeping track of diagram metadata and will only regenerate the images if the diagram source code actually changed.
This keeps incremental rendering of documents a speedy process.

== Controlling the output

By default asciidoctor-diagram creates PNG images and calculates an output file name automatically based on the diagram source code.
This behaviour can be overridden using the `target` and `format` attributes.
You can specify these as the first and second positional attributes or as named attributes.
An SVG file with a specific name a graphviz diagram can be generated as follows

[source]
---------
[graphviz, target="dotexample", format="svg"]
----
digraph {
    a -> b;
	b -> c;
	c -> d;
    d -> a;
}
----
---------

Asciidoctor-diagram generates regular image blocks and applies any additional attributes to the generated block.
This means you can use the normal Asciidoctor facilities to control the positioning of the generated image.
Titles and ids can also be assigned in the same way.

[source]
---------
[[main-classes]]
.The main classes in our system
[plantuml, alt="Class diagram", width="300", height="200"]
----
class BlockProcessor
class PlantUmlBlock
BlockProcessor <|-- PlantUmlBlock
----
---------

== Including external diagrams

It might not always be desirable to embed the source code for diagrams in your document.
External diagrams can also be processed using the block macro syntax.
This is very similar to how you typically include images in your documents.

[source]
---------
plantuml::classes.txt[format="svg", alt="Class diagram", width="300", height="200"]
---------

== Enabling the extension

Asciidoctor 0.1.4 does not yet allow extensions to be enabled via the command line.
The easiest way to enable the extensions today is to use a small wrapper Ruby script that requires the extension and then invokes Asciidoctor.

[source,ruby]
----
# Require Asciidoctor
require 'asciidoctor'
require 'asciidoctor/cli/options'
require 'asciidoctor/cli/invoker'

# Require Asciidoctor-diagram to enable the extensions
require 'asciidoctor-diagram'

# Delegate to Asciidoctors CLI
Asciidoctor::Cli::Invoker.new(*ARGV).invoke!
----
