blank_issues_enabled: false
contact_links:
- name: Asciidoctor Project Chat
  url: https://chat.asciidoctor.org
  about: This issues in this repository pertain only to the pages in the aciidoctor.org website and are restricted to project maintainers. Please direct any questions about Asciidoctor and AsciiDoc to the project chat.
