////
Included in:

- user-manual
////

You specify index terms using one of the following syntaxes

----
=== Sir Lancelot

The Lady of the Lake, her arm clad in the purest shimmering samite,
held aloft Excalibur from the bosom of the water,
signifying by divine providence that I, ((Arthur)), <1>
was to carry Excalibur (((Sword, Broadsword, Excalibur))). <2>
That is why I am your king. Shut up! Will you shut up?!
Burn her anyway! I'm not a witch.
Look, my liege! We found them.

indexterm2:[Lancelot] was one of the Knights of the Round Table. <3>
indexterm:[knight,Knight of the Round Table,Lancelot] <4>
----
<1> The double parenthesis form adds a primary index term and includes the term in the generated output.
<2> The triple parenthesis form allows for an optional second and third index term and _does not_ include the terms in the generated output.
<3> The inline macro `\indexterm2:[primary]` is equivalent to the double parenthesis form.
<4> The inline macro `\indexterm:[primary, secondary, tertiary]` is equivalent to the triple parenthesis form.

WARNING: Asciidoctor does not currently generate the index when using the built-in HTML5 or Asciidoctor PDF converter (a limitation that is shared with AsciiDoc Python).
To generate an index in the interim, you have to produce HTML5 or PDF by way of DocBook using the DocBook toolchain (`a2x` or `fopub`).
We're tracking support for native index generation when using the built-in HTML5 converter in https://github.com/asciidoctor/asciidoctor/issues/450[issue #450]
and for the Asciidoctor PDF converter in https://github.com/asciidoctor/asciidoctor-pdf/issues/386[issue #386].
