title: Asciidoctor
description: An open source implementation of AsciiDoc in Ruby
author: Asciidoctor Project
blog_path: /news
# Disable interpolate after upgrading to Awestruct 0.5.4
#interpolate: false
# FIXME timezone will need to be specified per post for a global team
local_tz: America/Denver
disqus: asciidoctor
disqus_generate_id: true
disqus_developer: true
haml:
  :ugly: true
asciidoctor:
  :base_dir: null
  :attributes:
    compat-mode: '@'
    idprefix: ''
    idseparator: '-'
    icons: font
    sectanchors: ''
    linkattrs: ''
    #source-highlighter: highlight.js
    source-highlighter: coderay
    prewrap: null
# if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    deploy: nil
  staging:
    deploy: nil
  production:
    base_url: http://asciidoctor.org
    disqus_developer: false
    google_analytics:
      account: UA-38215684-1
    compass_output_style: :compressed
    # TODO enable minify once we verify it's working as expected
    #minify: true
    deploy:
      host: github_pages
      branch: gh-pages
