= Asciidoctor 1.5 Release Notes
:awestruct-layout: base
ifdef::awestruct[]
:toc:
:toc-placement: preamble
endif::awestruct[]
ifndef::awestruct[]
:toc: right
:icons: font
:idprefix:
:idseparator: -
:sectanchors:
:source-highlighter: highlightjs
endif::awestruct[]
:experimental:
:mdash: &#8212;
:language: asciidoc
:docbook5-uri:
:stem-uri:
:plantuml-uri:


== Integrations

=== LaTeXMath and AsciiMath (#492)


=== Plantuml (#120)

plantuml is an open source tool for drawing UML diagrams. Add support for this in the style of an AsciiDoc filter.

Example:

[planetuml]
----
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
----
Since asciiart is a prominent feature in the AsciiDoc community, we may want to support a generic style name that delegates to the registered implementation. For instance:

[diagram]
----
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
----
As standards emerge around the syntax for these types of diagrams, any number of implementations may be able to satisfy that block. But this way, the documents would not have to be modified when changing implementation. This is similar to how the source highlighting works.

@mojavelinux Hello Dan,
Perhaps you will be interested by this info.

I love plantuml ( BTW, take care to typo error "planetuml" ), and I found long time ago an AsciiDoc filter for this tool.

Even if author seems not to be active, I've applied few patches, and make it operational with AsciiDoc, and of course AsciiDoc-Bootstrap backend.

Here is a concrete example of an UML class diagram of what we can do with it.

UML source is at my github account : https://github.com/llaville/php-compat-info/blob/master/docs/UML.txt

Enjoy
Laurent


This issue is resolved by the introduction of Asciidoctor Diagram.

https://github.com/asciidoctor/asciidoctor-diagram

== Converters


=== DocBook 5 is now the default DocBook converter (#554)

Asciidoctor took a step forward by making DocBook 5 the default DocBook output.
DocBook 5 has been a stable since 2008.
{docbook5-uri}[Learn more].

=== HTML 5 converter supports XHTML (#494)

This issue has lots of content, go to it

=== Changes external CDNs to HTTPS if possible. #970

Resolved by #993.

== Styles

=== Honor background colors in highlight.js and pygments themes #813

Honor the background colors from highlight.js and pygments themes in syntax highlighted listings.

=== Enable copycss attribute to copy any stylesheet, not just asciidoctor.css #300

I think that we are overloading the purpose of stylesdir and stylesheet when looking for a stylesheet to copy. I think that stylesdir and stylesheet should only be used for creating the link to the stylesheet in the HTML.

For example, if Asciidoctor is invoked with the following attributes:

-a stylesheet=colony.css -a stylesdir=./styles
then the HTML link should be:

<link rel="stylesheet" href="./styles/colony.css">
The target location to copy the stylesheet is "styles/colony.css" in the output directory (i.e., outdir).

The question remains, where is the location of the stylesheet to copy? Here's the proposed implementation.

If copycss is blank (as it is by default), then the stylesheet attribute is resolved as a file relative to the base directory (in the future we could look in other built-in locations as well). If the stylesheet is somewhere else on the filesystem, then that location must be supplied to copycss.

For example:

-a copycss=/etc/asciidoctor-themes/colony.css -a stylesheet=colony.css -a stylesdir=./styles

resolves #300 copy custom stylesheet if linkcss is set

=== Vertical headers in table should render as th element in HTML backend #738

DavidGamba	resolves #738 vertical table headers use th element instead of header class

- Update Asciidoc compatibility file
- Update stylesheet

=== Add missing border styles in default stylesheet #569

== Syntax

=== Do not include tagged lines nested in selected tagged region #1027

Do not include lines that contain the tag directive when selecting lines in a tagged region. By ignoring these lines, it's possible to have fine-grained tagged regions inside larger tagged regions.

For example, if our include file has the following content:

```
tag::snippets[]
tag::snippet-a[]
snippet a
end::snippet-a[]

tag::snippet-b[]
snippet b
end::snippet-b[]
end::snippets[]
```

And we include this file using the following include directive:

```
include::file-with-snippets.adoc[tag=snippets]
```

The following lines should be selected:

```
snippet a

snippet b
```

Notice that none of the lines with the tag directives are selected.

=== Specify leveloffset on the include macro (#530)

This issue has lots of content, go to it

resolves #530 support leveloffset on include directive and relative values

=== Incremental substitutions control (#522)

It's possible to override all the substitutions on a block using the subs attribute. However, doing so requires that that you specify all the substitution you want performed. It would be nice if it were possible to add or remove a substitution from the default list using a shorthand notation.

+attributes - append the attributes substitution to the default list
-attributes - remove the attributes substitution from the default list

For example, here's an example of how you would add the attributes substitution on a block under this proposal:

[source,xml]
[subs="+attributes"]
----
<version>{version}</version>
----
Similarly, here's how you would remove the callouts substitution:

[source,xml]
[subs="-callouts"]
.An illegal XML tag
----
<1>foo</1>
----
This feature should be available where ever the subs attribute is used.

Please note that this change is merely a convenience. It is possible to override the substitutions today. You're just required to specify all the substitutions you want.

I'd like to propose that if the + comes before the name of the sub, then it's added to the beginning of the existing list and if the + comes after the name, it's added to the end of the list. For example:

[source,xml]
[subs="+attributes,quotes+,-callouts"]
The effective subs are: attributes, specialcharacters, quotes

An incremental subs list may contain any explicit substitutions. It's not clear what the user intends if that is the case.



resolves #522 allow substitutions to be incrementally added & removed

=== Allow specialchars as a shorthand for specialcharacters subs value #579

resolves #579 specialchars subs alias, shorthand subs

NOTE: This feature may already be fully documented - double check it

=== Add document attribute to control depth of of section numbering

Add a document attribute that can be used to control the depth of section numbering.

Currently, the logic is hardcoded as to 3 levels:

@numbered = numbered && @level > 0 && @level < 4
This should merely be the default if otherwise unspecified.

I propose the attribute name sectnumlevels to be consistent with toclevels to control toc depth.

Example:

:sectnumlevels: 4

resolves #549 added sectnumlevels to control depth of section numbering

=== Add attribute to drop URI scheme in automatic link label #800

=== Swap the function of the backtick and plus characters #718

=== Allow xref to be specified using reftext (e.g., section title) #589

=== nofooter attribute #826

done

////
=== Remove leading and trailing blank lines in verbatim blocks #724

resolves #724 drop leading & trailing blank lines in verbatim & raw content
////

== AST

=== Add Enumerable (or similar) methods to AbstractBlock #862

(AST)

=== Make Asciidoctor compatible with Opal #679

=== Windows/JRuby: include, specifying full path with drive letter or UNC

resolves #806 recognized Windows UNC path as absolute and preserve it
I was not thinking of the Windows UNC paths when I developed the path resolution logic in Asciidoctor. Turns out, the change I needed to make was quite small. I was assuming all Windows paths would begin with a drive letter. I now see that a double slash is a legal start path for a network resource.

The shortcoming is not with Ruby, but with the path logic that I had in Asciidoctor. Ruby is as good at handling paths cross platform as Java. It takes a similar approach of internally converting backslashes to forward slashes, which also makes Java interop very good.

The reason there is special logic for path handling in Asciidoctor is because of the rigid security requirements GitHub (and other users) have for Asciidoctor. We must chop up every path and be absolutely, positively sure that we are not allowing access to ancestor directories that fall outside of the jail when the jail is used. Given we are enforcing this constraint, we also try to calculate the path in the most intelligent way. What Ruby lacks in this case is a proper standard library to resolve paths in a jail / chroot situation.

You should find that the fix I implemented allows the path resolution to behave as expected on Windows. If you encounter other problematic situations, don't hesitate to report them.

=== BOM in file confuses parser

resolves #824 handle BOM when normalizing source …
* Ruby >= 1.9 - use BOM to set encoding, then encode to UTF-8
* Ruby 1.8 - drop the UTF-8 BOM, ignore all others

////
== Don't use preamble if document has no sections #533

If a document has a title but no sections, the content of the document should not be wrapped in a preamble. This is common in short articles, blog posts, etc.

resolves #533 unwrap preamble if standalone
////
