= AsciiDoc Syntax Quick Reference
Dan Allen; Sarah White
v1.0.4, 2014-08-08
:page-layout: base
:page-javascripts: [view-result]
:description: This guide is a quick reference for the common AsciiDoc document and text formatting markup.
:keywords: AsciiDoc, Asciidoctor, syntax, reference, cheatsheet
:compat-mode!:
:imagesdir: ../images
:includedir: _includes
:toc:
:toc-placement!:
:experimental:
:table-caption!:
:example-caption!:
:figure-caption!:
ifndef::env-site[]
:idprefix:
:idseparator: -
endif::[]
:linkattrs:
// URLs
:docs: http://asciidoctor.org/docs
:user: {docs}/user-manual
:uri-config: https://github.com/asciidoctor/asciidoctor/blob/master/compat/asciidoc.conf
:uri-fontawesome: http://fortawesome.github.io/Font-Awesome/
:uri-icon-in: {user}/#inline-icons
:uri-icon-attrs: {user}/#size-rotate-and-flip
:uri-video: {user}/#video
:uri-checklist: {user}/#checklist
:uri-marker: {user}/#custom-markers
:uri-list-num: {user}/#numbering-styles
:uri-imagesdir: {user}/#set-the-images-directory
:uri-image-attrs: {user}/#put-images-in-their-place
:uri-toc: {user}/#user-toc
:uri-para: {user}/#paragraph
:uri-literal: {user}/#literal-text-and-blocks
:uri-admon: {user}/#admonition
:uri-bold: {user}/#bold-and-italic
:uri-quote: {user}/#curved
:uri-sub: {user}/#subscript-and-superscript
:uri-mono: {user}/#mono
:uri-css: {user}/#custom-styling-with-attributes
:uri-pass: {user}/#pass-mac
:uri-mailinglist: http://discuss.asciidoctor.org
:uri-char-xml: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
:uri-data-uri: https://developer.mozilla.org/en-US/docs/data_URIs

////
Syntax to cover:
- preface
- index terms
- built-in attributes (such as {author}, {revision}, etc)
- start=n for ordered lists
- horizontal labeled list
- anchor for any block element
- block metadata (missing example of normal attributes)
- command line reference? perhaps another doc? yes

PDF TODO:
- add license on title page (legalnotice tag)
- table cell bg
- show example of section levels
- syntax highlight ruby code (requires switch to https://code.google.com/p/java-syntax-highlighter)
- style sidebar block
////

ifdef::basebackend-docbook[]
[preface]
== About
endif::basebackend-docbook[]

AsciiDoc is a lightweight markup language for authoring notes, articles, documentation, books, web pages, slide decks and man pages in plain text.
{description}

[NOTE]
====
These examples focus on the output generated by the HTML backend.
AsciiDoc produces complementary output when generating PDF, EPUB, and DocBook.

Most features labeled _Asciidoctor only_ can be made available to the legacy AsciiDoc Python processor by using {uri-config}[this AsciiDoc configuration file] provided by the Asciidoctor project.
====

toc::[]

== Paragraphs

.Normal
----
include::{includedir}/ex-text.adoc[tags=b-para]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=b-para]
====

.Line breaks
----
include::{includedir}/ex-text.adoc[tags=hb-all]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=hb-all]
====

.Literal
----
include::{includedir}/ex-literal.adoc[tags=b-imp]
----

[.result]
====
include::{includedir}/ex-literal.adoc[tags=b-imp]
====

.Admonition
----
include::{includedir}/ex-admon.adoc[tags=b-para]
----

[.result]
====
include::{includedir}/ex-admon.adoc[tags=b-para]
====

NOTE: You can also create <<admon-bl,admonition blocks>>.

.Lead paragraph
----
include::{includedir}/ex-text.adoc[tags=b-lead]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=b-lead]
====

NOTE: The default Asciidoctor stylesheet automatically styles the first paragraph of the preamble as a lead paragraph.

.More Paragraph, Admonition and Literal Block Examples
****
See these sections in the Asciidoctor User Manual for more information and examples.

* {uri-para}[Paragraphs]
* {uri-literal}[Literal Text and Blocks]
* {uri-admon}[Admonitions]
****

== Formatted Text

.Bold, Italic, and Monospace
----
include::{includedir}/ex-text.adoc[tags=b-bold-italic-mono]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=b-bold-italic-mono]
====

.Custom Styling
----
include::{includedir}/ex-text.adoc[tags=css-all]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=css-all]
====

.Superscript and Subscript
----
include::{includedir}/ex-text.adoc[tags=b-sub-sup]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=b-sub-sup]
====

.Curved Quotation Marks and Apostrophes
----
include::{includedir}/ex-text.adoc[tags=b-c-quote]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=b-c-quote]
====

.More Text Formatting Examples
****
See these sections in the Asciidoctor User Manual for more information and examples.

* {uri-bold}[Bold and Italic Formatting]
* {uri-quote}[Quotation Marks and Apostrophes]
* {uri-sub}[Subscript and Superscript]
* {uri-mono}[Monospace Formatting]
* {uri-css}[Custom Styling with Attributes]
* {uri-pass}[Passthrough Macros]
****

== Document Header

IMPORTANT: A header is optional.

CAUTION: The header may not contain blank lines and must be offset from the content by at least one blank line.

.Title only
----
include::{includedir}/ex-header-title.adoc[tags=b-base]
----

.Title and author line
----
include::{includedir}/ex-author.adoc[tags=b-base]
----

TIP: Asciidoctor allows multiple authors in the author line.
Use the semi-colon character to separate each author.

.Title, author line and revision line
----
include::{includedir}/ex-rev.adoc[tags=b-base]
----

IMPORTANT: You cannot have a revision line without an author line.

.Document header with attributes
----
include::{includedir}/ex-header-attr.adoc[tags=b-base]
----

[[section-titles]]
== Section Titles (Headings)

.Article doctype
----
include::{includedir}/ex-section.adoc[tags=base]
----

[.result]
====
include::{includedir}/ex-section.adoc[tags=b-base]
====

WARNING: When using the article doctype (the default), you can only have one level-0 section title (i.e., the document title) and it must be in the document header.

NOTE: The number of equal signs matches the heading level in the HTML output.
For example, _Section Level 1_ becomes an `<h2>` heading.

.Book doctype
----
include::{includedir}/ex-section.adoc[tags=book]
----

[.result]
====
include::{includedir}/ex-section.adoc[tags=b-book]
====

////
IMPORTANT: There are two other ways to define a section title.
_Their omission is intentional_.
They both require more markup and are therefore unnecessary.
The http://en.wikipedia.org/wiki/Setext[setext] title syntax (underlined text) is especially wasteful, hard to remember, hard to maintain and error prone.
The reader never sees the extra markup, so why type it?
*Be frugal!*
////

.Explicit id
----
[[primitives-nulls]]
== Primitive types and null values
----

.Section anchors and links (Asciidoctor only)

`sectanchors`::
When this document attribute is set, a section icon anchor appears in front of the section title.

`sectlinks`::
When this document attribute is set, the section titles become self-links.
This enables a reader to bookmark the section.

NOTE: Section title anchors depend on the default Asciidoctor stylesheet to render properly.

== Include Files

.Document parts
----
include::{includedir}/ex-include.adoc[tags=base]
----

CAUTION: Asciidoctor does not insert blank lines between adjacent include statements to keep the content separated.
Be sure to add a blank line in the source document to avoid unexpected results, such as a section title being swallowed.

.Include content from a URI
----
include::{includedir}/ex-include.adoc[tags=uri]
----

NOTE: Including content from a URI is potentially dangerous, so it's disabled if the safe mode is SECURE or greater.
Assuming the safe mode is less than SECURE, you must also set the `allow-uri-read` attribute to permit Asciidoctor to read content from a URI.

== Horizontal Rules and Page Breaks

.Horizontal rule
----
include::{includedir}/ex-hr.adoc[tags=base]
----

[.result]
====
include::{includedir}/ex-hr.adoc[tags=base]
====

.Page break
----
<<<
----

== Lists

.Unordered, basic
----
include::{includedir}/ex-u-list.adoc[tags=base]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tags=base]
====

NOTE: Blank lines are required before and after a list.

TIP: You can force two lists apart with a line comment, as the previous example demonstrates.
The text in the comment, (`+^+`), is optional, but serves as a hint to other authors that this line serves as an "`end of list`" marker.

.Unordered, max nesting
----
include::{includedir}/ex-u-list.adoc[tags=max]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tags=max]
====

TIP: The unordered list marker can be changed using {uri-marker}[block styles].

.Checklist
----
include::{includedir}/ex-u-list.adoc[tags=check]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tags=check]
====

TIP: Checklists can use {uri-checklist}[font-based icons and be interactive].

.Ordered, basic
----
include::{includedir}/ex-o-list.adoc[tags=b-base]
----

[.result]
====
include::{includedir}/ex-o-list.adoc[tags=b-base]
====

.Ordered, nested
----
include::{includedir}/ex-o-list.adoc[tags=nest]
----

[.result]
====
include::{includedir}/ex-o-list.adoc[tags=nest]
====

.Ordered, max nesting
----
include::{includedir}/ex-o-list.adoc[tags=max]
----

[.result]
====
include::{includedir}/ex-o-list.adoc[tags=max]
====

TIP: For ordered lists, Asciidoctor supports {uri-list-num}[numeration styles] such as `lowergreek` and `decimal-leading-zero`.

.Labeled, single-line
----
include::{includedir}/ex-l-list.adoc[tags=b-base]
----

[.result]
====
include::{includedir}/ex-l-list.adoc[tags=b-base]
====

.Labeled, multi-line
----
include::{includedir}/ex-l-list.adoc[tags=b-base-multi]
----

[.result]
====
include::{includedir}/ex-l-list.adoc[tags=b-base-multi]
====

.Q&A
----
include::{includedir}/ex-l-list.adoc[tags=qa]
----

[.result]
====
include::{includedir}/ex-l-list.adoc[tags=qa]
====

.Mixed
----
include::{includedir}/ex-l-list.adoc[tags=3-mix]
----

[.result]
====
include::{includedir}/ex-l-list.adoc[tags=3-mix]
====

TIP: Lists can be indented.
Leading whitespace is not significant.

.Complex content in outline lists
----
include::{includedir}/ex-u-list.adoc[tags=b-complex]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tags=b-complex]
====

== Links

.External
----
include::{includedir}/ex-url.adoc[tags=b-base]
----

[.result]
====
include::{includedir}/ex-url.adoc[tags=b-base]
====

.With spaces and special characters
----
include::{includedir}/ex-url.adoc[tags=b-spaces]
----

[.result]
====
include::{includedir}/ex-url.adoc[tags=b-spaces]
====

.Windows path
----
include::{includedir}/ex-url.adoc[tags=b-windows]
----

[.result]
====
include::{includedir}/ex-url.adoc[tags=b-windows]
====

.Relative
----
link:index.html[Docs]
----

[.result]
====
link:index.html[Docs]
====

.Email and IRC
----
include::{includedir}/ex-url.adoc[tags=b-scheme]
----

[.result]
====
include::{includedir}/ex-url.adoc[tags=b-scheme]
====

.Link with attributes (Asciidoctor only)
----
include::{includedir}/ex-url.adoc[tags=b-linkattrs]
----

[.result]
====
include::{includedir}/ex-url.adoc[tags=b-linkattrs]
====

NOTE: Links with attributes (including the subject and body segments on mailto links) are a feature unique to Asciidoctor.
To enable them, you must set the `linkattrs` attribute on the document.
When they are enabled, you must quote the link text if it contains a comma.

.Inline anchors
----
include::{includedir}/ex-xref.adoc[tags=anchor]
----

[.result]
====
include::{includedir}/ex-xref.adoc[tags=anchor]
====

.Internal cross references
----
include::{includedir}/ex-xref.adoc[tags=b-base]
----

[.result]
====
include::{includedir}/ex-xref.adoc[tags=b-base]
====

.Inter-document cross references (Asciidoctor only)
----
include::{includedir}/ex-xref.adoc[tags=b-inter]
----

== Images

.Block
----
include::{includedir}/ex-image.adoc[tags=base]

include::{includedir}/ex-image.adoc[tags=alt]

include::{includedir}/ex-image.adoc[tags=attr]

include::{includedir}/ex-image.adoc[tags=ab-url]
----

[.result]
====
include::{includedir}/ex-image.adoc[tags=base]

include::{includedir}/ex-image.adoc[tags=alt]

include::{includedir}/ex-image.adoc[tags=attr]

include::{includedir}/ex-image.adoc[tags=ab-url]
====

IMPORTANT: Images are resolved relative to the value of the {uri-imagesdir}[imagesdir document attribute], which defaults to an empty value.
The `imagesdir` attribute can be an absolute path, relative path or base URL.
If the image target is a URL or absolute path, the imagesdir prefix is _not_ added.

TIP: You should use the `imagesdir` attribute to avoid hard coding the shared path to your images in every image macro.

.Image macro using positioning role
----
include::{includedir}/ex-image.adoc[tags=in-role]
----

[.result]
====
include::{includedir}/ex-image.adoc[tags=in-role]
====

TIP: There are a variety of attributes available to {uri-image-attrs}[position and frame images].

.Inline
----
include::{includedir}/ex-image.adoc[tags=in]
----

[.result]
====
include::{includedir}/ex-image.adoc[tags=in]
====

.Embedded
----
include::{includedir}/ex-image.adoc[tags=data]
----

NOTE: When the `data-uri` attribute is set, all images in the document--including admonition icons--are embedded into the document as {uri-data-uri}[data URIs].

TIP: Instead of declaring the `data-uri` attribute in the document, you can pass it as a command-line argument using `-a data-uri`.

== Videos

.Block
----
include::{includedir}/ex-video.adoc[tags=base]

include::{includedir}/ex-video.adoc[tags=attr]
----

.Embedded Youtube video
----
include::{includedir}/ex-video.adoc[tags=you]
----

.Embedded Vimeo video
----
include::{includedir}/ex-video.adoc[tags=vim]
----

TIP: You can control the video settings using {uri-video}[additional attributes and options] on the macro.

== Source Code

.Inline
----
include::{includedir}/ex-text.adoc[tags=b-mono-code]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=b-mono-code]
====

.Literal line
----
include::{includedir}/ex-literal.adoc[tags=b-imp-code]
----

[.result]
====
include::{includedir}/ex-literal.adoc[tags=b-imp-code]
====

.Literal block
----
include::{includedir}/ex-literal.adoc[tags=b-block]
----

[.result]
====
include::{includedir}/ex-literal.adoc[tags=b-block]
====

[listing]
.Listing block with title, no syntax highlighting
....
include::{includedir}/ex-listing.adoc[tags=b-base]
....

[.result]
====
include::{includedir}/ex-listing.adoc[tags=b-base]
====

[listing]
.Code block with title and syntax highlighting
....
include::{includedir}/ex-src.adoc[tags=src-base]
....

[.result]
====
include::{includedir}/ex-src.adoc[tags=src-base]
====

[listing, subs="specialcharacters"]
.Code block with callouts
....
include::{includedir}/ex-callout.adoc[tags=b-src]
....

[.result]
====
include::{includedir}/ex-callout.adoc[tags=b-src]
====

[listing,subs="specialcharacters"]
.Code block with non-selectable callouts
....
include::{includedir}/ex-callout.adoc[tags=b-nonselect]
....

[.result]
====
include::{includedir}/ex-callout.adoc[tags=b-nonselect]
====

[listing,subs="specialcharacters"]
.XML code block with a non-selectable callout
....
include::{includedir}/ex-callout.adoc[tags=source-xml]
....

[.result]
====
include::{includedir}/ex-callout.adoc[tags=source-xml]
====

[listing]
.Code block sourced from file
....
include::{includedir}/ex-src.adoc[tags=src-inc]
....

[listing]
.Code block sourced from file relative to source directory
....
include::{includedir}/ex-src.adoc[tags=rel]
....

[listing]
.Strip leading indentation from source
....
include::{includedir}/ex-src.adoc[tags=ind]
....

[NOTE]
====
* When `indent` is 0, the leading block indent is stripped (tabs are replaced with 4 spaces).
* When `indent` is > 0, the leading block indent is first stripped (tabs are replaced with 4 spaces), then a block is indented by the number of columns equal to this value.
====

.Code block without delimiters (no blank lines)
----
include::{includedir}/ex-src.adoc[tags=src-para]
----

[.result]
====
include::{includedir}/ex-src.adoc[tags=src-para]
====

[IMPORTANT]
.Enabling the syntax highlighter
====
Syntax highlighting is enabled by setting the `source-highlighter` attribute in the document header or passed as an argument.

 :source-highlighter: pygments

The valid options are `coderay`, `highlightjs`, `prettify`, and `pygments`.
====

== More Delimited Blocks

.Sidebar
----
include::{includedir}/ex-sidebar.adoc[tags=base]
----

[.result]
====
include::{includedir}/ex-sidebar.adoc[tags=base]
====

NOTE: Any block can have a title, positioned above the block.
A block title is a line of text that starts with a dot.
The dot cannot be followed by a space.

.Example
----
include::{includedir}/ex-example.adoc[tags=base]
----

[example.result]
--
include::{includedir}/ex-example.adoc[tags=base]
--

[[admon-bl]]
.Admonition
----
include::{includedir}/ex-admon.adoc[tags=b-bl]
----

[.result]
=====
include::{includedir}/ex-admon.adoc[tags=b-bl]
=====

[TIP]
.Admonition and callout icons
====
Asciidoctor can "`draw`" icons using {uri-fontawesome}[Font Awesome^] and CSS.

To use this feature, set the value of the `icons` document attribute to `font`.
Asciidoctor will then emit HTML markup that selects an appropriate font character from the Font Awesome font for each admonition block.

Icons can also be used {uri-icon-in}[inline] and {uri-icon-attrs}[styled].
====

.Blockquote
----
include::{includedir}/ex-quote.adoc[tags=bl]

include::{includedir}/ex-quote.adoc[tags=para]

include::{includedir}/ex-quote.adoc[tags=no-cite]

include::{includedir}/ex-quote.adoc[tags=link-text]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=bl]

include::{includedir}/ex-quote.adoc[tags=para]

include::{includedir}/ex-quote.adoc[tags=no-cite]
====

.Abbreviated blockquote (Asciidoctor only)
----
include::{includedir}/ex-quote.adoc[tags=abbr]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=abbr]
====

.Air quotes: the best thing since fenced code blocks (Asciidoctor only)
----
include::{includedir}/ex-quote.adoc[tags=air]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=air]
====

.Passthrough
----
include::{includedir}/ex-pass.adoc[tags=b-bl]
----

[.result]
====
include::{includedir}/ex-pass.adoc[tags=b-bl]
====

.Open
----
include::{includedir}/ex-open.adoc[tags=base]

include::{includedir}/ex-open.adoc[tags=src]
----

[.result]
====
include::{includedir}/ex-open.adoc[tags=base]

include::{includedir}/ex-open.adoc[tags=src]
====

[listing]
.Custom substitutions
....
include::{includedir}/ex-listing.adoc[tags=subs]
....

[.result]
====
// the attribute value is hard-coded in this result since the example depends
// on a hypothetical document attribute
include::{includedir}/ex-listing.adoc[tags=subs-out]
====

== Block Id, Role and Options

.Traditional markup method for assigning block id and role
----
[[goals]]
[role="incremental"]
* Goal 1
* Goal 2
----

.Shorthand markup method for assigning block id and role (Asciidoctor only)
----
[#goals.incremental]
* Goal 1
* Goal 2
----

[TIP]
====
* To specify multiple roles using the shorthand syntax, separate them by dots.
* The order of `id` and `role` values in the shorthand syntax does not matter.
====

.Traditional markup method for assigning quoted text anchor (id) and role
----
[[free_the_world]][big goal]_free the world_
----

.Shorthand markup method for assigning quoted text anchor (id) and role (Asciidoctor only)
----
[#free_the_world.big.goal]_free the world_
----

.Role assigned to text enclosed in backticks
----
[rolename]`monospace text`
----

.Traditional markup method for assigning block options
----
[options="header,footer,autowidth"]
|===
|Cell A |Cell B
|===
----

.Shorthand markup method for assigning block options (Asciidoctor only)
----
[%header%footer%autowidth]
|===
|Cell A |Cell B
|===
----

== Comments

.Line
----
include::{includedir}/ex-comment.adoc[tags=line]
----

TIP: Single-line comments can be used to divide elements, such as two adjacent lists.

.Block
----
include::{includedir}/ex-comment.adoc[tags=bl]
----

== Tables

.Table with a title, three columns, a header, and two rows of content
----
include::{includedir}/ex-table.adoc[tags=b-base-h-co]
----
<1> Unless the `cols` attribute is specified, the number of columns is equal to the number of vertical bars on the first non-blank line inside the block delimiters.
<2> When a blank line follows a single line of column titles, the column titles row will be styled as a header row by default.

[.result]
====
include::{includedir}/ex-table.adoc[tags=b-base-h]
====

.Table with two columns, a header, and two rows of content
----
include::{includedir}/ex-table.adoc[tags=b-col-h-co]
----
<1> The `+*+` in the `cols` attribute is the repeat operator. It means repeat the column specification for the remainder of columns. In this case, it means to repeat the default formatting across 4 columns. When the header row is not defined on a single line, you must use the cols attribute to set the number of columns and `options` attributes to make the first row a header.

[.result]
====
include::{includedir}/ex-table.adoc[tags=b-col-h]
====

.Table with three columns, a header, and two rows of content
----
include::{includedir}/ex-table.adoc[tags=b-col-indv-co]
----
<1> In this example, the `cols` attribute has two functions. It specifies that this table has three columns, and it sets their relative widths.

[.result]
====
include::{includedir}/ex-table.adoc[tags=b-col-indv]
====

.Table with column containing AsciiDoc content
----
include::{includedir}/ex-table.adoc[tags=b-col-a]
----

[.result]
====
include::{includedir}/ex-table.adoc[tags=b-col-a]
====

.Table from CSV data
----
include::{includedir}/ex-table-data.adoc[tags=csv]
----

[.result]
====
include::{includedir}/ex-table-data.adoc[tags=csv]
====

.Table from CSV data using shorthand (Asciidoctor only)
----
include::{includedir}/ex-table-data.adoc[tags=s-csv]
----

[.result]
====
include::{includedir}/ex-table-data.adoc[tags=s-csv]
====

.Table from CSV data in file
----
include::{includedir}/ex-table-data.adoc[tags=i-csv]
----

.Table from DSV data using shorthand (Asciidoctor only)
----
include::{includedir}/ex-table-data.adoc[tags=s-dsv]
----

[.result]
====
include::{includedir}/ex-table-data.adoc[tags=s-dsv]
====

.Table with formatted, aligned and merged cells
----
include::{includedir}/ex-table-cell.adoc[tags=b-spec]
----

[.result]
====
include::{includedir}/ex-table-cell.adoc[tags=b-spec]
====

== UI Macros

IMPORTANT: You *must* set the `experimental` attribute in the document header to enable these macros.

.Keyboard shortcuts (inline kbd macro)
----
include::{includedir}/ex-ui.adoc[tags=key]
----

[.result]
====
include::{includedir}/ex-ui.adoc[tags=key]
====

.Menu selections (inline +menu+ macro)
----
include::{includedir}/ex-ui.adoc[tags=menu]
----

[.result]
====
include::{includedir}/ex-ui.adoc[tags=menu]
====

.Buttons (inline +btn+ macro)
----
include::{includedir}/ex-ui.adoc[tags=button]
----

[.result]
====
include::{includedir}/ex-ui.adoc[tags=button]
====

== Attributes and Substitutions

.Attribute declaration and usage
----
include::{includedir}/ex-header-attr.adoc[tags=b-attr]
----

[.result]
====
// I have to use a nested doc hack here, otherwise the attributes won't resolve
[.unstyled]
|===
a|
include::{includedir}/ex-header-attr.adoc[tags=b-attr]
|===
====

.Attribute assignment precedence (highest to lowest)
- Attribute passed to the API or CLI that does not end in `@`
- Attribute defined in the document
- Attribute passed to the API or CLI that ends in `@`
- Intrinsic attribute value (default values)

TIP: To make an attribute value that is passed to the API or CLI have a lower precedence than an assignment in the document, add an `@` symbol to the end of the attribute value.

// Table of predefined attributes for character replacements
include::{includedir}/attr-charref.adoc[tags=table]

// Table of environment attributes
include::{includedir}/attr-env.adoc[tags=table]

.Named substitutions
include::{includedir}/subs-apply.adoc[tags=group]

.Counter attributes
----
include::{includedir}/ex-counter.adoc[tags=base]
----

[.result]
====
include::{includedir}/ex-counter.adoc[tags=base]
====

==  Text Replacement

// Table of text replacements performed during replacements substitution
include::{includedir}/subs-symbol-repl.adoc[]

TIP: Any named, numeric or hex {uri-char-xml}[XML entity reference] is supported.

== Escaping Text

.Backslash
----
include::{includedir}/ex-subs.adoc[tags=b-slash]
----

[.result]
====
include::{includedir}/ex-subs.adoc[tags=b-slash]
====

////
.Double dollar
----
include::{includedir}/ex-pass.adoc[tags=b-dollar]
----

[.result]
====
include::{includedir}/ex-pass.adoc[tags=b-dollar]
====
////

.Triple plus and inline passthrough macro
----
include::{includedir}/ex-pass.adoc[tags=b-3p-macro]
----

[.result]
====
include::{includedir}/ex-pass.adoc[tags=b-3p-macro]
====

////
.Backticks
----
include::{includedir}/ex-pass.adoc[tags=b-tick]
----

[.result]
====
include::{includedir}/ex-pass.adoc[tags=b-tick]
====
////

== Table of Contents (ToC)

.Document with ToC
----
include::{includedir}/ex-toc.adoc[tags=base]
----

.Document with ToC positioned on the right
----
include::{includedir}/ex-toc.adoc[tags=pos]
----

TIP: The ToC {uri-toc}["title, levels, and positioning"] can be customized.

== Bibliography

.References
----
include::{includedir}/ex-biblio.adoc[tags=base]
----

[.result]
====
include::{includedir}/ex-biblio.adoc[tags=base]
====

[[section-footnotes]]
== Footnotes

.Normal and reusable footnotes
----
include::{includedir}/ex-footnote.adoc[tags=base]
----

[.result]
====
[.unstyled]
|===
a|
include::{includedir}/ex-footnote.adoc[tags=base]
|===
====

[#markdown-compatibility]
== Markdown Compatibility

.Markdown-style headings
----
include::{includedir}/ex-section.adoc[tags=md]
----

[.result]
====
include::{includedir}/ex-section.adoc[tags=b-md]
====

.Fenced code block with syntax highlighting
----
include::{includedir}/ex-src.adoc[tags=fence]
----

[.result]
====
include::{includedir}/ex-src.adoc[tags=fence]
====

.Markdown-style blockquote
----
include::{includedir}/ex-quote.adoc[tags=md]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=md]
====

.Markdown-style blockquote with block content
----
include::{includedir}/ex-quote.adoc[tags=md-alt]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=md-alt]
====

.Markdown-style horizontal rules
----
include::{includedir}/ex-hr.adoc[tags=md]
----

[.result]
====
include::{includedir}/ex-hr.adoc[tags=md]
====

== User Manual and Help

To learn more about Asciidoctor and its capabilities, check out the other {docs}[Asciidoctor guides] and its {user}[User Manual].
Also, don't forget to join the {uri-mailinglist}[Asciidoctor mailing list], where you can ask questions and leave comments.
