= Installing and Using the Asciidoctor Maven Plugin
Jason Porter; Sarah White
:page-layout: docs
ifndef::env-site[]
:toc: left
:icons: font
:idprefix:
:idseparator: -
:sectanchors:
:source-highlighter: highlightjs
endif::[]
:linkattrs:
:nocaption: caption=""
//Refs
:home-ref: link:/
:repo-ref: http://github.com/asciidoctor/asciidoctor-maven-plugin
:issues-ref: http://github.com/asciidoctor/asciidoctor-maven-plugin/issues
:discuss-ref: http://discuss.asciidoctor.org
:asciidoc-ref: http://asciidoc.org
:maven-ref: http://maven.apache.org
:plugin-version: 1.5.3
:artifact-query-ref: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.asciidoctor%22%20AND%20a%3A%22asciidoctor-maven-plugin%22
:artifact-detail-1-5-3-ref: http://search.maven.org/#artifactdetails%7Corg.asciidoctor%7Casciidoctor-maven-plugin%7C1.5.3%7Cmaven-plugin
:artifact-file-1-5-3-ref: http://search.maven.org/remotecontent?filepath=org/asciidoctor/asciidoctor-maven-plugin/1.5.3/asciidoctor-maven-plugin-1.5.3
:asciidoctorj-repo: http://github.com/asciidoctor/asciidoctorj
:asciidoctorj-ref: link:/docs/asciidoctorj
:hack-maven-ref: link:/docs/hack-asciidoctor-maven-plugin

The {repo-ref}[Asciidoctor Maven plugin] is the official means of using {home-ref}[Asciidoctor] to render your {asciidoc-ref}[AsciiDoc] documentation using {maven-ref}[Apache Maven].

== Distribution

The Asciidoctor Maven plugin is published to the Maven Central repository.
The artifact information is summarized in the table below.

.Plugin artifact information
[cols="1,2,^1,2", {nocaption}]
|===
|Group Id |Artifact Id |Version |Download

|org.asciidoctor
|{artifact-query-ref}[asciidoctor-maven-plugin]
|{artifact-detail-1-5-3-ref}[1.5.3]
|{artifact-file-1-5-3-ref}.pom[pom] {artifact-file-1-5-3-ref}.jar[jar]
|===

This plugin depends on the {asciidoctorj-repo}[AsciidoctorJ] library.
If you want to learn more about the library, refer to the {asciidoctorj-ref}[AsciidoctorJ manual].

== Plugin or Maven Site Integration?

The conversion can happen in 2 flavors:

. as a Maven plugin: AsciiDoc files are converted at full Asciidoctor power independently from Maven site,

. as a Maven site integration: AsciiDoc files are integrated with Maven reports, which comes with
a few limitations (see below for details).

== Maven Plugin

=== Setup

As this is a typical Maven plugin, simply declare the plugin in the `<plugins>` section of your POM file:

[source,xml,subs=attributes+]
.Plugin declaration in pom.xml
----
<plugins>
    <plugin>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctor-maven-plugin</artifactId>
        <version>{plugin-version}</version> <!--1-->
        ...
    </plugin>
</plugins>
----
<1> As this plugin tracks the version of Asciidoctor, you can use whichever version of Asciidoctor you prefer.

[source,xml]
.Execution setup
----
<plugin>
    ...
    <executions>
        <execution>
            <id>output-html</id>              <!--1-->
            <phase>generate-resources</phase> <!--2-->
            <goals>
                <goal>process-asciidoc</goal> <!--3-->
            </goals>
        </execution>
    </executions>
</plugin>
----
<1> This is simply an unique id for the execution
<2> The asciidoctor-maven-plugin does not run in any phase by default, so one must be specified
<3> The (only for the moment) Asciidoctor Maven plugin goal

=== Configuration options

There are several configuration options that the Asciidoctor Maven plugin accepts:

sourceDirectory:: defaults to [path]_$\{basedir}/src/main/asciidoc_
sourceDocumentName:: an override to process a single source file; defaults to all files in [path]_$\{sourceDirectory}_
outputDirectory:: defaults to [path]_${project.build.directory}/generated-docs_
imagesDir:: defaults to `images`, which will be relative to the directory containing the source files
backend:: defaults to `docbook`
doctype:: defaults to `article`
eruby:: defaults to erb, the version used in jruby
headerFooter:: defaults to `true`
compact:: defaults to `false`
templateDir:: disabled by default
templateEngine:: disabled by default
sourceHighlighter:: enables and sets the source highlighter; currently `coderay` and `highlightjs` are supported
templateDir:: defaults to `null`
attributes:: a `Map<String,String>` of attributes to pass to Asciidoctor, defaults to `null`
extensions:: a `List<String>` of non-standard extensions to render; currently `.ad`, `.adoc`, and `.asciidoc` will be rendered by default

=== Built-in attributes

There are various attributes Asciidoctor recognizes.
Below is a list of them and what they do::

title:: An override for the title of the document.

NOTE: This attribute, for backwards compatibility, can still be used in the top level configuration options.

Many other attributes are possible and more will be added in the future to take advantage of other options and attributes of Asciidoctor.
Any setting in the `attributes` section that conflicts with an explicitly named attribute configuration will be overidden by the explicitly named attribute configuration.
These settings can be changed in the `<configuration>` section of the plugin section.

[source,xml]
.Plugin configuration options
----
<plugin>
  ...
    </executions>
    <configuration>
      <sourceDirectory>src/main/doc</sourceDirectory>
      <outputDirectory>target/docs</outputDirectory>
      <backend>html</backend>
      <doctype>book</doctype>
      <attributes>
        <stylesheet>my-theme.css</stylesheet>
      </attributes>
    </configuration>
    ...
</plugin>
...
----

=== Multiple outputs for the same file

Maven has the ability to execute a Mojo multiple times.
Instead of reinventing the wheel inside the Mojo, we'll push this off to Maven to handle the multiple executions.
An example of this setup is below:

[source,xml]
.Multiple configuration extract
----
<plugin>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-plugin</artifactId>
    <version>1.5.3</version>
    <executions>
        <execution>
            <id>output-html</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <sourceHighlighter>coderay</sourceHighlighter>
                <backend>html</backend>
                <attributes>
                    <toc/>
                    <linkcss>false</linkcss>
                </attributes>
            </configuration>
        </execution>
        <execution>
            <id>output-docbook</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <backend>docbook</backend>
                <doctype>book</doctype>
            </configuration>
        </execution>
    </executions>
    <configuration>
        <sourceDirectory>src/main/asciidoc</sourceDirectory>
        <headerFooter>true</headerFooter>
        <imagesDir>../resources/images</imagesDir> <!--1-->
    </configuration>
</plugin>
----
<1> `imagesDir` should be relative to the source directory.
It defaults to `images` but in this example the images used in the docs are also used elsewhere in the project.

Any configuration specified outside the executions section is inherited by each execution.
This allows an easier way of defining common configuration options.

== Maven Site Integration

=== Setup

To author your Maven-generated site in AsciiDoc, you must first add a dependency on the Asciidoctor plugin to your maven-site-plugin declaration (which more precisely adds a Doxia Parser Module).

IMPORTANT: Maven v3.2.1 or above required, and since asciidoctor-maven-plugin v1.5.6 only maven-site-plugin v3.4 or above is supported.

[source,xml,subs=attributes+]
.Maven site integration
-----
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-site-plugin</artifactId>
            <version>3.4</version>
            <dependencies>
                <dependency><!-- add Asciidoctor Doxia Parser Module -->
                    <groupId>org.asciidoctor</groupId>
                    <artifactId>asciidoctor-maven-plugin</artifactId>
                    <version>{plugin-version}</version>
                </dependency>
            </dependencies>
        </plugin>
    </plugins>
</build>
-----

All of your AsciiDoc-based files should be placed in `src/site/asciidoc` with an extension of `.adoc`.
These files will be rendered into the `target/site` directory.
For example, the file `src/site/asciidoc/usage.adoc` will be rendered into `target/site/usage.html`.

The Asciidoctor base directory (i.e., document root) is configured as `src/site/asciidoc` by default, though this can be overridden.
Also note that AsciiDoc files are converted to embeddable HTML and inserted into the site's page layout.
This disables certain features such as a the sidebar toc.

Make sure you add a `menu` item for each page so you can access it from the site navigation:

[source,xml]
-----
<body>
    ...
    <menu name="User guide">
        <item href="usage.html" name="Usage" />
    </menu>
    ...
</body>
-----

=== Configuration

As of version 1.5.3 of the plugin, you can configure Asciidoctor by specifying configuration properties in the plugin declaration, just like with the main plugin goal.
There is one important difference, however.
All the configuration for Asciidoctor in the site integration must be nested inside an `<asciidoc>` element.
This is necessary since the `<configuration>` element is used to configure more than just the Asciidoctor integration.

Here's an example that shows how to set options, attributes and ignore partial AsciiDoc files (i.e., files that begin with an underscore).

[source,xml]
.Maven site integration with Asciidoctor configuration
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-site-plugin</artifactId>
    <version>3.4</version>
    <configuration>
        <asciidoc>
            <templateDirs>
                <dir>src/site/asciidoc/templates</dir>
            </templateDirs>
            <requires>
                <require>asciidoctor-diagram</require>
            </requires>
            <attributes>
                <source-highlighter>coderay</source-highlighter>
                <coderay-css>style</coderay-css>
            </attributes>
        </asciidoc>
        <moduleExcludes>
            <asciidoc>**/_*.adoc</asciidoc>
        </moduleExcludes>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctor-maven-plugin</artifactId>
            <version>1.5.3</version>
        </dependency>
    </dependencies>
</plugin>
----

IMPORTANT: The Asciidoctor base directory (i.e., document root) is configured as `src/site/asciidoc` by default, though this can be overridden using the `baseDir` configuration option.

You'll notice that excludes have been added for certain AsciiDoc files.
This prevents the site integration from processing partial files (i.e., includes) as individual pages.
You can tune this pattern to your liking.
There's currently no way (that we can tell) to configure this automatically.

We've also activated the built-in template converter by specifying a templates directory (i.e., `templatesDir`).
This feature enables you to provide a custom template for converting any node in the tree (e.g., document, section, listing, etc).
Custom templates can be extremely helpful when trying to customize the appearance of your site.

== Resources

If you're interested in modifying or impoving this plugin, checkout the {hack-maven-ref}[Hacking on the Asciidoctor Maven plugin guide].
To file an issue regarding this plugin, visit the {issues-ref}[plugin's repository].

Also, don't forget to join the {discuss-ref}[Asciidoctor discussion list], where you can ask questions and leave comments.
