= AsciiDoc 语法快速参考
Dan Allen; Sarah White
v1.0.4, 2014-08-08
:page-layout: docs
:page-javascripts: [view-result]
:description: 本指南是常用的 AsciiDoc 文档和文字格式化标记的快速参考。
:keywords: AsciiDoc, Asciidoctor, syntax, reference, cheatsheet
:compat-mode!:
:imagesdir: ../images
:includedir: _includes
:experimental:
:table-caption!:
:example-caption!:
:figure-caption!:
ifndef::env-site[]
:idprefix:
:idseparator: -
:toc: macro
endif::[]
:linkattrs:
:data-uri:
// URLs
:docs: http://asciidoctor.org/docs
:user: {docs}/user-manual
:uri-config: https://github.com/asciidoctor/asciidoctor/blob/master/compat/asciidoc.conf
:uri-fontawesome: http://fortawesome.github.io/Font-Awesome/
:uri-icon-in: {user}/#inline-icons
:uri-icon-attrs: {user}/#size-rotate-and-flip
:uri-video: {user}/#video
:uri-checklist: {user}/#checklist
:uri-marker: {user}/#custom-markers
:uri-list-num: {user}/#numbering-styles
:uri-imagesdir: {user}/#set-the-images-directory
:uri-image-attrs: {user}/#put-images-in-their-place
:uri-toc: {user}/#user-toc
:uri-para: {user}/#paragraph
:uri-literal: {user}/#literal-text-and-blocks
:uri-admon: {user}/#admonition
:uri-bold: {user}/#bold-and-italic
:uri-quote: {user}/#curved
:uri-sub: {user}/#subscript-and-superscript
:uri-mono: {user}/#mono
:uri-css: {user}/#custom-styling-with-attributes
:uri-pass: {user}/#pass-mac
:uri-mailinglist: http://discuss.asciidoctor.org
:uri-char-xml: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
:uri-data-uri: https://developer.mozilla.org/en-US/docs/data_URIs

////
Syntax to cover:
- preface
- index terms
- built-in attributes (such as {author}, {revision}, etc)
- start=n for ordered lists
- horizontal labeled list
- anchor for any block element
- block metadata (missing example of normal attributes)
- command line reference? perhaps another doc? yes

PDF TODO:
- add license on title page (legalnotice tag)
- table cell bg
- show example of section levels
- syntax highlight ruby code (requires switch to https://code.google.com/p/java-syntax-highlighter)
- style sidebar block
////

ifdef::basebackend-docbook[]
[preface]
== About
endif::basebackend-docbook[]

AsciiDoc 是一种轻量级标记语言，它可以让我们以纯文本的形式来书写笔记、文章、文档、书籍、网页、幻灯片和 man 帮助。
{description}

[NOTE]
====
这些例子主要关注生成的 HTML 后端。
AsciiDoc 生成 PDF、EPUB 和 DocBook 时，它们之间是互补的。

很多标注着 _仅 _Asciidoctor 可用_ 的特性通过 Asciidoctor 项目提供的 {uri-config}[AsciiDoc 配置文件] 也可以在传统的 AsciiDoc Python 处理器中使用。
====

toc::[]

[[paragraphs]]
== 段落

.正常
----
include::{includedir}/ex-text.adoc[tags=b-para]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=b-para]
====

.换行
----
include::{includedir}/ex-text.adoc[tags=hb-all]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=hb-all]
====

.文字
----
include::{includedir}/ex-literal.adoc[tags=b-imp]
----

[.result]
====
include::{includedir}/ex-literal.adoc[tags=b-imp]
====

.警告
----
include::{includedir}/ex-admon.adoc[tags=b-para]
----

[.result]
====
include::{includedir}/ex-admon.adoc[tags=b-para]
====

NOTE: 你也可以创建 <<admon-bl,警示块>>.

.概要段落
----
include::{includedir}/ex-text.adoc[tags=b-lead]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=b-lead]
====

NOTE: 默认的 Asciidoctor 样式会自动将序文的第一段作为摘要段落。

.更多段落、警告和文字块示例
****
在 Asciidoctor 用户手册中的这些章节中，有更多的信息以及示例。

* {uri-para}[段落]
* {uri-literal}[文字以及块]
* {uri-admon}[警告]
****

[[formatted-text]]
== 格式化文本

.加粗、斜体和等宽字体
----
include::{includedir}/ex-text.adoc[tags=b-bold-italic-mono]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=b-bold-italic-mono]
====

.自定义样式
----
include::{includedir}/ex-text.adoc[tags=css-all]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=css-all]
====

.上角标 和 脚注
----
include::{includedir}/ex-text.adoc[tags=b-sub-sup]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=b-sub-sup]
====

.引号
----
include::{includedir}/ex-text.adoc[tags=b-c-quote]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=b-c-quote]
====

.更多文本格式化示例
****
在 Asciidoctor 用户手册的这些章节中，更多的信息以及示例。

* {uri-bold}[加粗和斜体]
* {uri-quote}[引号]
* {uri-sub}[上角标和脚注]
* {uri-mono}[等宽字体]
* {uri-css}[通过属性自定义样式]
* {uri-pass}[Pass 宏]
****

[[document-header]]
== 文档标题

IMPORTANT: 标题是可选的。

CAUTION: 标题不能包含空号，并且下面必须紧跟至少一个空行。

.标题
----
include::{includedir}/ex-header-title.adoc[tags=b-base]
----

.标题以及作者行
----
include::{includedir}/ex-author.adoc[tags=b-base]
----

TIP: Asciidoctor 允许在作者行中出现多位作者，使用分号来分割开来。

.标题、作者行以及版本行
----
include::{includedir}/ex-rev.adoc[tags=b-base]
----

IMPORTANT: 你不能只写版本行而不写作者行！

.带属性的文档标题
----
include::{includedir}/ex-header-attr.adoc[tags=b-base]
----

[[section-titles]]
== 章节标题

.文章标题类型
----
include::{includedir}/ex-section.adoc[tags=base]
----

[.result]
====
include::{includedir}/ex-section.adoc[tags=b-base]
====

WARNING: 当使用文章标题类型时，默认只能有一个级别为0的文章标题（也就是文档标题），并且必须在文档头部。

NOTE: 等号的数量与输出的 HTML 标题级别想匹配。
例如，_Section Level 1_ 将会转化为 `<h2>` 标题。

.书籍标题类型
----
include::{includedir}/ex-section.adoc[tags=book]
----

[.result]
====
include::{includedir}/ex-section.adoc[tags=b-book]
====

////
IMPORTANT: There are two other ways to define a section title.
_Their omission is intentional_.
They both require more markup and are therefore unnecessary.
The http://en.wikipedia.org/wiki/Setext[setext] title syntax (underlined text) is especially wasteful, hard to remember, hard to maintain and error prone.
The reader never sees the extra markup, so why type it?
*Be frugal!*
////

.指定 ID
----
[[primitives-nulls]]
== Primitive types and null values
----

.章节锚点以及链接 (仅 Asciidoctor 支持)

`sectanchors`::
当设置该文档属性后，章节的锚点图标就会出现在章节标题前面。

`sectlinks`::
当设置该文档属性后，章节标题就变成自链接。
这使得读者可以书签标记这个章节。

NOTE: 章节标题锚点依赖默认 Asciidoctor 样式的正确渲染。

[[include-files]]
== 包含文件

.文档分块
----
include::{includedir}/ex-include.adoc[tags=base]
----

CAUTION: Asciidoctor does not insert blank lines between adjacent include statements to keep the content separated.
Be sure to add a blank line in the source document to avoid unexpected results, such as a section title being swallowed.

.从一个 URI 中含内容
----
include::{includedir}/ex-include.adoc[tags=uri]
----

NOTE: Including content from a URI is potentially dangerous, so it's disabled if the safe mode is SECURE or greater.
Assuming the safe mode is less than SECURE, you must also set the `allow-uri-read` attribute to permit Asciidoctor to read content from a URI.

[[horizontal-rules-and-page-breaks]]
== 水平线和分页符

.水平线
----
include::{includedir}/ex-hr.adoc[tags=base]
----

[.result]
====
include::{includedir}/ex-hr.adoc[tags=base]
====

.分页
----
<<<
----

[[lists]]
== 列表

.基本无序列表
----
include::{includedir}/ex-u-list.adoc[tags=base]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tags=base]
====

NOTE:列表前后的空行是必须的。

TIP: 你可以通过在列表中间放一行注释来将其分成两个列表，就像上面的演示示例一样。
注释中的文字(例如 `+^+`)是可选的，但是可以个作为给其他作者的一个提示，来说明改行是列表的结束行。

.无序嵌套列表
----
include::{includedir}/ex-u-list.adoc[tags=max]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tags=max]
====

TIP: 可以通过 {uri-marker}[块样式] 来改变无序列表的标识类型。

.清单
----
include::{includedir}/ex-u-list.adoc[tags=check]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tags=check]
====

TIP: 清单可以使用 {uri-checklist}[字体图标，还可互动]。

.基本有序列表
----
include::{includedir}/ex-o-list.adoc[tags=b-base]
----

[.result]
====
include::{includedir}/ex-o-list.adoc[tags=b-base]
====

.有序嵌套列表
----
include::{includedir}/ex-o-list.adoc[tags=nest]
----

[.result]
====
include::{includedir}/ex-o-list.adoc[tags=nest]
====

.有序最大嵌套列表
----
include::{includedir}/ex-o-list.adoc[tags=max]
----

[.result]
====
include::{includedir}/ex-o-list.adoc[tags=max]
====

TIP: 对于有序列表，Asciidoctor 支持不同的 {uri-list-num}[数字样式]，例如 `lowergreek` 和 `decimal-leading-zero`。

.单行标签列表
----
include::{includedir}/ex-l-list.adoc[tags=b-base]
----

[.result]
====
include::{includedir}/ex-l-list.adoc[tags=b-base]
====

.多行标签列表
----
include::{includedir}/ex-l-list.adoc[tags=b-base-multi]
----

[.result]
====
include::{includedir}/ex-l-list.adoc[tags=b-base-multi]
====

.常见问题以及解答
----
include::{includedir}/ex-l-list.adoc[tags=qa]
----

[.result]
====
include::{includedir}/ex-l-list.adoc[tags=qa]
====

.混合样式列表
----
include::{includedir}/ex-l-list.adoc[tags=3-mix]
----

[.result]
====
include::{includedir}/ex-l-list.adoc[tags=3-mix]
====

TIP: 列表可以缩进。
开头空白不需要显示指定。

.复杂内容列表
----
include::{includedir}/ex-u-list.adoc[tags=b-complex]
----

[.result]
====
include::{includedir}/ex-u-list.adoc[tags=b-complex]
====

[[links]]
== 链接

.外部链接
----
include::{includedir}/ex-url.adoc[tags=b-base]
----

[.result]
====
include::{includedir}/ex-url.adoc[tags=b-base]
====

.带空格以及特殊字符
----
include::{includedir}/ex-url.adoc[tags=b-spaces]
----

[.result]
====
include::{includedir}/ex-url.adoc[tags=b-spaces]
====

.Windows 路径
----
include::{includedir}/ex-url.adoc[tags=b-windows]
----

[.result]
====
include::{includedir}/ex-url.adoc[tags=b-windows]
====

.相对路径
----
link:index.html[Docs]
----

[.result]
====
link:index.html[Docs]
====

.电子邮件和 IRC
----
include::{includedir}/ex-url.adoc[tags=b-scheme]
----

[.result]
====
include::{includedir}/ex-url.adoc[tags=b-scheme]
====

.带属性的链接（仅 Asciidoctor 支持）
----
include::{includedir}/ex-url.adoc[tags=b-linkattrs]
----

[.result]
====
include::{includedir}/ex-url.adoc[tags=b-linkattrs]
====

NOTE: 带属性的链接（包含 mailto 链接的主题和正文）是唯有 Asciidoctor 支持的特性。
为了启用这个特性，必须在文档中设置 `linkattrs` 属性。
当启用这个特性时，如果链接内容包含逗号，则必须用引号将链接文本括起来。

.行内锚点
----
include::{includedir}/ex-xref.adoc[tags=anchor]
----

[.result]
====
include::{includedir}/ex-xref.adoc[tags=anchor]
====

.内部交叉引用
----
include::{includedir}/ex-xref.adoc[tags=b-base]
----

[.result]
====
include::{includedir}/ex-xref.adoc[tags=b-base]
====

.文档间的交叉引用（仅 Asciidoctor 支持）
----
include::{includedir}/ex-xref.adoc[tags=b-inter]
----

[[images]]
== 图片

.块
----
include::{includedir}/ex-image.adoc[tags=base]

include::{includedir}/ex-image.adoc[tags=alt]

include::{includedir}/ex-image.adoc[tags=attr]

include::{includedir}/ex-image.adoc[tags=ab-url]
----

[.result]
====
include::{includedir}/ex-image.adoc[tags=base]

include::{includedir}/ex-image.adoc[tags=alt]

include::{includedir}/ex-image.adoc[tags=attr]

include::{includedir}/ex-image.adoc[tags=ab-url]
====

IMPORTANT: 图片路径会被解析成一个相对于 {uri-imagesdir}[imagesdir 文档属性] 的一个值，默认是一个空字符串。
`imagesdir` 属性可以是绝对路径、相对路径或者是基本 URL。
如果图片的目标（target）是一个 URL 或者绝对路径，则 `imagesdir` 前缀就不会被添加。

TIP: 应该使用 `imagesdir` 属性来避免在每一个图片宏中硬编码分享路径。

.使用位置信息的图片宏
----
include::{includedir}/ex-image.adoc[tags=in-role]
----

[.result]
====
include::{includedir}/ex-image.adoc[tags=in-role]
====

TIP: 在 {uri-image-attrs}[图片的位置和帧] 中，有很多很多可用的属性。

.行内
----
include::{includedir}/ex-image.adoc[tags=in]
----

[.result]
====
include::{includedir}/ex-image.adoc[tags=in]
====

.嵌入式
----
include::{includedir}/ex-image.adoc[tags=data]
----

NOTE: 当 `data-uri` 属性被设置时，文档中的所有图片，包含警告图标，都会作为 {uri-data-uri}[数据 URI] 嵌入到文档中。

TIP: 除了在文档中声明 `data-uri` 属性，你还可以将 `-a data-uri` 参数传递给命令行。

[[videos]]
== 视频

.块
----
include::{includedir}/ex-video.adoc[tags=base]

include::{includedir}/ex-video.adoc[tags=attr]
----

.嵌入 Youtube 视频
----
include::{includedir}/ex-video.adoc[tags=you]
----

.嵌入 Vimeo 视频
----
include::{includedir}/ex-video.adoc[tags=vim]
----

TIP: 可以在宏中使用 {uri-video}[附加属性及选项] 来控制视频设置。

[[source-code]]
== 源码

.行内代码
----
include::{includedir}/ex-text.adoc[tags=b-mono-code]
----

[.result]
====
include::{includedir}/ex-text.adoc[tags=b-mono-code]
====

.代码行
----
include::{includedir}/ex-literal.adoc[tags=b-imp-code]
----

[.result]
====
include::{includedir}/ex-literal.adoc[tags=b-imp-code]
====

.代码块
----
include::{includedir}/ex-literal.adoc[tags=b-block]
----

[.result]
====
include::{includedir}/ex-literal.adoc[tags=b-block]
====

[listing]
.带标题的代码块，没有语法高亮
....
include::{includedir}/ex-listing.adoc[tags=b-base]
....

[.result]
====
include::{includedir}/ex-listing.adoc[tags=b-base]
====

[listing]
.加标题和语法高亮代码块
....
include::{includedir}/ex-src.adoc[tags=src-base]
....

[.result]
====
include::{includedir}/ex-src.adoc[tags=src-base]
====

[listing, subs="specialcharacters"]
.加注标的代码块
....
include::{includedir}/ex-callout.adoc[tags=b-src]
....

[.result]
====
include::{includedir}/ex-callout.adoc[tags=b-src]
====
// 翻译的不好
[listing,subs="specialcharacters"]
.加非选择性标注的代码块
....
include::{includedir}/ex-callout.adoc[tags=b-nonselect]
....

[.result]
====
include::{includedir}/ex-callout.adoc[tags=b-nonselect]
====

[listing,subs="specialcharacters"]
.加非选择性标注的 XML 代码块
....
include::{includedir}/ex-callout.adoc[tags=source-xml]
....

[.result]
====
include::{includedir}/ex-callout.adoc[tags=source-xml]
====

[listing]
.从文件中引入的代码块
....
include::{includedir}/ex-src.adoc[tags=src-inc]
....

[listing]
.从相对路径中文件引入的代码块
....
include::{includedir}/ex-src.adoc[tags=rel]
....

[listing]
.Strip leading indentation from source
....
include::{includedir}/ex-src.adoc[tags=ind]
....

[NOTE]
====
* When `indent` is 0, the leading block indent is stripped (tabs are replaced with 4 spaces).
* When `indent` is > 0, the leading block indent is first stripped (tabs are replaced with 4 spaces), then a block is indented by the number of columns equal to this value.
====

.不需要分隔符的代码块（没有空白行）
----
include::{includedir}/ex-src.adoc[tags=src-para]
----

[.result]
====
include::{includedir}/ex-src.adoc[tags=src-para]
====

[IMPORTANT]
.启用语法高亮
====
启用语法高亮可以在文档头部设置 `source-highlighter` 属性或者将其作为一个参数传递给命令行工具。

 :source-highlighter: pygments

可用选项有： `coderay`、`highlightjs`、`prettify` 和 `pygments`。
====

[[more-delimited-blocks]]
== 更多分隔块

.侧边栏
----
include::{includedir}/ex-sidebar.adoc[tags=base]
----

[.result]
====
include::{includedir}/ex-sidebar.adoc[tags=base]
====

NOTE: 任何块可以在块上面定义标题。
块标题是一行以点号开头的文字。
点号后面不能有空白。

.示例
----
include::{includedir}/ex-example.adoc[tags=base]
----

[example.result]
--
include::{includedir}/ex-example.adoc[tags=base]
--

[[admon-bl]]
.警告
----
include::{includedir}/ex-admon.adoc[tags=b-bl]
----

[.result]
=====
include::{includedir}/ex-admon.adoc[tags=b-bl]
=====

[TIP]
.警告和注标图标
====
Asciidoctor 可以使用 {uri-fontawesome}[Font Awesome^] 和 CSS "`描绘`" 图标。

将文档属性 `icons` 的值设置为 `font` 来启用该特性。
Asciidoctor 会在文档中添加 HTML 标记，通过这些标记来从 Font Awesome 字体为每一个警告块选择一个合适的字符来展示。


图标还可以使用 {uri-icon-in}[inline] 和 {uri-icon-attrs}[styled]。
====

.引用块
----
include::{includedir}/ex-quote.adoc[tags=bl]

include::{includedir}/ex-quote.adoc[tags=para]

include::{includedir}/ex-quote.adoc[tags=no-cite]

include::{includedir}/ex-quote.adoc[tags=link-text]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=bl]

include::{includedir}/ex-quote.adoc[tags=para]

include::{includedir}/ex-quote.adoc[tags=no-cite]
====

.简略引用块（仅 Asciidoctor 支持）
----
include::{includedir}/ex-quote.adoc[tags=abbr]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=abbr]
====

.Air quotes: the best thing since fenced code blocks (Asciidoctor only)
----
include::{includedir}/ex-quote.adoc[tags=air]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=air]
====

.Pass 宏
----
include::{includedir}/ex-pass.adoc[tags=b-bl]
----

[.result]
====
include::{includedir}/ex-pass.adoc[tags=b-bl]
====

.Open
----
include::{includedir}/ex-open.adoc[tags=base]

include::{includedir}/ex-open.adoc[tags=src]
----

[.result]
====
include::{includedir}/ex-open.adoc[tags=base]

include::{includedir}/ex-open.adoc[tags=src]
====

[listing]
.自定义代换
....
include::{includedir}/ex-listing.adoc[tags=subs]
....

[.result]
====
// the attribute value is hard-coded in this result since the example depends
// on a hypothetical document attribute
include::{includedir}/ex-listing.adoc[tags=subs-out]
====

[[block-id-role-and-options]]
== 块ID，角色和选项

.为块添加 ID 和角色的传统标记方法
----
[[goals]]
[role="incremental"]
* Goal 1
* Goal 2
----

.为块添加 ID 和角色的简略标记方法（仅 Asciidoctor 支持）
----
[#goals.incremental]
* Goal 1
* Goal 2
----

[TIP]
====
* 在简略语法中，可以使用点号分割来指定多个角色。
* 简略语法中 `id` 和 `role` 值的顺序无关紧要。
====

.为引用文本添加锚点和角色的传统标记方法
----
[[free_the_world]][big goal]_free the world_
----

.为引用文本添加锚点和角色的简略标记方法（仅 Asciidoctor 支持）
----
[#free_the_world.big.goal]_free the world_
----

.为反引号包括的文本添加角色
----
[rolename]`monospace text`
----

.为块添加选项的传统标记方法
----
[options="header,footer,autowidth"]
|===
|Cell A |Cell B
|===
----

.为块添加选项的简略标记方法（仅 Asciidoctor 支持）
----
[%header%footer%autowidth]
|===
|Cell A |Cell B
|===
----

[[comments]]
== 评论

.单行
----
include::{includedir}/ex-comment.adoc[tags=line]
----

TIP: 单行注释可以用于划分元素，例如两个相邻的清单。

.注释块
----
include::{includedir}/ex-comment.adoc[tags=bl]
----

[[tables]]
== 表格

.带标题的三行二列表格
----
include::{includedir}/ex-table.adoc[tags=b-base-h-co]
----
<1> Unless the `cols` attribute is specified, the number of columns is equal to the number of vertical bars on the first non-blank line inside the block delimiters.
<2> When a blank line follows a single line of column titles, the column titles row will be styled as a header row by default.

[.result]
====
include::{includedir}/ex-table.adoc[tags=b-base-h]
====

.Table with two columns, a header, and two rows of content
----
include::{includedir}/ex-table.adoc[tags=b-col-h-co]
----
<1> The `+*+` in the `cols` attribute is the repeat operator. It means repeat the column specification for the remainder of columns. In this case, it means to repeat the default formatting across 4 columns. When the header row is not defined on a single line, you must use the cols attribute to set the number of columns and `options` attributes to make the first row a header.

[.result]
====
include::{includedir}/ex-table.adoc[tags=b-col-h]
====

.Table with three columns, a header, and two rows of content
----
include::{includedir}/ex-table.adoc[tags=b-col-indv-co]
----
<1> In this example, the `cols` attribute has two functions. It specifies that this table has three columns, and it sets their relative widths.

[.result]
====
include::{includedir}/ex-table.adoc[tags=b-col-indv]
====

.Table with column containing AsciiDoc content
----
include::{includedir}/ex-table.adoc[tags=b-col-a]
----

[.result]
====
include::{includedir}/ex-table.adoc[tags=b-col-a]
====

.Table from CSV data
----
include::{includedir}/ex-table-data.adoc[tags=csv]
----

[.result]
====
include::{includedir}/ex-table-data.adoc[tags=csv]
====

.Table from CSV data using shorthand (Asciidoctor only)
----
include::{includedir}/ex-table-data.adoc[tags=s-csv]
----

[.result]
====
include::{includedir}/ex-table-data.adoc[tags=s-csv]
====

.Table from CSV data in file
----
include::{includedir}/ex-table-data.adoc[tags=i-csv]
----

.Table from DSV data using shorthand (Asciidoctor only)
----
include::{includedir}/ex-table-data.adoc[tags=s-dsv]
----

[.result]
====
include::{includedir}/ex-table-data.adoc[tags=s-dsv]
====

.Table with formatted, aligned and merged cells
----
include::{includedir}/ex-table-cell.adoc[tags=b-spec]
----

[.result]
====
include::{includedir}/ex-table-cell.adoc[tags=b-spec]
====

[[ui-macros]]
== UI 宏

IMPORTANT: You *must* set the `experimental` attribute in the document header to enable these macros.

.Keyboard shortcuts (inline kbd macro)
----
include::{includedir}/ex-ui.adoc[tags=key]
----

[.result]
====
include::{includedir}/ex-ui.adoc[tags=key]
====

.Menu selections (inline +menu+ macro)
----
include::{includedir}/ex-ui.adoc[tags=menu]
----

[.result]
====
include::{includedir}/ex-ui.adoc[tags=menu]
====

.Buttons (inline +btn+ macro)
----
include::{includedir}/ex-ui.adoc[tags=button]
----

[.result]
====
include::{includedir}/ex-ui.adoc[tags=button]
====

[[attributes-and-substitutions]]
== 属性与代换

.Attribute declaration and usage
----
include::{includedir}/ex-header-attr.adoc[tags=b-attr]
----

[.result]
====
// I have to use a nested doc hack here, otherwise the attributes won't resolve
[.unstyled]
|===
a|
include::{includedir}/ex-header-attr.adoc[tags=b-attr]
|===
====

.Attribute assignment precedence (highest to lowest)
- Attribute passed to the API or CLI that does not end in `@`
- Attribute defined in the document
- Attribute passed to the API or CLI that ends in `@`
- Intrinsic attribute value (default values)

TIP: To make an attribute value that is passed to the API or CLI have a lower precedence than an assignment in the document, add an `@` symbol to the end of the attribute value.

// Table of predefined attributes for character replacements
include::{includedir}/attrs-charref.adoc[tags=table]

// Table of environment attributes
include::{includedir}/attrs-env.adoc[tags=table]

.Named substitutions
include::{includedir}/subs-apply.adoc[tags=group]

.Counter attributes
----
include::{includedir}/ex-counter.adoc[tags=base]
----

[.result]
====
include::{includedir}/ex-counter.adoc[tags=base]
====

[[text-replacement]]
== 文本替换

// Table of text replacements performed during replacements substitution
include::{includedir}/subs-symbol-repl.adoc[]

TIP: Any named, numeric or hex {uri-char-xml}[XML entity reference] is supported.

[[escaping-text]]
== 文字转义

.Backslash
----
include::{includedir}/ex-subs.adoc[tags=b-slash]
----

[.result]
====
include::{includedir}/ex-subs.adoc[tags=b-slash]
====

////
.Double dollar
----
include::{includedir}/ex-pass.adoc[tags=b-dollar]
----

[.result]
====
include::{includedir}/ex-pass.adoc[tags=b-dollar]
====
////

.Triple plus and inline passthrough macro
----
include::{includedir}/ex-pass.adoc[tags=b-3p-macro]
----

[.result]
====
include::{includedir}/ex-pass.adoc[tags=b-3p-macro]
====

////
.Backticks
----
include::{includedir}/ex-pass.adoc[tags=b-tick]
----

[.result]
====
include::{includedir}/ex-pass.adoc[tags=b-tick]
====
////

[[table-of-contents-toc]]
== 目录

.Document with ToC
----
include::{includedir}/ex-toc.adoc[tags=base]
----

.Document with ToC positioned on the right
----
include::{includedir}/ex-toc.adoc[tags=pos]
----

TIP: The ToC {uri-toc}["title, levels, and positioning"] can be customized.

[[bibliography]]
== 参考书目

.References
----
include::{includedir}/ex-biblio.adoc[tags=base]
----

[.result]
====
include::{includedir}/ex-biblio.adoc[tags=base]
====

[[section-footnotes]]
== 脚注

.Normal and reusable footnotes
----
include::{includedir}/ex-footnote.adoc[tags=base]
----

[.result]
====
[.unstyled]
|===
a|
include::{includedir}/ex-footnote.adoc[tags=base]
|===
====

[[markdown-compatibility]]
== Markdown 兼容性

Markdown compatible syntax is only available when using Asciidoctor.

.Markdown-style headings
----
include::{includedir}/ex-section.adoc[tags=md]
----

[.result]
====
include::{includedir}/ex-section.adoc[tags=b-md]
====

.Fenced code block with syntax highlighting
----
include::{includedir}/ex-src.adoc[tags=fence]
----

[.result]
====
include::{includedir}/ex-src.adoc[tags=fence]
====

.Markdown-style blockquote
----
include::{includedir}/ex-quote.adoc[tags=md]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=md]
====

.Markdown-style blockquote with block content
----
include::{includedir}/ex-quote.adoc[tags=md-alt]
----

[.result]
====
include::{includedir}/ex-quote.adoc[tags=md-alt]
====

.Markdown-style horizontal rules
----
include::{includedir}/ex-hr.adoc[tags=md]
----

[.result]
====
include::{includedir}/ex-hr.adoc[tags=md]
====

[[user-manual-and-help]]
== 用户手册以及帮助

To learn more about Asciidoctor and its capabilities, check out the other {docs}[Asciidoctor guides] and its {user}[User Manual].
Also, don't forget to join the {uri-mailinglist}[Asciidoctor mailing list], where you can ask questions and leave comments.
