= Frequently Asked Questions and Trouble Shooting
Sarah White <https://github.com/graphitefriction[@graphitefriction]>;
:description: Frequently asked questions (FAQ) about the Asciidoctor project, Asciidoctor syntax and processor, and the AsciiDoc syntax. +
Tips for fixing installation, syntax, processing, and rendering problems when using Asciidoctor.
:keywords: Asciidoctor, AsciiDoc, syntax, question, render, process, problem, issue, tips
:linkattrs:
:icons: font
:source-highlighter: coderay
:idprefix:
:idseparator: -
:language: asciidoc
:table-caption!:
:example-caption!:
:figure-caption!:
// :imagesdir: ../images
:includedir: _includes


// == Frequently Asked Questions

:q1: Does Asciidoctor only encode in US-ASCII?
:q1a: How do I enable syntax highlighting in the deck.js backend?
:q2: How do I make relative links to other AsciiDoc files to work correctly on GitHub?
:q3: What is the internet mime type (aka MIME type) for AsciiDoc?
:q4: Part way through the document, the blocks stop rendering correctly. What went wrong?
:q5: Why don't URLs containing underscores (`_`) or carets (`{caret}`) work after they're rendered?

. xref:faq1[_{q1}_]
. xref:faq1a[_{q1a}_]
. xref:faq2[_{q2}_]
. xref:faq3[_{q3}_]
. xref:faq_rendering[_{q4}_]
. xref:faq_urls[_{q5}_]

[qanda]
[[faq1]]{q1}::
No.
Asciidoctor encodes in UTF-8 and has full Unicode support.

[[faq1a]]{q1a}::
+
--
You begin by setting the +source-highlighter+ attribute to one of the accepted values, such as +coderay+.

 :source-highlighter: coderay

That only gets you half way, though.
The problem is that Asciidoctor only performs syntax highlighting when the "base" backend attribute (i.e., basebackend attribute) is html.
The basebackend attribute is determined by removing the trailing numbers from the backend name.
For instance, html5 becomes html.
However, deckjs becomes...deckjs.
There in lies our problem (see https://github.com/asciidoctor/asciidoctor/issues/891[issue #891]).

The workaround is to set the backend to html5 (or just don't set it) and point the -T command argument to the [file]_haml/deckjs_ folder under the https://github.com/asciidoctor/asciidoctor-backends[asciidoctor-backends] directory.
For example:

 $ asciidoctor -T /path/to/asciidoctor-backends/haml/deckjs deck.adoc

Notice that the backend attribute _is not set_.
The templates will be used in exactly the same way as if you had set the backend to +deckjs+, except this time syntax highlighting will work!

[TIP]
====
If you want to have CodeRay embed the styles inline instead of using CSS classes, set the following attribute in your AsciiDoc document:

 :coderay-css: style

====
--

[[faq2]]{q2}::
+
--
include::{includedir}/xref-source-to-source.adoc[]
--

[[faq3]]{q3}::
+
--
// http://en.wikipedia.org/wiki/Internet_media_type
The first idea that emerged from the http://discuss.asciidoctor.org/Mimetype-for-Asciidoc-td211.html[Mimetype for AsciiDoc] discussion on the Asciidoctor mailinglist was:

 text/x-asciidoc

Recently, the internet media type `text/markdown` was registered for Markdown, so another option to consider is:

 text/asciidoc

Either one will do, though it probably makes sense to align with Markdown on this one.
--

include::{includedir}/ts-block-render.adoc[tags="faq_rendering"]

[[faq_urls]]{q5}::
+
--
include::{includedir}/ts-url-format.adoc[tags="sb"]
--

