= Frequently Asked Questions (FAQs) and Troubleshooting
Sarah White <https://github.com/graphitefriction[@graphitefriction]>;
:description: Frequently asked questions (FAQ) about the Asciidoctor project, Asciidoctor syntax and processor, and the AsciiDoc syntax. +
Tips for fixing installation, syntax, processing, and rendering problems when using Asciidoctor.
:keywords: Asciidoctor, AsciiDoc, syntax, question, render, process, problem, issue, tips
:linkattrs:
:icons: font
:source-highlighter: coderay
:idprefix:
:idseparator: -
:language: asciidoc
:table-caption!:
:example-caption!:
:figure-caption!:
// :imagesdir: ../images
:includedir: _includes
:toc:

== FAQs

=== Does Asciidoctor only process text that is US-ASCII encoded?

No.
Asciidoctor has full support for Unicode.
👌

Asciidoctor assumes input is encoded in UTF-8 and it encodes output documents in UTF-8 as well.

=== How do I make relative links to other AsciiDoc files to work correctly on GitHub?

include::{includedir}/xref-source-to-source.adoc[]

=== What is the media type for AsciiDoc?

A http://en.wikipedia.org/wiki/Internet_media_type[media type], or MIME type, is a code for identifying file formats and format contents transmitted on the Internet.

The first idea for an official MIME type for AsciiDoc came from the http://discuss.asciidoctor.org/Mimetype-for-Asciidoc-td211.html[Mimetype for AsciiDoc] discussion on the Asciidoctor mailinglist:

 text/x-asciidoc

Recently, the internet media type `text/markdown` was registered for Markdown, so a stronger case can now be made for:

 text/asciidoc

Either one will do, though it probably makes sense to align with Markdown on this one.

=== How do I enable syntax highlighting in the deck.js backend?

You begin by setting the `source-highlighter` attribute to one of the accepted values, such as `coderay`.

 :source-highlighter: coderay

That only gets you half way, though.
The problem is that Asciidoctor only performs syntax highlighting when the "base" backend attribute (i.e., basebackend attribute) is html.
The basebackend attribute is determined by removing the trailing numbers from the backend name.
For instance, html5 becomes html.
However, deckjs becomes...deckjs.
There in lies our problem (see https://github.com/asciidoctor/asciidoctor/issues/891[issue #891]).

The workaround is to set the backend to html5 (or just don't set it) and point the -T command argument to the [.path]_haml/deckjs_ folder under the https://github.com/asciidoctor/asciidoctor-backends[asciidoctor-backends] directory.
For example:

 $ asciidoctor -T /path/to/asciidoctor-backends/haml/deckjs deck.adoc

Notice that the backend attribute _is not set_.
The templates will be used in exactly the same way as if you had set the backend to `deckjs`, except this time syntax highlighting will work!

[TIP]
====
If you want to have CodeRay embed the styles inline instead of using CSS classes, set the following attribute in your AsciiDoc document:

 :coderay-css: style

====

== Troubleshooting

=== Part way through the document, the blocks stop rendering correctly. What went wrong?

include::{includedir}/ts-block-render.adoc[tag=answer]

=== Why don't links to URLs that contain an underscore or caret work?

include::{includedir}/ts-url-format.adoc[tag=sb]
