= FAQs and Troubleshooting
Sarah White <https://github.com/graphitefriction[@graphitefriction]>;
:description: Frequently asked questions (FAQ) about the Asciidoctor project, Asciidoctor syntax and processor, and the AsciiDoc syntax. +
Tips for fixing installation, syntax, processing, and rendering problems when using Asciidoctor.
:keywords: Asciidoctor, AsciiDoc, syntax, question, render, process, problem, issue, tips
:linkattrs:
:icons: font
:source-highlighter: coderay
:idprefix:
:idseparator: -
:language: asciidoc
:table-caption!: 
:example-caption!:
:figure-caption!:
// :imagesdir: ../images
:includedir: _includes

== Frequently Asked Questions

[qanda]
Does Asciidoctor only encode in US-ASCII?::
No. 
Asciidoctor encodes in UTF-8 and has full Unicode support.

How do I enable syntax highlighting in the deck.js backend?::
+
--
You begin by setting the +source-highlighter+ attribute to one of the accepted values, such as +coderay+.

 :source-highlighter: coderay

That only gets you half way, though.
The problem is that Asciidoctor only performs syntax highlighting when the "base" backend attribute (i.e., basebackend attribute) is html.
The basebackend attribute is determined by removing the trailing numbers from the backend name.
For instance, html5 becomes html.
However, deckjs becomes...deckjs.
There in lies our problem (see https://github.com/asciidoctor/asciidoctor/issues/891[issue #891]).

The workaround is to set the backend to html5 (or just don't set it) and point the -T command argument to the [file]_haml/deckjs_ folder under the https://github.com/asciidoctor/asciidoctor-backends[asciidoctor-backends] directory.
For example:

 $ asciidoctor -T /path/to/asciidoctor-backends/haml/deckjs deck.adoc

Notice that the backend attribute _is not set_.
The templates will be used in exactly the same way as if you had set the backend to +deckjs+, except this time syntax highlighting will work!

[TIP]
====
If you want to have CodeRay embed the styles inline instead of using CSS classes, set the following attribute in your AsciiDoc document:

 :coderay-css: style

====
--

How do I get relative links to other AsciiDoc files to work correctly on GitHub?::
By default, the suffix for relative links in the generated HTML is `.html`.
You need to adjust the `outfilesuffix` parameter to be `.adoc` so that the links work properly, since GitHub uses the `.adoc` extension in the URL even though the document is rendered as HTML.
+
For example:
+
[source,asciidoc]
----
\ifdef::env-github[:outfilesuffix: .adoc]

This is a link:example{outfilesuffix}[relative link] to an example file.

This is a <<example#,relative link>> to the same file using the xref macro.
----
+
Note that you probably don't want to set `outfilesuffix` to `.adoc` unconditionally, as that could result in Asciidoctor overwriting input files (although there's some guarantee it won't).

== Troubleshooting

include::{includedir}/troubleshoot.adoc[tags=faq]

////
Add windows 32 bit caveat
////
