= Hacking on the Asciidoctor Maven Plugin
Jason Porter
:awestruct-layout: base
:toc:
:mavenreporef: http://github.com/asciidoctor/asciidoctor-maven-plugin
:asciidocref: http://asciidoc.org
:maven: http://maven.apache.org
:docref: link:/docs
:mavenguideref: {docref}/install-and-use-asciidoctor-maven-plugin
:spock: http://spockframework.org
:mavenpluginissue: http://github.com/asciidoctor/asciidoctor-maven-plugin/issues
:mailinglist: http://discuss.asciidoctor.org

The {mavenreporef}[Asciidoctor Maven plugin] is the official means of using Asciidoctor to render all your {asciidocref}[AsciiDoc] documentation using {maven}[Apache Maven].

For help running this plugin, review the {mavenguideref}[How do I install and use the Asciidoctor Maven plugin guide].

== Hacking

Developer setup for hacking on this project isn't difficult. 
The requirements are:

* Java
* Maven 3

All the other dependencies will be brought in by Maven. 
You should be able to use IntelliJ, Eclipse, or Netbeans without any issue for hacking on the project.

== Building

Standard Maven build:

 mvn clean install

== Testing

{spock}[Spock] is used for testing the calling of the Mojo. 
This will be downloaded by Maven. 
Tests are run simply by:

 mvn clean test

Or any of the other goals which run tests. 
If I can figure out a good way to setup a Ruby testing environment I'll do that as well, but none exists at this time.

== Resources and help

To file an issue regarding this plugin, visit the {mavenpluginissue}[plugin's repository].

Also, don't forget to join the {mailinglist}[Asciidoctor mailing list], where you can ask questions and leave comments.

