= Hacking on the Asciidoctor Maven Plugin
Jason Porter
:page-layout: documentation
:toc:
:repo-ref: http://github.com/asciidoctor/asciidoctor-maven-plugin
:issues-ref: http://github.com/asciidoctor/asciidoctor-maven-plugin/issues
:discuss-ref: http://discuss.asciidoctor.org
:asciidoc-ref: http://asciidoc.org
:maven-ref: http://maven.apache.org
:docs-ref: link:/docs
:maven-guide-ref: link:/docs/install-and-use-asciidoctor-maven-plugin
:spock-ref: http://spockframework.org

The {repo-ref}[Asciidoctor Maven plugin] is the official means of using Asciidoctor to render your {asciidoc-ref}[AsciiDoc] documentation using {maven-ref}[Apache Maven].
This guide teaches you how to hack on it.

For help running this plugin, review the {maven-guide-ref}[How do I install and use the Asciidoctor Maven plugin guide].

== Hacking

Developer setup for hacking on this project isn't difficult. 
The requirements are:

* Java
* Maven 3

All the other dependencies will be brought in by Maven. 
You should be able to use IntelliJ, Eclipse, or Netbeans without any issue for hacking on the project.

== Building

Standard Maven build:

 $ mvn clean install

== Testing

{spock-ref}[Spock] is used for testing the calling of the Mojo. 
This will be downloaded by Maven. 
Tests are run simply by:

 $ mvn clean test

Or any of the other goals which run tests. 
If I can figure out a good way to setup a Ruby testing environment I'll do that as well, but none exists at this time.

== Resources

To file an issue regarding this plugin, visit the {issues-ref}[plugin's repository].

Also, don't forget to join the {discuss-ref}[Asciidoctor discussion list], where you can ask questions and leave comments.
