= Asciidoctor Documentation
:page-layout: docs

You've arrived at the landing page for the old Asciidoctor documentation.
The landing page for the new documentation is located at https://docs.asciidoctor.org, now a dedicated site.
On the new site you can find the most up-to-date documentation for the AsciiDoc markup language, the Asciidoctor processor and toolchain, and numerous Asciidoctor integrations.

If you're looking for real-time support from fellow community members, please ask your question in the https://asciidoctor.zulipchat.com[community chat] under the #users stream.
You can also find useful information on the https://discuss.asciidoctor.org[discussion list], though keep in mind that the discussion list has been deprecated as a means of communication in favor of the community chat.

== The Basics

Discover Asciidoctor and how it can help you.

* https://docs.asciidoctor.org/asciidoctor/latest/#what-is-asciidoctor[What is Asciidoctor?]

* link:what-is-asciidoc/[What is AsciiDoc?]

* https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/[How do AsciiDoc and Markdown differ?]

* link:/#authors[Who created Asciidoctor?]

* https://github.com/asciidoctor/asciidoctor/blob/HEAD/LICENSE[What is the Asciidoctor license?]

* http://www.vogella.com/tutorials/AsciiDoc/article.html[Using AsciiDoc and Asciidoctor to write documentation] (article by vogella)

== Get Started with Asciidoctor

Now, let's setup and use the Asciidoctor toolchain!

* https://docs.asciidoctor.org/asciidoctor/latest/install/[Install Asciidoctor]
//Follow the guide link:install-asciidoctor-macos/[Installing Asciidoctor on macOS] for an in-depth tutorial.

* https://docs.asciidoctor.org/asciidoctor/latest/get-started/[Convert your first document]

//* link:produce-custom-themes-using-asciidoctor-stylesheet-factory[How do I use the Asciidoctor stylesheet factory to produce custom themes?]

== Write with AsciiDoc

https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc Language Documentation]::
  The documentation for the AsciiDoc language as it’s implemented in Asciidoctor.

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[AsciiDoc Syntax Quick Reference]::
  An overview of the AsciiDoc syntax you'll likely need to structure and format a document.

link:asciidoc-writers-guide/[AsciiDoc Writer's Guide]::
  A comprehensive tutorial with examples that show you how to use the AsciiDoc syntax.

link:asciidoc-recommended-practices/[AsciiDoc Style Guide and Recommended Practices] (DRAFT)::
  Style tips and recommended practices for writing an easy to read and convert document.

link:asciidoc-article/[AsciiDoc Article Template]::
  A template containing the most common content structures and markup used in an AsciiDoc article document.

== Syntax Extensions

link:asciidoctor-diagram[Asciidoctor Diagram]::
  Learn how to create diagrams and ASCII art in your AsciiDoc documents using PlantUML, Graphviz, ditaa, and Shaape.

== Processors

https://docs.asciidoctor.org/asciidoctor/latest/[Asciidoctor Documentation]::
  Asciidoctor is a fast, open source, Ruby-based text processor for parsing AsciiDoc into a document model and converting it to output formats such as HTML 5, DocBook 5, manual pages, PDF, and EPUB 3. This Ruby library is often referred to as Asciidoctor core.
link:install-and-use-asciidoctor-java-integration/[Install and use AsciidoctorJ]::
  AsciidoctorJ bundles all gems that are required for executing Asciidoctor and wraps it into a Java API so that Asciidoctor can be used in Java like any other Java library.
link:install-and-use-asciidoctorjs/[Install and use Asciidoctor.js]::
  Asciidoctor.js brings AsciiDoc to the JavaScript world!

== Extended Converters

link:convert-asciidoc-to-pdf/[Convert AsciiDoc to PDF with Asciidoctor]::
  Asciidoctor PDF is a native PDF converter for AsciiDoc. We're talking AsciiDoc direct to PDF! Learn how to install Asciidoctor PDF and use it to convert your AsciiDoc documents to PDF.

link:convert-asciidoc-to-epub/[Convert AsciiDoc to EPUB3 with Asciidoctor]::
  Asciidoctor EPUB3 is a native EPUB3 converter for AsciiDoc. Learn how to install Asciidoctor EPUB3 and use it to convert your AsciiDoc documents directly to EPUB3 and Amazon's KF8/Mobi format for Kindle.

link:asciidoctor-revealjs[Create a reveal.js presentation with Asciidoctor]::
  Asciidoctor reveal.js is a converter for Asciidoctor and Asciidoctor.js that transforms an AsciiDoc document into an HTML5 presentation designed to be executed by the reveal.js presentation framework.

== Build Automation Plugins

* link:install-and-use-asciidoctor-gradle-plugin/[How do I install and use the Asciidoctor Gradle plugin?]
* link:install-and-use-asciidoctor-maven-plugin/[How do I install and use the Asciidoctor Maven plugin?]
* link:hack-asciidoctor-maven-plugin/[Hacking on the Asciidoctor Maven plugin]
* link:install-and-use-asciidoclet/[How do I install and use Asciidoclet?]

== Migrate to Asciidoctor

* https://docs.asciidoctor.org/asciidoctor/latest/migrate/asciidoc-py/[Migrate from AsciiDoc.py to Asciidoctor]
* https://docs.asciidoctor.org/asciidoctor/latest/migrate/docbook-xml/[Migrate from Docbook XML to Asciidoctor]
* https://docs.asciidoctor.org/asciidoctor/latest/migrate/confluence-xhtml/[Migrate from Confluence XHTML to Asciidoctor]
* https://docs.asciidoctor.org/asciidoctor/latest/migrate/ms-word/[Migrate from MS Word to Asciidoctor]

== Contribute to Asciidoctor

* https://github.com/asciidoctor/asciidoctor/blob/HEAD/CONTRIBUTING.adoc#submitting-an-issue[How do I report a bug?]

* "`I have code I'd like to contribute!`" Then checkout this guide => https://github.com/asciidoctor/asciidoctor/blob/HEAD/CONTRIBUTING.adoc#submitting-a-pull-request[How do I submit code to the project?]

== References and Developer Resources

* link:faq/[FAQs and Troubleshooting]
* link:extensions/[Extension list]
* https://www.rubydoc.info/gems/asciidoctor[Asciidoctor Ruby API Documentation]
* https://www.javadoc.io/doc/org.asciidoctor/asciidoctorj/[AsciidoctorJ API Documentation]
* link:/[Asciidoctor README]
* link:/man/asciidoctor/[Asciidoctor man page]
* https://www.redhat.com[Red Hat dot com]
