= Installing and Using the Asciidoctor Java Integration
Alex Soto
:awestruct-layout: base
:toc:
:repo-ref: http://github.com/asciidoctor/asciidoctor-java-integration
:issues-ref: https://github.com/asciidoctor/asciidoctor-java-integration/issues
:discuss-ref: http://discuss.asciidoctor.org
:artifact-version: 0.1.3
:artifact-query-ref: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.asciidoctor%22%20AND%20a%3A%22asciidoctor-java-integration%22
:artifact-detail-ref: http://search.maven.org/#artifactdetails%7Corg.asciidoctor%7Casciidoctor-java-integration%7C0.1.3%7Cjar
:artifact-file-ref: http://search.maven.org/remotecontent?filepath=org/asciidoctor/asciidoctor-java-integration/0.1.3/asciidoctor-java-integration-0.1.3.jar
:jruby-startup-ref: http://github.com/jruby/jruby/wiki/Improving-startup-time
:docs-ref: link:/docs
:maven-guide-ref: link:/docs/install-and-use-asciidoctor-maven-plugin
:gradle-guide-ref: link:/docs/install-and-use-asciidoctor-gradle-plugin
:asciidoc-ref: http://asciidoc.org/README.html
:header-nocaption: options="header", caption=""
:language: java
:font-awesome-url: http://fortawesome.github.io/Font-Awesome/

The {repo-ref}[Asciidoctor Java integration] is the official means of using Asciidoctor to render your {asciidoc-ref}[AsciiDoc] documentation using Java instead of Python or Ruby.

toc::[levels=1]

== Distribution

The Asciidoctor Java integration is published to Maven Central.
The artifact information is summarized in the table below.

[cols="2,4,^1,5", {header-nocaption}]
.Artifact information for the Asciidoctor Java integration library
|===
|Group Id |Artifact Id |Version |Download

|org.asciidoctor
|{artifact-query-ref}[asciidoctor-java-integration]
|{artifact-detail-ref}[{artifact-version}]{asterisk}
|{artifact-file-ref}.pom[pom] {artifact-file-ref}.jar[jar] {artifact-file-ref}-javadoc.jar[javadoc (jar)] {artifact-file-ref}-sources.jar[source (jar)]
|===

{asterisk} This release is based on the Asciidoctor {artifact-version} release.

== Installation

Since the Asciidoctor Java integration is a standard +.jar+ file, the only thing you should do is add the library to the classpath.

// SW: Need functional tests for a java maven project and a java gradle project
// SW: Need to field test

[source, xml]
.Dependency declaration in Maven's pom.xml
----
<dependencies>
  <dependency>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-java-integration</artifactId>
    <version>${asciidoctor.version}</version> <1>
  </dependency>
</dependencies>
----

// SW: The JRuby runtime dependency is missing

[source, groovy]
.Dependency declaration in Gradle's build.gradle
----
dependencies {
  compile('org.asciidoctor:asciidoctor-java-integration:${asciidoctor.version}') { <1>
    transitive = false
  }
}
----
<1> As this library tracks the version of Asciidoctor, you can use which ever version of Asciidoctor you prefer.

You can learn more about these plugins in the following two guides:

- {maven-guide-ref}[How to Install and Use the Asciidoctor Maven Plugin]
- {gradle-guide-ref}[How to Install and Use the Asciidoctor Gradle Plugin]

== Usage

The main entry point for the Asciidoctor Java integration is the +Asciidoctor+ Java interface.
This interface provides four methods for rendering AsciiDoc content, +render+, +renderFile+, +renderFiles+ and +renderDirectory+.

[cols="1m,2", {header-nocaption}]
.+Asciidoctor+ methods
|===
|Name |Description

|render
|Parses the AsciiDoc content read from a string or stream and renders it to the specified backend format.

|renderFile
|Parses the AsciiDoc content read from a file and renders it to the specified backend format.

|renderFiles
|Parses a list of AsciiDoc files and renders them to the specified backend format.

|renderDirectory
|Parses all AsciiDoc files present in the specified directory (and any subdirectories) and renders them to the specified backend format.

|readDocumentHeader
|Retrieves information from the header of an AsciiDoc document without parsing or rendering the entire document.
|===

NOTE: All methods are overloaded to accomodate various ways to supply content and options.

Additionally, a factory method is provided to create an instance of the +Asciidoctor+ interface.

[source]
.Creating an +Asciidoctor+ instance
----
import static org.asciidoctor.Asciidoctor.Factory.create;
import org.asciidoctor.Asciidoctor;

Asciidoctor asciidoctor = create();
----

Below the code that creates the +Asciidoctor+ interface instance, you can call the +render+ method that best suits your needs.
Use +render+ to render a string.

[source]
.Rendering a string
----
//...
import java.util.Collections;
//...
String rendered = asciidoctor.render(
    "AsciiDoc is *easy*!", Collections.<String,Object>emptyMap());
System.out.println(rendered);
----

+renderFile+ will render the content of an AsciiDoc file.

[source]
.Rendering a file
----
//...
import java.util.Collections;
//...
String rendered = asciidoctor.renderFile(
    new File("sample.adoc"), Collections.<String,Object>emptyMap());
System.out.println(rendered);
----

+renderFiles+ will render a list of AsciiDoc files:

[source]
.Rendering a list of files
----
//...
String[] renderedFiles = asciidoctor.renderFiles(
    Arrays.asList(new File("target/test-classes/rendersample.asciidoc")), new HashMap<String, Object>());

for(String renderedFile : renderedFiles) {
    System.out.println(renderedFile);
}
----

If the rendered content is not written into files, +renderDirectory+ will return an array listing all the documents rendered.

Another method provided by the +Asciidoctor+ interface is +renderDirectory+.
This method renders all of the files with AsciiDoc extensions (+.asc+, +.asciidoc+, +.ad+ or +.adoc+) that are present within a specified folder and its subfolders.

If the rendered content is not written into files, +renderDirectory+ will return an array listing all the documents rendered.

// SW: Maybe provide an example of this array output?

[source]
.Rendering all the files in a directory
----
//...
String[] renderedFiles = asciidoctor.renderDirectory(
    new File("docs"), new HashMap<String, Object>());

for(String renderedFile : renderedFiles) {
    System.out.println(renderedFile);
}
----

Another way to render AsciiDoc content is by calling the +render+ method and providing a standard Java +java.io.Reader+ and +java.io.Writer+.
The +Reader+ interface is used as the source, and the rendered content is written to the +Writer+ interface.

[source]
.Rendering content read from a +java.io.Reader+ to a +java.io.Writer+
----
//...
FileReader reader = new FileReader(new File("sample.adoc"));
StringWriter writer = new StringWriter();

asciidoctor.render(reader, writer, options().asMap());

StringBuffer rendered = writer.getBuffer();
System.out.println(rendered.toString());
----

+readDocumentHeader+ retrieve information from the header of an AsciiDoc document without parsing or rendering the entire document.
This method returns an instance of +org.asciidoctor.DocumentHeader+ with all information from the header filled.

[source, asciidoc]
.Example AsciiDoc document with header information
----
= Sample Document
Doc Writer <doc.writer@asciidoc.org>; John Smith <john.smith@asciidoc.org>
v1.0, 2013-05-20: First draft
:title: Sample Document
:tags: [document, example]

Preamble...
----

[source]
.Reading header information from the AsciiDoc document
----
//...
DocumentHeader header = asciidoctor.readDocumentHeader(
    new File("target/test-classes/documentheaders.asciidoc"));

System.out.println(header.getDocumentTitle()); <1>

Author author = header.getAuthor(); <2>
System.out.println(author.getEmail()); <3>
System.out.println(author.getFullName()); <4>

RevisionInfo revisionInfo = header.getRevisionInfo();

System.out.println(revisionInfo.getDate()); <5>
System.out.println(revisionInfo.getNumber()); <6>
System.out.println(revisionInfo.getRemark()); <7>
----
<1> prints +Sample Document+
<2> prints +Doc Writer+
<3> prints `doc.writer@asciidoc.org`
<4> prints +Doc Writer+
<5> prints +2013-05-20+
<6> prints +1.0+
<7> prints +First draft+

The +readDocumentHeader+ method can be extremely useful for building an index of documents.

[source]
----
import java.io.File;
import java.util.HashSet;
import java.util.Set;
import org.asciidoctor.Asciidoctor;
import org.asciidoctor.AsciiDocDirectoryWalker;
import org.asciidoctor.DirectoryWalker;
import org.asciidoctor.DocumentHeader;

//...

Asciidoctor asciidoctor = Asciidoctor.Factory.create();
Set<DocumentHeader> documentIndex = new HashSet<DocumentHeader>();
DirectoryWalker directoryWalker = new AsciiDocDirectoryWalker("docs");
for (File file : directoryWalker.scan()) {
    documentIndex.add(asciidoctor.readDocumentHeader(file));
}
----

=== Options

Asciidoctor supports numerous options, such as:

+in_place+::
  Renders the output to a file adjacent to the input file.

+template_dir+::
  Specifies a directory of https://github.com/rtomayko/tilt[Tilt]-compatible templates to be used instead of the default built-in templates

+attributes+::
  A Hash (key-value pairs) of attributes to configure various aspects of the AsciiDoc processor

The second parameter of the +render+ method is +java.util.Map+.
The options listed above can be set in +java.util.Map+.

[source]
.Using the +in_place+ option and the +backend+ attribute
----
Map<String, Object> attributes = new HashMap<String, Object>();
attributes.put("backend", "docbook"); <1>

Map<String, Object> options = new HashMap<String, Object>();
options.put("attributes", attributes); <2>
options.put("in_place", true); <3>

String rendered = asciidoctor.renderFile(new File("sample.adoc"), options);
----
<1> Defines the +backend+ attribute as +docbook+ in the attributes map
<2> Registers the attributes map as the +attributes+ option in the options map
<3> Defines the +in_place+ option in the options map

Another way for setting options is by using +org.asciidoctor.Options+ class.
+Options+ is a simple Java class which contains methods for setting required options.
Note that related with +org.asciidoctor.Options+ class, there is +org.asciidoctor.Attributes+ class, which can be used for setting attributes.

+render+ method is overloaded so +org.asciidoctor.Options+ can be passed instead of a +java.util.Map+.

[source]
.Using the +in_place+ option and the +backend+ attribute
----
Attributes attributes = new Attributes();
attributes.setBackend("docbook"); <1>

Options options = new Options();
options.setAttributes(attributes); <2>
options.setInPlace(true); <3>

String rendered = asciidoctor.renderFile(new File("sample.adoc"), options);
----
<1> Defines the +backend+ attribute as +docbook+ in the attributes class
<2> Registers the attributes class as the +attributes+ option in the options class
<3> Defines the +in_place+ option in the options class

The Asciidoctor Java integration also provides two builder classes to create these maps and classes in a more readable form.

+AttributesBuilder+::
  Used to define attributes with a fluent API

+OptionsBuilder+::
  Used to define options with a fluent API

The code below results in the same output as the previous example but uses the builder classes.

[source]
.Setting attributes and options with the builder classes
----
import static org.asciidoctor.AttributesBuilder.attributes;
import static org.asciidoctor.OptionsBuilder.options;

//...
Map<String, Object> attributes = attributes().backend("docbook") <1>
                                             .asMap();

Map<String, Object> options = options().inPlace(true)
                                       .attributes(attributes) <2>
                                       .asMap(); <3>

String rendered = asciidoctor.renderFile(new File("sample.adoc"), options);
----
<1> Defines the +backend+ attribute as +docbook+ using fluent API.
<2> Registers the attributes map as +attributes+.
<3> Converts options to +java.util.Map+ instance.

[source]
.Setting attributes and options with the builder classes
----
import static org.asciidoctor.AttributesBuilder.attributes;
import static org.asciidoctor.OptionsBuilder.options;

//...
Attributes attributes = attributes().backend("docbook").get(); <1>
Options options = options().inPlace(true).attributes(attributes).get(); <2>

String rendered = asciidoctor.renderFile(new File("sample.adoc"), options); <3>
----
<1> Defines and returns an +Attributes+ class instead of +java.util.Map+ by calling +get()+ method instead of +asMap()+.
<2> Defines and returns an +Options+ class instead of +java.util.Map+ by calling +get()+ method instead of +asMap()+.
<3> Renders the document passing +Options+ class.

TIP: All methods used to render content are overloaded with +OptionsBuilder+ parameter, so it is no longer required to call +get+ nor +asMap+ methods.

WARNING: +icons+ attribute requires a +String+ to set the value used to "draw" icons.
At this time, you can use two constants +org.asciidoctor.Attributes.ORIGINAL_ADMONITION_ICONS_WITH_IMG+ for using the same approach as AsciiDoc, that is using +img+ tags, or org.asciidoctor.Attributes.FONTAWESOME_ADMONITION_ICONS for using icons from http://fortawesome.github.io/Font-Awesome[Font Awesome^].

From Asciidoctor 0.1.3, attributes can be specified as +String+ or +Array+ instead of pair key/value by using +org.asciidoctor.Attributes.setAttributes(String)+ or `org.asciidoctor.Attributes.setAttributes(String...)` and +AttributesBuilder+ methods.

[source]
.Passing attributes as a String
----
//...
Attributes attributes = attributes().attributes("toc numbered").get();
Options options = options().attributes(attributes).get();
----

is equivalent to:

[source]
.Passing individual attributes
----
//...
Attributes attributes = attributes().tableOfContents(true).sectionNumbers(true).get();
Options options = options().attributes(attributes).get();
----

You can also use an Array:

[source]
.Passing attributes as an Array
----
//...
String[] attributesArray = new String[]{"toc", "source-highlighter=coderay"};
Attributes attributes = attributes().attributes(attributesArray).sectionNumbers(true).get();
Options options = options().attributes(attributes).get();
----

is equivalent to:

[source]
.Passing individual attributes
----
//...
Attributes attributes = attributes().tableOfContents(true).sectionNumbers(true).sourceHighlighter("coderay").get();
Options options = options().attributes(attributes).get();
----

=== Utilities

A utility class +AsciiDocDirectoryWalker+ is available for searching the AsciiDoc files present in a root folder and its subfolders.
+AsciiDocDirectoryWalker+ locates all files that end with +.asc+, +.asciidoc+, +.ad+ or +.adoc+.

[source]
.Locating AsciiDoc files with +AsciiDocDirectoryWalker+
----
import java.util.List;
import org.asciidoctor.AsciiDocDirectoryWalker;

DirectoryWalker directoryWalker = new AsciiDocDirectoryWalker("docs"); <1>
List<File> asciidocFiles = directoryWalker.scan();                     <2>
----
<1> Defines which parent directory is used for searching.
<2> Returns a list of all AsciiDoc files found in root folder and its subfolders.

=== GEM_PATH

By default +asciidoctor-java-integration+ comes with all required gems bundled within the jar.
But in some circumstances like OSGi environments you may require to store gems in an external folder and be loaded by +asciidoctor-java-integration+.
To accomplish this scenario, +create+ method provides a parameter to set folder where gems are present.
Internally +asciidoctor-java-integration+ will set +GEM_PATH+ environment variable to given path.

[source]
.Example of setting GEM_PATH
----
import static org.asciidoctor.Asciidoctor.Factory.create;
import org.asciidoctor.Asciidoctor;

Asciidoctor asciidoctor = create("/my/gem/path"); <1>
----
<1> Creates +Asciidoctor+ instance with given GEM_PATH location.

== Optimization

Sometimes JRuby starts slower than expected versus standard C-based, non-optimizing Ruby.
To improve this start time, JRuby offers flags that can be used to tune JRuby applications.
Several Java flags can also be used in conjunction with or apart from the JRuby flags, in order to improve the start time even more.

// SW: Need examples of JRuby and Java flags being used

For small tasks such as converting an AsciiDoc document, two JRuby flags can improve the start time:

[cols="1m,2", width="50%", {header-nocaption}]
.JRuby flags
|===
|Name |Value

|jruby.compat.version
|RUBY1_9

|jruby.compile.mode
|OFF
|===

Both flags are set by default inside the Asciidoctor Java integration project.

The Java flags available for improving start time depend on whether your working on a 32 or 64 bit processor and your JDK version.
These flags are set by using the +JRUBY_OPTS+ environment variable.
Let's see a summary of these flags and in which environments they can be used.

[cols="1m,2", width="75%", {header-nocaption}]
.Java flags
|===
|Name |JDK

|-client
|32 bits Java

|-Xverify:none
|32/64 bits Java

|-XX:+TieredCompilation
|32/64 bits Java SE 7

|-XX:TieredStopAtLevel=1
|32/64 bits Java SE 7
|===

[source, shell]
.Setting flags for Java SE 6
----
export JRUBY_OPTS="-J-Xverify:none -J-client" <1>
----
<1> Note that you should add +-J+ before the flag.

You can find a full explanation on how to improve the start time of JRuby applications at {jruby-startup-ref}[Improving Startup Time].

== Resources

The Asciidoctor Java integration's source code, including its latest developments and issues, can be found in the project's {repo-ref}[repository].
If you identify an issue while using the Asciidoctor Java integration, please don't hesitate to {issues-ref}[file a bug report].
Also, don't forget to join the {discuss-ref}[Asciidoctor discussion list], where you can ask questions and leave comments.
