= How do I create slides with the deck.js backend?
Alex Soto; Sarah White
:awestruct-layout: base
:toc:
:sectanchors:
:icons: font
:source-highlighter: highlight.js
ifndef::awestruct[]
:idprefix:
:idseparator: -
endif::awestruct[]
// Refs
:backend-git: http://github.com/asciidoctor/asciidoctor-backends
:deckjs-org: http://imakewebthings.com/deck.js
:install-ref: http://asciidoctor.org/docs/install-toolchain/
:install-mac-ref: http://asciidoctor.org/docs/install-asciidoctor-macosx/
:deckjs-zip: https://github.com/imakewebthings/deck.js/zipball/stable
:deckjs-git: https://github.com/imakewebthings/deck.js
:decksplitjs-git: https://github.com/houqp/deck.split.js
:render-ref: http://asciidoctor.org/docs/render-documents
:factory-ref: http://asciidoctor.org/docs/produce-custom-themes-using-asciidoctor-stylesheet-factory
:backend-issue: https://github.com/asciidoctor/asciidoctor-backends/issues
:discuss-ref: http://discuss.asciidoctor.org/

== Deck.js Backend

The {backend-git}[deck.js backend] is a collection of Haml templates that transform a document written with AsciiDoc syntax into HTML5 slides animated by {deckjs-org}[deck.js].

=== Ruby Gem Requirements

The Asciidoctor deck.js backend requires the following gems:

* asciidoctor
* tilt
* haml

To determine what gems are installed on your system, open a terminal window and type:
 
 $ gem list --local

A list of installed gems will be returned.

If you're missing the +asciidoctor+, +tilt+, or +haml+ gems, install them from the command-line with +gem install+.

 $ gem install asciidoctor tilt haml

To learn more about installing the Asciidoctor toolchain, read the {install-ref}[Installing the Toolchain] or {install-mac-ref}[Installing Asciidoctor on Mac OS X] guides.

=== Backend and Deck.js Installation

. Download or +git clone+ the {backend-git}[Asciidoctor backends] repository.

 $ git clone git://github.com/asciidoctor/asciidoctor-backends.git

. Create a directory named +deck.js+ inside your working directory (i.e. where your AsciiDoc document resides).

. {deckjs-zip}[Download] and extract the deck.js archive or +git clone+ the {deckjs-git}[deck.js] repository into the +deck.js+ directory you created in step 2.

 $ git clone git://github.com/imakewebthings/deck.js.git

. If you plan to split your slides, {decksplitjs-git}[download the +deck.split.js+ extension] and copy it into the +deck.js/extensions+ directory.

. If you want to use the fullscreen photo feature, create an +images+ directory in your working directory.

=== Document Attributes

There are a number of document attributes specific to the +deckjs+ backend.

.+deckjs+ backend document attributes
[cols="2,1,2m",options="header"]
|===
|Attribute |Description |Example

|:backend: <backend name>
|Sets the custom backend used to render the document
|:backend: deckjs

|:deckjs_theme: <theme>
|Sets the deck.js theme to neon, swiss or web-2.0
|:deckjs_theme: web-2.0

|:deckjs_transition: <type>
|Sets the transition style to horizontal-slide, vertical-slide or fade
|:deckjs_transition: fade

|:customjs: <javascript location>
|Sets a custom javascript file; can be used as a deck.js custom configuration
|:customjs: <javascript location>

|:customcss: <css location>
|Sets a custom css file
|:customcss: <css location>

|:menu:
|Toggle to and from a grid layout overview of all the slides by pressing the +m+ key
|:menu:

|:navigation:
|Renders clickable previous and next navigation icons on the slides
|:navigation:

|:status:
|Renders the current slide number and total number of slides
|:status:

|:split:
|Registers the split module for use in the document
|:split:
|===

NOTE: You can also specify a custom stylesheet using the +stylesheet+ attribute, which customizes AsciiDoc elements like section, paragraph, images, etc.
Learn more about the +stylesheet+ attribute in the {factory-ref}[How do I use the Asciidoctor stylesheet factory to produce custom themes?] guide.

The attributes described in the table above are set in the header of your document.

.Header with +deckjs+ backend attributes
....
= Presentation Title
Presenter Name
:backend: deckjs
:deckjs_theme: web-2.0
:deckjs_transition: horizontal-slide
:navigation:
....

=== Slide Syntax Examples

Structuring a slideshow and writing the slide content uses the same syntax as a typical AsciiDoc document, with a few added features.

Let's see some examples of the +deckjs+ backend features:

.Slide titles and background images
----
= Title of Presentation <1>
Presenter Name
:backend: deckjs
:deckjs_transition: fade
:navigation:

== Title of Slide One <2>

This is the first slide after the title slide.

[canvas-image="images/example.jpg"] <3>
== Slide Two's Title will not be displayed <4>

[role="canvas-caption", position="center-up"] <5>
This text is displayed on top of the example.jpg image.
----
<1> The presentation title and author's name will be displayed on the title slide.
<2> Each new slide is designated by a level 1 section title (`==`).
<3> The +canvas-image+ attribute embeds a fullscreen image as a slide background. Position the attribute above the title of the slide you want the image applied to.
<4> When the +canvas-image+ attribute is applied to a slide, that slide's title will not be displayed.
<5> +canvas-caption+ applies a colored box around the caption text. +position+ specifies the location of the caption block (bottom-left, top-left, bottom-right, top-right, center-up, center-down)

.Stepped paragraphs, lists, and blocks
----
== Stepped paragraphs

[options="step"]
This paragraph is displayed first.

[options="step"]
Then this paragraph is displayed when the _Next_ arrow is clicked.

== Stepped list items

[options="step"]
* A bullet is displayed each time the _Next_ arrow is clicked.
* B
* C

== Stepped blocks

[options="step"]
----
Block one
----

[options="step"]
----
Block two
----
----

The +step+ option reveals each paragraph, bullet, etc. separately each time you click the _Next_ arrow.

WARNING: The original AsciiDoc +deckjs+ backend for the AsciiDoc processor used the option +incremental+ instead of +step+. 
We've changed it to +step+ in order to save you some typing.

.Split
----
= Presentation Title
Presenter Name
:backend: deckjs
:split: <1>

== This Slide is Split

This Slide will act like

<<< <2>

three individual slides with the same title

<<<

once the document is rendered.
----
<1> To create multiple, consecutive slides with the same title, set the +split+ attribute in the document header.
<2> Then, within a slide, insert `<<<` to specify the slide breaks.

=== Rendering

To render your presentation as HTML5, execute the command:

 $ asciidoctor -T ../asciidoctor-backends/haml presentation.adoc

. The command +-T+ (+--template-dir+) tells the Asciidoctor processor to override the built-in backends.
. Directly after +-T+ is the path to where you saved or cloned the Asciidoctor backends repository containing the +deckjs+ backend (step 1 under the <<backend-and-deckjs-installation,installation section>>).  

Further information about rendering documents with Asciidoctor is available in the {render-ref}[How do I render a document?] guide.

== Stay Connected

If you encounter a bug or need additional deck.js features ported to Asciidoctor's +deckjs+ backend, visit the {backend-issue}[Asciidoctor issue tracker] and file an issue.

If you have questions or would like to help develop this project, please join the {discuss-ref}[Asciidoctor discussion list].
