= Installing and Using the Asciidoctor Maven Plugin
Jason Porter
:awestruct-layout: base
:mavenreporef: http://github.com/asciidoctor/asciidoctor-maven-plugin
:asciidocref: http://asciidoc.org
:maven: http://maven.apache.org
:docref: link:/docs
:java-int-ref: {docref}/install-and-use-java-integration
:query-ref: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.asciidoctor%22%20AND%20a%3A%22asciidoctor-maven-plugin%22
:detail-0-1-1-1-ref: http://search.maven.org/#artifactdetails%7Corg.asciidoctor%7Casciidoctor-maven-plugin%7C0.1.1.1%7Cmaven-plugin
:detail-0-1-2-ref: http://search.maven.org/#artifactdetails%7Corg.asciidoctor%7Casciidoctor-maven-plugin%7C0.1.2%7Cmaven-plugin
:get-0-1-1-1-ref: http://search.maven.org/remotecontent?filepath=org/asciidoctor/asciidoctor-maven-plugin/0.1.1.1/asciidoctor-maven-plugin-0.1.1.1
:get-0-1-2-ref: http://search.maven.org/remotecontent?filepath=org/asciidoctor/asciidoctor-maven-plugin/0.1.2/asciidoctor-maven-plugin-0.1.2
:hackmavenref: {docref}/hack-asciidoctor-maven-plugin
:mavenpluginissue: http://github.com/asciidoctor/asciidoctor-maven-plugin/issues
:mailinglist: http://discuss.asciidoctor.org

The {mavenreporef}[Asciidoctor Maven plugin] is the official means of using Asciidoctor to render all your {asciidocref}[AsciiDoc] documentation using {maven}[Apache Maven].

This plugin depends on the {java-int-ref}Asciidoctor Java integration] library.
If you want to learn more about the library, read the {java-int-ref}[How to Install and Use the Asciidoctor Java Integration guide].
Both versions of the plugin have been migrated to Asciidoctor Java integration 0.1.2, and thus support all the options exposed through that library.

.Plugin artifact information
[cols="4", options="header", caption=""]
|===
|Group ID
|Artifact ID
|Latest versions
|Download

|org.asciidoctor
|{query-ref}[asciidoctor-maven-plugin]
|{detail-0-1-2-ref}[0.1.2]
|{get-0-1-2-ref}.pom[pom] {get-0-1-2-ref}.jar[jar]

|org.asciidoctor
|{query-ref}[asciidoctor-maven-plugin]
|{detail-0-1-1-1-ref}[0.1.1.1]
|{get-0-1-1-1-ref}.pom[pom] {get-0-1-1-1-ref}.jar[jar]
|===

Upgrading to 0.1.2 (recommended)is simple.
Just update the version in your Maven POM and all the necessary dependencies should be pulled in via Maven.

== Installation

As this is a typical Maven plugin, there isn't much to do to use it, simply add it to your plugins section in your pom:

[source,xml]
.Plugin declaration
----
...
<plugins>
  <plugin>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-plugin</artifactId>
    <version>${asciidoctor.version}</version>                   <1>
    ...
  </plugin>
</plugins>
...
----

<1> This plugin tracks the version of Asciidoctor, so you can use which ever version of Asciidoctor you prefer.

== Usage

[source,xml]
.Execution setup
----
...
  <plugin>
    ...
    <executions>
      <execution>
        <id>output-html</id>                                    <1>
        <phase>generate-resources</phase>                       <2>
        <goals>
          <goal>process-asciidoc</goal>                         <3>
        </goals>
      </execution>
    </executions>
    ...
  </plugin>
...
----

<1> This is simply an unique id for the execution.
<2> The Asciidoctor Maven plugin does not run in a specific phase, so one must be specified.
<3> The (only for the moment) Asciidoctor Maven plugin goal.

=== Configuration options

Currently there are only three configuration options that the Asciidoctor Maven plugin uses:

// This is more than 3 or these aren't all configuration options

* sourceDirectory -- defaults to `${basedir}/src/main/asciidoc`
* outputDirectory -- defaults to `${project.build.directory}/generated-docs`
* backend -- defaults to `docbook`
* doctype -- defaults to `article`
* attributes -- a Map<String,String> of attributes to pass to Asciidoctor, defaults to `null`

More will be added in the future to take advantage of other Asciidoctor options and attributes.
These settings can all be changed in the `<configuration>` section of the plugin section:

[source,xml]
.Plugin configuration options
----
<plugin>
  ...
    </executions>
    <configuration>
      <sourceDirectory>src/main/doc</sourceDirectory>      
      <outputDirectory>target/docs</outputDirectory>
      <backend>html</backend>
      <doctype>book</doctype>
      <attributes>
        <stylesheet>my-theme.css</stylesheet>
      </attributes>
    </configuration>
    ...
</plugin>
...
----

== Resources and Help

If you're interested in modifying or impoving this plugin, checkout the {hackmavenref}[Hacking on the Asciidoctor Maven plugin guide].
To file an issue regarding this plugin, visit the {mavenpluginissue}[plugin's repository].

Also, don't forget to join the {mailinglist}[Asciidoctor mailing list], where you can ask questions and leave comments.


