= Installing the Toolchain
Dan Allen
:keywords: AsciiDoc, Asciidoctor, install, upgrade
:awestruct-layout: base
:toc:
:icons: font
:source-highlighter: coderay
:includedir: _includes
:fopdf-ref: https://github.com/mojavelinux/asciidoctor-fopd
:fopdf-doc-ref: https://github.com/mojavelinux/asciidoctor-fopdf/blob/master/README.adoc
:fedora-docs: http://docs.fedoraproject.org
:docref: link:/docs
:asciidoc-edit-ref: http://asciidoc.org/#_editor_support
:editing-ref: {docref}/editing-asciidoc-with-live-preview
:quick-ref: {docref}/asciidoc-syntax-quick-reference
:user-ref: {docref}/user-manual
:render-ref: {docref}/render-documents
:build-ref: http://github.com/asciidoctor/asciidoctor-stylesheet-factory/blob/master/README.adoc
:mailinglist: http://discuss.asciidoctor.org

// Bruce Wolfe bwolfe@redhat.com 2013-04-26 Issue #284 - Asciidoctor update instructions

// A new introduction that introduces and ties together all the elements in the chain (installing gem, text editors, previewer) needs to be created eventually.

Asciidoctor, an implementation of the AsciiDoc processor written in Ruby, is a drop-in replacement for AsciiDoc in most cases.
Asciidoctor provides a command line tool and a Ruby API for converting AsciiDoc documents to HTML 5, Docbook 5.0, DocBook 4.5 and custom output formats.

NOTE: To convert your document to PDF, you'll need to use the {fopdf-ref}[Asciidoctor fopdf extension].
Directions for using the extension are documented in its {fopdf-doc-ref}[README].

include::{includedir}/install-upgrade-asciidoctor.adoc[]

== Text editors and syntax highlighting

include::{includedir}/text-editor.adoc[]

Open up your favorite text editor and get ready to write some AsciiDoc!

== Next steps and help

Now that you have installed Asciidoctor, you may want to learn more about the AsciiDoc syntax and the growing variety of integrations, backends, and customizations the Asciidoctor project is developing.

Need an overview of the AsciiDoc syntax?

* {quick-ref}[AsciiDoc Quick Reference]

Want to dive deep into the details of the syntax?

* {user-ref}[Asciidoctor User's Manual]

Are you ready to convert your AsciiDoc document into HTML, DocBook or PDF?

* {render-ref}[How do I render my document]?

Interested in building a theme from the Asciidoctor Stylesheet Factory or applying a custom stylesheet?

* {build-ref}[How do I create and build and a theme]?

Additional guides are listed on the {docref}[Documentation] page.
Also, don't forget to join the {mailinglist}[Asciidoctor mailing list], where you can ask questions and leave comments.


