= Installing and Using the Asciidoctor Java Integration
Alex Soto
2013-04-28
:revdate:
:awestruct-layout: base
:toc:
:asciidocref: http://asciidoc.org/README.html
:javaintref: http://github.com/asciidoctor/asciidoctor-java-integration
:query-ref: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.asciidoctor%22%20AND%20a%3A%22asciidoctor-java-integration%22
:detail-0-1-2-ref: http://search.maven.org/#artifactdetails%7Corg.asciidoctor%7Casciidoctor-java-integration%7C0.1.2%7Cjar
:get-0-1-2-ref: http://search.maven.org/remotecontent?filepath=org/asciidoctor/asciidoctor-java-integration/0.1.2/asciidoctor-java-integration-0.1.2
:detail-0-1-1-ref: http://search.maven.org/#artifactdetails%7Corg.asciidoctor%7Casciidoctor-java-integration%7C0.1.1%7Cjar
:get-0-1-1-ref: http://search.maven.org/remotecontent?filepath=org/asciidoctor/asciidoctor-java-integration/0.1.1/asciidoctor-java-integration-0.1.1
:docref: link:/docs
:mavenguideref: {docref}/install-and-use-asciidoctor-maven-plugin
:gradleguideref: {docref}/install-and-use-asciidoctor-gradle-plugin
:javaintissue: https://github.com/asciidoctor/asciidoctor-java-integration/issues
:mailinglist: http://discuss.asciidoctor.org

The {javaintref}[Asciidoctor Java integration] is the official means of using Asciidoctor to render all your {asciidocref}[AsciiDoc] documentation using Java instead of Ruby.

// Need a smooth transition between artifact info and installation section

The releases below are based on Asciidoctor 0.1.2 and 0.1.1, respectively.

.Asciidoctor Java integration artifact information
[cols="4", options="header", caption=""]
|===
|Group ID
|Artifact ID
|Version
|Download

|org.asciidoctor
|{query-ref}[asciidoctor-java-integration]
|{detail-0-1-2-ref}[0.1.2]
|{get-0-1-2-ref}.pom[pom] {get-0-1-2-ref}.jar[jar] {get-0-1-2-ref}-javadoc.jar[javadoc.jar] {get-0-1-2-ref}-sources.jar[sources.jar]

|org.asciidoctor
|{query-ref}[asciidoctor-java-plugin]
|{detail-0-1-1-ref}[0.1.1]
|{get-0-1-1-ref}.pom[pom] {get-0-1-1ref}.jar[jar] {get-0-1-1-ref}-javadoc.jar[javadoc.jar] {get-0-1-1-ref}-sources.jar[sources.jar]
|===

== Installation

Since the Asciidoctor Java integration is a standard +.jar+ file, the only thing you should do is add the library into classpath.

// Need functional tests for a java maven project and a java gradle project
// Need to field test

[source, xml]
.Dependency declaration in Maven
----
...
<dependencies>
  <dependency>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-java-integration</artifactId>
    <version>${asciidoctor.version}</version>                   <1>
    ...
  </dependency>
</dependencies>
...
----

// If transitive is false, JRuby will not be pulled in? So then you might need more than just the library?

[source, groovy]
.Dependency declaration in Gradle
----
...
dependencies {
	compile('org.asciidoctor:asciidoctor-java-integration:${asciidoctor.version}') {  <1>
		transitive = false
	}
}
...
----

<1> As this library tracks the version of Asciidoctor, you can use which ever version of Asciidoctor you prefer.

You can learn more about the Asciidoctor Maven plugin in {mavenguideref}[How to Install and Use the Asciidoctor Maven Plugin] and the Asciidoctor Gradle plugin in {gradleguideref}[How to Install and Use the Asciidoctor Gradle Plugin].

== Usage

The main entry point for the Asciidoctor Java integration is the +Asciidoctor+ Java interface. 
This interface provides two methods for rendering AsciiDoc content, +render+ and +renderFile+. 
Both of these methods return a string with rendered content.

.Method descriptions
[cols="1,2" options="header"]
|===
|Name
|Description

|+render+
|Parse the AsciiDoc content into a document and render it to the specified backend format.

|+renderFile+
|Parse an AsciiDoc file into a document and render it to the specified backend format.
|===

// It seems that the instance of the Asciidoctor interface needs to be created prior to the render methods being used?

Additionally, a +factory+ method is provided to create an instance of the +Asciidoctor+ interface.

[source, java]
.Creation of Asciidoctor interface
----
import static org.asciidoctor.Asciidoctor.Factory.create;
import org.asciidoctor.Asciidoctor;
...
Asciidoctor asciidoctor = create();
...
----

Now you can call the +render+ method that best suits your needs.
Use +render+ to render a string.

[source, java]
.Rendering a string
----
...
String rendered = asciidoctor.render("*This* is it.", Collections.EMPTY_MAP);
System.out.println(rendered);
...
---- 

+renderFile+ will render the content of an AsciiDoc file.

[source, java]
.Rendering a file
----
...
String rendered = asciidoctor.renderFile(new File("target/test-classes/rendersample.asciidoc"), Collections.EMPTY_MAP);
System.out.println(rendered);
...
----

Another method provided by the +Asciidoctor+ interface is +renderDirectory+. 
This method renders all of the files with AsciiDoc extensions (+_.asc_+,+ _.asciidoc_+,+ _.ad_+ or +_.adoc_+) that are present within a specified folder and its subfolders.

If the rendered content is not written into files, +renderDirectory+ will return an array listing all the documents rendered.

// Maybe provide an example of this array output?

[source, java]
.Rendering all the files in a directory
----
...
String[] allRenderedFiles = asciidoctor.renderDirectory(new File("target/test-classes/src"), new HashMap<String, Object>());

for(String renderedFile:allRenderedFiles) {
	System.out.println(renderedFile);
}
...
----

Another way to render AsciiDoc content is by calling the +render+ method and providing a standard Java +Reader+ and +Writer+. 
The +Reader+ interface is used as the source, and the rendered content is written to the +Writer+ interface.

[source, java]
.Rendering content to a +Writer+
----
...
FileReader inputAsciidoctorFile = new FileReader(new File("target/test-classes/rendersample.asciidoc"));
StringWriter rendererWriter = new StringWriter();

asciidoctor.render(inputAsciidoctorFile, rendererWriter, options().asMap());
		
StringBuffer renderedContent = rendererWriter.getBuffer();
assertRenderedFile(renderedContent.toString());
...
----

=== Options

Asciidoctor supports numerous options, such as:

+in_place+:: renders the output inside a file
+template_dir+:: provides a directory of Tilt-compatible templates to be used instead of the default built-in templates
+attributes+:: where you can set the key-value pairs of attributes that will be used within an AsciiDoc document

The second parameter of +render+ methods is +java.util.Map+. 
The options listed above can be set in +java.util.Map+.

.Using the +in_place+ option and the +backend+ attribute
[source, java]
----
Map<String, Object> attributes = new HashMap<String, Object>(); <1>
attributes.put("backend", "docbook"); <2>

Map<String, Object> options = new HashMap<String, Object>(); <3>
options.put("in_place", true); <4>
options.put("attributes", attributes);

String render = asciidoctor.renderFile("target/test-classes/rendersample.asciidoc", options);
----
// Maybe we could add call outs to this example?

<1> A new +HashMap+ was created
<2> The DocBook +backend+ (attribute) was specified 
<3> Another new +HashMap+ was created
<4> to add the the +in_place+ option and additional attributes

The Asciidoctor Java integration also provides two builder classes to create these maps in a more readable form. 

// Need a definition for OptionsBuilder

+AttributesBuilder+:: creates a map with a required attributes set
+OptionsBuilder+:: can be used for options 

The code below results in the same output as the previous example but uses the builder classes.

.Setting attributes and options with the builder classes
[source, java]
----
import static org.asciidoctor.AttributesBuilder.attributes;
import static org.asciidoctor.OptionsBuilder.options;

...

Map<String, Object> attributes = attributes().backend("docbook").asMap();
Map<String, Object> options = options().inPlace(true).attributes(attributes).asMap();

String render = asciidoctor.renderFile("target/test-classes/rendersample.asciidoc", options);

...
----

// Maybe we could add call outs to this example?


=== Utilities

A utility class +AsciiDocDirectoryWalker+ is available for searching the AsciiDoc files present in a root folder and its subfolders. 
+AsciiDocDirectoryWalker+ locates all files that end with +_.asc_+,+ _.asciidoc_+,+ _.ad_+ or +_.adoc_+.

.Locating AsciiDoc files with +AsciiDocDirectoryWalker+
[source, java]
----
DirectoryWalker directoryWalker = new AsciiDocDirectoryWalker("target/test-classes/src");
List<File> asciidocFiles = directoryWalker.scan();
----

// Maybe we could add call outs to this example?


== Optimization

Sometimes JRuby starts slower than expected versus standard C-based, non-optimizing Ruby.
To improve this start time, JRuby offers flags that can be used to tune JRuby applications. 
Several Java flags can also be used in conjunction with or apart from the JRuby flags, in order to improve the start time even more.

// Need examples of JRuby and Java flags being used

For small tasks such as converting an AsciiDoc document, two JRuby flags can improve the start time:

.JRuby flags
[cols="1m,2", options="header"]
|===
|Name
|Value

|jruby.compat.version
|RUBY1_9

|jruby.compile.mode
|OFF
|===

Both flags are set by default inside the Asciidoctor Java integration project.

The Java flags available for improving start time depend on whether your working on a 32 or 64 bit processor and your JDK version.
These flags are set by using the +JRUBY_OPTS+ environment variable. 
Let's see a summary of these flags and in which environments they can be used.

.Java flags
[cols="1m,2", options="header"]
|===
|Name
|JDK

|-client
|32 bits Java

|-Xverify:none
|32/64 bits Java

|-XX:+TieredCompilation
|32/64 bits Java SE 7

|-XX:TieredStopAtLevel=1
|32/64 bits Java SE 7
|===

[source, bash]
.Setting flags for Java SE 6
----
export JRUBY_OPTS="-J-Xverify:none -J-client" <1>
----

<1> Note that you should add +-J+ before the flag.

You can find a full explanation on how to improve the start time of JRuby applications at {https://github.com/jruby/jruby/wiki/Improving-startup-time}[Improving Startup Time]

== Resources and help

The Asciidoctor Java integration's source code, including its latest developments and issues, can be found in the project's {javaintref}[repository].
If you identify an issue while using the Asciidoctor Java integration, please don't hesitate to {javaintissue}[file a bug report]. 
Also, don't forget to join the {mailinglist}[Asciidoctor mailing list], where you can ask questions and leave comments.
