= Installing Asciidoctor on Mac OS X
Dan Allen
:page-layout: documentation
:description: A detailed guide covering Asciidoctor installation on Mac OS X.
:toc:
:toc-placement!:
:idprefix:
:idseparator: -

This document describes, in detail, how to install Asciidoctor on Mac OS X.
Several procedures are presented.
Select the procedure that works best for you.

The safest and most reliable choice is RVM.
If you're already using Homebrew, that might a better choice for you than RVM.
The vanilla (out of the box) procedure is the least recommended, but it may be necessary if you're looking for a quick install or don't want to install XCode.

CAUTION: These installation instructions are mutually exclusive.
You may experience problems if you partially follow one procedure, then try another one.
Make sure you undo any steps you performed in a procedure before attempting another.

toc::[]

== Vanilla procedure

The vanilla procedure uses the Ruby tools that come with Mac OS X out of the box.
It's the simplest approach, but also the least deterministic.
Unless you are determined to take this approach, using RVM or Homebrew is a much better choice.

First, update the version of RubyGems installed on your system. (Highly recommended)

 $ sudo gem update --system

Install Asciidoctor using one of the following two commands.

.System install
 $ sudo gem install asciidoctor -N

or

.User (home directory) install
 $ gem install asciidoctor -N
 $ echo 'export PATH=$PATH:$(find $HOME/.gem/ruby/*/bin -type d)' >> $HOME/.bash_profile
 $ source $HOME/.bash_profile

Verify Asciidoctor is installed and you can execute the +asciidoctor+ command:

 $ asciidoctor -V

If you see the Asciidoctor version information printed in the terminal, then you're ready to start processing documents!

== RVM procedure (recommended)

https://rvm.io[RVM] is a Ruby installation and version manager.
RVM works by installing Ruby inside your home directory and manages the environment variables to allow you to switch between the system-wide Ruby and any Ruby installed using RVM.

To install RVM, you first need to install https://developer.apple.com/xcode[XCode].
XCode is available on the Mac OS X Install DVD.
After installing XCode, perform a software update (&#63743; &#9656; Software Update...).

Install git, using either Homebrew (as described above) or the http://git-scm.com/download/mac[installer for Mac OS X].

Install RVM along with the latest version of Ruby:

 $ \curl -#L https://get.rvm.io | bash -s stable --autolibs=3 --ruby

NOTE: RVM will download and build the Ruby language, install RubyGems along with several essential gems and configure your +PATH+ environment variable.

Source your shell configuration (only necessary in the window you used to install RVM):

 $ source $HOME/.bash_profile

Remove your local Gem configuration, if you have one (or move it out of the way):

 $ rm -f $HOME/.gemrc

Install Asciidoctor:

 $ gem install asciidoctor

Verify Asciidoctor is installed and you can execute the +asciidoctor+ command:

 $ asciidoctor -V

If you see the Asciidoctor version information printed in the terminal, then you're ready to start processing documents!

When using RVM, you can switch between the system-wide Ruby and RVM-managed Ruby using these two commands:

.Switch to system-wide Ruby
 $ rvm use system

.Switch to RVM-managed Ruby

 $ rvm use default

When you switch to the system-wide Ruby, the +asciidoctor+ command will become unavailable (unless you previously installed it into the system).
This gives you the peace of mind that RVM is not interferring with your system.

== Homebrew procedure

http://mxcl.github.io/homebrew[Homebrew] is ``the missing package manager for OS X''.
Homebrew installs the stuff you need that Apple didn't.

Homebrew works by installing packages to their own directory and creates symlinks to those files under [path]'/usr/local'.

// Helpful URL: http://hivelogic.com/articles/compiling-ruby-rubygems-and-rails-on-snow-leopard/

To install and use Homebrew, you must first install https://developer.apple.com/xcode[XCode].
XCode is available on the Mac OS X Install DVD.
After installing XCode, perform a software update (&#63743; &#9656; Software Update...).

Install Homebrew:

 $ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Verify Homebrew is setup correctly:

 $ brew doctor

Install Git and Ruby:

 $ brew install git
 $ brew install ruby

NOTE: RVM will download and build the Ruby language, install RubyGems and setup your +PATH+ environment variable.

Add the location where Homebrew installed Ruby to your +PATH+ environment variable:

// echo 'export PATH=$(brew --prefix ruby)/bin:$PATH' >> $HOME/.bash_profile

 $ echo 'PATH=/usr/local/bin:${PATH/:\/usr\/local\/bin}' >> $HOME/.bash_profile
 $ source $HOME/.bash_profile

Configure RubyGems to install executables into [path]'/usr/local/bin' so they will be available on your executable path:

 $ echo "gem: -N -n /usr/local/bin" >> $HOME/.gemrc

Install Asciidoctor:

 $ gem install asciidoctor

Verify Asciidoctor is installed and you can execute the +asciidoctor+ command:

 $ asciidoctor -V

If you see the Asciidoctor version information in the terminal, then you're ready to start processing documents!

TIP: If you decide to uninstall Homebrew, run https://gist.github.com/1173223[this uninstall script] and remove the line added to [path]'$HOME/.bash_profile'.
