= Produce Custom Themes Using the Asciidoctor Stylesheet Factory
Dan Allen; Sarah White
:page-layout: docs
ifndef::env-site[]
:toc: left
endif::[]
:icons: font
:source-highlighter: coderay
:imagesdir: ../images
:includedir: _includes
:docref: link:/docs
:factory-ref: http://github.com/asciidoctor/asciidoctor-stylesheet-factory
:showcase-ref: http://themes.asciidoctor.org/preview/
:compass-ref: http://compass-style.org
:sass-ref: http://sass-lang.com
:uri-foundation: http://foundation.zurb.com
:get-ruby-ref: http://www.ruby-lang.org/en/downloads
:bundler-ref: http://rubygems.org/gems/bundler
:render-ref: {docref}/render-documents
:quick-ref: {docref}/asciidoc-syntax-quick-reference
:user-ref: {docref}/user-manual
:deckjs-ref: {docref}/install-and-use-deckjs-backend/
:discuss-ref: http://discuss.asciidoctor.org/

The {factory-ref}[Asciidoctor stylesheet factory] is where themes are developed for styling your documents.
Specifically, these stylesheets can be used to quickly customize the look and feel of HTML 5 documents generated by Asciidoctor.

To view the Asciidoctor themes in action, visit the {showcase-ref}[theme showcase].

WARNING: The Asciidoctor stylesheet factory is currently only compatible with Asciidoctor 0.1.2 and greater.

== Setting up the factory

The stylesheets in the Asciidoctor stylesheet factory are built using {compass-ref}[Compass], a CSS authoring framework that uses {sass-ref}[Sass] to generate CSS files.
The styles and components are generated by {uri-foundation}[Foundation 4], an awesome and flexible CSS component framework that ensures your stylesheet is cross-browser and mobile friendly.

=== Install the gems

include::_includes/factory-setup.adoc[tag=gem]

=== Build the stylesheets

To build the stylesheets:

. Navigate to the Asciidoctor stylesheet factory directory on your system.
. Run Compass's `compile` command.

 $ compass compile

The stylesheets are compiled from the Sass source files in the [path]_sass/_ folder and written to the [path]_stylesheets/_ folder.
You can reference the stylesheets in [path]_stylesheets/_ from your HTML file.

== Applying a stylesheet to HTML

Let's practice applying a stylesheet to a simple AsciiDoc file.
If you're unfamiliar with the general commands needed to render and style a document created with the AsciiDoc syntax, you may want to review the {render-ref}[How Do I Render My Document guide] before proceeding.

. Create an AsciiDoc file like the one below.
. Save the file as [path]_mysample.adoc_.

// end

[source, asciidoc]
----
= Introduction to AsciiDoc
Doc Writer <doc@example.com>

A preface about http://asciidoc.org[AsciiDoc].

== First Section

* item 1
* item 2

[source,ruby]
puts "Hello, World!"
----

Next, you'll use the Asciidoctor processor to generate HTML and apply a stylesheet to it from the [path]_stylesheets/_ directory.

=== Generate an HTML document

Now it's time to pick the stylesheet you want to apply to your content when it is rendered.
In your file browser, navigate to the [path]_stylesheets/_ directory.
Or, using a console, change to the [path]_stylesheets/_ directory and list the available stylesheets using the `ls` command.

 $ ls

.Console output of `ls` command
....
asciidoctor.css  foundation-lime.css    iconic.css       riak.css
colony.css       foundation-potion.css  maker.css        rubygems.css
foundation.css   golo.css               readthedocs.css
....

Let's apply the [path]_colony.css_ stylesheet to the sample document.

. Navigate to the directory where you saved [path]_mysample.adoc_.
. Call the `asciidoctor` processor.
. Specify the stylesheet you want applied with the `stylesheet` attribute.
. Tell the processor where the specified stylesheet is located with the `stylesdir` attribute.

 $ asciidoctor -a stylesheet=colony.css -a stylesdir=../stylesheets mysample.adoc

Open a browser, navigate to [path]_mysample.html_ and checkout the result!

If you prefer to link the [path]_colony.css_ stylesheet to the generated HTML output, set the `linkcss` attribute when you render the document.

 $ asciidoctor -a linkcss -a stylesheet=colony.css -a stylesdir=../stylesheets mysample.adoc

If you inspect the [path]_mysample.html_ document, you should see that the stylesheet is linked to the rendered document.

 <link rel="stylesheet" href="../stylesheets/colony.css">

.Stylesheet images
****
The Golo, Maker, and Riak themes include image assets.
To apply these themes to your document correctly, the applicable images must be copied into the same directory as the generated output.

For example, to apply the [path]_maker.css_ stylesheet to [path]_mysample.adoc_:

. Copy [path]_body-bh.png_ from the [path]_images/maker/_ directory into the output directory.
. Call the `stylesheet` and `styledir` attributes.

 $ asciidoctor -a stylesheet=maker.css -a stylesdir=../stylesheets mysample.adoc

Navigate to [path]_mysample.html_ in your browser.
The [path]_body-bh.png_ image should add a graph paper-like background to your generated output.
****

=== External preview

You may want to preview sample HTML files on another computer or device.
To do that, you need to serve them through a web server.
You can quickly serve HTML files in the root directory of the project using the following command:

.Using Python
 $ python -m SimpleHTTPServer 4242

or

.Using Ruby >= 1.9.3
 $ ruby -run -e httpd . -p 4242

== Create a custom theme

include::{includedir}/create-theme.adoc[]

== Apply a custom theme

include::{includedir}/apply-theme.adoc[]

Happy theming!

== Resources and help

Now that you have applied a custom theme to your AsciiDoc document, you may want to learn more about the AsciiDoc syntax and the growing variety of integrations, backends, and customizations the Asciidoctor project is developing.

Need an overview of the AsciiDoc syntax?

* {quick-ref}[AsciiDoc Quick Reference]

Want to dive deep into all of Asciidoctor's features?

* {user-ref}[Asciidoctor User's Manual]

Interested in writing your next presentation with Asciidoctor?

* {deckjs-ref}[Create a presentation with the Asciidoctor deck.js backend]

Additional guides are listed on the {docref}[Documentation] page.
Also, don't forget to join the {discuss-ref}[Asciidoctor mailing list], where you can ask questions and leave comments.
