= Produce Custom Themes Using the Asciidoctor Stylesheet Factory
Dan Allen; Sarah White
:awestruct-layout: base
:toc:
:repo-ref: http://github.com/asciidoctor/asciidoctor-stylesheet-factory
:issues-ref: http://github.com/asciidoctor/asciidoctor-stylesheet-factory/issues
:showcase-ref: http://themes.asciidoctor.org/preview/
:asciidoc-ref: http://asciidoc.org
:docs-ref: link:/docs
:toolchain-ref: link:/docs/install-toolchain
:render-ref: link:/docs/render-documents
:compass-ref: http://compass-style.org
:sass-ref: http://sass-lang.com
:foundation-ref: http://foundation.zurb.com
:bundler-ref: http://rubygems.org/gems/bundler
:discuss-ref: http://discuss.asciidoctor.org/
:get-ruby-ref: http://www.ruby-lang.org/en/downloads

The {repo-ref}[Asciidoctor stylesheet factory] is where themes are developed for styling your {asciidoc-ref}[AsciiDoc] documentation.
Specifically, these stylesheets can be used to quickly customize the look and feel of HTML 5 documents generated by Asciidoctor.

To view the Asciidoctor themes in action, visit the {showcase-ref}[theme showcase].

WARNING: The Asciidoctor stylesheet factory is currently only compatible with {toolchain-ref}[Asciidoctor 0.1.2].

toc::[levels=1]

== Setting up the factory

The stylesheets in the Asciidoctor stylesheet factory are built using {compass-ref}[Compass], a CSS authoring framework that uses {sass-ref}[Sass] to generate CSS files.
The styles and components are generated by {foundation-ref}[Foundation 4], an awesome and flexible CSS component framework that ensures your stylesheet is cross-browser and mobile friendly.

=== Install the gems

In order to build the stylesheets, you must download the Asciidoctor stylesheet factory repository and install the Compass and Foundation gems.

. Download or clone the {repo-ref}[Asciidoctor stylesheet factory repository].
+
NOTE: It does not matter where you save the project on your system.
. Make sure you have {get-ruby-ref}[Ruby and RubyGems] installed, and, ideally, {bundler-ref}[Bundler].
. Run Bundler to install the Compass and Foundation gems.

 $ bundle install

+
This +bundle+ command is equivalent to executing:

 $ gem install --version '0.12.2' compass
 $ gem install --version '4.1.1' zurb-foundation

Once you have the gems installed, you can build the stylesheets.

=== Build the stylesheets

To build the stylesheets:

. Navigate to the Asciidoctor stylesheet factory directory on your system. 
. Run Compass's +compile+ command.

 $ compass compile

The stylesheets are compiled from the Sass source files in the [path]'sass/' folder and written to the [path]'stylesheets/' folder.
You can reference the stylesheets in [path]'stylesheets/' from your HTML file.

== Applying a stylesheet to HTML

Let's practice applying a stylesheet to a simple AsciiDoc file.
If you're unfamiliar with the general commands needed to render and style a document created with the AsciiDoc syntax, you may want to review the {render-ref}[How Do I Render My Document guide] before proceeding. 

. Create an AsciiDoc file like the one below.
. Save the file as [path]'sample.adoc'.

// end

[source, asciidoc]
----
= Introduction to AsciiDoc
Doc Writer <doc@example.com>

A preface about http://asciidoc.org[AsciiDoc].

== First Section

* item 1
* item 2

[source,ruby]
puts "Hello, World!"
----

Next, you'll use the Asciidoctor processor to generate HTML and apply a stylesheet to it from the [path]'stylesheets/' directory.

=== Generate an HTML document

Now it's time to pick the stylesheet you want to apply to your content when it is rendered.
In your file browser, navigate to the [path]'stylesheets/' directory.
Or, using a console, change to the [path]'stylesheets/' directory and list the available stylesheets using the +ls+ command.

 $ ls

.Console output of +ls+ command
....
asciidoctor.css  foundation-lime.css    iconic.css       riak.css
colony.css       foundation-potion.css  maker.css        rubygems.css
foundation.css   golo.css               readthedocs.css
....

Let's apply the [path]'colony.css' stylesheet to the sample document.

. Navigate to the directory where you saved [path]'sample.adoc'.
. Call the +asciidoctor+ processor.
. Specify the stylesheet you want applied with the +stylesheet+ attribute.
. Tell the processor where the specified stylesheet is located with the +stylesdir+ attribute.

 $ asciidoctor -a stylesheet=colony.css -a stylesdir=../stylesheets sample.adoc

Open a browser, navigate to [path]'sample.html' and checkout the result!

If you inspect the [path]'sample.html' document, you should see that the stylesheet is linked to the rendered document.

 <link rel="stylesheet" href="../stylesheets/colony.css">

If you prefer to embed the [path]'colony.css' stylesheet into the generated HTML output, unset the +linkcss+ attribute when you render the document.

 $ asciidoctor -a linkcss! -a stylesheet=colony.css -a stylesdir=../stylesheets sample.adoc

IMPORTANT: Unlike in AsciiDoc, Asciidoctor sets +linkcss+ by default.
We believe linking to the stylesheet is more manageable, and it is the accepted practice on the web.

.Stylesheet images
****
The Golo, Maker, and Riak themes include image assets.
To apply these themes to your document correctly, the applicable images must be copied into the same directory as the generated output.

For example, to apply the [path]'maker.css' stylesheet to [path]'sample.adoc':

. Copy [path]'body-bh.png' from the [path]'images/maker/' directory into the output directory.
. Call the +stylesheet+ and +styledir+ attributes.

 $ asciidoctor -a stylesheet=maker.css -a stylesdir=../stylesheets sample.adoc
 
Navigate to [path]'sample.html' in your browser. The [path]'body-bh.png' image should add a graph paper-like background to your generated output.
****

=== External preview

You may want to preview sample HTML files on another computer or device.
To do that, you need to serve them through a web server.
You can quickly serve HTML files in the root directory of the project using the following command:

 $ python -m SimpleHTTPServer 4242

== Create a custom theme

Themes go in the [path]'sass/' folder.
To create a new theme, let's call it +hipster+, start by creating two new files:

[path]'sass/hipster.scss'::
  * Imports the theme settings, which includes default variables and resets
  * Imports the AsciiDoc components
  * Defines any explicit customizations

[path]'sass/settings/_hipster.scss'::
  * Sets variables that customize Foundation 4 and the AsciiDoc CSS components

Here's a minimal version of [path]'sass/hipster.scss':

[source, scss]
----
@import "settings/hipster";
@import "components/asciidoc";
@import "components/awesome-icons";
----

NOTE: You don't have to include the underscore prefix when importing files.

NOTE: The +awesome-icons+ component is only applicable to HTML generated by Asciidoctor >= 0.1.2 with the +icons+ attribute set to +awesome+.

You can add any explicit customizations below the import lines.

The variables you can set in [path]'sass/settings/_hipster.scss' are a combination of the {repo-ref}/blob/master/sass/settings/_settings.scss.dist[Foundation 4 built-in global settings] and {repo-ref}/blob/master/sass/settings/_defaults.scss[global settings and imports for the AsciiDoc components].

Happy theming!

== Resources

Also, don't forget to join the {discuss-ref}[Asciidoctor discussion list], where you can ask questions and leave comments.

To file an issue related to the default Asciidoctor stylesheet (generated by the stylesheet factory), visit the {issues-ref}[Asciidoctor issue tracker].
