= How do I render a document?
Dan Allen; Sarah White
:page-layout: base
:toc:
:icons: font
:source-highlighter: coderay
// refs:
:imagesdir: ../images
:includedir: _includes
:docref: link:/docs
:install-ref: {docref}/install-toolchain
:fopdf-doc-ref: https://github.com/mojavelinux/asciidoctor-fopdf/blob/master/README.adoc
:docbook5-ref: http://www.docbook.org/tdg5/en/html/ch01.html#introduction-whats-new
:yelp-ref: http://live.gnome.org/Yelp
:backends-repo-ref: http://github.com/asciidoctor/asciidoctor-backends
:quick-ref: {docref}/asciidoc-syntax-quick-reference
:user-ref: {docref}/user-manual
:build-ref: {docref}/produce-custom-themes-using-asciidoctor-stylesheet-factory/
:showcase-ref: http://themes.asciidoctor.org/
:deckjs-ref: {docref}/install-and-use-deckjs-backend
:discuss-ref: http://discuss.asciidoctor.org

This guide introduces the Asciidoctor processor and the output formats it produces.
You will learn how to:

- [x] process a document from the CLI and API
- [x] render a document to HTML
- [x] apply the default Asciidoctor CSS theme
- [x] render a document to DocBook 5

NOTE: In order to render your document, you'll need to have Asciidoctor installed.
For step-by-step installation instructions, read the {install-ref}[Installing the Toolchain] guide.

include::{includedir}/process-intro.adoc[]

== Selecting an Output Format

include::{includedir}/output-format.adoc[]

== Rendering a document to HTML

Asciidoctor's default output is HTML.
You can render a document to HTML using the CLI or the Ruby API.

=== Using the command line tool

include::{includedir}/html-command-line.adoc[]

=== Using the Ruby API

include::{includedir}/html-ruby-api.adoc[]

=== Styling the HTML with CSS

include::{includedir}/html-styles.adoc[]

=== Managing images

include::{includedir}/html-manage-images.adoc[]

=== CodeRay and Pygments stylesheets

include::{includedir}/html-code-styles.adoc[]

== Rendering a document to DocBook

Despite the fact that writing in DocBook is inhumane, it's useful as a intermediary format.
And, since the AsciiDoc syntax was designed with DocBook output in mind, the conversion is very good.
There's a corresponding DocBook element for each markup in the AsciiDoc syntax.

Asciidoctor 0.1.4 can produce DocBook 5.0 output, which is generated by the +docbook5+ backend.
The output from the +docbook5+ backend only differs from the +docbook45+ backend so far as to make it compliant to the DocBook 5.0 specification.
A summary of the differences are as follows:

* XSD declarations are used on the document root instead of a DTD
* +<info>+ elements for document info instead of +<articleinfo>+ and +<bookinfo>+
* elements that hold the author's name are wrapped in a +<personname>+ element
* the id for an element is defined using an +xml:id+ attribute
* +<link>+ is used for links instead of +<ulink>+
* the URL for a link is defined using the +xlink:href+ attribute

Refer to {docbook5-ref}[What's new in DocBook v5.0?] for more details about how DocBook 5.0 differs from DocBook 4.5.

To use the DocBook 5.0 backend, set the backend to +docbook5+, as shown in this example:

 $ asciidoctor -b docbook5 sample.adoc

Here's a sample DocBook 5.0 document generated by this backend:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns="http://docbook.org/ns/docbook"
    xmlns:xlink="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
  <info>
    <title>Hello, AsciiDoc!</title>
    <date>2013-09-03</date>
    <author>
      <personname>
        <firstname>Doc</firstname>
        <surname>Writer</surname>
      </personname>
      <email>doc@example.com</email>
    </author>
    <authorinitials>DW</authorinitials>
  </info>
  <simpara>
    An introduction to <link xlink:href="http://asciidoc.org">AsciiDoc</link>.
  </simpara>
  <section xml:id="_first_section">
    <title>First Section</title>
    <itemizedlist>
      <listitem>
        <simpara>item 1</simpara>
      </listitem>
      <listitem>
        <simpara>item 2</simpara>
      </listitem>
    </itemizedlist>
  </section>
</article>
```

[TIP]
====
The +xmlns+ attribute is now added to the root DocBook element by default.
Set the attribute +noxmlns+ to disable this feature.
====

To convert the +mysample.adoc+ document to DocBook format, call the processor with the backend flag set to +docbook5+:

 $> asciidoctor -b docbook5 mysample.adoc

A new XML document, named +mysample.xml+, will now be present in the current directory.

 $> ls
 mysample.adoc  mysample.html  mysample.xml

If you're on Linux, you can view the DocBook file with {yelp-ref}[Yelp].

 $> yelp mysample.xml

Using the Asciidoctor Ruby API, you can generate a DocBook document directly from a Ruby application:

[source,ruby]
----
Asciidoctor.render_file('mysample.adoc', :in_place => true,
    :backend => 'docbook5')
----

== Resources and help

There's really no end to the customization you can apply to the output that the Asciidoctor processor generates.
We've just scratched the surface in this guide.

To learn about the other backends and stylesheets, checkout out the following resources:

* {showcase-ref}[The Asciidoctor Stylesheet Factory showcase]
* {build-ref}[Create and use a custom theme]
* <<user-manual#manpages,Create and render a manpage>>
* Render a document to PDF with the {fopdf-doc-ref}[Asciidoctor fopdf extension]
* {deckjs-ref}[Create a Deck.js presentation]
* {backends-repo-ref}[Asciidoctor's backend repository]

Need an overview of the AsciiDoc syntax?

* {quick-ref}[AsciiDoc Quick Reference]

Want to dive deep into all of Asciidoctor's features?

* {user-ref}[Asciidoctor User's Manual]

Additional guides are listed on the {docref}[Documentation] page.
Also, don't forget to join the {discuss-ref}[Asciidoctor mailing list], where you can ask questions and leave comments.
