= How do I render a document?
Dan Allen; Sarah White
:page-layout: base
:toc:
:icons: font
:source-highlighter: coderay
// refs:
:imagesdir: ../images
:includedir: _includes
:docref: link:/docs
:install-ref: {docref}/install-toolchain
:fopdf-ref: https://github.com/mojavelinux/asciidoctor-fopd
:fopdf-doc-ref: https://github.com/mojavelinux/asciidoctor-fopdf/blob/master/README.adoc
:docbook5-ref: http://www.docbook.org/tdg5/en/html/ch01.html#introduction-whats-new
:yelp: http://live.gnome.org/Yelp
:publican: http://fedorahosted.org/publican
:backends-repo-ref: http://github.com/asciidoctor/asciidoctor-backends
:quick-ref: {docref}/asciidoc-syntax-quick-reference
:user-ref: {docref}/user-manual
:build-ref: {docref}/produce-custom-themes-using-asciidoctor-stylesheet-factory/
:showcase-ref: http://themes.asciidoctor.org/
:discuss-ref: http://discuss.asciidoctor.org

While the AsciiDoc syntax is designed to be human-readable, it's doubtful you'll want to present your finished document as raw AsciiDoc syntax.
That's where the AsciiDoc processors and backends come into play.

In this guide, you learn how to convert a short sample document to the following formats:

* HTML
* DocBook

////
* PDF
////

You'll also discover how to apply the default stylesheet or a custom one to the generated HTML document during processing.

NOTE: In order to render your document, you'll need to have Asciidoctor installed.
For step-by-step installation instructions, read the {install-ref}[Installing the Toolchain] guide.

== Processor and backends overview

The Asciidoctor processor parses a document and translates it into a variety of formats, including HTML, DocBook and PDF.
The processor produces the output format by using a backend that you specify with the +-b+ (+--backend+) command line option.
If no backend is indicated, the processor's default backend (+html5+) is used.

Asciidoctor has three native backends.

+html5+ (or +html+):: HTML 5 markup styled with CSS 3.
This is the default backend in Asciidoctor.
+docbook45+ (or +docbook+):: DocBook XML 4.5 markup.
+docbook5+:: DocBook XML 5.0 markup.

////
The AsciiDoc processor supports numerous backends, including:

+xhtml11+ (or +html+):: XHTML 1.1 markup styled with CSS2.
This is the default backend in AsciiDoc.
+html5+:: HTML 5 markup styled with CSS3.
+docbook45+ (or +docbook+):: DocBook XML 4.5 markup.
+pdf+:: Portable Document Format (PDF).
////

NOTE: To convert your document to PDF, you'll need to use the {fopdf-ref}[Asciidoctor fopdf extension].
Directions for using the extension are documented in its {fopdf-doc-ref}[README].

== Converting a document to HTML

Asciidoctor's default output is HTML.
It provides both a command line tool and a Ruby API for converting AsciiDoc documents to HTML.

=== Using the command line tool

include::{includedir}/html-command-line.adoc[]

=== Using the Ruby API

include::{includedir}/html-ruby-api.adoc[]

=== Styling the HTML with CSS

include::{includedir}/html-styles.adoc[]

=== Managing images

include::{includedir}/html-manage-images.adoc[]

=== CodeRay and Pygments stylesheets

include::{includedir}/html-code-styles.adoc[]

== Converting a document to DocBook

Despite the fact that writing in DocBook is inhumane, it's useful as a intermediary format.
And, since the AsciiDoc syntax was designed with DocBook output in mind, the conversion is very good.
There's a corresponding DocBook element for each markup in the AsciiDoc syntax.

Asciidoctor 0.1.4 can produce DocBook 5.0 output, which is generated by the +docbook5+ backend.
The output from the +docbook5+ backend only differs from the +docbook45+ backend so far as to make it compliant to the DocBook 5.0 specification.
A summary of the differences are as follows:

* XSD declarations are used on the document root instead of a DTD
* +<info>+ elements for document info instead of +<articleinfo>+ and +<bookinfo>+
* elements that hold the author's name are wrapped in a +<personname>+ element
* the id for an element is defined using an +xml:id+ attribute
* +<link>+ is used for links instead of +<ulink>+
* the URL for a link is defined using the +xlink:href+ attribute

Refer to {docbook5-ref}[What's new in DocBook v5.0?] for more details about how DocBook 5.0 differs from DocBook 4.5.

To use the DocBook 5.0 backend, set the backend to +docbook5+, as shown in this example:

 $ asciidoctor -b docbook5 sample.adoc

Here's a sample DocBook 5.0 document generated by this backend:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns="http://docbook.org/ns/docbook"
    xmlns:xlink="http://www.w3.org/1999/xlink" version="5.0" xml:lang="en">
  <info>
    <title>Hello, AsciiDoc!</title>
    <date>2013-09-03</date>
    <author>
      <personname>
        <firstname>Doc</firstname>
        <surname>Writer</surname>
      </personname>
      <email>doc@example.com</email>
    </author>
    <authorinitials>DW</authorinitials>
  </info>
  <simpara>
    An introduction to <link xlink:href="http://asciidoc.org">AsciiDoc</link>.
  </simpara>
  <section xml:id="_first_section">
    <title>First Section</title>
    <itemizedlist>
      <listitem>
        <simpara>item 1</simpara>
      </listitem>
      <listitem>
        <simpara>item 2</simpara>
      </listitem>
    </itemizedlist>
  </section>
</article>
```

[TIP]
====
The +xmlns+ attribute is now added to the root DocBook element by default.
Set the attribute +noxmlns+ to disable this feature.
====

To convert the +mysample.adoc+ document to DocBook format, call the processor with the backend flag set to +docbook5+:

 $> asciidoctor -b docbook5 mysample.adoc

A new XML document, named +mysample.xml+, will now be present in the current directory.

 $> ls
 mysample.adoc  mysample.html  mysample.xml

If you're on Linux, you can view the DocBook file with {yelp}[Yelp].

 $> yelp mysample.xml

Using the Asciidoctor Ruby API, you can generate a DocBook document directly from a Ruby application:

[source,ruby]
----
Asciidoctor.render_file('mysample.adoc', :in_place => true,
    :backend => 'docbook5')
----

DocBook is only an intermediary format in the Asciidoctor toolchain.
You'll either feed it into a system that processes DocBook (like {publican}[publican]), or you can convert it to PDF using the {fopdf-doc-ref}[Asciidoctor fopdf extension].

////
== Converting a document to PDF using +a2x+
:a2x_1-uri: http://asciidoc.org/a2x.1.html
PDF is a nice format for presenting a final version of a document.
For legacy reasons, the conversion to PDF is handled by a separate program in the AsciiDoc distribution, {a2x_1-uri}[+a2x+].

+a2x+ accepts a DocBook file, like the +sample.xml+ file created in the section above, as input and converts it to a PDF.

In your console: 

. Call the +a2x+ program
. Select the output format with +-f+ (+--format+)
. Followed by the format type +pdf+

//^

 $> a2x -f pdf sample.xml

A PDF document, named +sample.pdf+, will now be present in the current directory:

 $> ls
 sample.adoc  sample.html  sample.pdf  sample.xml

You can view the PDF using any PDF viewer.

Rather than converting from AsciiDoc to DocBook and then from DocBook to PDF in two steps, +a2x+ can go directly from AsciiDoc to PDF in a single call:

 $> a2x -f pdf sample.adoc
////

There's really no end to the customization you can apply to the output that the AsciiDoctor processor generates.
We've just scratched the surface here.

== Resources and help

Now that you have rendered your first document with Asciidoctor, you may want to learn more about the AsciiDoc syntax and the growing variety of integrations, backends, and customizations the Asciidoctor project is developing.
Also, there are a number of specialized backends available or under development for Asciidoctor.
More information and the latest available developments can be found in the project's {backends-repo-ref}[backend repository].

Need an overview of the AsciiDoc syntax?

* {quick-ref}[AsciiDoc Quick Reference]

Want to dive deep into all of Asciidoctor's features?

* {user-ref}[Asciidoctor User's Manual]

Interested in using a theme from the Asciidoctor Stylesheet Factory?

* {showcase-ref}[A Showcase of the Asciidoctor Stylesheet Factory themes]
* {build-ref}[How do I create and build and a theme]?

Additional guides are listed on the {docref}[Documentation] page.
Also, don't forget to join the {discuss-ref}[Asciidoctor mailing list], where you can ask questions and leave comments.
