= How do I render a document?
Dan Allen; Sarah White
:page-layout: base
:toc:
:icons: font
:source-highlighter: coderay
// refs:
:install-toolchain-uri: link:/docs/install-toolchain
:stylefactory-readme-uri: http://github.com/asciidoctor/asciidoctor-stylesheet-factory/blob/master/README.adoc
:stylefactory-repo-uri: http://github.com/asciidoctor/asciidoctor-stylesheet-factory
:theme-showcase-uri: http://themes.asciidoctor.org/
:theme-guide-uri: http://github.com/asciidoctor/asciidoctor-stylesheet-factory/blob/master/README.adoc#create-a-new-theme
:yelp-uri: http://live.gnome.org/Yelp
:publican-ref: http://fedorahosted.org/publican
:a2x_1-uri: http://asciidoc.org/a2x.1.html
:backends-repo-uri: http://github.com/asciidoctor/asciidoctor-backends
:backends-issues-uri: http://github.com/asciidoctor/asciidoctor-backends/issues
:discuss-uri: http://discuss.asciidoctor.org
:userguide-uri: http://asciidoc.org/userguide.html
:fopdf-ref: https://github.com/mojavelinux/asciidoctor-fopd
:fopdf-doc-ref: https://github.com/mojavelinux/asciidoctor-fopdf/blob/master/README.adoc

While the AsciiDoc syntax is designed to be human-readable, it's doubtful you'll want to present your finished document as raw AsciiDoc syntax.
That's where the AsciiDoc processors and backends come into play.

In this guide, you learn how to convert a short sample document to the following formats:

* HTML
* DocBook

////
* PDF
////

You'll also discover how to apply the default stylesheet or a custom one to the generated HTML document during processing.

NOTE: In order to render your document, you'll need to have Asciidoctor installed.
For step-by-step installation instructions, read the {install-toolchain-uri}[Installing the Toolchain] guide.

== Processor and backends overview

The Asciidoctor processor parses a document and translates it into a variety of formats, including HTML, DocBook and PDF.
The processor produces the output format by using a backend that you specify with the +-b+ (+--backend+) command line option.
If no backend is indicated, the processor's default backend is used.

Asciidoctor has three native backends.

+html5+ (or +html+):: HTML 5 markup styled with CSS 3.
This is the default backend in Asciidoctor.
+docbook45+ (or +docbook+):: DocBook XML 4.5 markup.
+docbook5+:: DocBook XML 5.0 markup.

////
The AsciiDoc processor supports numerous backends, including:

+xhtml11+ (or +html+):: XHTML 1.1 markup styled with CSS2.
This is the default backend in AsciiDoc.
+html5+:: HTML 5 markup styled with CSS3.
+docbook45+ (or +docbook+):: DocBook XML 4.5 markup.
+pdf+:: Portable Document Format (PDF).
////

NOTE: To convert your document to PDF, you'll need to use the {fopdf-ref}[Asciidoctor fopdf extension].
Directions for using the extension are documented in its {fopdf-doc-ref}[README].A native PDF backend is planned for Asciidoctor.

== Converting a document to HTML

Asciidoctor provides both a command line tool and a Ruby API for converting AsciiDoc documents to HTML.

=== Using the command line tool

In this section, we'll create a sample document, then render and style it with Asciidoctor and the +html5+ backend.

. Create an AsciiDoc file like the one below
. Save the file as +sample.adoc+

----
 = Introduction to AsciiDoc
 Doc Writer <doc@example.com>

 A preface about http://asciidoc.org[AsciiDoc].

 == First Section

 * item 1
 * item 2

 [source,ruby]
 puts "Hello, World!"
----

To convert +sample.adoc+ to HTML from the command-line:

. Open a console
. Switch to the directory that contains the +sample.adoc+ document
. Call the Asciidoctor processor with the +asciidoctor+ command, followed by the name of the document you want to render

//^

 $> asciidoctor sample.adoc

Remember, Asciidoctor's default backend is +html5+, and therefore it isn't necessary to specify it with the +-b+ command.

You won't see any messages printed to the console.
If you type +ls+ or view the directory in a file manager, there is a new file named +sample.html+.

 $> ls
 sample.adoc  sample.html

Asciidoctor derives the name of the output document from the name of the input document.

=== Using the Ruby API

// TODO: expand this section 

Asciidoctor also includes a Ruby API that lets you generate an HTML document directly from a Ruby application.

[source,ruby]
----
require 'asciidoctor'

Asciidoctor.render_file('sample.adoc', :in_place => true)
----

Alternatively, you can capture the HTML output in a variable instead of writing it to a file.

[source,ruby]
----
html = Asciidoctor.render_file('sample.adoc', :header_footer => true)
puts html
----

=== Styles and attributes

Asciidoctor uses CSS to style the generated HTML document.
To help your documents look share, Asciidoctor ships with a fresh, modern stylesheet named +asciidoctor.css+.

=== Working with the default stylesheet

When you generate an HTML document using the (default) +html5+ backend, the +asciidoctor.css+ stylesheet is embedded into the document by default.

 $> asciidoctor sample.adoc

Just browse to +sample.html+ in your browser and checkout the result!

TIP: If you specify a custom stylesheet using the +stylesheet+ attribute, Asciidoctor will embed the custom stylesheet instead of the default stylesheet.

If you prefer to link to the +asciidoctor.css+ stylesheet, set the +linkcss+ attribute:

 $> asciidoctor -a linkcss sample.adoc

When the +linkcss+ attribute is set, Asciidoctor will automatically copy the stylesheet to the output directory.
If the +stylesdir+ attribute is set, then the stylesheet will be copied to the folder specified by +stylesdir+ relative to the output directory.

If you don't want Asciidoctor to copy the stylesheet to the output directory, unset the +copycss+ attribute:

 $> asciidoctor -a linkcss -a copycss! sample.adoc

NOTE: As of version 0.1.4, Asciidoctor does not copy the custom stylesheet to the output directory.

If you unset the stylesheet attribute, Asciidoctor will generate HTML without any styles:

 $> asciidoctor -a stylesheet! sample.adoc

=== Applying a custom stylesheet

One of Asciidoctor's strengths is the ease in which you can swap the default stylesheet for your own custom stylesheet or alternative Asciidoctor themes.

To view the Asciidoctor themes in action, visit the {theme-showcase-uri}[theme showcase].
For information on using the stylesheets in the Asciidoctor Stylesheet Factory, read the {stylefactory-readme-uri}[Building the Asciidoctor Factory Themes guide] or explore the {stylefactory-repo-uri}[Factory's repository].

If you want to apply your own stylesheet to the rendered HTML:

. Save it in the same directory as +sample.adoc+
. Call the +asciidoctor+ processor
. Add the +stylesheet+ attribute with +-a+ (+--attribute+)
. Include the stylesheet file's name

//^

 $> asciidoctor -a stylesheet=mystyles.css sample.adoc

By default, Asciidoctor embeds the custom stylesheet into the generated HTML document.
If you want Asciidoctor to link to the custom stylesheet instead, set the +linkcss+ attribute:

 $> asciidoctor -a stylesheet=mystyles.css -a linkcss sample.adoc

Stylesheets can be stored in a nested folder.
In this case, you need to tell Asciidoctor where to look for them using the +stylesdir+ attribute.

 $> asciidoctor -a stylesdir=./stylesheets -a stylesheet=mystyles.css sample.adoc

TIP: The {theme-guide-uri}[Custom Theme guide] provides detailed steps for using your custom stylesheet with Asciidoctor.

A stable of attributes are also available to add feature and style customizations to the rendered HTML.

// TODO: expand this section 

For example, you can activate syntax highlighting options in the code with this argument:

 -a source-highlighter=highlightjs 

If you have image references in your document, you'll have to move those with the output document.
Or, by passing the +data-uri+ attribute to the processor, you can embed the images into the document.

 $> asciidoctor -a data-uri sample.adoc

If you want the document to include a table of contents, pass the +toc+ attribute to the processor:

 $> asciidoctor -a data-uri -a toc sample.adoc

Alternatively, if you want to use +data-uri+ and +toc+ by default, you can add them to the header of the document.

----
 = Introduction to AsciiDoc
 Doc Writer <doc@example.com>
 :data-uri:
 :toc:

 Content...
----

If you include the attributes in the document's header, you do not need to pass them through the processor when you render the document.

== Converting a document to DocBook

Despite the fact that writing in DocBook is inhumane, it's useful as a intermediary format.
And, since the AsciiDoc syntax was designed with DocBook output in mind, the conversion is very good.
There's a corresponding DocBook element for each markup in the AsciiDoc syntax.

To convert the +sample.adoc+ document to DocBook format, call the processor with the backend flag set to +docbook+:

 $> asciidoctor -b docbook sample.adoc

A new XML document, named +sample.xml+, will now be present in the current directory.

 $> ls
 sample.adoc  sample.html  sample.xml

If you're on Linux, you can view the DocBook file with {yelp-uri}[Yelp].

 $> yelp sample.xml

Using the Asciidoctor Ruby API, you can generate a DocBook document directly from a Ruby application:

[source,ruby]
----
Asciidoctor.render_file('sample.adoc', :in_place => true,
    :backend => 'docbook')
----

DocBook is only an intermediary format in the Asciidoctor toolchain.
You'll either feed it into a system that processes DocBook (like {publican-ref}[publican]), or you can convert it to PDF using the {fopdf-doc-ref}[Asciidoctor fopdf extension].

////
== Converting a document to PDF using +a2x+

PDF is a nice format for presenting a final version of a document.
For legacy reasons, the conversion to PDF is handled by a separate program in the AsciiDoc distribution, {a2x_1-uri}[+a2x+].

+a2x+ accepts a DocBook file, like the +sample.xml+ file created in the section above, as input and converts it to a PDF.

In your console: 

. Call the +a2x+ program
. Select the output format with +-f+ (+--format+)
. Followed by the format type +pdf+

//^

 $> a2x -f pdf sample.xml

A PDF document, named +sample.pdf+, will now be present in the current directory:

 $> ls
 sample.adoc  sample.html  sample.pdf  sample.xml

You can view the PDF using any PDF viewer.

Rather than converting from AsciiDoc to DocBook and then from DocBook to PDF in two steps, +a2x+ can go directly from AsciiDoc to PDF in a single call:

 $> a2x -f pdf sample.adoc
////

There's really no end to the customization you can apply to the output that the AsciiDoctor processor generates.
We've just scratched the surface here.

== Resources and help

There are a number of specialized backends available or under development for Asciidoctor.
More information and the latest available developments can be found in the project's {backends-repo-uri}[backend repository].

Please consider joining the {discuss-uri}[Asciidoctor mailing list], where you can ask questions and leave comments.
If you identify an issue while using a backend with the Asciidoctor processor, please don't hesitate to {backends-issues-uri}[file a bug report].
