// rvm use 2.1@runtime
// asciidoctor -D /tmp/ -a data-uri -a stem user-manual.adoc
= Asciidoctor User Manual
Sarah White <https://twitter.com/carbonfray[@carbonfray]>; Dan Allen <https://github.com/mojavelinux[@mojavelinux]>
:description: This guide describes the Asciidoctor attributes, values, and layout options available for producing a customized and polished document.
:keywords: AsciiDoc, Asciidoctor, syntax, reference, learn, how to, AsciiMath, LaTeX math, MathJax, Pygments, CodeRay
:doctype: book
:compat-mode:
:page-layout!:
:toc: right
:toclevels: 2
:sectanchors:
:sectlinks:
:sectnums:
:linkattrs:
:icons: font
:source-highlighter: coderay
:source-language: asciidoc
:experimental:
:stem:
:idprefix:
:idseparator: -
:ast: &ast;
:dagger: pass:normal[^&dagger;^]
:y: icon:check[role="green"]
:n: icon:times[role="red"]
:c: icon:file-text-o[role="blue"]
:table-caption!:
:example-caption!:
:figure-caption!:
:imagesdir: ../images
:includedir: _includes
:underscore: _
// Refs
:uri-home: http://asciidoctor.org
:uri-gem: http://rubygems.org/gems/asciidoctor
:uri-org: https://github.com/asciidoctor
:uri-repo: {uri-org}/asciidoctor
:uri-tilt: https://github.com/rtomayko/tilt
:uri-jruby: http://jruby.org
:uri-man: {uri-home}/man/asciidoctor
:uri-rewrite: https://github.com/ocpsoft/rewrite/tree/master/transform-markup
:markup-ref: http://en.wikipedia.org/wiki/Lightweight_markup_language
:markdown-ref: http://daringfireball.net/projects/markdown
:fedora-docs: http://docs.fedoraproject.org
:java: http://asciidoctor.org/docs/install-and-use-asciidoctor-java-integration
:tests: https://github.com/asciidoctor/asciidoctor/tree/master/test
:asciidoc-edit-ref: http://asciidoc.org/#_editor_support
:docref: link:/docs
:editing-ref: {docref}/editing-asciidoc-with-live-preview
:asciidoclet-ref: {docref}/install-and-use-asciidoclet/
:docbook-info-ref: http://www.docbook.org/tdg5/en/html/info.html
:richfaces-docinfo: https://github.com/richfaces/richfaces-docs/blob/master/Developer_Guide/src/main/docbook/en-US/Developer_Guide-docinfo.xml
:air-ref: http://en.wikipedia.org/wiki/Air_quotes
:uri-xml: http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
:uri-unicode: http://en.wikipedia.org/wiki/List_of_Unicode_characters
:fontawesome-ref: http://fortawesome.github.io/Font-Awesome/
:factory-ref: http://github.com/asciidoctor/asciidoctor-stylesheet-factory
:uri-http: http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html
:pygments-org: http://pygments.org
:pygments-gem: https://rubygems.org/gems/pygments.rb
:pygments-lang: {pygments-org}/languages/
:coderay-uri: http://coderay.rubychan.de/
:coderay-gem: https://rubygems.org/gems/coderay
:showcase-ref: http://themes.asciidoctor.org/preview/
:uri-docbook5: http://www.docbook.org/tdg5/en/html/ch01.html#introduction-whats-new
:uri-yelp: https://wiki.gnome.org/action/show/Apps/Yelp
:publican: http://fedorahosted.org/publican
:a2x: http://asciidoc.org/a2x.1.html
:man-raw: https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/man/asciidoctor.adoc
:man-backend-git: https://github.com/asciidoctor/asciidoctor-backends/tree/master/erb/manpage
:fopub-ref: https://github.com/asciidoctor/asciidoctor-fopub
:fopub-doc-ref: https://github.com/asciidoctor/asciidoctor-fopub/blob/master/README.adoc
:backend-git: http://github.com/asciidoctor/asciidoctor-backends
:deckjs-org: http://imakewebthings.com/deck.js
:deckjs-git: https://github.com/imakewebthings/deck.js
:deckjs-zip: {deckjs-git}/archive/latest.zip
:decksplitjs-git: https://github.com/houqp/deck.split.js
:compass-ref: http://compass-style.org
:sass-ref: http://sass-lang.com
:uri-foundation: http://foundation.zurb.com
:get-ruby-ref: http://www.ruby-lang.org/en/downloads
:bundler-ref: http://rubygems.org/gems/bundler
:issue-ref: https://github.com/asciidoctor/asciidoctor/issues
:license: https://github.com/asciidoctor/asciidoctor/blob/master/LICENSE.adoc
:mojavelinux: https://github.com/mojavelinux
:erebor: https://github.com/erebor
:lightguard: https://github.com/lightguard
:nickh: http://github.com/nickh
:contributors: https://github.com/asciidoctor/asciidoctor/graphs/contributors
:gitscm-next: https://github.com/github/gitscm-next
:seed-contribution: https://github.com/github/gitscm-next/commits/master/lib/asciidoc.rb
:uri-asciimath: http://docs.mathjax.org/en/latest/asciimath.html
:uri-latexmath: http://docs.mathjax.org/en/latest/tex.html
:uri-mathjax: http://www.mathjax.org
:uri-mathjax-docs: http://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference
:uri-mailinglist: http://discuss.asciidoctor.org
:uri-ad-org-issues: https://github.com/asciidoctor/asciidoctor.org/issues
:uri-asciidoctorj: {uri-org}/asciidoctorj
:uri-asciidoctorjs: {uri-org}/asciidoctor.js
:uri-irc: irc://irc.freenode.org/#asciidoctor
:uri-asciidoc-leveloffset: http://asciidoc.org/userguide.html#X90

:compat-mode!:

[NOTE]
.This document is under active development and discussion!
====
If you find errors or omissions in this document, please don't hesitate to {uri-ad-org-issues}[submit an issue or open a pull request] with a fix.
We also encourage you to ask questions and discuss any aspects of the project on the {uri-mailinglist}[mailing list] or {uri-irc}[IRC].
New contributors are always welcome!
====

This manual assumes you are using Asciidoctor to produce and render your document.
Asciidoctor implements more syntax, attributes and functions than the legacy AsciiDoc.py processor.
<<asciidoctor-vs-asciidoc,Appendix A>> lists which features are available to the Asciidoctor and AsciiDoc processors.

////
== Navigating this document

The first sections define the general concepts and terms used by Asciidoctor
Next, each Asciidoctor feature, its capabilities, and how it can be customized is reviewed.
And when applicable, the feature's attributes and options are summarized in a table at the section's end.
////

= Introduction to Asciidoctor

[partintro]
--
NOTE: Section Pending
--

include::{includedir}/about-asciidoctor.adoc[]

=== Asciidoctor's most notable benefits

include::{includedir}/benefits.adoc[]

==== AsciiDoc syntax processing

Asciidoctor reads and parses text written in the AsciiDoc syntax, then feeds the parse tree into a set of built-in templates to produce HTML5, PDF, DocBook 5, etc.
You have the option of writing your own converter or providing {uri-tilt}[Tilt]-supported templates to customize the generated output or produce alternative formats.

NOTE: Asciidoctor is a drop-in replacement for the original AsciiDoc Python processor (`asciidoc.py`).
The Asciidoctor test suite has > 1,500 tests to ensure compatibility with the AsciiDoc syntax.

In addition to the standard AsciiDoc syntax, Asciidoctor recognizes additional markup and formatting options, such as font-based icons (e.g., [x-]`icon:fire[]`) and UI elements (e.g., [x-]`button:[Save]`).
Asciidoctor also offers a modern, responsive theme based on {uri-foundation}[Foundation] to style the HTML5 output.

=== Compared to AsciiDoc

NOTE: Section Pending

////
.What is AsciiDoc?

AsciiDoc is two things:

. A mature{empty}footnote:[AsciiDoc is over 10 years old. It was first introduced in 2002.], plain-text format for authoring notes, articles, documentation, books, ebooks, web pages, slide decks, blog posts, man pages and more.
. A text processor and toolchain for translating AsciiDoc documents into various formats (called _backends_), including HTML, DocBook, PDF and ePub{empty}footnote:[There are two implementations of the AsciiDoc processor. The original processor, named AsciiDoc, is written in Python. A more modern implementation, named Asciidoctor, is written in Ruby.].

AsciiDoc belongs to the family of {markup-ref}[lightweight markup languages], the most renowned of which is {markdown-ref}[Markdown].
AsciiDoc stands out from this group because it supports all the structural elements necessary for drafting articles, technical manuals, books, presentations and prose.
In fact, it's capable of meeting even the most advanced publishing requirements and technical semantics.


Serving as testament of this fact, many O'Reilly authors, including https://github.com/matthewmccullough[Matthew McCullough], https://github.com/tlberglund[Tim Berglund], https://github.com/oreillymedia/etudes-for-erlang[Simon St.Laurent] and http://www.apeth.net/matt/iosbooktoolchain.html[Matt Neuburg], have used AsciiDoc to write their books for that iconic technical library.

From the very beginning, AsciiDoc was designed to be a shorthand replacement for http://www.docbook.org/whatis[DocBook], one of the formats AsciiDoc can generate.
AsciiDoc can also produce beautiful HTML 5, PDFs, eBooks, man pages and even slide decks.
It has you covered from first draft to publishing.
////

=== Compared to MarkDown

NOTE: Section Pending

= Quick Starts

[partintro]
--
NOTE: Section Pending
--

== Installation Quick Start

NOTE: Section Pending

== Usage Quick Start

NOTE: Section Pending

:compat-mode:

=== Using the Command Line Interface

include::{includedir}/command-line-usage.adoc[]

=== Using the Ruby API

include::{includedir}/api-intro.adoc[]

include::{includedir}/load-render-api.adoc[]

You can also use the API to <<user-manual#render-strings,render strings>> and <<user-manual#provide-custom-templates,load custom templates>>.

== Syntax Quick Start

NOTE: Section Pending

== Custom Output Quick Start

NOTE: Section Pending

= Getting Started

[partintro]
--
NOTE: Section Pending
--

== System Requirements

include::{includedir}/install-upgrade-asciidoctor.adoc[tags=systemreq]

== Installing the Asciidoctor Ruby Gem

include::{includedir}/install-upgrade-asciidoctor.adoc[tags=basicgem]

.Two API Flavors
****
In addition to the CLI, Asciidoctor provides a <<api,Ruby API>>.
The API is intended for integration with other software projects and is suitable for server-side applications, such as Rails, Sinatra and GitHub.

Asciidoctor also has a Java API that mirrors the Ruby API.
The Java API calls through to the Ruby API using an embedded JRuby runtime.
See the {java}[Asciidoctor Java integration project] for more information.
****

=== Install with Bundler

include::{includedir}/install-upgrade-asciidoctor.adoc[tags=bundler]

=== Install with +yum+

include::{includedir}/install-upgrade-asciidoctor.adoc[tags=yum]

=== Install with +apt-get+

include::{includedir}/install-upgrade-asciidoctor.adoc[tags=aptget]

== Upgrading the Asciidoctor Ruby Gem

include::{includedir}/install-upgrade-asciidoctor.adoc[tags=upgrade]

:compat-mode!:

== Extensions and Integrations

See <<Extensions>>.

= Terms and Concepts

[partintro]
--
All of the content in an Asciidoctor document, including lines of text, predefined styles, and processing commands, is classified as either a block or an inline element.
Within each of these elements are an array of styles, options, and functions that can be applied to your content.

This section will provide you with an overview of what each of these elements and sub-elements are and the basic syntax and rules for using them.
--

== Elements

include::{includedir}/element.adoc[]

== Macros

NOTE: Section pending

== Attributes

include::{includedir}/attr.adoc[tags=intro]

=== Attribute assignment precedence

include::{includedir}/attr.adoc[tags=order]

=== Using attributes: set, assign, and reference

include::{includedir}/attr-use.adoc[]

=== Setting attributes on a document

include::{includedir}/attr-doc.adoc[]

=== Built-in data attributes

include::{includedir}/attr-data.adoc[]

=== Setting attributes on an element

include::{includedir}/attr-element.adoc[tags=intro]

==== Positional attribute

include::{includedir}/attr-element.adoc[tags=pos]

==== Named attribute

include::{includedir}/attr-element.adoc[tags=name]

==== Style

include::{includedir}/attr-style.adoc[tags=intro]

==== Id

include::{includedir}/attr-style.adoc[tags=id]

===== Block assignment

include::{includedir}/attr-style.adoc[tags=bl]

===== Inline assignment

include::{includedir}/attr-style.adoc[tags=in]

==== Role

NOTE: Section introduction pending

An element can be assigned numerous roles.

===== Block assignment

In an attribute list, there are two ways to assign a role attribute to a block element.

. Prefixing the name with a dot (`.`).
. Specifying the name with `role=<name>`.

[source]
----
[.summary]
* Review 1
* Review 2
----

[source]
----
[role="summary"]
* Review 1
* Review 2
----

To specify multiple roles using the shorthand syntax, separate them by dots.

[source]
----
[.summary.incremental]
* Review 1
* Review 2
----

[source]
----
[role="summary,incremental"]
* Review 1
* Review 2
----

===== Inline assignment

The role (`.`) shorthand can be used on inline quoted text.

.Quoted text with role assignments using traditional AsciiDoc syntax
----
[big goal]*free the world*
----

.Quoted text with role assignments using Asciidoctor shorthand
----
[.big.goal]*free the world*
----

TIP: The attribute list preceding formatted text can be escaped using a backslash (e.g., `+[role]*bold*+`).
In this case, the text will still be formatted, but the attribute list will be unescaped and output verbatim.

.Role-playing for text enclosed in backticks
To align with other formatted (i.e., quoted) text in AsciiDoc, roles can now be assigned to text enclosed in backticks.

Given:

```
[rolename]`escaped monospace text`
```

the following HTML is produced:

```html
<code class="rolename">escaped monospace text</code>
```

Using the shorthand notation, an id (i.e., anchor) can also be specified:

```
[#idname.rolename]`escaped monospace text`
```

which produces:

```html
<a id="idname"></a><code class="rolename">escaped monospace text</code>
```

Keep in mind that text enclosed is not subject to other inline substitutions, but rather passed through as is.

==== Options

The options attribute is a versatile named attribute that can contain a comma separated list of values.

It can also be defined globally with an attribute entry.

===== Block assignment

In an attribute list, there are three ways to assign an options attribute to a block element.

. Prefixing the value with a percent sign (`%`).
. Specifying the value with `opts=<name>`
. Specifying the value with `options=<name>`.

Consider a table block with the three option values `header`, `footer`, and `autowidth`.

Here's how the options are assigned to the table using the shorthand notation (`%`).

.Shorthand Asciidoctor syntax
----
[%header%footer%autowidth]
|===
| Cell A | Cell B
|===
----

Here's how the options are assigned to the table using `options`.

.Traditional AsciiDoc syntax
----
[options="header,footer,autowidth"]
|===
| Cell A | Cell B
|===
----

Let's consider the options when combined with other attributes.

.Shorthand Asciidoctor block syntax
----
[horizontal.properties%step]
property 1:: does stuff
property 2:: does different stuff
----

.Traditional AsciiDoc block syntax
----
[horizontal, role="properties", options="step"]
property 1:: does stuff
property 2:: does different stuff
----

=== Assigning document variables inline

Document variables can be assigned using the following syntax:

 {set:<attrname>[!][:<value>]}

For example:

[source]
{set:sourcedir:src/main/java}

It's effectively the same as:

 :sourcedir: src/main/java

This is important for being able to assign document attributes in places where attribute entry lines are not normally processed, such as in a table cell.

////
An example of where this might be used is documented in the {doc-variable-ref}[how to set the background color of a table cell] tip.
////

=== Attribute conventions

NOTE: Section Pending

==== Catch a missing or undefined attribute

include::{includedir}/attr-miss.adoc[]

= Building a Document

[partintro]
--
NOTE: Introduction Pending
--

== Text Editor

include::{includedir}/text-editor.adoc[]

== Document Types

include::{includedir}/doctype.adoc[]

== Basic Document Anatomy

NOTE: Section pending

[[doc-header]]
== Header

include::{includedir}/header-intro.adoc[]

=== Document title

include::{includedir}/header-title.adoc[]

=== Author and email

include::{includedir}/author.adoc[]

=== Revision number, date, and remark

include::{includedir}/revision.adoc[]

=== Metadata

include::{includedir}/meta.adoc[tags=intro]

==== Description

include::{includedir}/meta.adoc[tags=desc]

==== Keywords

include::{includedir}/meta.adoc[tags=key]

==== Alternate title

include::{includedir}/meta.adoc[tags=atitle]

==== Custom metadata, styles and functions

include::{includedir}/meta.adoc[tags=cmeta]

=== Header summary

include::{includedir}/sum-header.adoc[]

[[doc-preamble]]
== Preamble

include::{includedir}/preamble-tut.adoc[]

== Sections

include::{includedir}/sections.adoc[tags=intro]

=== Titles as headings

include::{includedir}/sections.adoc[tags=heading]

=== Title id and prefix

include::{includedir}/sections.adoc[tags=id]

=== Links

include::{includedir}/sections.adoc[tags=link]

=== Anchors

include::{includedir}/sections.adoc[tags=anchor]

=== Numbering

include::{includedir}/sections.adoc[tags=number]

=== Discrete or floating section titles

include::{includedir}/float-title.adoc[]

=== Section styles

include::{includedir}/section-styles.adoc[]

=== Sections summary

include::{includedir}/sum-section.adoc[]

== Blocks

include::{includedir}/block.adoc[]

== Paragraph

include::{includedir}/para.adoc[]

=== Line breaks

include::{includedir}/para-line-break.adoc[]

=== Lead style

include::{includedir}/para-lead.adoc[]

== Text Formatting

include::{includedir}/text.adoc[]

=== Bold and italic

include::{includedir}/text-bold-italic.adoc[]

[[curved]]
=== Quotation marks and apostrophes

include::{includedir}/text-quote-apos.adoc[]

=== Subscript and superscript

include::{includedir}/text-sub-sup.adoc[]

[[mono]]
=== Monospace

include::{includedir}/text-mono.adoc[]

=== Custom styling with attributes

include::{includedir}/text-css.adoc[]

== Unordered Lists

include::{includedir}/u-list.adoc[]

=== Nested

include::{includedir}/u-list-nest.adoc[]

=== Complex list content

include::{includedir}/u-list-complex.adoc[]

=== Custom markers

include::{includedir}/u-list-marker.adoc[]

=== Checklist

include::{includedir}/u-list-check.adoc[]

=== Summary

NOTE: Pending

== Ordered Lists

include::{includedir}/o-list.adoc[]

=== Nested

include::{includedir}/o-list-nest.adoc[]

=== Numbering styles

include::{includedir}/o-list-num.adoc[]

=== Summary

NOTE: Pending

== Labeled List

include::{includedir}/l-list.adoc[]

=== Question and answer style list

include::{includedir}/l-list-qa.adoc[]

=== Summary

NOTE: Section pending

== Tables

include::{includedir}/table.adoc[]

include::{includedir}/table-col.adoc[]

include::{includedir}/table-cell.adoc[]

include::{includedir}/table-formatting.adoc[]

include::{includedir}/table-data.adoc[]

=== Summary

include::{includedir}/sum-table.adoc[]

== Horizontal Rules

include::{includedir}/hr.adoc[]

== Page break

include::{includedir}/page-break.adoc[]

[[url]]
== URLs

include::{includedir}/url.adoc[]

=== Link to relative files

include::{includedir}/url-relative.adoc[]

=== Summary

include::{includedir}/sum-url.adoc[]

[[xref]]
== Internal cross references

include::{includedir}/xref.adoc[]

=== Inter-document cross references

include::{includedir}/xref-interdoc.adoc[]

== Images

include::{includedir}/image.adoc[]

=== Set the images directory

include::{includedir}/image-dir.adoc[]

==== Include images by full URL

include::{includedir}/image-url.adoc[]

=== Put images in their place

include::{includedir}/image-position.adoc[]

=== Summary

include::{includedir}/sum-image.adoc[]

== Video

include::{includedir}/video.adoc[]

=== Summary

include::{includedir}/sum-video.adoc[]

== Audio

NOTE: Pending

////
Macro name:

 audio::ocean_waves.mp3[options=loop]
////

=== Summary

include::{includedir}/sum-audio.adoc[]

== Admonition

include::{includedir}/admonition.adoc[]

== Sidebar

include::{includedir}/sidebar.adoc[]

== Example

include::{includedir}/example.adoc[]

== Prose Excerpts, Quotes and Verses

include::{includedir}/quote.adoc[tags=intro]

=== Quote

include::{includedir}/quote.adoc[tags=basic]

include::{includedir}/quote-alt.adoc[]

=== Verse

include::{includedir}/verse.adoc[]

== Comments

include::{includedir}/comment.adoc[]

= Controlling Your Content

[partintro]
--
NOTE: Part introduction pending
--

[[subs]]
== Text Substitutions

include::{includedir}/subs.adoc[]

=== Special characters

include::{includedir}/subs-specchar.adoc[]

=== Quotes

include::{includedir}/subs-quote.adoc[]

=== Attributes

include::{includedir}/subs-attr.adoc[]

=== Replacements

include::{includedir}/subs-repl.adoc[]

[[subs-mac]]
=== Macros

include::{includedir}/subs-macro.adoc[]

=== Post replacements

include::{includedir}/subs-post.adoc[]

=== Applying substitutions

include::{includedir}/subs-apply.adoc[]

=== Preventing substitutions

include::{includedir}/subs-prevent.adoc[]

== Literal Text and Blocks

include::{includedir}/literal.adoc[]

== Listing Blocks

include::{includedir}/listing.adoc[]

=== To wrap or to scroll

include::{includedir}/listing-wrap.adoc[]

=== Summary

NOTE: Pending

[[passthru]]
== Macro and Block Passthroughs

include::{includedir}/pass-intro.adoc[]

[[pass-mac]]
=== Passthrough macros

include::{includedir}/pass-macro.adoc[]

////

This section is not valid until Issue #720 is corrected.

==== Nesting blocks and passthrough macros

When you're using passthroughs inside literal and listing blocks, it can be easy to forget that the triple-plus, double-dollar, and backtick passthroughs are macros.
If you want to enable the passthroughs, make sure to assign the +macros+ value to the +subs+ attribute.

....
[source,java]
[subs="verbatim,quotes,macros"]
----
protected void configure(HttpSecurity http) throws Exception {
    http
        .authorizeRequests()
            **.antMatchers("/resources/$$**$$").permitAll()**
            .anyRequest().authenticated()
            .and()
        .formLogin()
            .loginPage("/login")
            .permitAll();
----
....

====
[source,java]
[subs="verbatim,quotes,macros"]
----
protected void configure(HttpSecurity http) throws Exception {
    http
        .authorizeRequests()
            **.antMatchers("/resources/$$**$$").permitAll()**
            .anyRequest().authenticated()
            .and()
        .formLogin()
            .loginPage("/login")
            .permitAll();
----
====

////

[[pass-bl]]
=== Block passthroughs

include::{includedir}/pass-block.adoc[]

== Open Blocks

include::{includedir}/open.adoc[]

= Enriching Your Content

[partintro]
--
NOTE: Part introduction pending
--

[[stem]]
== Equations and Formulas

include::{includedir}/stem.adoc[tags=intro]

[[stem-in]]
=== Inline stem content

include::{includedir}/stem.adoc[tags=in]

[[stem-bl]]
=== Block stem content

include::{includedir}/stem.adoc[tags=bl]

=== Using multiple stem interpreters

include::{includedir}/stem.adoc[tags=inter]

== User Interface Macros

include::{includedir}/ui.adoc[]

== Icons

include::{includedir}/icons.adoc[]

[[syntax-highlighting]]
[[source-code-blocks]]
== Source Code and Syntax Highlighting

include::{includedir}/src.adoc[]

=== Pygments

include::{includedir}/src-pygments.adoc[]

=== CodeRay

include::{includedir}/src-coderay.adoc[]

== Callouts

NOTE: Pending

=== Copy and paste friendly callouts

include::{includedir}/callout-copy.adoc[]

==== XML callouts

include::{includedir}/callout-xml.adoc[]

=== Callout icons

include::{includedir}/callout-icon.adoc[]

== Include Directive

include::{includedir}/include-directive.adoc[]

=== Selecting parts of a document to include

include::{includedir}/include-lines-tags.adoc[]

=== Relative leveloffset

include::{includedir}/include-relative-leveloffset.adoc[]

=== Normalizing block indentation

include::{includedir}/indent-include.adoc[]

=== Include files relative to a common source directory

include::{includedir}/relative-include.adoc[]

=== Include content from a URI

include::{includedir}/uri-include.adoc[]

== Docinfo file

include::{includedir}/docinfo.adoc[]

== Counter Attributes

include::{includedir}/counter.adoc[]

= Structuring, Navigating, and Referencing Your Content

[partintro]
--
include::{includedir}/structure-intro.adoc[]
--

== Title Page

NOTE: Section pending

[[user-colophon]]
== Colophon

include::{includedir}/colophon.adoc[]

[[user-toc]]
== Table of Contents

include::{includedir}/toc-intro.adoc[]

=== Left or right column layout

include::{includedir}/toc-layout.adoc[tags=column]

=== Manual placement

include::{includedir}/toc-layout.adoc[tags=place]

=== Title

include::{includedir}/toc-custom.adoc[tags=title]

=== Levels

include::{includedir}/toc-custom.adoc[tags=level]

=== Table of Contents summary

include::{includedir}/sum-toc.adoc[]

[[user-abstract]]
== Abstract

include::{includedir}/abstract.adoc[]

[[user-preface]]
== Preface

include::{includedir}/preface.adoc[]

[[user-dedication]]
== Dedication

include::{includedir}/dedication.adoc[]

== Book Parts and Part Introductions

include::{includedir}/book-part.adoc[]

[[user-appendix]]
== Appendix

include::{includedir}/appendix.adoc[]

[[user-glossary]]
== Glossary

include::{includedir}/glossary.adoc[]

[[user-biblio]]
== Bibliography

include::{includedir}/biblio.adoc[]

[[user-index]]
== Index

include::{includedir}/index.adoc[]

[[user-footnotes]]
== Footnotes

include::{includedir}/footnote.adoc[]

= Processing Your Content

[partintro]
--
include::{includedir}/process-intro.adoc[]
--

== Selecting an Output Format

include::{includedir}/output-format.adoc[]

////
The AsciiDoc processor supports numerous backends, including:

+xhtml11+:: XHTML 1.1 markup styled with CSS2.
AsciiDoc's default backend.
////

== HTML

// TODO: expand this introduction

Asciidoctor's default output format is HTML.

`html5`:: HTML 5 markup styled with CSS3.

=== Using the command line

include::{includedir}/html-command-line.adoc[]

=== Using the Ruby API

include::{includedir}/html-ruby-api.adoc[]

=== Styling the HTML with CSS

include::{includedir}/html-styles.adoc[]

=== Managing images

include::{includedir}/html-manage-images.adoc[]

[[hl-css]]
=== CodeRay and Pygments stylesheets

include::{includedir}/html-code-styles.adoc[]

== XHTML

include::{includedir}/xhtml.adoc[]

== DocBook

include::{includedir}/docbook.adoc[]

== Man pages

include::{includedir}/manpage.adoc[]

== PDFs

NOTE: To convert your document to PDF, you'll need to use the new {fopub-ref}[asciidoctor-fopub tool].
Directions for using the tool are documented in the {fopub-doc-ref}[asciidoctor-fopub README].

////
WARNING: The content regarding PDF generation below this warning block is out of date. Asciidoctor 0.1.4 does not require the +a2x+ tool to produce PDFs. New instructions pending.

PDF is a nice format for presenting a final version of a document.
For legacy reasons, the conversion to PDF is handled by a separate program in the AsciiDoc distribution, {a2x}[+a2x+].

+a2x+ accepts a DocBook file, like the +sample.xml+ file created in the section above, as input and converts it to a PDF.

In your console:

. Call the +a2x+ program
. Select the output format with +-f+ (+--format+)
. Followed by the format type +pdf+

//
 $> a2x -f pdf sample.xml

A PDF document, named +sample.pdf+, will now be present in the current directory:

 $> ls
 sample.adoc  sample.html  sample.pdf  sample.xml

You can view the PDF using any PDF viewer.

Rather than converting from AsciiDoc to DocBook and then from DocBook to PDF in two steps, +a2x+ can go directly from AsciiDoc to PDF in a single call:

 $> a2x -f pdf sample.adoc
////

== Preview Your Content

NOTE: Section pending

=== Guard/Live viewer

NOTE: Section pending

== Process multiple source files from the CLI

include::{includedir}/process-multi.adoc[]

== Specifying an output file

include::{includedir}/file-output.adoc[]

:compat-mode:

== Running Asciidoctor Securely

include::{includedir}/secure.adoc[]

=== Set the safe mode in the CLI

include::{includedir}/secure-cli.adoc[]

=== Set the safe mode in the API

include::{includedir}/secure-api.adoc[]

=== Set attributes based on the safe mode

include::{includedir}/secure-attr.adoc[]

= Customizing Your Output

[partintro]
--
Asciidoctor provides a default stylesheet and built-in converters so you can quickly process and render your document, but it also lets you use custom stylesheets and converters.
The Asciidoctor project includes alternative stylesheet themes from <<stylesheet-factory,the stylesheet factory>> and <<slideshows,specialized backends>>, such as the <<deckjs,Deck.js backend>>.
You can also create your own <<custom-themes,themes>> and <<custom-backends,backends>>.
--

== Custom Themes

NOTE: Section introduction pending

=== Creating a theme

include::{includedir}/create-theme.adoc[]

=== Applying a theme

include::{includedir}/apply-theme.adoc[]

== Stylesheet Factory

include::{includedir}/factory-intro.adoc[]

=== Setting up the factory

include::{includedir}/factory-setup.adoc[tags=setup]

==== Install the gems

include::{includedir}/factory-setup.adoc[tags=gem]

==== Build the stylesheets

include::{includedir}/factory-setup.adoc[tags=build]


=== Applying a stylesheet

include::{includedir}/factory-apply.adoc[]

=== Generate an HTML document

include::{includedir}/factory-gen.adoc[]

=== External preview

include::{includedir}/factory-preview.adoc[]

== Slideshows

The conversion to HTML-based slides is handled by a custom backend.
The backends usually requires that you adhere to a set of conventions to define a slide and its content.
But there's nothing in that content that restricts the document from being converted to a regular HTML page or PDF.

The first backend created was the one for deck.js.
Asciidoctor has backends for generating dzslides and reveal.js presentations as well.
Backends for other presentation frameworks are in the works.

[[deckjs]]
=== Deck.js

The {backend-git}[deck.js backend] for Asciidoctor is a collection of Haml templates that transform an AsciiDoc document to HTML 5-based slides animated by {deckjs-org}[deck.js].

==== Gem requirements

The Asciidoctor deck.js backend requires the following gems:

* asciidoctor
* tilt
* haml

To determine what gems are installed on your system, open a terminal window and type:

 $ gem list --local

A list of installed gems will be returned.

If you're missing the +asciidoctor+, +tilt+, or +haml+ gems, install them from the command line with +gem install+.

 $ gem install asciidoctor tilt haml

==== Backend and deck.js installation

. Download or +git clone+ the {backend-git}[Asciidoctor backends] repository.

 $ git clone git://github.com/asciidoctor/asciidoctor-backends.git

. Create a directory named +deck.js+ inside your working directory (i.e. where your AsciiDoc document resides).

. {deckjs-zip}[Download] and extract the deck.js archive or +git clone+ the {deckjs-git}[deck.js] repository into the +deck.js+ directory you created in step 2.

 $ git clone git://github.com/imakewebthings/deck.js.git

. If you plan to split your slides, {decksplitjs-git}[download the +deck.split.js+ extension] and copy it into the +deck.js/extensions+ directory.

. If you want to use the fullscreen photo feature, create an +images+ directory in your working directory.

==== Deckjs backend attributes

There are a number of document attributes specific to the +deckjs+ backend.

.+deckjs+ backend document attributes
[cols="2,1,2m"]
|===
|Attribute |Description |Example

|:backend: deckjs
|Activates the deck.js backend to render the document as a deck.js presentation
|:backend: deckjs

|:deckjs_theme: <theme>
|Sets the deck.js theme to neon, swiss or web-2.0
|:deckjs_theme: web-2.0

|:deckjs_transition: <type>
|Sets the transition style to horizontal-slide, vertical-slide or fade
|:deckjs_transition: fade

|:customjs: <javascript location>
|Sets a custom javascript file; can be used as a deck.js custom configuration
|:customjs: <javascript location>

|:customcss: <css location>
|Sets a custom css file
|:customcss: <css location>

|:menu:
|Toggle to and from a grid layout overview of all the slides by pressing the +m+ key
|:menu:

|:navigation:
|Renders clickable previous and next navigation icons on the slides
|:navigation:

|:status:
|Renders the current slide number and total number of slides
|:status:

|:split:
|Registers the split module for use in the document
|:split:
|===

NOTE: You can also specify a custom stylesheet using the +stylesheet+ attribute, which customizes AsciiDoc elements like section, paragraph, images, etc.

The attributes described in the table above are set in the header of your document.

.Header with +deckjs+ backend attributes
....
= Presentation Title
Presenter Name
:backend: deckjs
:deckjs_theme: web-2.0
:deckjs_transition: horizontal-slide
:navigation:
....

==== Slide syntax examples

Structuring a slideshow and writing the slide content uses the same syntax as a typical AsciiDoc document, with a few added features.

Let's see some examples of the +deckjs+ backend features:

.Slide titles and background images
----
= Title of Presentation <1>
Presenter Name
:backend: deckjs
:deckjs_transition: fade
:navigation:

== Title of Slide One <2>

This is the first slide after the title slide.

[canvas-image="images/example.jpg"] <3>
== Slide Two's Title will not be displayed <4>

[role="canvas-caption", position="center-up"] <5>
This text is displayed on top of the example.jpg image.
----
<1> The presentation title and author's name will be displayed on the title slide.
<2> Each new slide is designated by a level 1 section title (`==`).
<3> The +canvas-image+ attribute embeds a fullscreen image as a slide background. Position the attribute above the title of the slide you want the image applied to.
<4> When the +canvas-image+ attribute is applied to a slide, that slide's title will not be displayed.
<5> +canvas-caption+ applies a colored box around the caption text. +position+ specifies the location of the caption block (bottom-left, top-left, bottom-right, top-right, center-up, center-down)

.Stepped paragraphs, lists, and blocks
----
== Stepped paragraphs

[options="step"]
This paragraph is displayed first.

[options="step"]
Then this paragraph is displayed when the _Next_ arrow is clicked.

== Stepped list items

[options="step"]
* A bullet is displayed each time the _Next_ arrow is clicked.
* B
* C

== Stepped blocks

[options="step"]
----
Block one
----

[options="step"]
----
Block two
----
----

The +step+ option reveals each paragraph, bullet, etc. separately each time you click the _Next_ arrow.

WARNING: The original AsciiDoc +deckjs+ backend for the AsciiDoc processor used the option +incremental+ instead of +step+.
We've changed it to +step+ in order to save you some typing.

.Split
----
= Presentation Title
Presenter Name
:backend: deckjs
:split: <1>

== This Slide is Split

This Slide will act like

<<< <2>

three individual slides with the same title

<<<

once the document is rendered.
----
<1> To create multiple, consecutive slides with the same title, set the +split+ attribute in the document header.
<2> Then, within a slide, insert `<<<` to specify the slide breaks.

==== Rendering

To render your presentation as HTML5, execute the command:

 $ asciidoctor -T ../asciidoctor-backends/haml presentation.adoc

. The command +-T+ (+--template-dir+) tells the Asciidoctor processor to override the built-in backends.
. Directly after +-T+ is the path to where you saved or cloned the Asciidoctor backends repository containing the +deckjs+ backend (step 1 under the <<backend-and-deck-js-installation,installation section>>).

== Custom Backends

NOTE: Section pending

=== Creating a backend

NOTE: Section pending

==== Storing multiple templates

Custom templates can be stored in multiple directories.
That means you can build on an existing backend by copying only the templates you want to modify.
Then, just pass both the directory holding the original templates and the directory containing your customized templates when you invoke Asciidoctor.

In the CLI, multiple template directories are specified by using the +-T+ option multiple times.

 $ asciidoctor -T /path/to/original/templates -T /path/to/modified/templates sample.adoc

In the API, multiple template directories are specified by passing an array to the +template_dirs+ option:

```ruby
Asciidoctor.convert_file 'sample.adoc', :safe => :safe, :in_place => true,
    :template_dirs => ['/path/to/original/templates', '/path/to/modified/templates']
```

////
Styling DocBook and PDF Output

NOTE: Section pending
////

= Publishing Your Content

[partintro]
NOTE: Section pending

== Repositories

NOTE: Section pending

== Static website generators

NOTE: Section pending

=== Front matter added for static site generators

include::{includedir}/static-front.adoc[]

==== Configuring attributes for Awestruct

include::{includedir}/static-awe.adoc[]

[[api]]
= Using Asciidoctor's API

[partintro]
--
include::{includedir}/api-intro.adoc[]
--

== Load and Render a File Using the API

include::{includedir}/load-render-api.adoc[]

=== Render strings

include::{includedir}/string-api.adoc[]

== Provide custom templates

include::{includedir}/templates-api.adoc[]

= Extensions

[partintro]
--
include::{includedir}/exten-intro.adoc[]
--

== Extension Points

include::{includedir}/exten-point.adoc[]

== Example Extensions

Below are several examples of extensions and how they are registered.

=== Preprocessor example

include::{includedir}/exten-pre.adoc[]

=== Treeprocessor example

include::{includedir}/exten-tree.adoc[]

=== Postprocessor example

include::{includedir}/exten-post.adoc[]

=== Block processor example

include::{includedir}/exten-block.adoc[]

=== Block macro processor example

include::{includedir}/exten-macro.adoc[]

=== Inline macro processor example

include::{includedir}/exten-in-macro.adoc[]

=== Include processor example

include::{includedir}/exten-include.adoc[]

You can see plenty more extension examples in the https://github.com/asciidoctor/asciidoctor-extensions-lab[extensions lab].

= Build Integrations and Implementations

[partintro]
NOTE: Section pending

== Java

NOTE: Section pending

== Gradle

NOTE: Section pending

== Maven

NOTE: Section pending

== JavaDoc

NOTE: Section pending

== JavaScript

NOTE: Section pending

== Yard

NOTE: Section pending

== Rdoc

NOTE: Section pending

= Conversions and Migrations

[partintro]
NOTE: Section pending

== Convert Markdown *to* Asciidoctor

NOTE: Section pending

== Migrate from AsciiDoc to Asciidoctor

NOTE: Section pending

= Resources

[partintro]
NOTE: Section pending

== Copyright and License

include::{includedir}/project-lic.adoc[]

== Authors

include::{includedir}/project-author.adoc[]

// TODO fill in this section and enable
// Thanks, acknowledgments, and credits

:leveloffset: 1
[[troubleshoot]]
include::{includedir}/troubleshoot.adoc[]
:leveloffset: 0

== Additional Help

NOTE: Section pending

[glossary]
== Glossary

[glossary]
admonition paragraph:: a callout paragraph that has a label or icon indicating its priority
admonition block:: a callout block containing complex content that has a label or icon indicating its priority
backend:: a set of templates for converting AsciiDoc source to different output format
cross reference:: a link from one location in the document to another location marked by an anchor
list continuation:: a plus sign (`+`) on a line by itself that connects adjacent lines of text to a list item
quoted text:: text which is enclosed in special punctuation to give it emphasis or special meaning

NOTE: Section expansion pending

:leveloffset: 1
[[asciidoctor-vs-asciidoc]]
[appendix]
include::asciidoc-asciidoctor-diffs-table.adoc[]

:leveloffset: 1
[[char-ref-table]]
[appendix]
include::character-ref-attributes.adoc[]

////

Include license and copyright

== Index

NOTE: Section pending

////
