= Asciidoctor User Manual
Sarah White <https://github.com/graphitefriction[@graphitefriction]>; Dan Allen <https://github.com/mojavelinux[@mojavelinux]>
:description: This guide describes the Asciidoctor attributes, values, and layout options available for producing a customized and polished document.
:keywords: AsciiDoc, Asciidoctor, syntax, reference
:doctype: book
:toc: right
:toclevels: 2
:sectanchors:
:sectlink:
:linkattrs:
:numbered:
:icons: font
:source-highlighter: coderay
:experimental:
:idprefix:
:idseparator: -
:ast: &ast;
:dagger: pass:normal[^&dagger;^]
:y: icon:ok[role="green"]
:n: icon:remove[role="red"]
:c: icon:file-text-alt[role="blue"]
:language: asciidoc
:table-caption!: 
:example-caption!:
:figure-caption!:
:imagesdir: ../images
:includedir: _includes
:underscore: _
// Refs
:homepage: http://asciidoctor.org
:gem: http://rubygems.org/gems/asciidoctor
:gh-org: https://github.com/asciidoctor
:tilt: https://github.com/rtomayko/tilt
:jruby: http://jruby.org
:man: http://asciidoctor.org/man/asciidoctor
:rewrite-git: https://github.com/ocpsoft/rewrite/tree/master/transform-markup
:markup-ref: http://en.wikipedia.org/wiki/Lightweight_markup_language
:markdown-ref: http://daringfireball.net/projects/markdown
:fedora-docs: http://docs.fedoraproject.org
:java: http://asciidoctor.org/docs/install-and-use-asciidoctor-java-integration
:templates: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/backends
:tests: https://github.com/asciidoctor/asciidoctor/tree/master/test
:asciidoc-edit-ref: http://asciidoc.org/#_editor_support
:docref: link:/docs
:editing-ref: {docref}/editing-asciidoc-with-live-preview
:asciidoclet-ref: {docref}/install-and-use-asciidoclet/
:docbook-info-ref: http://www.docbook.org/tdg5/en/html/info.html
:richfaces-docinfo: https://github.com/richfaces/richfaces-docs/blob/master/Developer_Guide/src/main/docbook/en-US/Developer_Guide-docinfo.xml
:air-ref: http://en.wikipedia.org/wiki/Air_quotes
:xml-ref: http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
:unicode-ref: http://en.wikipedia.org/wiki/List_of_Unicode_characters
:fontawesome-ref: http://fortawesome.github.io/Font-Awesome
:factory-ref: http://github.com/asciidoctor/asciidoctor-stylesheet-factory
:http-ref: http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html
:pygments-org: http://pygments.org
:showcase-ref: http://themes.asciidoctor.org/preview/
:docbook5-ref: http://www.docbook.org/tdg5/en/html/ch01.html#introduction-whats-new
:yelp: http://live.gnome.org/Yelp
:publican: http://fedorahosted.org/publican
:a2x: http://asciidoc.org/a2x.1.html
:man-raw: https://raw.github.com/asciidoctor/asciidoctor/master/man/asciidoctor.adoc
:man-backend-git: https://github.com/asciidoctor/asciidoctor-backends/tree/master/erb/manpage
:fopdf-ref: https://github.com/mojavelinux/asciidoctor-fopdf
:fopdf-doc-ref: https://github.com/mojavelinux/asciidoctor-fopdf/blob/master/README.adoc
:backend-git: http://github.com/asciidoctor/asciidoctor-backends
:deckjs-org: http://imakewebthings.com/deck.js
:deckjs-zip: https://github.com/imakewebthings/deck.js/zipball/stable
:deckjs-git: https://github.com/imakewebthings/deck.js
:decksplitjs-git: https://github.com/houqp/deck.split.js
:compass-ref: http://compass-style.org
:sass-ref: http://sass-lang.com
:foundation-ref: http://foundation.zurb.com
:get-ruby-ref: http://www.ruby-lang.org/en/downloads
:bundler-ref: http://rubygems.org/gems/bundler
:issue-ref: https://github.com/asciidoctor/asciidoctor/issues
:license: https://github.com/asciidoctor/asciidoctor/blob/master/LICENSE
:mojavelinux: https://github.com/mojavelinux
:erebor: https://github.com/erebor
:lightguard: https://github.com/lightguard
:nickh: http://github.com/nickh
:contributors: https://github.com/asciidoctor/asciidoctor/graphs/contributors
:gitscm-next: https://github.com/github/gitscm-next
:seed-contribution: https://github.com/github/gitscm-next/commits/master/lib/asciidoc.rb

[NOTE]
.This document is under active development and discussion!
====
If you discover errors or omissions in this document, please don't hesitate to submit an issue or open a pull request with a fix.
We also encourage you to ask questions and discuss any aspects of the project on the mailing list or IRC.
New contributors are always welcome!
====

This manual assumes you are using Asciidoctor to produce and render your document.
Asciidoctor implements additional syntax, attributes and functions that the AsciiDoc processor can not handle.
<<asciidoctor-vs-asciidoc,Appendix A>> lists which features are available to the Asciidoctor and AsciiDoc processors.

////
== Navigating this document

The first sections define the general concepts and terms used by Asciidoctor
Next, each Asciidoctor feature, its capabilities, and how it can be customized is reviewed.
And when applicable, the feature's attributes and options are summarized in a table at the section's end.
////

= Introduction to Asciidoctor

[partintro]
--
NOTE: Section Pending
--

== What is Asciidoctor?

{homepage}[Asciidoctor] is an open source text processor and publishing toolchain for transforming AsciiDoc markup into HTML 5, DocBook 4.5 and 5.0 and other custom formats.
Asciidoctor is written entirely in Ruby, packaged as a RubyGem and published to {gem}[RubyGems.org].
There are also Fedora, Debian and Ubuntu packages available for installing Asciidoctor.
The git repositories for the project are hosted under the {gh-org}[Asciidoctor organization on GitHub] to encourage continued growth.

=== AsciiDoc syntax processing

////
Asciidoctor is a drop-in replacement for the original AsciiDoc python processor.
It reads and parses AsciiDoc markup (from a file or string) and feeds the parsed result to a set of built-in templates to render the document as HTML 5, DocBook 5.0 or 4.5.
////

AsciiDoc belongs to the family of {markup-ref}[lightweight markup languages], the most renowned of which is {markdown-ref}[Markdown].
AsciiDoc stands out from this group because it supports all the structural elements necessary for drafting articles, technical manuals, books, presentations and prose.
In fact, it's capable of meeting even the most advanced publishing requirements and technical semantics.

////
You can override the built-in templates, or produce a custom format, by pointing the processor at a set of template files written in a language supported by {tilt}[Tilt].
////

NOTE: With few exceptions, Asciidoctor is compliant with the original AsciiDoc processor.
Asciidoctor has well over 1,000 tests to ensure compatibility with the AsciiDoc syntax.
We continue to work hard to ensure Asciidoctor continues to serve as a drop-in replacement for AsciiDoc. 

=== Asciidoctor's most notable benefits

include::{includedir}/benefits.adoc[]

=== Compared to AsciiDoc

NOTE: Section Pending

////
.What is AsciiDoc?

AsciiDoc is two things:

. A mature{empty}footnote:[AsciiDoc is over 10 years old. It was first introduced in 2002.], plain-text format for authoring notes, articles, documentation, books, ebooks, web pages, slide decks, blog posts, man pages and more.
. A text processor and toolchain for translating AsciiDoc documents into various formats (called _backends_), including HTML, DocBook, PDF and ePub{empty}footnote:[There are two implementations of the AsciiDoc processor. The original processor, named AsciiDoc, is written in Python. A more modern implementation, named Asciidoctor, is written in Ruby.].

AsciiDoc belongs to the family of {markup-ref}[lightweight markup languages], the most renowned of which is {markdown-ref}[Markdown].
AsciiDoc stands out from this group because it supports all the structural elements necessary for drafting articles, technical manuals, books, presentations and prose.
In fact, it's capable of meeting even the most advanced publishing requirements and technical semantics.


Serving as testament of this fact, many O'Reilly authors, including https://github.com/matthewmccullough[Matthew McCullough], https://github.com/tlberglund[Tim Berglund], https://github.com/oreillymedia/etudes-for-erlang[Simon St.Laurent] and http://www.apeth.net/matt/iosbooktoolchain.html[Matt Neuburg], have used AsciiDoc to write their books for that iconic technical library.

From the very beginning, AsciiDoc was designed to be a shorthand replacement for http://www.docbook.org/whatis[DocBook], one of the formats AsciiDoc can generate.
AsciiDoc can also produce beautiful HTML 5, PDFs, eBooks, man pages and even slide decks.
It has you covered from first draft to publishing.
////

=== Compared to MarkDown

NOTE: Section Pending

= Quick Starts

[partintro]
--
NOTE: Section Pending
--

== Installation Quick Start

NOTE: Section Pending

== Usage Quick Start

NOTE: Section Pending

=== Using the Command Line Interface

include::{includedir}/command-line-usage.adoc[]

=== Using the Ruby API

include::{includedir}/api-intro.adoc[]

include::{includedir}/load-render-api.adoc[]

You can also use the API to <<user-manual#render-strings,render strings>> and <<user-manual#provide-custom-templates,load custom templates>>.

== Syntax Quick Start

NOTE: Section Pending

== Custom Output Quick Start

NOTE: Section Pending

= Getting Started

[partintro]
--
NOTE: Section Pending
--

== System Requirements

include::{includedir}/install-upgrade-asciidoctor.adoc[tags=systemreq]

== Installing the Asciidoctor Ruby Gem

include::{includedir}/install-upgrade-asciidoctor.adoc[tags=basicgem]

.Two API Flavors
****
In addition to the CLI, Asciidoctor provides a <<api,Ruby API>>.
The API is intended for integration with other software projects and is suitable for server-side applications, such as Rails, Sinatra and GitHub.

Asciidoctor also has a Java API that mirrors the Ruby API.
The Java API calls through to the Ruby API using an embedded JRuby runtime.
See the {java}[Asciidoctor Java integration project] for more information.
****

=== Install with Bundler

include::{includedir}/install-upgrade-asciidoctor.adoc[tags=bundler]

=== Install with +yum+
 
include::{includedir}/install-upgrade-asciidoctor.adoc[tags=yum]

=== Install with +apt-get+
 
include::{includedir}/install-upgrade-asciidoctor.adoc[tags=aptget]

== Upgrading the Asciidoctor Ruby Gem

include::{includedir}/install-upgrade-asciidoctor.adoc[tags=upgrade]

== Extensions and Integrations

NOTE: Section Pending

= Terms and Concepts

[partintro]
--
All of the content in an Asciidoctor document, including lines of text, predefined styles, and processing commands, is classified as either a block or an inline element.
Within each of these elements are an array of styles, options, and functions that can be applied to your content.

This section will provide you with an overview of what each of these elements and sub-elements are and the basic syntax and rules for using them.
--

== Elements

include::{includedir}/element.adoc[]

== Macros

NOTE: Section pending

== Attributes

include::{includedir}/attr.adoc[tags=intro]

=== Attribute assignment precedence

include::{includedir}/attr.adoc[tags=order]

=== Using attributes: set, assign, and reference

include::{includedir}/attr-use.adoc[]

=== Built-in data attributes

include::{includedir}/attr-data.adoc[]

=== Setting attributes on a document

include::{includedir}/attr-doc.adoc[]

=== Setting attributes on an element

include::{includedir}/attr-element.adoc[tags=intro]

==== Positional attribute

include::{includedir}/attr-element.adoc[tags=pos]

==== Named attribute

include::{includedir}/attr-element.adoc[tags=name]

==== Style

include::{includedir}/attr-style.adoc[tags=intro]

==== Id

include::{includedir}/attr-style.adoc[tags=id]

===== Block assignment

include::{includedir}/attr-style.adoc[tags=bl]

===== Inline assignment

include::{includedir}/attr-style.adoc[tags=in]

==== Role

NOTE: Section introduction pending

An element can be assigned numerous roles.

===== Block assignment

In an attribute list, there are two ways to assign a role attribute to a block element.

. Prefixing the name with a dot (+.+).
. Specifying the name with +role="name"+.

[source]
----
[.summary]
* Review 1
* Review 2
----

[source]
----
[role="summary"]
* Review 1
* Review 2
----

To specify multiple roles using the shorthand syntax, separate them by dots.

[source]
----
[.summary.incremental]
* Review 1
* Review 2
----

[source]
----
[role="summary,incremental"]
* Review 1
* Review 2
----

===== Inline assignment

The role (+.+) shorthand can be used on inline quoted text.

.Quoted text with +role+ assignments using traditional AsciiDoc syntax
----
[big goal]*free the world*
----

.Quoted text with +role+ assignments using Asciidoctor shorthand
----
[.big.goal]*free the world*
----

* The attribute list preceding formatted text can be escaped using a backslash (e.g., +\[role]*bold*+). In this case, the text will still be formatted, but the attribute list will unescaped and output verbatim.

.Role-playing for text enclosed in backticks
To align with other formatted (i.e., quoted) text in AsciiDoc, roles can now be assigned to text enclosed in backticks.

Given:

```
[rolename]`escaped monospace text`
```

the following HTML is produced:

```html
<code class="rolename">escaped monospace text</code>
```

Using the new shorthand notation in Asciidoctor 0.1.4, an id (i.e., anchor) can also be specified:

```
[#idname.rolename]`escaped monospace text`
```

which produces:

```html
<a id="idname"></a><code class="rolename">escaped monospace text</code> 
```
 
Keep in mind that text enclosed is not subject to other inline substitutions, but rather passed through as is.

==== Options

The options attribute is a versatile named attribute that can contain a comma separated list of values.

It can also be defined globally with an attribute entry.

===== Block assignment

In an attribute list, there are three ways to assign an options attribute to a block element.

. Prefixing the value with a percent sign (+%+).
. Specifying the value with +opts="name"+
. Specifying the value with +options="name"+.

Consider a table block with the three option values +header+, +footer+, and +autowidth+. 

Here's how the options are assigned to the table using the shorthand notation (+%+).

.Shorthand Asciidoctor syntax
----
[%header%footer%autowidth]
|===
| Cell A | Cell B
|===
----

Here's how the options are assigned to the table using +options=+.

.Traditional AsciiDoc syntax
----
[options="header,footer,autowidth"]
|===
| Cell A | Cell B
|===
----

Let's consider the options when combined with other attributes. 

.Shorthand Asciidoctor block syntax
----
[horizontal.properties%step]
property 1:: does stuff
property 2:: does different stuff
----

.Traditional AsciiDoc block syntax
----
[horizontal, role="properties", options="step"]
property 1:: does stuff
property 2:: does different stuff
----

=== Assigning document variables inline

Document variables can be assigned using the following syntax:

 {set:<attrname>[!][:<value>]}

For example:

[source,asciidoc]
{set:sourcedir:src/main/java}

It's effectively the same as:

 :sourcedir: src/main/java

This is important for being able to assign document attributes in places where attribute entry lines are not normally processed, such as in a table cell.

////
An example of where this might be used is documented in the {doc-variable-ref}[how to set the background color of a table cell] tip.
////

=== Attribute conventions

NOTE: Section Pending

==== Catch a missing or undefined attribute

include::{includedir}/attr-miss.adoc[]

= Building a Document

[partintro]
--
NOTE: Introduction Pending
--

== Text Editor

include::{includedir}/text-editor.adoc[]

== Document Types

include::{includedir}/doctype.adoc[]

== Basic Document Anatomy

NOTE: Section pending

[[doc-header]]
== Header

include::{includedir}/header-intro.adoc[]

=== Document title

include::{includedir}/header-title.adoc[]

=== Author and email

include::{includedir}/author.adoc[]

=== Revision number, date, and remark

include::{includedir}/revision.adoc[]

=== Metadata

include::{includedir}/meta.adoc[tags=intro]

==== Description

include::{includedir}/meta.adoc[tags=desc]

==== Keywords

include::{includedir}/meta.adoc[tags=key]

==== Alternate title

include::{includedir}/meta.adoc[tags=atitle]

==== Custom metadata, styles and functions

include::{includedir}/meta.adoc[tags=cmeta]

=== Header summary

include::{includedir}/sum-header.adoc[]

[[doc-preamble]]
== Preamble

include::{includedir}/preamble-tut.adoc[]

== Sections

include::{includedir}/sections.adoc[tags=intro]

=== Titles as headings

include::{includedir}/sections.adoc[tags=heading]

=== Title id and prefix

include::{includedir}/sections.adoc[tags=id]

=== Links

include::{includedir}/sections.adoc[tags=link]

=== Anchors

include::{includedir}/sections.adoc[tags=anchor]

=== Numbering

include::{includedir}/sections.adoc[tags=number]

=== Discrete or floating section titles

include::{includedir}/float-title.adoc[]

=== Section styles

include::{includedir}/section-styles.adoc[]

=== Sections summary

include::{includedir}/sum-section.adoc[]

== Blocks

NOTE: Section Pending

=== Title

You can assign a title to any paragraph, list, delimited block, or block macro.
In most cases, the title is displayed immediately above the content.
If the content is a figure or image, the title is displayed below the content.

A block title is defined on a line above the element.
The line must begin with a dot (+.+) and be followed immediately by the title text with no spaces in between.

Here's an example of a list with a title:

[source]
----
.TODO list
- Learn the AsciiDoc syntax
- Install Asciidoctor
- Write my document
----

=== Metadata

In addition to a title, a block can be assigned additional metadata including:

* Id (i.e., anchor)
* Style (first unnamed block attribute)
* Named block attributes

Here's an example of a quote block with metadata:

[source]
----
.Gettysburg Address <1>
[[gettysburg]] <2>
[quote, Abraham Lincoln, Soldiers' National Cemetery Dedication] <3> <4> <5>
____
Four score and seven years ago our fathers brought forth
on this continent a new nation...

Now we are engaged in a great civil war, testing whether
that nation, or any nation so conceived and so dedicated,
can long endure. ...
____
----
<1> Title: Gettysburg Address
<2> Id: gettysburg
<3> Style: quote
<4> attribution: Abraham Lincoln (Named block attribute)
<5> citetitle: Dedication of the Soldiers' National Cemetery (Named block attribute)

TIP: A block can have multiple block attribute lines.
The attributes will be aggregated.
If there is a name conflict, the last attribute defined wins.

Some metadata is used as supplementary content, such as the title, whereas other metadata controls how the block is rendered, such as the style.

////
Block id

NOTE: Pending

Block Style

A block style is the first positional attribute in the block attribute list.
////

=== Delimited blocks

The AsciiDoc syntax provides a set of components for including non-paragraph text--such as block quotes, source code listings, sidebars and tables--in your document.
These components are referred to as _delimited blocks_ because they are surrounded by delimiter lines.

Within the boundaries of a delimited block, you can enter any content or blank lines.
The block doesn't end until the ending delimiter is found.
The delimiters around the block determine the type of block, how the content is processed and rendered and what elements are used to wrap the content in the output.

==== Optional delimiters

If the content is contiguous (not interrupted by blank lines), you can forgo the use of the block delimiters and instead use the block style above a paragraph to repurpose it as one of the delimited block types.

This format is often used for single-line listings:

[source]
----
[listing]
sudo yum install asciidoc
----

or single-line quotes:

[source]
----
[quote]
Never do today what you can put off 'til tomorrow.
----

==== Masquerading blocks

Some blocks can masquerade as other blocks, a feature which is controlled by the block style.

=== Built-in block style summary

The following table identifies the built-in paragraph and delimited blocks syntax, their purposes, and the substitutions performed on their contents.

[cols="1,1m,1m,3,1"]
|===
|Style |Paragraph |Delimiter |Purpose |Substitutions

|Admonition
|$$[<LABEL>]$$
d|Any delimiter
|Content labeled with a tag or icon, can masquerade as any delimited block type
|Varies

|Example
|$$[example]$$
|$$====$$
|Designates example content or defines an admonition block
|Normal

|Fenced
d|N/A
|$$```$$
|Source code or keyboard input is displayed as entered
|Verbatim

|Literal
|$$[literal]$$
|$$....$$
|Output text is displayed exactly as entered
|Verbatim

|Listing
|$$[listing]$$
|$$----$$
|Source code or keyboard input is displayed as entered
|Verbatim

|Quote
|$$[quote]$$
|$$____$$
|A quotation with optional attribution
|Normal

|Verse
|$$[verse]$$
|$$____$$
|A verse with optional attribution
|Normal

|Sidebar
|$$[sidebar]$$
|$$****$$
|Aside text and content rendered outside the flow of the document
|Normal

|Source
|$$[source]$$
|$$----$$
|Source code or keyboard input to be displayed as entered
|Verbatim

|Table
d|N/A
|$$\|===$$
|Displays tabular content
|Varies

|Open
d|Most block styles
|$$--$$
|Anonymous block that can act as any block except _passthrough_ or _table_ blocks
|Varies

|Passthrough
d|N/A
|$$++++$$
|Raw text that is passed to the output unprocessed
|Pass

|Comment
d|N/A
|$$////$$
|Private notes that are not displayed in the output
|None

|===

This table shows the substitutions performed by each substitution group referenced in the previous table.

.Substitution groups
|===
|Group     |Special characters  |Quotes |Attributes |Replacements |Macros |Post replacements |Callouts

h|Header   |Yes                 |No     |Yes        |No           |No     |No                |No
h|None     |No                  |No     |No         |No           |No     |No                |No
h|Normal   |Yes                 |Yes    |Yes        |Yes          |Yes    |Yes               |No
h|Pass     |No                  |No     |Yes        |No           |Yes    |No                |No
h|Verbatim |Yes                 |No     |No         |No           |No     |No                |Yes
|===

== Paragraph

include::{includedir}/para.adoc[]

=== Line breaks

include::{includedir}/para-line-break.adoc[]

=== Lead style

include::{includedir}/para-lead.adoc[]

== Text Formatting

include::{includedir}/text.adoc[]

=== Bold and italic

include::{includedir}/text-bold-italic.adoc[]

=== Quotation marks and apostrophes

include::{includedir}/text-quote-apos.adoc[]

=== Subscript and superscript

include::{includedir}/text-sub-sup.adoc[]

=== Monospace

include::{includedir}/text-mono.adoc[]

=== Custom styling with attributes

include::{includedir}/text-css.adoc[]

== Unordered Lists

include::{includedir}/u-list.adoc[]

=== Nested

include::{includedir}/u-list-nest.adoc[]

=== Complex list content

include::{includedir}/u-list-complex.adoc[]

=== Custom markers

include::{includedir}/u-list-marker.adoc[]

=== Checklist

include::{includedir}/u-list-check.adoc[]

=== Summary

NOTE: Pending

== Ordered Lists

include::{includedir}/o-list.adoc[]

=== Nested

include::{includedir}/o-list-nest.adoc[]

=== Numbering styles

include::{includedir}/o-list-num.adoc[]

=== Summary

NOTE: Pending

== Labeled List

include::{includedir}/l-list.adoc[]

=== Question and answer style list

include::{includedir}/l-list-qa.adoc[]

=== Summary

NOTE: Section pending

== Tables

include::{includedir}/table.adoc[]

=== Columns

include::{includedir}/table-col.adoc[]

=== Column specifiers

include::{includedir}/table-col-spec.adoc[]

=== Cell specifiers

include::{includedir}/table-cell-spec.adoc[]

=== Header row

include::{includedir}/table-header.adoc[]

=== Footer row

include::{includedir}/table-footer.adoc[]

=== Table lines, placement, and size

include::{includedir}/table-line-size.adoc[]

=== Data formats

include::{includedir}/table-data.adoc[]

=== Summary

include::{includedir}/sum-table.adoc[]

== Horizontal Rules

----
'''
----

====
'''
====

=== Markdown-style horizontal rules

include::{includedir}/hr-markdown.adoc[]

=== Summary

NOTE: Section pending

== Page break

----
<<<
----

== URLs

include::{includedir}/url.adoc[]

=== Link to relative files

include::{includedir}/url-relative.adoc[]

=== Cross references

include::{includedir}/xref.adoc[]

=== Inter-document cross references

include::{includedir}/xref-interdoc.adoc[]

=== Summary

include::{includedir}/sum-url.adoc[]

== Images

include::{includedir}/images.adoc[]

=== Set the images directory

include::{includedir}/images-dir.adoc[]

==== Include images by full URL

include::{includedir}/images-url.adoc[]

=== Put images in their place

include::{includedir}/images-position-intro.adoc[]

==== Positioning attributes

include::{includedir}/images-position-attr.adoc[]

==== Positioning roles

include::{includedir}/images-position-role.adoc[]

==== Framing roles

include::{includedir}/images-position-frame.adoc[]

==== Control the float

include::{includedir}/images-position-float.adoc[]

=== Summary

include::{includedir}/sum-images.adoc[]

== Video

include::{includedir}/video.adoc[]

=== YouTube and Vimeo videos

include::{includedir}/video-external.adoc[]

=== Summary

include::{includedir}/sum-video.adoc[]

== Audio

NOTE: Pending

////
Macro name:

 audio::ocean_waves.mp3[options="loop]"
////

=== Summary

include::{includedir}/sum-audio.adoc[]

== Admonition

include::{includedir}/admonition.adoc[]

== Sidebar

include::{includedir}/sidebar.adoc[]

== Example

include::{includedir}/example.adoc[]

== Quote

include::{includedir}/quote.adoc[]

=== Quoted paragraph

include::{includedir}/quote-para.adoc[]

=== Air quotes

include::{includedir}/quote-air.adoc[]

=== Markdown-style blockquotes

include::{includedir}/quote-markdown.adoc[]

== Verse

include::{includedir}/verse.adoc[]

== Comments

include::{includedir}/comment.adoc[]

= Controlling Your Content

[partintro]
--
NOTE: Part introduction pending
--

== Text Substitutions

include::{includedir}/subs.adoc[]

=== Special characters

include::{includedir}/subs-specchar.adoc[]

=== Quotes

include::{includedir}/subs-quote.adoc[]

=== Attributes

include::{includedir}/subs-attr.adoc[]

=== Replacements

include::{includedir}/subs-repl.adoc[]

[[sub-macros]]
=== Macros

include::{includedir}/subs-macro.adoc[]

=== Post replacements

include::{includedir}/subs-post.adoc[]

=== Applying substitutions

include::{includedir}/subs-apply.adoc[]

=== Preventing substitutions

include::{includedir}/subs-prevent.adoc[]

== Literal Text and Blocks

include::{includedir}/literal.adoc[]

== Listing Blocks

include::{includedir}/listing.adoc[]

=== To wrap or to scroll

include::{includedir}/listing-wrap.adoc[]

=== Summary

NOTE: Pending

[[passthru]]
== Macro and Block Passthroughs

include::{includedir}/pass-intro.adoc[]

=== Passthrough macros

include::{includedir}/pass-macro.adoc[]

////

This section is not valid until Issue #720 is corrected.

==== Nesting blocks and passthrough macros

When you're using passthroughs inside literal and listing blocks, it can be easy to forget that the triple-plus, double-dollar, and backtick passthroughs are macros.
If you want to enable the passthroughs, make sure to assign the +macros+ value to the +subs+ attribute.

....
[source,java]
[subs="verbatim,quotes,macros"]
----
protected void configure(HttpSecurity http) throws Exception {
    http
        .authorizeRequests()
            **.antMatchers("/resources/$$**$$").permitAll()**
            .anyRequest().authenticated()
            .and()
        .formLogin()
            .loginPage("/login")
            .permitAll();
----
....

====
[source,java]
[subs="verbatim,quotes,macros"]
----
protected void configure(HttpSecurity http) throws Exception {
    http
        .authorizeRequests()
            **.antMatchers("/resources/$$**$$").permitAll()**
            .anyRequest().authenticated()
            .and()
        .formLogin()
            .loginPage("/login")
            .permitAll();
----
====

////

=== Block passthroughs

include::{includedir}/pass-block.adoc[]

== Open Blocks

include::{includedir}/open.adoc[]

= Enriching Your Content

[partintro]
--
NOTE: Part introduction pending
--

== User Interface Macros

include::{includedir}/ui-intro.adoc[]

=== Keyboard shortcuts

include::{includedir}/ui-key.adoc[]

=== Menu selections

include::{includedir}/ui-menu.adoc[]

=== UI buttons

include::{includedir}/ui-button.adoc[]

== Icons

include::{includedir}/icon-intro.adoc[]

=== Admonition icons

include::{includedir}/icon-admon.adoc[]

=== Inline icons

include::{includedir}/icon-inline.adoc[]

==== Size, rotate, and flip

include::{includedir}/icon-position.adoc[]

==== Link and window

include::{includedir}/icon-link.adoc[]

==== Regular icon attributes

include::{includedir}/icon-reg.adoc[]

== Callouts

NOTE: Pending

=== Callouts don't get caught in copy

include::{includedir}/callout-copy.adoc[]

=== XML-friendly callouts

include::{includedir}/callout-xml.adoc[]

=== Callout icons

include::{includedir}/callout-icon.adoc[]

== Source Code Blocks

NOTE: Pending

=== Syntax Highlighting

include::{includedir}/hl.adoc[]

==== Pygments installation

include::{includedir}/hl-pygment.adoc[]

== Include Directive

include::{includedir}/include-directive.adoc[]

=== Selecting parts of a document to include

include::{includedir}/include-lines-tags.adoc[]

=== Normalizing block indentation

include::{includedir}/indent-include.adoc[]

=== Include files relative to a common source directory

include::{includedir}/relative-include.adoc[]
 
=== Include content from a URI

include::{includedir}/uri-include.adoc[]

== Metadata and Chunking

NOTE: Section pending

== Docinfo file

include::{includedir}/docinfo-intro.adoc[]

=== Create a docinfo file

include::{includedir}/docinfo-create.adoc[]

=== Docinfo attributes and file names

include::{includedir}/docinfo-attr.adoc[]

=== Footer docinfo files

include::{includedir}/docinfo-footer.adoc[]

=== Attribute substitution

include::{includedir}/docinfo-attr-subs.adoc[]

== Counter Attributes

include::{includedir}/counter.adoc[]

= Structuring, Navigating, and Referencing Your Content

[partintro]
--
include::{includedir}/structure-intro.adoc[]
--

== Title Page

NOTE: Section pending

[[user-colophon]]
== Colophon

include::{includedir}/colophon.adoc[]

[[user-toc]]
== Table of Contents

include::{includedir}/toc-intro.adoc[]

=== Left or right column layout

include::{includedir}/toc-layout.adoc[tags=column]

=== Manual placement

include::{includedir}/toc-layout.adoc[tags=place]

=== Title

include::{includedir}/toc-custom.adoc[tags=title]

=== Levels

include::{includedir}/toc-custom.adoc[tags=level]

=== Table of Contents summary

include::{includedir}/sum-toc.adoc[]

[[user-abstract]]
== Abstract

include::{includedir}/abstract.adoc[]

[[user-preface]]
== Preface

include::{includedir}/preface.adoc[]

[[user-dedication]]
== Dedication

include::{includedir}/dedication.adoc[]

== Book Parts and Part Introductions

include::{includedir}/book-part.adoc[]

[[user-appendix]]
== Appendix

NOTE: Section pending

[[user-glossary]]
== Glossary

NOTE: Section pending

[[user-biblio]]
== Bibliography

.References
----
'The Pragmatic Programmer' <<prag>> should be required reading for
all developers.

[bibliography]
- [[[prag]]] Andy Hunt & Dave Thomas. 'The Pragmatic Programmer:
  From Journeyman to Master'. Addison-Wesley. 1999.
- [[[seam]]] Dan Allen. 'Seam in Action'. Manning Publications.
  2008.
----

====
'The Pragmatic Programmer' <<prag>> should be required reading for
all developers.

[bibliography]
- [[[prag]]] Andy Hunt & Dave Thomas. 'The Pragmatic Programmer:
  From Journeyman to Master'. Addison-Wesley. 1999.
- [[[seam]]] Dan Allen. 'Seam in Action'. Manning Publications.
  2008.
====

[[user-index]]
== Index

NOTE: Section pending

[[user-footnotes]]
== Footnotes

.Normal and reusable footnotes
----
A statement.footnote:[Clarification about this statement.]

A bold statement.footnoteref:[disclaimer,These opinions are my own.]

Another bold statement.footenoteref:[disclaimer]
----

====
[.unstyled]
|===
a|
A statement.footnote:[Clarification about this statement.]

A bold statement.footnoteref:[disclaimer,These opinions are my own.]

Another bold statement.footnoteref:[disclaimer]
|===
====

= Processing Your Content

[partintro]
--
include::{includedir}/process-intro.adoc[]
--

== Selecting an Output Format

include::{includedir}/output-format.adoc[]

////
The AsciiDoc processor supports numerous backends, including:

+xhtml11+:: XHTML 1.1 markup styled with CSS2.
AsciiDoc's default backend.
////

== HTML

// TODO: expand this introduction 

Asciidoctor's default output format is HTML.

+html5+:: HTML 5 markup styled with CSS3.

=== Using the command line

include::{includedir}/html-command-line.adoc[]

=== Using the Ruby API

include::{includedir}/html-ruby-api.adoc[]

=== Styling the HTML with CSS

include::{includedir}/html-styles.adoc[]

=== Managing images

include::{includedir}/html-manage-images.adoc[]

=== CodeRay and Pygments stylesheets

include::{includedir}/html-code-styles.adoc[]

== DocBook

include::{includedir}/docbook.adoc[]

== Man pages

include::{includedir}/manpage.adoc[]

== PDFs

NOTE: To convert your document to PDF, you'll need to use the new {fopdf-ref}[Asciidoctor fopdf extension].
Directions for using the extension are documented in its {fopdf-doc-ref}[README].

////
WARNING: The content regarding PDF generation below this warning block is out of date. Asciidoctor 0.1.4 does not require the +a2x+ tool to produce PDFs. New instructions pending.

PDF is a nice format for presenting a final version of a document.
For legacy reasons, the conversion to PDF is handled by a separate program in the AsciiDoc distribution, {a2x}[+a2x+].

+a2x+ accepts a DocBook file, like the +sample.xml+ file created in the section above, as input and converts it to a PDF.

In your console: 

. Call the +a2x+ program
. Select the output format with +-f+ (+--format+)
. Followed by the format type +pdf+

//
 $> a2x -f pdf sample.xml

A PDF document, named +sample.pdf+, will now be present in the current directory:

 $> ls
 sample.adoc  sample.html  sample.pdf  sample.xml

You can view the PDF using any PDF viewer.

Rather than converting from AsciiDoc to DocBook and then from DocBook to PDF in two steps, +a2x+ can go directly from AsciiDoc to PDF in a single call:

 $> a2x -f pdf sample.adoc
////

== Preview Your Content

NOTE: Section pending

=== Guard/Live viewer

NOTE: Section pending

== Process multiple source files from the CLI

include::{includedir}/process-multi.adoc[]

== Specifying an output file

include::{includedir}/file-output.adoc[]
 
== Running Asciidoctor Securely

include::{includedir}/secure.adoc[]

=== Set the safe mode in the CLI

include::{includedir}/secure-cli.adoc[]

=== Set the safe mode in the API

include::{includedir}/secure-api.adoc[]

=== Set attributes based on the safe mode

include::{includedir}/secure-attr.adoc[]

= Customizing Your Output

[partintro]
--
Asciidoctor provides a default stylesheet and built-in backends so you can quickly process and render your document, but it also lets you use custom stylesheets and backends.
The Asciidoctor project includes alternative stylesheet themes from <<stylesheet-factory,the stylesheet factory>> and <<slideshows,specialized backends>>, such as the <<deckjs,Deck.js backend>>.
You can also create your own <<custom-themes,themes>> and <<custom-backends,backends>>.
--

== Custom Themes

NOTE: Section introduction pending

=== Creating a theme

include::{includedir}/create-theme.adoc[]

=== Applying a theme

include::{includedir}/apply-theme.adoc[]

== Stylesheet Factory

include::{includedir}/factory-intro.adoc[]

=== Setting up the factory

include::{includedir}/factory-setup.adoc[tags=setup]

==== Install the gems

include::{includedir}/factory-setup.adoc[tags=gem]

==== Build the stylesheets

include::{includedir}/factory-setup.adoc[tags=build]


=== Applying a stylesheet

include::{includedir}/factory-apply.adoc[]

=== Generate an HTML document

include::{includedir}/factory-gen.adoc[]

=== External preview

include::{includedir}/factory-preview.adoc[]

== Slideshows

The conversion to HTML-based slides is handled by a custom backend.
The backends usually requires that you adhere to a set of conventions to define a slide and its content.
But there's nothing in that content that restricts the document from being converted to a regular HTML page or PDF.

The first backend created was the one for deck.js.
Asciidoctor has backends for generating dzslides and reveal.js presentations as well.
Backends for other presentation frameworks are in the works.

[[deckjs]]
=== Deck.js

The {backend-git}[deck.js backend] for Asciidoctor is a collection of Haml templates that transform an AsciiDoc document to HTML 5-based slides animated by {deckjs-org}[deck.js].

==== Gem requirements

The Asciidoctor deck.js backend requires the following gems:

* asciidoctor
* tilt
* haml

To determine what gems are installed on your system, open a terminal window and type:
 
 $ gem list --local

A list of installed gems will be returned.

If you're missing the +asciidoctor+, +tilt+, or +haml+ gems, install them from the command line with +gem install+.

 $ gem install asciidoctor tilt haml

==== Backend and deck.js installation

. Download or +git clone+ the {backend-git}[Asciidoctor backends] repository.

 $ git clone git://github.com/asciidoctor/asciidoctor-backends.git

. Create a directory named +deck.js+ inside your working directory (i.e. where your AsciiDoc document resides).

. {deckjs-zip}[Download] and extract the deck.js archive or +git clone+ the {deckjs-git}[deck.js] repository into the +deck.js+ directory you created in step 2.

 $ git clone git://github.com/imakewebthings/deck.js.git

. If you plan to split your slides, {decksplitjs-git}[download the +deck.split.js+ extension] and copy it into the +deck.js/extensions+ directory.

. If you want to use the fullscreen photo feature, create an +images+ directory in your working directory.

==== Deckjs backend attributes

There are a number of document attributes specific to the +deckjs+ backend.

.+deckjs+ backend document attributes
[cols="2,1,2m"]
|===
|Attribute |Description |Example

|:backend: deckjs
|Activates the deck.js backend to render the document as a deck.js presentation
|:backend: deckjs

|:deckjs_theme: <theme>
|Sets the deck.js theme to neon, swiss or web-2.0
|:deckjs_theme: web-2.0

|:deckjs_transition: <type>
|Sets the transition style to horizontal-slide, vertical-slide or fade
|:deckjs_transition: fade

|:customjs: <javascript location>
|Sets a custom javascript file; can be used as a deck.js custom configuration
|:customjs: <javascript location>

|:customcss: <css location>
|Sets a custom css file
|:customcss: <css location>

|:menu:
|Toggle to and from a grid layout overview of all the slides by pressing the +m+ key
|:menu:

|:navigation:
|Renders clickable previous and next navigation icons on the slides
|:navigation:

|:status:
|Renders the current slide number and total number of slides
|:status:

|:split:
|Registers the split module for use in the document
|:split:
|===

NOTE: You can also specify a custom stylesheet using the +stylesheet+ attribute, which customizes AsciiDoc elements like section, paragraph, images, etc.

The attributes described in the table above are set in the header of your document.

.Header with +deckjs+ backend attributes
....
= Presentation Title
Presenter Name
:backend: deckjs
:deckjs_theme: web-2.0
:deckjs_transition: horizontal-slide
:navigation:
....

==== Slide syntax examples

Structuring a slideshow and writing the slide content uses the same syntax as a typical AsciiDoc document, with a few added features.

Let's see some examples of the +deckjs+ backend features:

.Slide titles and background images
----
= Title of Presentation <1>
Presenter Name
:backend: deckjs
:deckjs_transition: fade
:navigation:

== Title of Slide One <2>

This is the first slide after the title slide.

[canvas-image="images/example.jpg"] <3>
== Slide Two's Title will not be displayed <4>

[role="canvas-caption", position="center-up"] <5>
This text is displayed on top of the example.jpg image.
----
<1> The presentation title and author's name will be displayed on the title slide.
<2> Each new slide is designated by a level 1 section title (`==`).
<3> The +canvas-image+ attribute embeds a fullscreen image as a slide background. Position the attribute above the title of the slide you want the image applied to.
<4> When the +canvas-image+ attribute is applied to a slide, that slide's title will not be displayed.
<5> +canvas-caption+ applies a colored box around the caption text. +position+ specifies the location of the caption block (bottom-left, top-left, bottom-right, top-right, center-up, center-down)

.Stepped paragraphs, lists, and blocks
----
== Stepped paragraphs

[options="step"]
This paragraph is displayed first.

[options="step"]
Then this paragraph is displayed when the _Next_ arrow is clicked.

== Stepped list items

[options="step"]
* A bullet is displayed each time the _Next_ arrow is clicked.
* B
* C

== Stepped blocks

[options="step"]
----
Block one
----

[options="step"]
----
Block two
----
----

The +step+ option reveals each paragraph, bullet, etc. separately each time you click the _Next_ arrow.

WARNING: The original AsciiDoc +deckjs+ backend for the AsciiDoc processor used the option +incremental+ instead of +step+. 
We've changed it to +step+ in order to save you some typing.

.Split
----
= Presentation Title
Presenter Name
:backend: deckjs
:split: <1>

== This Slide is Split

This Slide will act like

<<< <2>

three individual slides with the same title

<<<

once the document is rendered.
----
<1> To create multiple, consecutive slides with the same title, set the +split+ attribute in the document header.
<2> Then, within a slide, insert `<<<` to specify the slide breaks.

==== Rendering

To render your presentation as HTML5, execute the command:

 $ asciidoctor -T ../asciidoctor-backends/haml presentation.adoc

. The command +-T+ (+--template-dir+) tells the Asciidoctor processor to override the built-in backends.
. Directly after +-T+ is the path to where you saved or cloned the Asciidoctor backends repository containing the +deckjs+ backend (step 1 under the <<backend-and-deckjs-installation,installation section>>).  

== Custom Backends

NOTE: Section pending

=== Creating a backend

NOTE: Section pending

==== Storing multiple templates

Custom templates can be stored in multiple directories.
That means you can build on an existing backend by copying only the templates you want to modify.
Then, just pass both the directory holding the original templates and the directory containing your customized templates when you invoke Asciidoctor.

In the CLI, multiple template directories are specified by using the +-T+ option multiple times.

 $ asciidoctor -T /path/to/original/templates -T /path/to/modified/templates sample.adoc

In the API, multiple template directories are specified by passing an array to the +template_dirs+ option:

```ruby
Asciidoctor.render_file 'sample.adoc', :safe => :safe, :in_place => true,
    :template_dirs => ['/path/to/original/templates', '/path/to/modified/templates']
```

////
Styling DocBook and PDF Output

NOTE: Section pending
////

= Publishing Your Content

[partintro]
NOTE: Section pending

== Repositories

NOTE: Section pending

== Static website generators

NOTE: Section pending

=== Front matter added for static site generators

include::{includedir}/static-front.adoc[]

==== Configuring attributes for Awestruct

include::{includedir}/static-awe.adoc[]

[[api]]
= Using Asciidoctor's API

[partintro]
--
include::{includedir}/api-intro.adoc[]
--

== Load and Render a File Using the API

include::{includedir}/load-render-api.adoc[]

=== Render strings

include::{includedir}/string-api.adoc[]

== Provide custom templates

include::{includedir}/templates-api.adoc[]

= Extensions

[partintro]
--
include::{includedir}/exten-intro.adoc[]
--

== Extension Points

include::{includedir}/exten-point.adoc[]

== Example Extensions

Below are several examples of extensions and how they are registered.

=== Preprocessor example

include::{includedir}/exten-pre.adoc[]

=== Treeprocessor example

include::{includedir}/exten-tree.adoc[]

=== Postprocessor example

include::{includedir}/exten-post.adoc[]

=== Block processor example

include::{includedir}/exten-block.adoc[]

=== Block macro processor example

include::{includedir}/exten-macro.adoc[]

=== Inline macro processor example

include::{includedir}/exten-in-macro.adoc[]

=== Include processor example

include::{includedir}/exten-include.adoc[]

= Build Integrations and Implementations

[partintro]
NOTE: Section pending

== Java

NOTE: Section pending

== Gradle

NOTE: Section pending

== Maven

NOTE: Section pending

== JavaDoc

NOTE: Section pending

== JavaScript

NOTE: Section pending

== Yard

NOTE: Section pending

== Rdoc

NOTE: Section pending

= Conversions and Migrations

[partintro]
NOTE: Section pending

== Convert Markdown *to* Asciidoctor

NOTE: Section pending

== Migrate from AsciiDoc to Asciidoctor

NOTE: Section pending

= Conclusion

[partintro]
NOTE: Section pending

= Resources

[partintro]
NOTE: Section pending

== Copyright and License

include::{includedir}/project-lic.adoc[]

== Authors

include::{includedir}/project-author.adoc[]

// TODO fill in this section and enable
// Thanks, acknowledgments, and credits

:leveloffset: 1
[[troubleshoot]]
include::{includedir}/troubleshoot.adoc[]
:leveloffset: 0

== Additional Help

NOTE: Section pending

[glossary]
== Glossary

[glossary]
admonition paragraph:: a callout paragraph that has a label or icon indicating its priority
admonition block:: a callout block containing complex content that has a label or icon indicating its priority
backend:: a set of templates for converting AsciiDoc source to different output format
cross reference:: a link from one location in the document to another location marked by an anchor
list continuation:: a plus sign (`+`) on a line by itself that connects adjacent lines of text to a list item
quoted text:: text which is enclosed in special punctuation to give it emphasis or special meaning

NOTE: Section expansion pending

:leveloffset: 1
[[asciidoctor-vs-asciidoc]]
[appendix]
include::asciidoc-asciidoctor-diffs-table.adoc[]

:leveloffset: 1
[[char-ref-table]]
[appendix]
include::character-ref-attributes.adoc[]

////

Include license and copyright

== Index

NOTE: Section pending

////

