= What is Asciidoctor?
Dan Allen, Sarah White
:page-layout: docs
:sectnums:
ifndef::env-site[]
:toc:
:idprefix:
:idseparator: -
endif::[]
:gh-org: https://github.com/asciidoctor

Asciidoctor is a _fast_ text processor and publishing toolchain for converting AsciiDoc content to HTML5, DocBook 5 or 4.5, EPUB3, PDF and other formats.
Asciidoctor is the leading implementation of the AsciiDoc syntax, first introduced and implemented in the Python-based AsciiDoc project.

Asciidoctor is written in Ruby and can be used on any Ruby runtime, including JRuby.
It can also be run on the JVM via AsciidoctorJ, a formal Java API which leverages JRuby underneath, or run in JavaScript using Asciidoctor.js, a transcompiled version of the Ruby codebase.

Asciidoctor is open source, made available under the MIT license.
The Asciidoctor RubyGem is published to http://rubygems.org/gems/asciidoctor[rubygems.org] and can also be installed on several popular Linux distributions using one of the provided packages.
The git repositories for the project are hosted under the {gh-org}[Asciidoctor organization on GitHub] to encourage the widest participation.

While Asciidoctor aims to offer full compliance with the AsciiDoc syntax implemented by AsciiDoc Python (http://asciidoctor.org/docs/asciidoc-asciidoctor-diffs[with some exceptions]), it's far more than just a clone of AsciiDoc Python.

== What's unique about the Asciidoctor implementation?

Asciidoctor renders AsciiDoc source files and strings to HTML 5, DocBook 4.5 and other formats, including HTML 5 presentations (deck.js, dzslides).

What follows are highlights of its most notable features.

.Built-in and custom templates
Asciidoctor uses a set of built-in ERB templates to generate HTML 5 and DocBook 4.5 output that is structurally equivalent to what AsciiDoc produces. 
Any of these templates can be replaced by a custom template written in any template language available in the Ruby ecosystem. 
Custom template rendering is handled by the https://github.com/rtomayko/tilt[Tilt] template abstraction library (among the most popular gems in the Ruby ecosystem).

.Parser and object model
Leveraging the Ruby stack isn't the only benefit of Asciidoctor. 
Unlike the AsciiDoc Python implementation, Asciidoctor parses and renders the source document in discrete steps. 
This makes rendering the document optional and gives Ruby programs the opportunity to extract, add or replace information in the document by interacting with the document object model Asciidoctor assembles. 
Developers can use the full power of the Ruby programming language to play with the content in the document.

.Performance and security
No coverage of Asciidoctor would be complete without mention of its 'speed'. 
Despite not being an original goal of the project, Asciidoctor has proven startlingly fast. 
It loads, parses and renders documents *50 times as fast* as the Python implementation. 
That's good news for developer productivity and good news for GitHub or any server-side application that needs to render AsciiDoc markup. 
Asciidoctor also offers several levels of security, further justifying its suitability for server-side deployments.

.Beyond Ruby
Asciidoctor's usage is not limited to the Ruby community. 
Thanks to http://jruby.org[JRuby], a port of Ruby to the JVM, Asciidoctor can be used inside Java applications as well.
Plugins are available for {gh-org}/asciidoctor-maven-plugin[Apache Maven],  {gh-org}/asciidoctor-gradle-plugin[Gradle], and https://github.com/ocpsoft/rewrite/tree/master/transform-markup[Rewrite].
These plugins are based on the {gh-org}/asciidoctor-java-integration[Java integration library] for Asciidoctor. 

Asciidoctor also ships with a command-line interface (cli). 
The Asciidoctor cli, link:/man/asciidoctor/[+asciidoctor+], is a drop-in replacement for the +asciidoc.py+ script from the AsciiDoc Python distribution.

== System requirements

Asciidoctor is published as a RubyGem and currently works with Ruby 1.8.7, Ruby 1.9.3, Ruby 2 (2.0.0 or better), JRuby 1.7, JRuby 9000 and Rubinius 2 (2.0 or better) on Linux, Mac and Windows. 
We expect it will work with other versions of Ruby as well.
