= What is Asciidoctor?
Dan Allen, Sarah White
:awestruct-layout: base
ifndef::awestruct[]
:toc:
:idprefix:
:idseparator: -
endif::awestruct[]
:gh-org: https://github.com/asciidoctor

Asciidoctor is a text processor and publishing toolchain for converting AsciiDoc markup into HTML 5, DocBook 4.5 and other formats.
Written in Ruby, Asciidoctor was the first project to implement the AsciiDoc syntax, first introduced by the Python AsciiDoc processor, in another language. 
Asciidoctor is an open source library (MIT licensed) and published as a Ruby gem to http://rubygems.org/gems/asciidoctor[rubygems.org]. 
The git repositories for the project are hosted under the {gh-org}[Asciidoctor organization on GitHub] to encourage continued growth.

While Asciidoctor aims to offer full compliance with the AsciiDoc syntax (with some exceptions, noted in the project link:/#differences-from-asciidoc[README]), it's more than just a clone.

== What's unique about the Asciidoctor implementation?

Asciidoctor renders AsciiDoc source files and strings to HTML 5, DocBook 4.5 and other formats, including HTML 5 presentations (deck.js, dzslides).

What follows are highlights of its most notable features.

.Built-in and custom templates
Asciidoctor uses a set of built-in ERB templates to generate HTML 5 and DocBook 4.5 output that is structurally equivalent to what AsciiDoc produces. 
Any of these templates can be replaced by a custom template written in any template language available in the Ruby ecosystem. 
Custom template rendering is handled by the https://github.com/rtomayko/tilt[Tilt] template abstraction library (among the most popular gems in the Ruby ecosystem).

.Parser and object model
Leveraging the Ruby stack isn't the only benefit of Asciidoctor. 
Unlike the AsciiDoc Python implementation, Asciidoctor parses and renders the source document in discrete steps. 
This makes rendering the document optional and gives Ruby programs the opportunity to extract, add or replace information in the document by interacting with the document object model Asciidoctor assembles. 
Developers can use the full power of the Ruby programming language to play with the content in the document.

.Performance and security
No coverage of Asciidoctor would be complete without mention of its 'speed'. 
Despite not being an original goal of the project, Asciidoctor has proven startlingly fast. 
It loads, parses and renders documents *25 times as fast* as the Python implementation. 
That's good news for developer productivity and good news for GitHub or any server-side application that needs to render AsciiDoc markup. 
Asciidoctor also offers several levels of security, further justifying its suitability for server-side deployments.

.Beyond Ruby
Asciidoctor's usage is not limited to the Ruby community. 
Thanks to http://jruby.org[JRuby], a port of Ruby to the JVM, Asciidoctor can be used inside Java applications as well.
Plugins are available for {gh-org}/asciidoctor-maven-plugin[Apache Maven],  {gh-org}/asciidoctor-gradle-plugin[Gradle], and https://github.com/ocpsoft/rewrite/tree/master/transform-markup[Rewrite].
These plugins are based on the {gh-org}/asciidoctor-java-integration[Java integration library] for Asciidoctor. 

Asciidoctor also ships with a command-line interface (cli). 
The Asciidoctor cli, link:/man/asciidoctor/[+asciidoctor+], is a drop-in replacement for the +asciidoc.py+ script from the AsciiDoc Python distribution.

== System requirements

Asciidoctor is published as a RubyGem and currently works with Ruby 1.8.7, Ruby 1.9.3, Ruby 2.0.0, JRuby 1.7.2 and Rubinius 1.2.4 on Linux, Mac and Windows. 
We expect it will work with other versions of Ruby as well.
