= What is AsciiDoc? Why do we need it?
Dan Allen <https://github.com/mojavelinux[@mojavelinux]>
v2.0, 2014-08-09
:page-layout: docs
:compat-mode!:
ifndef::env-site[]
:toc: left
:idprefix:
:idseparator: -
endif::[]

////
TODO:
- the preface still feels too long

- "write once, publish everywhere (html, pdf, latex, etc)
- versatile - custom backends let you produce any output
- supported on github

- XML is "hostile to the diff/merge algorithms used by most version-control systems"
////

“__书写是困难的。__”

曾经的经验使我们对此深信不疑。

但是，我们却不能逃避，尤其是在技术行业。
我们 _必须_ 书写。
如果没有好的文档，即使再华丽的软件都一无是处。
如果连用户都失败了，那么项目也好不到哪里去。

[quote, Nick Coghlan]
除非你的 UI 的可发现性 *特别好*，否则说 “这个特性不需要文档” 就等同于说 “产品做不到。”

换句话说

[quote, Matthew Ginnard]
成也文档，败也文档。

为什么，为什么我们要把文档隐藏在复杂的 XML 模式例如 DocBook，为什么要让复杂的文字处理器使我们分析？为什么我们要浪费时间与繁琐的所见即所得编辑器作战？

想象一下，如果写文档能像写电子邮件一样简单该多好？

_这 *真能* 办到_。

思想就在轻量级编辑语言背后，例如 AsciiDoc。
它们提供纯文本语法、精美的修饰、以及直觉性的标记，这些就是为方便人类以原始格式来阅读、书写和编辑文档而设计的。
自然直觉的语法让你可以专注在内容上。
最好的还在于纯文本可以非常快速容易地转化出其他格式，例如 HTML 5，来展示。

在这个 AsciiDoc 介绍里，我们将说明它是什么，它为什么有价值以及什么使它有别于其他的替代品，例如 Markdown。
你将会发现减少编写文档痛苦的关键在于减少尖括号，而你需要的知识就隐藏其中。

// 翻译的真烂，有机会重新琢磨一下。
学习如何减少书写和发布文档的工作--无论它是笔记、文档、文章、书籍、网页或者散文--参得书写之禅，释放禁锢在心灵中的灵感，前进。

[[what-is-asciidoc]]
== 什么是 AsciiDoc？

AsciiDoc is two things:

. A mature{empty}footnote:[AsciiDoc is over a decade old. It was first introduced in 2002.], plain-text writing format for authoring notes, articles, documentation, books, ebooks, web pages, slide decks, blog posts, man pages and more.
. A text processor and toolchain for translating AsciiDoc documents into various formats (called _backends_), including HTML, DocBook, PDF and ePub{empty}footnote:[There are two implementations of the AsciiDoc processor. The original processor, named AsciiDoc, is written in Python. A more modern implementation, named Asciidoctor, is written in Ruby.].

AsciiDoc belongs to the family of http://en.wikipedia.org/wiki/Lightweight_markup_language[lightweight markup languages], the most renowned of which is http://daringfireball.net/projects/markdown/[Markdown].
AsciiDoc stands out from this group because it supports all the structural elements necessary for drafting articles, technical manuals, books, presentations and prose.
In fact, it's capable of meeting even the most advanced publishing requirements and technical semantics.

Serving as testament of this fact, many O'Reilly authors including https://github.com/matthewmccullough[Matthew McCullough], https://github.com/tlberglund[Tim Berglund], https://github.com/oreillymedia/etudes-for-erlang[Simon St.Laurent], http://www.apeth.net/matt/iosbooktoolchain.html[Matt Neuburg] and http://www.oreilly.com/pub/au/219[Ian Darwin] have used AsciiDoc to write their books for that iconic technical library.

From the very beginning, AsciiDoc was designed to be a shorthand replacement for http://www.docbook.org/whatis[DocBook], one of the formats AsciiDoc can generate.
AsciiDoc can also produce beautiful HTML5, PDFs, eBooks, man pages and even slide decks.
It has you covered from first draft to publishing.

Now that we've established what AsciiDoc is, let's consider why we need it.

[[why-asciidoc]]
== 为什么使用 AsciiDoc？

As humans, we have no difficulty talking or thinking.
In fact, we're fluent in it.
It's an activity that just happens whenever a thought comes to mind.

_Writing, on the other hand, rarely comes so easy._

When it's time to write our thoughts down, we _struggle_ to find the words--or, at least, how to arrange and organize them.
That _damn_ inner critic disrupts the stream of consciousness we coast on while talking or thinking.

It's reasonable to conclude that writing is just hard.

_Or is it?_

[[on-writing-e-mail-vs-documents]]
=== On writing: e-mail vs documents

Writing e-mail is easy.
We do it all the time.
Every day, we respond to dozens of e-mail and social media messages.
That involves communication through writing.
That's right, _writing!_

Yet, amid the flurry of typing that occurs when we respond to an e-mail, we hardly even realize we're doing it...and _fluently!_

As it turns out...

[quote, 'http://blog.stoyanstefanov.com/asciidoc[Stoyan Stefanov]']
Most people are OK with writing e-mails.
They don't consider this writing.
There's no writer's block.
Someone asks you a question, you [press] reply and type away.

_So why do we struggle to write *documents*?_

The main reason we struggle is because we don't write documents the same way we write e-mail.
Instead, we allow ourselves to get distracted by complex word processors, bury the content in XML schemas like DocBook, or battle with finicky WYSIWYG editors.
How did we get ourselves into this mess?

[[word-processors-the-real-writer-s-block]]
=== Word processors, the real writer's block

When you're in the writing (i.e., http://blog.stoyanstefanov.com/writing-vs-typing/[typing]) phase, you want the words to flow onto the screen with minimal distractions and interruptions.
Flow, not just time, is essential.

Most word processors excel at distracting you from writing.
The result: _you write less_ (ironic, huh?).

In a word processor, before you can type the first word on a blank white screen, you're forced to think about what font family you want, what font size you want, what lines spacing you want and so on.
Once you do get going, auto-correct, spelling and grammar suggestions entice you to backtrack and lose your next thought.
“Smart” quotes and auto-linking messes with the text as fast as you can enter it.
If you paste text, it likely gets added to the document with a different font family, size and even color.

*Undo. Undo. Undo!*

Let's not even talk about inserting source code.
The designers of word processors clearly did not.

*Format. Format. Format!*

After burning time fighting with its interface, you rightfully conclude that the word processor is trying to _sabotage_ your writing process.

*We _need_ an easier way to write!*

But how?

[[use-what-you-know]]
=== 使用你所知道的

_What if you could write documentation like you write e-mail?_

Imagine being able to forget about layout, typesetting, styling (and even some semantics) and just _write_.
That's the idea behind *lightweight markup languages* such as Markdown and AsciiDoc.

Here's how John Gruber introduced Markdown (in March 2004):

[quote, "John Gruber, Creator of Markdown"]
____
The overriding design goal for Markdown's formatting syntax is to make it as readable as possible.

A Markdown-formatted document should be publishable as-is, as plain text, without looking like it's been marked up with tags or formatting instructions.

The single biggest source of inspiration for Markdown's syntax is the format of plain text e-mail.
____

Similarly, here's how Stuart Rackham introduced AsciiDoc (2 years earlier):

[quote, "Stuart Rackham, Creator of AsciiDoc"]
You write an AsciiDoc document the same way you would write a normal text document.
There are no markup tags or weird format notations.
AsciiDoc files are designed to be viewed, edited and printed directly or translated to other presentation formats.

These languages are designed to enable humans to write documents, and for other humans to be able to read them, *_as is_*, in _raw_ form.

Here's a basic example of an AsciiDoc document:

[source,asciidoc]
----
= Introduction to AsciiDoc
Doc Writer <doc@example.com>

A preface about http://asciidoc.org[AsciiDoc].

== First Section

* item 1
* item 2

[source,ruby]
puts "Hello, World!"
----

_It's a plain text syntax...I *know* this!_

Compare that to the same document written in DocBook:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN"
    "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd">
<article lang="en">
  <articleinfo>
    <title>Introduction to AsciiDoc</title>
    <date>2013-01-01</date>
    <author>
      <firstname>Doc</firstname>
      <surname>Writer</surname>
      <email>doc@example.com</email>
    </author>
    <authorinitials>DW</authorinitials>
  </articleinfo>
  <simpara>
    A preface about
    <ulink url="http://asciidoc.org">AsciiDoc</ulink>.
  </simpara>
  <section id="_first_section">
    <title>First Section</title>
    <itemizedlist>
      <listitem>
        <simpara>item 1</simpara>
      </listitem>
      <listitem>
        <simpara>item 2</simpara>
      </listitem>
    </itemizedlist>
    <programlisting language="ruby"
        linenumbering="unnumbered">
      <![CDATA[puts "Hello, World!"]]>
    </programlisting>
  </section>
</article>
----

Yikes!

While DocBook (and HTML) may not be complex, they fail the readability test.

[quote, Dag Wieers]
DocBook is nice, but (like XML) it is not meant for editing nor for merging changes (by humans).
Using AsciiDoc (which translates to DocBook perfectly) is a much easier way of developing.

AsciiDoc gets us back to what's important: _writing_.
You can drop those angle brackets, but you don't have to drop the semantics.
And it's a syntax a human can actually edit, efficiently.

[quote, Linus Torvalds]
Use AsciiDoc for document markup.
Really.
It's actually *readable* by humans, easier to parse and way more flexible than XML.

Here's the really great thing about AsciiDoc.
Worse case scenario, you convert it to DocBook as a common exchange format.
DocBook is the “no lock-in” exit path for AsciiDoc.
You decide AsciiDoc doesn't work out, you can bail on it without losing a word.
No need to invent another format.
That's why so many people are going all in on it.

[[who-s-using-asciidoc]]
== 谁在使用 AsciiDoc？

AsciiDoc is not as widely adopted as Markdown, but it's used in some pretty serious places. Here are a few notable examples:

- http://oreillynet.com/oreilly/authors/welcome/asciidoc.csp[O'Reilly] and https://github.com/MakerPress[MakerPress]
* http://clojure-cookbook.com[Clojure Cookbook] (https://github.com/clojure-cookbook/clojure-cookbook[AsciiDoc source])
- http://github.com[GitHub] supports AsciiDoc syntax in repositories, wikis and gists (powered by http://asciidoctor.org[Asciidoctor])
- http://www.nofluffjuststuff.com/home/magazine_subscribe[NFJS, the Magazine] is produced from articles written in AsciiDoc
- Context and Dependency Injection for the Java EE Platform (CDI)
* http://docs.jboss.org/cdi/spec/1.1/cdi-spec.html[Specification] (https://github.com/cdi-spec/cdi/tree/master/spec[AsciiDoc source])
* http://www.cdi-spec.org[Website] (https://github.com/cdi-spec/cdi-spec.org[AsciiDoc source])
- http://golo-lang.org/documentation/next[Golo Programming Language Guide] (https://github.com/golo-lang/golo-lang/tree/master/doc[AsciiDoc source])
- http://docs.neo4j.org/chunked/stable[Neo4j graph database project] (https://github.com/neo4j/neo4j/tree/master/manual/src[AsciiDoc source])
- http://www.modrails.com/documentation/Users%20guide%20Apache.html[Phusion Passenger Users Guides] (https://github.com/FooBarWidget/passenger/tree/master/doc[AsciiDoc source])
- https://www.kernel.org/pub/software/scm/git/docs/user-manual.html[Git user manual] (https://github.com/git/git/tree/master/Documentation[AsciiDoc source])
- http://enterprisewebbook.com[Enterprise Web Development: From Desktop to Mobile] (https://github.com/Farata/EnterpriseWebBook[AsciiDoc source])
- Bintray https://bintray.com/docs/api/[REST API] and https://bintray.com/docs/usermanual/[User Guide]

These examples are more than just testimonials.
They should give you ideas about how to be successful with AsciiDoc for your own project.

[[the-zen-of-writing-asciidoc]]
== 书写 AsciiDoc 之禅

AsciiDoc is about being able to focus on expressing your ideas, writing with ease and passing on knowledge without the distraction of complex applications or angle brackets.
In other words, it's about discovering _writing zen_.

AsciiDoc works because:

- It's readable
- It's concise
- It's comprehensive
- It's extensible
- It produces beautiful output (HTML, DocBook, PDF, ePub and more)

AsciiDoc is easy to write and its easy to read (in raw form).
It's also easy to proof and edit.
After all, it's plain text, just like that familiar e-mail.

The AsciiDoc syntax is intuitive because it recognizes time-tested, plain text conventions for marking up or structuring the text.
The punctuation was carefully chosen to look like what it means.
A user unfamiliar with AsciiDoc can figure out the structure and semantics (i.e., what you mean) just by looking at it.
Best of all, *it only requires a text editor to read or write*.

AsciiDoc allows you to focus on the actual writing and only worry about tweaking the output when you are ready to render the document.
The plain-text of an AsciiDoc document is easily converted into a variety of output formats, beautifully formatted, without having to rewrite the content.

Copy text from an e-mail into a document and see how quickly you can turn it into documentation.
Almost immediately, you'll find your writing zen and enjoy the rewarding experience of sharing knowledge.

Live or die by documentation? +
“Live!”

[[next-steps]]
== 下一步

With an understanding of what AsciiDoc is and why it's so desperately needed, you're encouraged to delve into the AsciiDoc syntax covered in the link:/docs/asciidoc-writers-guide[AsciiDoc Writer's Guide].
If you're just looking for a cheat sheet, check out the link:/docs/asciidoc-syntax-quick-reference[AsciiDoc Quick Reference].
Hopefully you'll agree the syntax just makes sense.
