= What is Asciidoctor?
Dan Allen
:awestruct-layout: base
ifndef::awestruct[]
:toc:
:idprefix:
:idseparator: -
endif::awestruct[]

== What is Asciidoctor?

Asciidoctor is a text processor and publishing toolchain. 
Written in Ruby, Asciidoctor is the first project to implement the native, Python AsciiDoc syntax processor in another language. 
It's an open source library (MIT licensed) published as a RubyGem to http://rubygems.org/gems/asciidoctor[rubygems.org]. 
The project recently moved to the http://github.com/asciidoctor[Asciidoctor organization on GitHub] to sustain its rapid growth.

While Asciidoctor aims to offer full compliance with the AsciiDoc syntax (with some exceptions, noted in the project link:/#differences-from-asciidoc[README]), it's more than just a clone.

== What does the Asciidoctor implementation do?

Asciidoctor renders AsciiDoc source files and strings into HTML 5, DocBook 4.5, PDF and ePub documents.

.Built-in and custom templates
Asciidoctor uses a set of built-in ERB templates to generate HTML 5 and DocBook 4.5 output that is structurally equivalent to what AsciiDoc produces. 
Any of these templates can be replaced by a custom template written in any template language available in the Ruby ecosystem. 
Custom template rendering is handled by the https://github.com/rtomayko/tilt[Tilt] template abstraction library.

.Parser and object model
Leveraging the Ruby stack isn't the only benefit of Asciidoctor. 
Unlike the AsciiDoc Python implementation, Asciidoctor parses and renders the source document in discrete steps. 
This makes rendering the document optional and gives Ruby programs the opportunity to extract, add or replace information in the document by interacting with the document object model Asciidoctor assembles. 
Developers can use the full power of the Ruby programming language to play with the content in the document.

.Performance and security
No coverage of Asciidoctor would be complete without mention of its 'speed'. 
Despite not being an original goal of the project, Asciidoctor has proven startlingly fast. 
It loads, parses and renders documents at least *25 times as fast* as the Python implementation. 
That's good news for developer productivity and good news for GitHub or any server-side application that needs to render AsciiDoc markup. 
Asciidoctor also offers several levels of security, further justifying its suitability for server-side deployments.

.Beyond Ruby
Asciidoctor's usage is not limited to the Ruby community. 
Thanks to http://jruby.org[JRuby], a port of Ruby to the JVM, Asciidoctor can be used inside Java applications as well (and eventually in Java build tools like Apache Maven). 

Asciidoctor also ships with a command-line interface (cli). 
The Asciidoctor cli, http://asciidoctor.org/man/asciidoctor[+asciidoctor+], is a drop-in replacement for the +asciidoc.py+ script from the AsciiDoc Python distribution.

== System requirements

Asciidoctor is published as a RubyGem and currently works with Ruby 1.8.7, Ruby 1.9.3, Ruby 2.0.0, JRuby 1.7.2 and Rubinius 1.2.4 on Linux, Mac and Windows. 
We expect it will work with other versions of Ruby as well.


