var idMapping = {
    '': '/asciidoctorj/latest/',
    'distribution': '/asciidoctorj/latest/distribution',
    'installation': '/asciidoctorj/latest/installation',
    'windows-installation': '/asciidoctorj/latest/cli/#windows-installation',
    'converting-documents': '/asciidoctorj/latest/converting-documents',
    'safe-mode-and-file-system-access': '/asciidoctorj/latest/safe-mode-and-filesystem-access',
    'conversion-options': '/asciidoctorj/latest/asciidoctor-api-options',
    'locating-files': '/asciidoctorj/latest/locating-files',
    'reading-the-document-tree': '/asciidoctorj/latest/read-document-tree',
    'extension-api': '/asciidoctorj/latest/extensions/extensions-introduction',
    'ruby-extensions': '/asciidoctorj/latest/ruby-extensions',
    'logs-handling-api': '/asciidoctorj/latest/logs-handling',
    'writing-a-custom-converter': '/asciidoctorj/latest/write-converter',
    'loading-ruby-libraries': '/asciidoctorj/latest/guides/load-ruby-library',
    'jruby-instance': '/asciidoctorj/latest/guides/access-jruby-instance',
    'gem_path': '/asciidoctorj/latest/guides/gem-path',
    'using-asciidoctorj-in-an-osgi-environment': '/asciidoctorj/latest/guides/run-in-osgi',
    'optimization': '/asciidoctorj/latest/guides/optimization',
    'running-asciidoctorj-on-wildfly-as': '/asciidoctorj/latest/guides/run-in-wildfly',
    'using-a-pre-release-version': '/asciidoctorj/latest/guides/use-prerelease-version',
    'using-a-snapshot-version': '/asciidoctorj/latest/guides/use-snapshot-version',
    'development': '/asciidoctorj/latest/project/project-layout',
    'project-layout': '/asciidoctorj/latest/project/project-layout',
    'build-the-project': '/asciidoctorj/latest/project/build',
    'develop-in-an-ide': '/asciidoctorj/latest/project/ide',
    'intellij-idea': '/asciidoctorj/latest/project/ide/#intellij-idea',
    'eclipse': '/asciidoctorj/latest/project/ide/#eclipse',
    'continuous-integration': '/asciidoctorj/latest/project/continuous-integration',
    'publish-the-artifacts': '/asciidoctorj/latest/project/continuous-integration/#publish-snapshot-versions',
    'publish-snapshot-versions': '/asciidoctorj/latest/project/continuous-integration/#publish-the-artifacts',
}

var hash = window.location.hash
window.location.href = 'https://docs.asciidoctor.org' + ((hash && idMapping[hash.slice(1)]) || (idMapping[''] + hash))
